### ISSUE TITLE
Javascript error, RangeError, Invalid string length at LocalServer._log

### ISSUE THREAD

**Issue by mattbourke** [OpenBazaar/openbazaar-desktop#1000]
Brief Description: 
I open my client, leave it open for say 20 minutes, then I get this error message popup, if I click OK then the message instantly appears again, the only way I can get rid of it is to kill the app.

Operating System (OS and version): 
windows 10
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
latest
Hardware: 
8core ryzen 1800x, 64gb ram.

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
happens 80% of the time

Steps to reproduce:
1. open client
2. leave open
3. wait

Observed Behavior:
Errro pops up  
> RangeError, Invalid string length at LocalServer._log  
OpenBazaar2/app-2.0.11/resources/app.asar/js/uti......79  
at  
OpenBazaar2/app-2.0.11/resources/app.asar/js/uti......23    
at Array.forEach  
at LocalServer.obServerLog

Expected Behavior:
No error should happen

Additional info (links, images, etc go here):

**Comment by jjeffryes** [comment]
Can you confirm the "latest" version you're on is 2.0.13? The error message is saying 2.0.11.

This should have been fixed in #950.

**Comment by mattbourke** [comment]
My bad, my version is `client 2.0.11, server 0.9.1`   
I'll update to 2.0.13 and report back if I experience it again
