### ISSUE TITLE
Listing save confirm is showing even after the listing changes are saved

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-desktop#1006]
When editing the listing on Windows, OB 2.00 latest I get this :
"You have unsaved changes while editing a listing. Are you sure you want to close?"
It was just a basic edit, when I click yes change appears. I changed an image to an item. 
Basically, I get the warrning, even though the change has been saved.

https://imgur.com/a/8vvpr

**Comment by rmisio** [comment]
@jjeffryes bitcoinshirt on the public slack is observing this. I'm not able to reproduce it. He's on windows, so maybe it's a windows things (can't see how...?). When you have a chance, would you mind seeing if you can reproduce it? There an attached video of the steps he's taking.

**Comment by jjeffryes** [comment]
I can't reproduce this on Windows either.

**Comment by rmisio** [comment]
I believe this is being caused by #1021.
