### ISSUE TITLE
When Saving Moderator Settings Fields Required Even if Not Moderator

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#1009]
You are prevented from saving Moderator settings if you don't fill out the fields even if moderation is set to Off. It should only validate and require the moderator fields if you are choosing to be a moderator.

**Comment by rmisio** [comment]
We could do what we do for SMTP settings where, when moderation is set to Off, we only validate fields that you enter a value in for. That way you can't save bad data, but if you omit a field, we don't force you to enter a value.
