### ISSUE TITLE
Can't translate default search suggestions

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#1010]
Please enable translation of search suggestions added in #969.

**Comment by rmisio** [comment]
I don't think we could since these are provided by the 3rd party search provider. At best we could translate the default ones, but those would only show if the 3rd party search didn't send any.

**Comment by rhcastilhos** [comment]
Yes, I mean translating the default suggestions in openbazaar-desktop/js/views/search/Search.js:
        'books',
        'clothing',
        'electronics',
        'food',
        'games',
        'health',
        'movies',
        'music',
        'sports',
        'toys',

**Comment by jjeffryes** [comment]
I don't think we're going to address this, since the defaults in the client code are really just placeholders until existing search providers have added their own, and will be removed once that happens.
