### ISSUE TITLE
"Moderated payment not available" message being displayed on orders bigger than minimum

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#1012]
v2.0.14
![123b](https://user-images.githubusercontent.com/10789865/31580609-519e9c3a-b12b-11e7-8dc5-9a9255519f7d.png)

![123a](https://user-images.githubusercontent.com/10789865/31580610-544f7e9a-b12b-11e7-98af-eae32904b932.png)

**Comment by jjeffryes** [comment]
I am unable to replicate this issue. @rhcastilhos can you document the exact steps you took to cause this, along with the link to the product?

**Comment by rhcastilhos** [comment]
2.0.14 win7 64 bits

This happens on a normal buy:
ob://QmXMbsoinvggFbLvDjH9PQ5C4bFwudg2vQf2y2nhiUo3se/store/mini-skirt-wendy

![image](https://user-images.githubusercontent.com/10789865/31638858-8d5ad466-b2b4-11e7-9071-78bda7e3dfcf.png)

![image](https://user-images.githubusercontent.com/10789865/31638872-a8391568-b2b4-11e7-9be3-2e49357a2b38.png)

**Comment by rhcastilhos** [comment]
However, it is working as expected on listings with free shipping:
ob://QmSnMV8cGQiyvKce4mhnunGMad7cB1EKoX7FpcoP2U1TbH/store/new-sandisk-ultra-flash-memory-card-32-gb-microsdhc-uhs-i-
![image](https://user-images.githubusercontent.com/10789865/31639554-2ef9167c-b2b8-11e7-8cfc-5f7182c3f1f9.png)
![image](https://user-images.githubusercontent.com/10789865/31639573-3d17ab10-b2b8-11e7-9de0-524f02683c40.png)
