### ISSUE TITLE
Two buttons with misaligned long translations

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#1014]
This is seen on long translations (v2.0.14)
"Receive Money" button on wallet:
![image](https://user-images.githubusercontent.com/10789865/31586855-ffd73a2a-b1b5-11e7-8fca-8c052b4359ef.png)

"Pay with wallet" button:
![image](https://user-images.githubusercontent.com/10789865/31586915-e8a132ec-b1b6-11e7-9720-c0a23943c600.png)

**Comment by rmisio** [comment]
This is working as designed. Every language is going to have different length translations and some will be long enough that they will require multiple lines to display the text. In this case the button supports two lines of text without the layout breaking.

Even if we tweaked the padding to give the text a little more room, it might help these specific translations, but the next language might have even longer ones and one line isn't going to work for everything.

**Comment by rhcastilhos** [comment]
I'm asking to centralize the text, just like most buttons of the software.

Em seg, 16 de out de 2017 às 02:16, Robert Misiorowski <
notifications@github.com> escreveu:

**Comment by rmisio** [comment]
@morebrownies What do you prefer when button text needs to wrap to multiple lines? Should it be centered or left-aligned?

centered:
![image](https://user-images.githubusercontent.com/794517/31622489-65d2d78a-b251-11e7-9744-2b29ec1de115.png)

![image](https://user-images.githubusercontent.com/794517/31622608-c3605a08-b251-11e7-9067-80b13bde5342.png)

left-aligned:
![image](https://user-images.githubusercontent.com/794517/31622477-5da03a30-b251-11e7-834c-441e88bb896c.png)

![image](https://user-images.githubusercontent.com/794517/31622624-cb92864c-b251-11e7-92dd-3e843f304fb3.png)

**Comment by morebrownies** [comment]
Center aligned makes sense to me. Most of our single lined buttons are centered, so I would think they should also stay centered when wrapping onto two lines.

It would also be nice to add some vertical padding to the buttons while you're in there. When the text wraps to 2 lines, the lack of padding really shows.

**Comment by rmisio** [comment]
> It would also be nice to add some vertical padding to the buttons while you're in there. When the text wraps to 2 lines, the lack of padding really shows.

There's not really space for vertical padding. If we added it in, it would increase the height of the button which would mean either a.) a two line button is taller than a one-line button b.) we increase the height of the buttons to accommodate 2 lines, but for buttons with one line, they'll just have extra vertical negative space.

Do either of those options sounds appealing at all? Option C would be leaving the vertical padding as is.

**Comment by morebrownies** [comment]
What if the button text wrapped to 3 lines? Would it still stay the same height as a single line button?

**Comment by rmisio** [comment]
> What if the button text wrapped to 3 lines? Would it still stay the same height as a single line button?

Well... the layout would break:

![image](https://user-images.githubusercontent.com/794517/31624140-869b0bfe-b256-11e7-8d65-addc29f3c784.png)

I think what we need to do is cut it off at two lines with the implicit expectation that translators keep things concise:

![image](https://user-images.githubusercontent.com/794517/31624772-a2170b9c-b258-11e7-913d-1b5d105f4b50.png)

Asking the layout to support between 1 and 3 lines would be a huge ask. I'm not sure the designs were made with such flexibility in mind. In many places we have space concerns and I'm not sure there would be room for the button to expand like that. Also, we have the consistency issue I mentioned above.

**Comment by morebrownies** [comment]
Ok a max of 2 lines with truncation sounds good to me. Still sad about the lack of padding, but I can live without it. :)
