### ISSUE TITLE
Can't translate some UI elements

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#1016]
v.2.0.14

1)  Send button on order chat:
![image](https://user-images.githubusercontent.com/10789865/31586993-37da608a-b1b8-11e7-9cf8-f55091bda953.png)

2) Edit/Clone/Delete listing buttons on Search Results and Store page:

![image](https://user-images.githubusercontent.com/10789865/31586989-26e29914-b1b8-11e7-8eb5-0d573a8e35bc.png)

![image](https://user-images.githubusercontent.com/10789865/31586982-1bc14b3e-b1b8-11e7-812a-4a06b4adee1f.png)

3) Home, Store, Following, Followers titles and Follow/Unfollow button

![image](https://user-images.githubusercontent.com/10789865/31587300-21cb1388-b1be-11e7-836b-a7a311fea9de.png)

**Comment by Kirvx** [comment]
Please upload the en-US.json file to Transifex @jjeffryes :relieved:
We want to be ready for the final 2.0 version 👍
