### ISSUE TITLE
Duplicate Reviews

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1019]
User theButterZone reports that one of their listings shows duplicate reviews. 

![image](https://user-images.githubusercontent.com/1584275/31634083-467a0d56-b290-11e7-88b5-7c132193dd3d.png)

**Comment by rhcastilhos** [comment]
I've also seen this only once on alpha version. After a purchase, I could click two times on the button to send a review.

**Comment by rmisio** [comment]
It's been six weeks and no one else has reported this. I'm closing as not reproducible. If it pops up again we could re-open (hopefully with some reproducible steps :)
