### ISSUE TITLE
Misaligned Free Shipping tag

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#1023]
This happens due to the price with +1 or -1 character

![image](https://user-images.githubusercontent.com/10789865/31639762-2e065d82-b2b9-11e7-9e9f-445545a82596.png)

**Comment by rmisio** [comment]
I can't reproduce this one. Are you still seeing it on the latest release?

![image](https://user-images.githubusercontent.com/794517/32242563-5acee942-be30-11e7-8328-eeaeb04f5db7.png)

**Comment by rhcastilhos** [comment]
Yes 2.0.16
Check ob://QmSnMV8cGQiyvKce4mhnunGMad7cB1EKoX7FpcoP2U1TbH/store

![image](https://user-images.githubusercontent.com/10789865/32252771-3bef05e0-be7e-11e7-8678-06f7c0614e8d.png)

**Comment by jjeffryes** [comment]
I've conformed this layout issue happens when one or more prices have a different number of characters than the others.

Fixing it would probably require a fixed size on the flex child objects to the left of the free shipping tag. That would be OK, I think, since that text is expected to wrap.
