### ISSUE TITLE
Decimal mark not being translated on some UI elements

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#1024]
Decimal mark iso not being translated (showing "." instead of "," in pt_BR) on wallet (amount), moderator tab in settings (price per dispute) and edit listing (listing price and shipping option price).

![image](https://user-images.githubusercontent.com/10789865/31640048-d949e85c-b2ba-11e7-82b4-62b1d8067455.png)
![image](https://user-images.githubusercontent.com/10789865/31642236-a6427b28-b2c8-11e7-8a04-15f806206a78.png)

![image](https://user-images.githubusercontent.com/10789865/31640057-ee52414a-b2ba-11e7-8642-15344df0324e.png)
![image](https://user-images.githubusercontent.com/10789865/31640077-038b5114-b2bb-11e7-8a73-3309314af725.png)

**Comment by rmisio** [comment]
Chromium support is limited for using a comma as the decimal separator. At least for the time being, we have taken the stance that we will not localize inputs. The expectation is that numbers are to be entered using a period as the separator.

We do localize any output. It's just the input that we aren't able to do right now.

**Comment by rhcastilhos** [comment]
If user types 1.50 the field should auyomatically convert to 1,50 or the error message displayed should inform that the comma separator can be the source of the error. Now error message just says that the number is invalid.

**Comment by rmisio** [comment]
> Alternatively, the displayed error message could inform that a comma being used as separator can be the source of the error. Current error message just says that the number is invalid.

I think that's the low hanging fruit here and what we're going to do.

**Comment by rmisio** [comment]
> Alternatively, the displayed error message could inform that a comma being used as separator can be the source of the error. Current error message just says that the number is invalid.

The error messages have been updated and should be in, in the next release.
