### ISSUE TITLE
Toogle View button displays listings with same price in random order

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#1027]
Toogle View button displays listings with same price in random order. They should be always in same order. This is seen only when visiting other vendor store, on both views. Can't reproduce this when visiting my own store.

Example: ob://QmNXuCT38vxa3dsows3tVcgxPod4DbLksh2czaPPHwmo9u/store
![image](https://user-images.githubusercontent.com/10789865/31643196-f73d1664-b2cd-11e7-9220-9c165415aa36.png)

![image](https://user-images.githubusercontent.com/10789865/31643198-fafcb534-b2cd-11e7-9cb9-08bb5ce77600.png)

**Comment by jjeffryes** [comment]
I can't reproduce this issue.
