### ISSUE TITLE
List of currencies should display ISO 4217 code

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#1032]
This list of currencies is seen on general settings, moderation settings and on onboarding.
![image](https://user-images.githubusercontent.com/10789865/31743915-9fb45708-b43b-11e7-85ab-38ad50db554d.png)

![image](https://user-images.githubusercontent.com/10789865/31744021-fa0bdbae-b43b-11e7-82f3-3c489e052c09.png)

"Euro" should be "Euro (EUR)"; 
"United States Dollar" should be "United States Dollar (USD)"; 

Alternatively it could be displayed this way:
EUR - Euro
USD - United States Dollar

This is useful because enables user to search for the code.

**Comment by rmisio** [comment]
@morebrownies what do you think of this one?

**Comment by morebrownies** [comment]
I agree it would be helpful for searching the input. Feels low priority though. 

**I prefer this format:**
Euro (EUR)
United States Dollar (USD)
etc...

**Comment by jjeffryes** [comment]
@jashot7 do you want to pick this one up? It was partially completed in #1357, but the submitter didn't update it when we asked for changes. 

This should also incorporate #1354
