### ISSUE TITLE
cant install and run on Windows

### ISSUE THREAD

**Issue by young1994** [OpenBazaar/openbazaar-desktop#1035]
Brief Description: 

Operating System (win7): 
OpenBazaar version (OpenBazaar Client v2): 
Hardware: 

Reproducible (Always )

Respect all your guys' work, awesime! But there is a headachy trouble for, I cant install and run OB Client v2 follow the README.md!
Does this just work on Mac or Linux? or is there some wrong of my operation. Please explain the issue for me, i am wating online, thx so much!

Additional info (links, images, etc go here):
![1508378114](https://user-images.githubusercontent.com/24214741/31750610-b6136656-b4b3-11e7-96e2-8ccd835a350a.png)

**Comment by young1994** [comment]
![1508378114](https://user-images.githubusercontent.com/24214741/31750668-ff6bb984-b4b3-11e7-8ad8-a0bd69e72b7d.png)

**Comment by jjeffryes** [comment]
Though errors should be safe to ignore. If you enter "npm start" after that, what happens?

**Comment by young1994** [comment]
i have try,but it still cant work. 
![1508380150 1](https://user-images.githubusercontent.com/24214741/31751539-864a51b4-b4b8-11e7-8b33-6995acde3d3d.png)
![1508380179 1](https://user-images.githubusercontent.com/24214741/31751559-9e36044e-b4b8-11e7-877c-01600894abb8.png)

**Comment by young1994** [comment]
you mean OB Clint v2 actually can install and run on Windows, maybe my node environment not right? PS,OB Client v1(https://github.com/OpenBazaar/OpenBazaar-Client) i can intsall and start after clone down, but this OB desktop cant work :(

**Comment by jjeffryes** [comment]
Update to the latest version of Node, if you're on an older version it could cause this issue.

**Comment by jjeffryes** [comment]
If you enter "npm start', let it fail, and then enter 'npm start' a second time, does it work the second time?

**Comment by young1994** [comment]
No matter how many times I try 'npm start',cmd's print and errors are  all the same :(
there is one thing i don't know if this is related to this problem, cmd prompted that:'cross-env'is not an internal or external command, nor a program or batch file that can be run

**Comment by M0Rf30** [comment]
try to replace electron-installer-redhat in your package.json. You could try with electron-installer-windows

**Comment by rhcastilhos** [comment]
just delete lines "electron-installer-debian": "^0.5.2", and "electron-installer-redhat": "^0.5.0", from package.json

**Comment by young1994** [comment]
i did as you say,bro,delete lines "electron-installer-debian": "^0.5.2", and "electron-installer-redhat": "^0.5.0", from package.json and then do 'npm install'. But there is a new problem. And when i try to new  a folder named 'asn1' at node_modules and do 'npm install' again, it report another error like before 'no such file or directory, access 'C:\Users\lenovo\Desktop\openbazaar-desktop\node_modules\xxx', and add 'xxx' again,  no '...\xxx' file or directory again... 
ps, my node -v: v8.7.0 ; npm -v: 5.4.2    did you meet the issue before, plz give me some help, thx!
![5](https://user-images.githubusercontent.com/24214741/31801365-4c885a08-b57a-11e7-89f7-84c93af4a15c.png)

**Comment by young1994** [comment]
is there anybody can help me,plz?!  Even if you do not encounter the same problem，so grateful for giving me your source code with the folder 'node_modules' atfer 'npm install', and can direct do 'npm start',
my email,Michael2012211106@bupt.edu.cn or 944053343@qq.com

**Comment by jjeffryes** [comment]
@young1994 is there a reason you can't just use the installer at https://www.openbazaar.org/download/ ?

Normally you would only install the client from source if you're trying to do development work on it.

**Comment by young1994** [comment]
ya，im just want to study and do some development work on OB v2，but now was stopped at the door，sad…

**Comment by young1994** [comment]
is there any way i can try to start
 the client from source. I had install the client v2 from https://www.openbazaar.org/download/ success fully and also can communicate to OB server. And i also install OB clientv1 from source successfully and start it...

**Comment by jjeffryes** [comment]
We've corrected the issue with the installer dependencies in the package, and I've confirmed it installs and runs correctly from source on Windows. 

https://github.com/OpenBazaar/openbazaar-desktop/commit/609200e16dd22b56c58f9270b18b9a4578710657

Please try again with the latest code from master. If your'e still unable to get it running, my best guess is it's an issue with the way your environment is set up.

**Comment by young1994** [comment]
有

**Comment by young1994** [comment]
Thank you very much for everyone！I finally do it！ 
don't know why it did install devDependencies and dependencies elements automatically when i run 'npm install',  after i installed them all one by one manually with command 'npm install xxx --save-dev', it can start and everything is ok now.
