### ISSUE TITLE
When I edit a listing, click save and then click view I get...

### ISSUE THREAD

**Issue by dsmurrell** [OpenBazaar/openbazaar-desktop#1056]
<img width="651" alt="screen shot 2017-10-24 at 13 48 44" src="https://user-images.githubusercontent.com/4035854/31943906-2842c412-b8c2-11e7-9780-72b4a0d6f96e.png">

**Comment by rmisio** [comment]
What version of the client are you on?

Does the listing this happens to have variants?

I assume you are waiting until the save completes before clicking view? (it should say "saved" in the bottom the bar and then you are free to nav away without warning)

![image](https://user-images.githubusercontent.com/794517/31953870-e1297400-b898-11e7-8a79-a4b8714ef37a.png)

**Comment by dsmurrell** [comment]
client 2.0.14, server 0.9.3  I'm on OSX, I downloaded the binary about a week ago.

[example.mov.zip](https://github.com/OpenBazaar/openbazaar-desktop/files/1411526/example.mov.zip)

Is there a preferred way to post vids to github? It didn't seem to like me uploading a .mov file.

**Comment by rmisio** [comment]
This has been fixed but hasn't made it into a release yet. Should be in the next one which should be soon. Please let us know if you are still seeing the issue.

**Comment by dsmurrell** [comment]
Is there a way of getting pinged for each release that comes out? So I can ensure I'm always testing on the latest one?

**Comment by rmisio** [comment]
If you're using the bundled app and you're on Windows or OSX, there's an auto-updater.

If you're running form source, then you just need to pull latest (in which case you'd have updates even before they are released - but you might also get bugs that may otherwise be caught before they make it into a release).
