### ISSUE TITLE
Style copy paste tool in the description

### ISSUE THREAD

**Issue by dsmurrell** [OpenBazaar/openbazaar-desktop#1057]
It would be nice to have a style copy and paste tool in the description edit section.

<img width="725" alt="screen shot 2017-10-24 at 13 56 09" src="https://user-images.githubusercontent.com/4035854/31944211-352ee18c-b8c3-11e7-97b1-389471065697.png">

It's also not obvious how font is controlled for pasted text.

**Comment by rmisio** [comment]
> It's also not obvious how font is controlled for pasted text.

We do not offer the ability to use your own font here. We only offer the options available in the toolbar at the top.

**Comment by dsmurrell** [comment]
How do I change the font if I've copied some text there and it's picked the font in the copied text somehow?

**Comment by rmisio** [comment]
> It would be nice to have a style copy and paste tool in the description edit section.

There is an option in the Edit menu (right-click) to Paste and Match Style:

![image](https://user-images.githubusercontent.com/794517/31954129-954556ca-b899-11e7-94aa-7c1fc079f7de.png)

> How do I change the font if I've copied some text there and it's picked the font in the copied text somehow?

You can't, but that font won't be honored in other parts of the app. Also, if you save the listing and come back, the custom font will be stripped away.

To avoid this in the first place, just use `Paste and Match Style`.

**Comment by dsmurrell** [comment]
Ok, thanks. That might help.

Is this functionality useful enough to export it to a button on the UI?

**Comment by rmisio** [comment]
> Is this functionality useful enough to export it to a button on the UI?

Maybe...? We'll keep that in mind if we find this being reported by more users as a source of confusion.

**Comment by dsmurrell** [comment]
Sounds good.
