### ISSUE TITLE
The follow button shows on my own page on the mini user card

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#106]
<img width="1111" alt="screenshot 2016-11-30 12 13 30" src="https://cloud.githubusercontent.com/assets/13066886/20769382/7f9550be-b6f6-11e6-9897-407dd4c93cb2.png">

**Comment by rmisio** [comment]
Please ensure this happens on both the User Card on the Home tab as well as the global User Card as found in other parts of the app (e,g. followers lists, etc...).

Ideally the Home tab would be re-factored to use the global User Card so we don't have to consistently make fixes in multiple places.

**Comment by jjeffryes** [comment]
This will be fixed when #209 is fixed, I'm closing this issue as a duplicate.
