### ISSUE TITLE
Open Bazaar Pop-up errors that don't close.

### ISSUE THREAD

**Issue by KevinKelbie** [OpenBazaar/openbazaar-desktop#1060]
Brief Description: I was not actively using the software when the errors popped up. I have to force quite the application as the second pop-up never closes.

Operating System (OS and version): macOS Sierra, 10.12.6
OpenBazaar version: OpenBazaar2, 2.0.11
Hardware: MacBook Pro (Retina, 15-inch, Mid 2014)

Reproducible: Couldn't Reproduce / Rarely (happened twice)

Steps to reproduce:
1. Unknown

Additional info (links, images, etc go here):
First pop-up
<img width="416" alt="screen shot 2017-10-25 at 13 14 26" src="https://user-images.githubusercontent.com/19197564/31998178-c4c9bf38-b986-11e7-9369-633995bc31ae.png">
After clicking multiple times on ok it then shows the next pop-up.
<img width="417" alt="screen shot 2017-10-25 at 13 14 43" src="https://user-images.githubusercontent.com/19197564/31998210-d9d86690-b986-11e7-8c0e-b95fdfd58cea.png">

**Comment by jjeffryes** [comment]
This was fixed in version 2.0.13, if you update to the most recent version everything should be good.
