### ISSUE TITLE
Block Users [Rough Draft]

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1062]
# User Story
As a user, when I see a user node I don't want to see again for any reason, I want to be able to take an action to prevent them from appearing in lists of users. If I navigate directly to their node, I want the screen to hide their content, with an option to temporarily show it, or to unblock them. I should be able to look at a list of all the nodes I have blocked, and have the ability to unblock nodes on that list, or look at them to decide if I should unblock them.

# Functional Requirements

## User Cards
- [ ] Each user card should have a block button. When clicked, this button will block that node.

If a node is blocked:
- [ ] all content other than its name should be obscured. 
- [ ] There should be a message stating the node is blocked.
- [ ] There should be a button to temporarily show the node (show the content until the next refresh).

- [ ] If the node is temporarily shown, the block button should instead be an unblock button, allowing the user to unblock that node.

## Listing Cards
- [ ] Each listing card should have a block button. When clicked, this button will block that node.

If a listing's node is blocked:
- [ ] All content other than the node's name should be obscured. 
- [ ] There should be a message stating the listing is blocked.
- [ ] There should be a button to temporarily show the listing (show the content until the next refresh).

- [ ] If the listing is temporarily shown, the block button should instead be an unblock button, allowing the user to unblock that node.

## Search Report Modal
 - [ ] When reporting a listing, there should be an option to send the report and block the node. This would block the node in addition to sending the report. There should also be a button to just report the listing.

## Moderator Cards
- [ ] Each moderator card should have a block button. When clicked, this button will block that node.

If a moderator is blocked:
- [ ] All content other than the node's name should be obscured. 
- [ ] There should be a message stating the listing is blocked.
- [ ]  There should be a button to temporarily show the moderator (show the content until the next refresh).

- [ ] If the moderator is temporarily shown, the block button should instead be an unblock button, allowing the user to unblock that node.

## User Page
- [ ] Each user page should have a block button. When clicked, this button will block that node.

If a user page's node is blocked:
- [ ] All content other than the node's name should be obscured. 
- [ ] There should be a message stating the node is blocked.
- [ ] There should be a button to temporarily show the page (show the content until the next refresh).

- [ ] If the page is temporarily shown, the block button should instead be an unblock button, allowing the user to unblock that node.

## Settings
- [ ] There should be a tab for blocked node management.
- [ ] That tab should have a list of blocked nodes. Each item on the list should:
    - [ ] Show the peer ID of the node.
    - [ ] The ID should be a link that navigates to that user page.
    - [ ] Have an unblock button
QUESTION: does it make sense to have an unblock button in the settings tab, when there is no information available about the blocked node? Would it be better to only have the links to the nodes, so the user can look at the node's page, de-obscure it, and then decide to unblock it or not?

![image](https://user-images.githubusercontent.com/1584275/32004138-143025e8-b96f-11e7-9afd-29f4f17f549d.png)

# Data

The list of blocked nodes is stored in the settings as "blockedNodes". It is an array of peerIDs.

To update the list, send a PUT with a new value for the blockedNodes to the server. This should be done by setting the new value on the settings model and saving it with type PATCH.

# Notes
- the obscuring of blocked nodes should work in a similar way to obscuring NSFW nodes if the user has opted to not see NSFW content. The buttons to temporarily show NSFW content should be similar to the buttons to temporarily show blocked content.

**Comment by jjeffryes** [comment]
@morebrownies we'll need a design for the block button on user/listing/moderator cards. Mostly just where the button goes and what icon it uses, unless you think of something beyond that.

**Comment by morebrownies** [comment]
Design work has been completed on this task
