### ISSUE TITLE
NSFW Content Blocking [Rough Draft]

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1065]
# User Story
As a user, I want to be able to choose whether to see NSFW content, and if I choose not to, listings and users that are labelled NSFW will be obscured when I see them. I also want to be able to take action to temporarily look at a specific NSFW listing or user without having to see all NSFW content. 

# Functional Requirements
When the user's NSFW flag in settings is set to false:
- Listing Cards marked NSFW
    - [ ] Should be obscured, including the name of the listing and the user name.
    - [ ] A message explaining they are blocked due to being NSFW should be shown.
    - [ ] A button that will temporarily (until the next render) show the listing should be available.
- User Cards marked NSFW
    - [ ] Should be obscured, including the user name.
    - [ ] A message explaining they are blocked due to being NSFW should be shown.
    - [ ] A button that will temporarily (until the next render) show the listing should be available.
- Listing Pages marked NSFW
    - [ ] Should be obscured, including the name of the listing and the user name.
    - [ ] A message explaining they are blocked due to being NSFW should be shown.
    - [ ] A button that will temporarily (until the next render) show the listing should be available.

QUESTION: Should moderators that are marked NSFW also be blocked? Their avatar and name may still be NSFW content.

# Notes
This functionality should work in a similar manner to the blocked user functionality.

**Comment by morebrownies** [comment]
Design work has been completed on this task
