### ISSUE TITLE
Text Getting Cut Off in Chat

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#1067]
![image](https://user-images.githubusercontent.com/45482/32054616-f00e0fcc-ba2c-11e7-8c09-5f99c7f06e07.png)

OSX 2.0.15-rc1

The location is cut off on the bottom.

**Comment by jjeffryes** [comment]
Good catch. This is probably from the modifications I made to the line heights in clamped text.
