### ISSUE TITLE
Clicking a link on a store profile breaks the client

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/openbazaar-desktop#107]
Brief Description: Clicking a link on a store profile breaks the client

Operating System (OS and version): Ubuntu 16.04

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Add a website link in profile and save.
2. Click the link when viewing profile.

Observed Behavior: Client goes white and is non responsive. No link is opened.

Expected Behavior: Link opens in external browser.

**Comment by jjeffryes** [comment]
We will need to add code to handle external links, similar to what was in v1.

Any time a link is clicked, it should be checked to see if it uses an external protocol (http, https, mailto, ftp), and if so fire shell.openExternal( whatever the url is );

If the link has no protocol, or the protocol is ob2://, then it should fire an internal route instead.

**Comment by rmisio** [comment]
I'll jump on this.
