### ISSUE TITLE
"Complete Your Orders" Reminder

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1072]
# User Story
As a buyer, I may not know that I need to complete orders. If I have one or more fulfilled orders that need to be completed, a very easy to notice message should appear on the screen reminding me to complete them. It should have a link that will take me to my transactions page.

As a seller, I want users to be strongly encouraged to complete orders. A constant, slightly annoying reminder to complete their orders would help make that happen.

# Notes
This issue requires some brainstorming before requirements can be completed.

**Comment by rmisio** [comment]
> This issue requires some brainstorming before requirements can be completed.

Totally agree with that because you don't want to have to fetch an unpaginated list of purchases just to find out which ones need completion.

And, if for some reason, all the data you'd need to make the determination would not be in the purchases api, you certainly wouldn't want to have to call the order api for each purchase needing completion.

**Comment by rmisio** [comment]
@jjeffryes is the 45 day timeout and the notifications it will include sufficient to account for this issue?

**Comment by jjeffryes** [comment]
@rmisio I think that will partially address it, though they might miss the time out notifications if they have a lot of other notifications. 

@hoffmabc and @morebrownies what do you think? Buyers get a reminder the purchase will timeout on day 45 shown to them at 15, 40 and 44 days, will that be enough of a reminder to complete orders that have been fulfilled and not completed?

**Comment by morebrownies** [comment]
It's a step in the right direction at the very least. 

We can eventually try alternative solutions to increase the % of orders that get completed by buyers, but it seems it will be a while before we'll have the bandwidth to do so. 

So to answer @rmisio question, I think this is sufficient to consider this task complete.

**Comment by jjeffryes** [comment]
I think this issue is sufficiently addressed by the 45 day timeout work that is in progress.
