### ISSUE TITLE
Seed address selection weird?

### ISSUE THREAD

**Issue by TheButterZone** [OpenBazaar/openbazaar-desktop#1074]
Screenshot from Electrum 2.9.2 wallet import of the OB 2.0 client 2.0.15, server 0.9.4 backup wallet seed.

![screenshot 2017-10-27 at 14 59 50](https://user-images.githubusercontent.com/2625857/32126904-116a9900-bb28-11e7-929d-95dc9f5b5aeb.jpg)

The highlighted address in Receiving is a direct online payment (received today), the other one in Change is from an offline multisig payment (received last month). Both unmoderated. 

Is there some reason why at least the highlighted payment wouldn't have gone to the first seeded address under Receiving, if not both of them to Receiving addresses 1&2, in order of receipt?

**Comment by rmisio** [comment]
This would be a better question to ask in the [server repo](https://github.com/OpenBazaar/openbazaar-go/). Would you mind asking there?

**Comment by rmisio** [comment]
@cpacia Do you know the answer to the question asked in this issue?

**Comment by cpacia** [comment]
New addresses are used for each order. So if some people placed orders and never funded them then those addresses will go unused.

**Comment by TheButterZone** [comment]
Ok, that makes sense, I still have 3 unfunded sales to match the 3 unfunded Received addresses. Then it's just the #1 change address being selected for that multisig.
