### ISSUE TITLE
AOL SMTP fails

### ISSUE THREAD

**Issue by TheButterZone** [OpenBazaar/openbazaar-desktop#1075]
client 2.0.15, server 0.9.4

> The integration test was not successful: EOF

https://help.aol.com/articles/how-do-i-use-other-email-applications-to-send-and-receive-my-aol-mail?ncid=mbr_comdefeml00000001
says 
> smtp.aol.com SMTP - 465 - SSL

![screen shot 2017-10-27 at 16 08 38](https://user-images.githubusercontent.com/2625857/32128355-d8c58344-bb31-11e7-8f72-ccf701b7927c.jpg)

**Comment by TheButterZone** [comment]
Same result with client 2.0.17, server 0.9.4

**Comment by rmisio** [comment]
@cpacia what does that error mean?

**Comment by rmisio** [comment]
Would you mind opening this in the [server repo](https://github.com/OpenBazaar/openbazaar-go)? The client is just showing the error (`EOF`) as returned by the server. I think we'll need the server devs to dig in as to what that error means.
