### ISSUE TITLE
Delete listing tooltip has different font size

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#1083]
2.0.16
![image](https://user-images.githubusercontent.com/10789865/32253042-f89ebef0-be7f-11e7-8a84-1bb2f111aa9a.png)

**Comment by rmisio** [comment]
Are you sure the font size is different? They look the same to me and the inspector is showing them all as 14px.

![image](https://user-images.githubusercontent.com/794517/33404756-6032081e-d51a-11e7-91fc-a85a15be8baf.png)

**Comment by rhcastilhos** [comment]
v.2.2.1 win7 64 bits
Please reopen. Tooltip is definitely with a different font:
![image](https://user-images.githubusercontent.com/10789865/40867853-f8ff8126-65dd-11e8-9ac8-e1d99df60ae6.png)

**Comment by jjeffryes** [comment]
We'll take a look at it.

**Comment by rmisio** [comment]
![image](https://user-images.githubusercontent.com/794517/40926020-0c0647e8-67d0-11e8-88e2-14817878993e.png) 
![image](https://user-images.githubusercontent.com/794517/40926041-15d7d340-67d0-11e8-8de0-dd575556aa49.png)

@rhcastilhos Are we seeing different things? Those texts look to be the same font to me.

@jjeffryes Are you seeing the difference?

(I confirmed in the code when I originally closed the issue that they were the same font. Now, before digging into the code again, I'm just looking at the screenshots and they look the same to me. Maybe others are seeing something different?)

**Comment by rhcastilhos** [comment]
Yes, fonts are different: 
![image](https://user-images.githubusercontent.com/10789865/40927223-92862c74-67f4-11e8-8265-b24d54920959.png)

**Comment by jjeffryes** [comment]
On Win 10 they are the same for me.

![image](https://user-images.githubusercontent.com/1584275/40937464-bd290b78-680c-11e8-8f97-f693d2bc8969.png)

I don't see a difference on Win 7 either.

![image](https://user-images.githubusercontent.com/1584275/40937658-568501d2-680d-11e8-9f88-b8dd52b93050.png)

It's possible if you have screen scaling set up that some quick of that is causing the antialiasing to make the text look different. 

I'm going to close this issue as unreproduceable, considering it doesn't cause any functional problems.
