### ISSUE TITLE
"Discover" fails.

### ISSUE THREAD

**Issue by Gitju** [OpenBazaar/openbazaar-desktop#1094]
Brief Description: 

Operating System (OS and version): Raspbian Stretch (based on Debian version 9)
OpenBazaar version (shown on About OpenBazaar page in menu): Client 2.0.17, server 0.10.0
Hardware: Raspberry Pi 3

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Start OpenBazaar Desktop
2. Click on "Discover"
3. 

Observed Behavior:

> The search query to http://my7nrnmkscxr32zo.onion/search/listings?q=*&network=mainnet&p=0&ps=24&nsfw=false has failed. Choose another provider above.

Expected Behavior:
See a list of items that can be purchased.

Additional info (links, images, etc go here):

1]

The OpenBazaar Installation runs in "Tor-only mode".

2]

I can access other OpenBazaar listings if I enter the address of them manually into OpenBazaar Desktop.  I tried it with a shop that was promoted on Twitter by someone.  This shows me that there is a working connection to other OpenBazaar Nodes.

3]

I also tried the other providers at ./js/data/defaultSearchProviders.js and get the same result:

> The search query to https://search.ob1.io/search/listings?q=*&network=mainnet&p=0&ps=24&nsfw=false has failed. Choose another provider above.

> The search query to https://ob2.duosear.ch/search/listings?q=*&network=mainnet&p=0&ps=24&nsfw=false has failed. Choose another provider above.

> The search query to https://search.rawflood.com/ob/search/listings?q=*&network=mainnet&p=0&ps=24&nsfw=false has failed. Choose another provider above.

4]

If I enter the urls from ./js/data/defaultSearchProviders.js into a normal browser then I can see the data as expected.  That tells me that the search providers are basically accessible.

5] 

ob://connected-peers shows me 69 connected pears.

**Comment by jjeffryes** [comment]
It looks like this was probably a temporary issue with the Tor endpoint. It looks like it's working correctly in our tests now.

**Comment by Gitju** [comment]
@jjeffryes I still get: 

![bildschirmfoto von 2017-11-07 17 00 32](https://user-images.githubusercontent.com/5765500/32503372-58270230-c3dd-11e7-85a5-1b0c92325b19.png)

The rest is working it is just the search for products.

Will try it again in the future with a newer version.

**Comment by jjeffryes** [comment]
@Gitju that's very strange. I just tried it a few seconds ago, and that end point is working as expected.

Could it be timing out for you?

**Comment by Gitju** [comment]
@jjeffryes it works with pure Debian 9 in my case but not on a "fresh" Raspberry Pi 3 with Raspbian 2017-09-07  if I let the OpenBazaar-go and OpenBazaar-Desktop run on it. I already uninstalled everything, added 2GB swap space and installed it again and this time also without "Tor-only". Have not looked into the source so far so this is from a user's point of view. Expeciences from other users running it on a Raspberry Pi 3 would be great (server + client at the same time). Will try it in a couple of days/weeks again. By what the search actually does I do not see any reason why it should not work as this is usually a simple and computational not so difficult task.

**Comment by jjeffryes** [comment]
If you try the url listed in the error on in a browser or with curl on the same machine, does it resolve?

The error you're getting is just an API call, the only reason I can think of that it wouldn't work is if the call was being blocked for some reason.

**Comment by Gitju** [comment]
I tested it again this week and found the error. It did not work because the device was behind a firewall. The error message said 
`The search query to https://search.ob1.io/search/listings?q=*&network=mainnet&p=0&ps=24&nsfw=false has failed. Choose another provider above.`
I thought that this should work too because HTTP was named and browsing the internet with HTTP/HTTPS on the same machine works without a problem.
After deactivating the firewall the search returns results.
After activating the firewall again the search returns no results.
Issue solved.
