### ISSUE TITLE
Remove DuoSearch if it isn't Updated

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1099]
Currently the logo for the DuoSearch search provider is returning a 404, and the domain http://duosear.ch/ is no longer active. 

As this seems to indicate the DuoSearch search provider is not being actively maintained, it should be removed in the next release.

**Comment by JustinDrake** [comment]
Thank you for the heads up. The logo is no longer returning a 404. (I just came back from Devcon in Mexico, and only just saw your issue.)

Duo Search was an OB1.0 project which is now deprecated as OB2.0 is out of beta. The icon was an accidental oversight.

The OB2.0 search API is still maintained. Please do not remove it in the next release.

**Comment by jjeffryes** [comment]
That's good to hear. Can you update the link to the logo you send in the search data?

**Comment by rmisio** [comment]
@jjeffryes is Duo working now?

**Comment by jjeffryes** [comment]
No, it looks like Duo's logo is broken again. 

https://duosear.ch/ looks like it's not working either.

Let's take them out of the default providers. @JustinDrake if you can fix things we'll keep Duo in.
