### ISSUE TITLE
Address bar missing the ob:// prefix

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#110]
![screenshot 2016-11-30 14 35 06](https://cloud.githubusercontent.com/assets/13066886/20774217/34655a80-b70a-11e6-8387-2ae30469e56f.png)

**Comment by hoffmabc** [comment]
Are we actually planning to add this?

**Comment by jjeffryes** [comment]
We're still planning to do this as far as I know.

**Comment by morebrownies** [comment]
Yeah it should work like 1.0

**Comment by jjeffryes** [comment]
This was fixed.
