### ISSUE TITLE
add on functionality

### ISSUE THREAD

**Issue by kiahmed** [OpenBazaar/openbazaar-desktop#1101]
How can I create an add on tool that would shop up on openbazaar tab like the other search button does. Not too familiar with OB architecture. Does the current code allows that if I develop and place an extension would it pick up?

Brief Description: 

Operating System (OS and version): 
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Hardware: 

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 

Steps to reproduce:
1. 
2. 
3. 

Observed Behavior:

Expected Behavior:

Additional info (links, images, etc go here):

**Comment by jjeffryes** [comment]
Can you explain in more detail what you're trying to do? 

There is no extension architecture right now, you'd need to have a fairly good understanding of the code base to add in a new button that does something, unless it did something very simple.
