### ISSUE TITLE
BTC Transaction Fees Issues

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1105]
Several issues have surfaced due to high BTC transaction fees. These issues are present with any cryptocurrency fee, but are especially critical now that fees are as large or larger than the price of many purchases.

#User Stories

- As a buyer, if the transaction fee puts my transaction at risk of never completing due to the purchase price being lower than the fee when the vendor is offline (making the total negative), I want to be stopped from making a purchase that will fail, and given an explanation of why I couldn't make the purchase.
- As a buyer, if the transaction fee puts my transaction at risk of being rejected by the vendor because the vendor is offline and the fee will take too much of the total, I want to be informed of that possibility, and my purchase should be blocked if a failure is likely, and/or the recovery fee would consume most of my funds (I spend $10, but the fee is $8 and I get $2 back when the order is cancelled by myself or the vendor).
- As a vendor, I want to know if listings I complete will be at risk of failed transactions because their price is too close to current transaction fees, so I can choose to not sell items that have a significant chance of failure.
- As a vendor, I want to be informed that fees will be subtracted from my earnings when an offline sale happens. I want to have an estimate of how fees might affect my listings, so I can make informed decisions on what to sell at what price.
- As a vendor, I want the option to not allow offline purchases, so my earnings from sales are what I expect, without having extra fees subtracted from them.

#Notes
- Fees constantly change. This makes it difficult to give users good information, as a listing of $10 is fine when fees are $0.10, but at risk when fees are $10. Some kind of average over recent history for fees may be needed.

**Comment by TheButterZone** [comment]
> As a vendor, I want the option to not allow offline purchases, so my earnings from sales are what I expect, without having extra fees subtracted from them.

That would be me. At the same time it would protect my buyers from having any recovery fee.

**Comment by CarbonMan** [comment]
I would suggest looking at Stellar Lumens, at 0.0001XLM per transaction it is close enough to free to use. It also has a form of smart contracts which would be very useful for moderation.

I would like to help with building an interface but I am new to OpenBazaar and it is going to take some time to get up to speed with the architecture. Is there anywhere where I could find a project overview or is it a matter of reading the code and comments?

**Comment by rmisio** [comment]
Going to close this since we decided that the server will block offline and moderated transactions where the purchase amount is less than 4x the fee amount.

We're also coupling that with upcoming altcoin support, so the users could have access to coins with much lower fees than bitcoin currently has.
