### ISSUE TITLE
Reputation Tab

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1109]
## User Story

As a buyer, I want to be able to look at a vendor's page and see all of their reviews in one place, so I can get an idea of how trustworthy they are independent of the reviews on a single listing.

As a seller, I want an easy way for buyers to see all of my reviews, so they can see that I can be trusted even if the listing they are interested in has no or few reviews.

## Functional Requirements
- [x] Show the Reputation Tab when the user's reputation score is clicked in the User Page top bar.
- [ ] When the user's reputation score is clicked in a User Card open the User Page with the Reputation Tab open.
- [x] There is no visible tab in the top bar of the User Page for the Reputation Tab. When it is active, no tab is marked as active.

### Reputation Screen
- [x] There will be a top area with the total number of reviews, the average for the past 90 days, and the all time average.
- [x] When loaded, the first 5 reviews will be loaded and shown. 
- [x] There will be a Load More button. When clicked it will load 5 more reviews.

### Review
- [x] Each review should have the current data returned from the fetchReviews API (date, optional user name, review text and star ratings)
- [x] Each review should also have a thumbnail of the listing. This should be given as an object with all the image sizes. 
- [x] If the image doesn't exist or can't load, a placeholder will be shown.
- [x] Each review should also have the title of the review. 
- [x] The image and title of the listing should be links that when clicked on load the listing.
- [ ] When the title is hovered over, it should have an underline.
- [ ] Update the user link to match the title link on hover.

### Ratings API
- [ ] An API will need to be created to get the rating hashes for a node.
- [ ] It should be very similar to the ratings API.
    - or the existing rating api can be modified, to return rating hashes from all reviews if no slug is provided.
- [ ] The API should accept a peerID to return ratings for.
- [ ] The API should return an array of hashes of reviews.
- [ ] The API should return the total average rating.

### Individual Reviews API
- [ ] It should be very similar to fetchratings (or fetchratings can be used, if possible)
- [ ] When given an array of review hashes, it should return the data for those hashes.
- [ ] It should have an asyc option, when true it returns an id for websocket messages
- [ ] The format of the returned messages should be identical to those returned from ratings.

## Notes
- the listing title and image will need to be saved when the review is made
- this may break compatibility with older nodes making purchases, because the purchase data will be different.

**Comment by DominiqueFrancon** [comment]
Additional functional requirements to consider:

- [ ] Only a buyer can rate a seller from whom they've purchased.
QUESTION: Should the item that the buyer purchased be shown alongside the buyer's review (a la Etsy reviews) or should what they bought remain anonymous?

- [ ] Buyers can choose to display their username next to a review or not.

**Comment by jjeffryes** [comment]
@DominiqueFrancon Good catch, each review should show an image of the listing that the review belongs to, along with the title of the listing. I forgot to include those.

Buyers can currently only rate items they have purchased, and can choose to make that rating anonymous or not, we don't need any new work to include those features.

**Comment by jjeffryes** [comment]
@cpacia I forgot to include the listing image and the title of the listing in the initial draft. Can you include those in the fetchRatings api, or should we have a different api that returns the reviews in this case?
