### ISSUE TITLE
Altcoin support for bundled app

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-desktop#1121]
The following are some preliminary designs for handling alt coins in the bundled app, notably how to configure your server or servers to work with a particular coin.

So the first time you run the client you will need to select what crypto you want your wallet in:

![image](https://user-images.githubusercontent.com/794517/33351500-ec9a73da-d458-11e7-9540-31fbe39b6d6a.png)

Then if you want to support any other coins, you would do so by creating a new server configuration. The first question will be the server type (built in or stand-alone).

![image](https://user-images.githubusercontent.com/794517/33351537-0963007c-d459-11e7-9cf5-d8fcafd97d2f.png)

If you select built-in, then there will be a “wallet coin type” field as part of the data you need to enter for the server configuration.

![image](https://user-images.githubusercontent.com/794517/33351560-21ffc368-d459-11e7-8425-84507d1a4d9d.png)

If you selected stand-alone, the same form as is currently in the app is presented where you basically need to fill out various things (e.g. ip, port, etc..). In this case, you will not get a wallet coin type. You will need to configure that via the stand alone server’s config file:

![image](https://user-images.githubusercontent.com/794517/33351596-42972f94-d459-11e7-8a5b-f154e78680cd.png)

This is what multiple built-in servers (for different coins) would look like:

![image](https://user-images.githubusercontent.com/794517/33351602-50a79218-d459-11e7-879e-c47218dd3677.png)

**Comment by rmisio** [comment]
FYI: @cpacia @jjeffryes @morebrownies

**Comment by jjeffryes** [comment]
Picking built-in vs stand alone seems like it could be a confusing step, most users won't know what that choice means. 

Could it be simplified by giving bundled clients a "create new crypto server" button of some kind, that's obviously for creating a server that runs a new coin?

Then the other button could be more explicitly for connecting to existing external servers. Some users get confused by it and assume it makes new servers as it is now.

**Comment by rmisio** [comment]
> Could it be simplified by giving bundled clients a "create new crypto server" button of some kind, that's obviously for creating a server that runs a new coin?

Yes, we could do it that way too. It's a matter of discussion which way is less confusing since I imagine having two "create server" buttons next to each other can be confusing as well.

**Comment by rmisio** [comment]
Another point of discussion is that if the user selects zcash, they'll also need to provide a binaryPath, username, and password. Also, they will have had to download the zcash binary. So.. obviosuly zcash is for super advanced users. I'm struggling to see the benefits of exposing all that in the UI. Why wouldn't they just download a stand-alone server and configure it via the server config file?

**Comment by jjeffryes** [comment]
@morebrownies @rmisio did we settle on how this will work?

I feel like we need to nail down the design, for instance whether there will be dedicated "create a server with BCH, create a server with ZCash" etc. buttons, or a drop down, or some other thing.

**Comment by jjeffryes** [comment]
We also discussed limiting it to being chosen on first startup. I believe we decided not to do that, and to have the crypto coin choice be made at first startup and to allow the user to create other bundled servers running other crypto coins later. I want to make sure we're all on the same page.

**Comment by morebrownies** [comment]
@jjeffryes i'm ready to pick up a new task today. Is this a good one to start with? Or is there something else more pressing?

**Comment by morebrownies** [comment]
We can regroup on a call for a few if needed too before I start on it.

**Comment by jjeffryes** [comment]
I think this is the most immediate thing. Let's coordinate a recap discussion.

**Comment by 6543** [comment]
A great coin is monero. they now have multisig!
