### ISSUE TITLE
Verified Moderators

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1123]
## User Story

- As a buyer, when browsing listings I want a way to see which listings have verified moderators so I can make informed choices when looking at listings.
- As a buyer, when looking at a listing, I want to know if I can pick a verified moderator when I purchase it, so I can make an informed choice whether to click the buy button.
- As a buyer, when I am purchasing a listing, if it has moderators I want to have the verified moderators indicated clearly, so I can easily choose one of them if I want to.
- As a buyer, when I am purchasing a listing, I should see a clear and very noticeable explanation of what a verified moderator is, and why I should choose one. The explanation should make the risks of not choosing a verified moderator clear, so I am warned that purchasing from vendors with no verified moderators comes at a risk.
- As a vendor, I want a way to show buyers browsing listings that my products use verified moderators, so they will be more likely to buy from me.
- As a vendor, I want buyers looking at my listing to see I have verified moderators, so they trust my listing more and are more likely to click the buy button.
- As a vendor, I want buyers to be able to see the verified moderators in the purchase process, so they can select one if they want and avoid selecting a risky moderator that will result in a bad experience. 
- As a vendor,  when I am selecting moderators for my store, I want to be able to easily find verified moderators. They should be clearly labeled, and I should have the ability to see them together, either first in the list or sorted.
- As a moderator, I want a way to show buyers and sellers that they can trust me when choosing a moderator.
- As a user, I want to have the default list downloaded automatically.
- As a user, I want to be able to change the list to a different list at a http or IPFS location.
- As a user, if I change the list I want an easy way to reset it to the default list.

## Functional Requirements
- [x] The client should call an http or IPFS address after starting to download the list of verified moderators.
- [x] The results should include a graphic to show (as a badge or something similar)
- [x] There should be a default or loading image to show while the badge is still loading.
- [x] The list should refresh periodically.
- [ ] On startup, the list should load from a cache instead of holding up startup.
- [ ] Show a loading message at the bottom of the page, letting the user know the list is loading and the current results are out of date (maybe show how old the list is). 
- [ ] Critical pages should show a warning if the current list is old or no list has loaded yet.

### Listing Card
- [x] (tentative) The listing card should show whether the listing has one or more moderator on the verified list.

### Listing Details
- [x] The listing screen should show whether the listing has one or more moderators on the verified list.

### Purchasing
- [x] There should be an explanation/warning letting users know why verified moderators are important, and what the risks are of purchasing without one.
- [x] Verified moderators should be clearly indicated. Maybe they should be shown first, or there should be a way to filter/sort by verified or not (TBD).
- [x] Show placeholders when loading so the moderators don't jump around when loading.
- [x] Show error states if a moderator doesn't load.
- [ ] Allow the user to hide errored moderators.
- [x] There should be a "show only verified" button that only shows verified moderators.
- [x] The button should be active by default.
- [x] It should be clear you can see the other moderators by de-activating the filter.

### Settings/Store
- [x] There should be an explanation/warning letting vendors know why verified moderators are important, and why they should choose them.
- [x] Verified moderators should be clearly indicated. Maybe they should be shown first, or there should be a way to filter/sort by verified or not (TBD).
- [x] Show placeholders when loading so the moderators don't jump around when loading.
- [x] Show error states if a moderator doesn't load.
- [ ] Allow the user to hide errored moderators.
- [x] There should be a "show only verified" button that only shows verified moderators.
- [x] The button should be active by default.
- [x] It should be clear you can see the other moderators by de-activating the filter.

### Settings/Advanced
- [ ] There should be an input for the list url.
- [ ] The default url should be intput.
- [ ] There should be a link or button to restore the default, so the user can recover it if they changed it to something else.

### Moderator Details
- [x] If the moderator is verified, it should be clearly indicated.

### Order Details
- [x] If the moderator is verified, it should be clearly indicated.

### User Card
- [x] If the user is a verified moderator, it should be clearly indicated

## Data
- the list should have an array of peerIDs.
- the list should include a link to the image for the badge
- if we want to show listings with verified moderators, the moderators would need to be included in search results and listings data. They are already in the data for individual listings and purchasing.

**Comment by jjeffryes** [comment]
An idea we discussed was adding different types, each with a different badge and description. This would give more flexibility to anyone that implements a Verified moderator list.

```
  types: [
    {
      name: 'standard',
      description: 'blah blah blah',
      badge: 'http://etc.com/standard.png'
    },
    {
      name: 'advanced',
      description: 'blah blah blah',
      badge: 'http://etc.com/advanced.png'
    }
  ],
  moderators: [
    {
      peerID: 'QmVFNEj1rv2d3ZqSwhQZW2KT4zsext4cAMsTZRt5dAQqFJ',
      type: 'standard'
    },
    {
      peerID: 'QmXFMkpBBpL4zcYAArVAecLyypFrRzp2Co4q9oXUtzF7XF',
      type: 'advanced'
    }
  ]
```

**Comment by jjeffryes** [comment]
Expanding on the data format after going through the designs, I thought the following would cover what we need now and allow a lot of flexibility in the future. @tyler-smith ?

```
{
  data: {
    name: 'name of provider',
    description: 'description',
    link: 'url to the provider'
  },
  types: [
    {
      name: 'standard',
      description: 'blah blah blah',
      badge: 'http://etc.com/standard.png'
    },
    {
      name: 'advanced',
      description: 'blah blah blah',
      badge: 'http://etc.com/advanced.png'
    }
  ],
  moderators: [
    {
      peerID: 'QmVFNEj1rv2d3ZqSwhQZW2KT4zsext4cAMsTZRt5dAQqFJ',
      type: 'standard'
    },
    {
      peerID: 'QmXFMkpBBpL4zcYAArVAecLyypFrRzp2Co4q9oXUtzF7XF',
      type: 'advanced'
    }
  ]
}
```

**Comment by tyler-smith** [comment]
I think this looks good and haven't thought of anything that needs to be added or changed.
