### ISSUE TITLE
Support Link Added to Client

### ISSUE THREAD

**Issue by jenncloud** [OpenBazaar/openbazaar-desktop#1124]
Link to https://openbazaar.org/support within the app under "Help" in the top menu as well as within "About OpenBazaar."

**Comment by rmisio** [comment]
@morebrownies do you have any thoughts on where in the About modal this link should be?

**Comment by morebrownies** [comment]
![screen shot 2017-11-29 at 1 23 37 pm](https://user-images.githubusercontent.com/13066886/33399758-978bd982-d508-11e7-8d21-5ac472c758eb.png)

**Comment by morebrownies** [comment]
Thinking about the `About modal` one sec

**Comment by morebrownies** [comment]
I would suggest adding a new tab to the `About modal` with a sentence or two and link to the help page. @jenncloud may have a better suggestion for copy on this page. 

![screen shot 2017-11-29 at 1 30 21 pm](https://user-images.githubusercontent.com/13066886/33400045-7b9765d8-d509-11e7-9473-afdc1faabb62.png)

**Comment by morebrownies** [comment]
We could include links to our subreddit and slack in there as well @jenncloud thjoughts?

**Comment by jenncloud** [comment]
We can't just link to Slack anymore unfortunately though @hoffmabc was looking for a way to be able to do so. Reddit is already linked on the Support page. I personally think it's easiest and cleanest to just share one link out of the client that directs users to many options on the web but am open if anyone wants to fight me.

**Comment by morebrownies** [comment]
Sounds good to me
