### ISSUE TITLE
Scrolling While Select2 is In Focus Does Bad Things

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#113]
If you click into any Select2 field inside the Settings modal, and then scroll, all the select2 dropdowns, the shipping tiles, and the photos stay fixed in the modal, while the other content scrolls under them. 

Note: we are planning to refactor this modal to match to the new full-page scrolling design, doing that may fix this issue.

![image](https://cloud.githubusercontent.com/assets/1584275/20805000/16c61c30-b7c3-11e6-94cf-ae2e80b46f5e.png)

**Comment by jjeffryes** [comment]
If we can fix this easily before refactoring the modals, we should, if we can't this issue can wait until we do that, which will probably be in milestone 2.

**Comment by rmisio** [comment]
The behavior described does not happen for me. What does happen is, if I focus into a select 2 field, I can't scroll via the mouse scroll wheel (or macbook touch-pad). I can still click on the scroll bar and scroll via that.

Basically, it seems that select2 is hijaking scroll when it's focused.

**Comment by jjeffryes** [comment]
It's definitely still happening for me. It may be a windows vs mac thing. 

Only select 2 instances with tagging seem to be affected.

![image](https://cloud.githubusercontent.com/assets/1584275/21248257/caa541cc-c303-11e6-8598-348eb3a5f24b.png)
