### ISSUE TITLE
Wallet coin selection: unconfirmed outputs used when confirmed outputs are available

### ISSUE THREAD

**Issue by pinheadmz** [OpenBazaar/openbazaar-desktop#1130]
OSX: client 2.0.18, server 0.10.0

1) Fund OB wallet with low fee transaction:

https://blockchain.info/tx/6daf6cb0e9e1b958105ae2129191b7680d9fcf6e50e5f5f04bade70614c40249

2) Try to make purchase on OB. Client won't let me because funds have not yet confirmed.

3) OK, fine. Send second tx to OB wallet with HIGH fee:

https://blockchain.info/tx/42509b8f5a79e051a00576e2705da831d55eb86974bb198dc6e5966d3f9a907b

4) High-fee transaction confirmed in the next block! Great, return to vendor site and complete purchase. HOWEVER: The OB wallet paid the vendor with the unconfirmed outputs from the first, low-fee transaction:

https://blockchain.info/tx/bd14fa9db714fb931a5630151f4e5be4e5e15d84ef1f2d5903a37f81cc27f8e7

... so even though the wallet has a confirmed output, it used the unconfirmed output which will probably delay the purchase for days

**Comment by pinheadmz** [comment]
I cancelled the purchase in OB, triggering a refund. So now the is a chain of three unconfirmed transactions. Hopefully some miner has CPFP turned on!

**Comment by rmisio** [comment]
Would you mind logging this in the [server repo](https://github.com/OpenBazaar/openbazaar-go)? The server code is the one responsible for determining where the funds are coming from on a wallet spend.

**Comment by pinheadmz** [comment]
Thanks.

https://github.com/OpenBazaar/openbazaar-go/issues/778
