### ISSUE TITLE
Order missing?

### ISSUE THREAD

**Issue by kiahmed** [OpenBazaar/openbazaar-desktop#1134]
Brief Description: 

Operating System (OS and version): Windows 10 Pro
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
client 2.0.17, server 0.9.4
Hardware: intel cori 7

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Hi,
One OB node ordered an item from my store more than 3 weeks ago and I never got notified and he already paid in full. He tried to get support many times but haven't had any luck then finally brought it to my attention. Here is the screen shot of the product purchase.  My store id QmQfbCEUEfmBr59ZvBDVek7rs71AywrcMkX2APEDwJWGDo
![missed_order](https://user-images.githubusercontent.com/28849607/33679482-e0a0c324-da8c-11e7-802b-9da9ff537c3f.PNG)

I feel horrible saying the customer that I never received any order from him. Is there anything I need to do or configure on OB node?

Steps to reproduce:
1. 
2. 
3. 

Observed Behavior: nothing on seller end

Expected Behavior: should have notified for an incoming order and show order status

Additional info (links, images, etc go here): see attached image

**Comment by jjeffryes** [comment]
Are you saying you don't see this order at all in your Sales screen?

There are some known issues with the server repo, sometimes transactions fail to transmit to the seller's node. I'm going to move your issue to that repo, where our backend team can try to help you.

**Comment by jjeffryes** [comment]
I've moved this issue to https://github.com/OpenBazaar/openbazaar-go/issues/781

**Comment by kiahmed** [comment]
correct no trace of the order from UI. Can the order be traced some other way on open bazaar chain?

**Comment by jjeffryes** [comment]
@kiahmed can you repeat your question on https://github.com/OpenBazaar/openbazaar-go/issues/781
