### ISSUE TITLE
Better Error Handling in Shipping

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#114]
In the edit listing shipping section if you enter invalid data, the error message says the data is missing, which is confusing.

The inputs should have max attributes to prevent excess text being entered. 

It's also possible to enter a number so big it is converted to an exponent. It would be better to put a max on the field so the user can't enter too large of a number.

![image](https://cloud.githubusercontent.com/assets/1584275/20808824/1042345c-b7d2-11e6-92f0-d3ab96aceb24.png)

**Comment by jjeffryes** [comment]
Closing this, the errors appear to be associated with the service above them. 

We should give these a different design.

**Comment by rmisio** [comment]
I think it may be as simple as also making the corresponding fields have a red (error color) border.
