### ISSUE TITLE
Couldn't get the installer working

### ISSUE THREAD

**Issue by wormite** [OpenBazaar/openbazaar-desktop#1140]
Brief Description: 

Operating System (OS and version): Windows 10 prof
OpenBazaar version (shown on `About OpenBazaar` page in menu): 2.0.18-setup 64 bit
Hardware: CPU i7-3770K

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Run installer
2. The error pops
3. open the setup log and saved.

Observed Behavior:
Always fail to install

Expected Behavior:

Additional info (links, images, etc go here):
log file:

[SquirrelSetup.log](https://github.com/OpenBazaar/openbazaar-desktop/files/1548578/SquirrelSetup.log)

**Comment by hoffmabc** [comment]
Do you have an anti-virus scanner installed?

**Comment by wormite** [comment]
Yes!
And after disabling it, I succeeded in installation.

**Comment by hoffmabc** [comment]
great thanks.

**Comment by wormite** [comment]
The antivirus software was 360 anquan, if you care to know. Thanks!
