### ISSUE TITLE
Unable to connect to OB search providers via Tor

### ISSUE THREAD

**Issue by rex4539** [OpenBazaar/openbazaar-desktop#1153]
Brief Description: 
Unable to connect to OB search providers via Tor

Operating System (OS and version): macOS 10.13.3 (17D25b)
OpenBazaar version (shown on `About OpenBazaar` page in menu): 2.0.21
Hardware: MacBookPro8,2

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Have Tor daemon running.
2. Enable connection via Tor in OB.
3. Click on "Discover" and select any search provider.

Observed Behavior:
The search query to XXXXXXX has failed. Choose another provider above.

Expected Behavior:
Connection to search provider is established.

Additional info (links, images, etc go here): 
[logs.zip](https://github.com/OpenBazaar/openbazaar-desktop/files/1584422/logs.zip)

**Comment by jjeffryes** [comment]
I am unable to reproduce this issue. All the search providers are working in Tor.
