### ISSUE TITLE
OB forces launch of zcashd even if it's already running

### ISSUE THREAD

**Issue by rex4539** [OpenBazaar/openbazaar-desktop#1157]
I'm running a Zcash full node and have zcashd running always.

When I launch OB it launches a new zcashd instance.

Can't it use the one already running?

Have a check during launch. If zcashd is already running, use it. Otherwise launch it.

**Comment by rmisio** [comment]
This is controlled by the server. Would you mind logging this in the [server repo](https://github.com/OpenBazaar/openbazaar-go)?
