### ISSUE TITLE
Dust error message on withdraw

### ISSUE THREAD

**Issue by EddieOne** [OpenBazaar/openbazaar-desktop#1159]
Brief Description: 

I'm trying withdraw btc roughly $110 and I get the message. The transaction amount is too small and falls below the network dust amount.

Operating System (OS and version): 
Windows

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Withdrawn 0.009

Observed Behavior:
Get the error message

Expected Behavior:

**Comment by hoffmabc** [comment]
Wow did it get fixed?
