### ISSUE TITLE
Decrease the size of the search filter text

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#1162]
As more search filters are being added, it's becoming more apparent that the text size is too large. Can we bump the size down a bit?

**Current**
![screenshot 2018-01-03 11 23 55](https://user-images.githubusercontent.com/13066886/34536001-b2fe9f98-f078-11e7-97fe-fb847d2104a9.png)

**Ideal**
![screenshot 2018-01-03 11 23 42](https://user-images.githubusercontent.com/13066886/34536000-b2ecef28-f078-11e7-95b2-190ac0dfa8b7.png)

In the screenshot above, I changed the label size from `1.4rem` to `1.3rem` and the filter header size from `1.5rem` to `1.3rem`. This will allow for more filters to display on the screen and draw less focus to them.

**Comment by jjeffryes** [comment]
I can add this to the WIP search PR before I complete it.

**Comment by morebrownies** [comment]
Sounds good, thanks

**Comment by rmisio** [comment]
Would we want to apply the same changes to the store as well?

**Comment by morebrownies** [comment]
Yes, store as well.

**Comment by rmisio** [comment]
@jjeffryes Have we completed this one?

**Comment by jjeffryes** [comment]
Yes, this was completed.
