### ISSUE TITLE
Address bar is not so helpful

### ISSUE THREAD

**Issue by ido-ran** [OpenBazaar/openbazaar-desktop#1163]
I've started to use OpenBazzar2 for few days and I've found the address bar to have very little value IMHO and it takes a lot of space.

The OB app seems to try and take the shape of a web browser but where a web browser address bar usually has the domain name, maybe another piece of information after that to help me ensure I'm in the right place, in OB the "domain" is a hash which is long and doesn't really tell me if I'm at the right place or not.

I think the address bar should be hidden by default and have an option to show it to advanced users.

**Comment by morebrownies** [comment]
Handles/domains are still in our development backlog. Hopefully we can get them integrated soonish and the address bar will start to become more functional.
