### ISSUE TITLE
I posted an order id in chat and it auto linked to a user page

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#1168]
When the link is clicked it takes me to ob://QmTbgvioznV3nfjotBbBo1gkCi8CqWkEDv7GmiGXQ7JLBA which doesn't exist.

Seems that order ids and user GUIDs are getting tangled up in chat. 

![screenshot 2018-01-09 09 32 32](https://user-images.githubusercontent.com/13066886/34734276-11952d46-f520-11e7-8c2e-23331ad8c846.png)

**Comment by jjeffryes** [comment]
Hmm. Just pasting an orderID won't produce a working link, but the link code sees that it is a hash and makes it a link.

**Comment by morebrownies** [comment]
It doesn't need to produce a working link to an order id (would be great if it did), but it definitely shouldn't link to a user page.

**Comment by rmisio** [comment]
hmmm... it seems like both order id's and peerIds are multihashes and there's now way to distinguish between them.

So, in order to not have order id's link to a user page, we'll also need to not allow peerIds to link to a user page.

If someone prefaced the link with `ob://`, then it will work.

**Comment by morebrownies** [comment]
I would imagine that most people paste links into chat with `ob://` included in them. Assuming they copy the full text from the address bar, so maybe that is fine @rmisio
