### ISSUE TITLE
There should be no setting for Zcash fee

### ISSUE THREAD

**Issue by rex4539** [OpenBazaar/openbazaar-desktop#1176]
Brief Description: 
There should be no setting for Zcash fee.

OpenBazaar version (shown on `About OpenBazaar` page in menu): 2.1.0

Steps to reproduce:
Navigation -> Settings -> Advanced

Observed Behavior:
There is option to set Zcash fees to Economic, Normal and Priority.

Expected Behavior:
There is no setting. Zcash fee should just be 0.0001 ZEC by default.

Additional info (links, images, etc go here):
@rex4539 [10:02 PM]
What are the exact Zcash fees per Economic, Normal and Priority?
Normal Zcash fee when running a full node for example is 0.0001 ZEC.

@cpacia  [10:46 PM]
It uses the zcash binary for fee estimation. I don't know what algorithm they use.
[10:46 PM]
It targets 1 block, 3 blocks and 6 blocks.

@zookozcash  [Zcash founder and CEO] 4:42 AM
Could you please tell Chris Pacia that currently every fee in Zcash is exactly 0.0001 ⓩ and they should just use that for now?

**Comment by jjeffryes** [comment]
We're going to leave this as-is, the binary returns a value as expected.
