### ISSUE TITLE
Setting for Accepted Currency in Search Doesn't Stick

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#1177]
If I'm running a BCH or ZEC server and I search I want to find listings that I can purchase so I select the correct currency in Accepted Currency. If I leave search to a listing page or profile and come back, the setting is cleared and is back to BTC.

**Comment by jjeffryes** [comment]
This isn't a bug, we just haven't merged in the PR that defaults search to your currency yet.

**Comment by jjeffryes** [comment]
This will be closed by #1161, it's just waiting for the search testing endpoint to be ready, as it also adds in checkboxes for search filters.
