### ISSUE TITLE
Payment Details Address Undefined in Moderator Order Details

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1182]
A user is reporting that when they click the Payment Details link in the Order Details of a case, the address is https://blockdozer.com/insight/address/undefined

This is on the alt coin rc3, and may only affect that branch.

**Comment by rmisio** [comment]
We'd really need more details here:
- what coin is there wallet running in?
- is rc3 on testnet or mainnet?

**Comment by jjeffryes** [comment]
BCH, main net, the dispute was started on rc3 but they are using rc4 now.
