### ISSUE TITLE
The "Free Shipping" badge renders differently between the filter panel and listing card

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#120]
@jjeffryes I'm having a difficult time tracking this one down. It appears both instances have the same classes applied, but they render differently. 

The instance on the listingCard is **incorrect**. It seems to have some extra vertical padding.  

![screenshot 2016-12-01 16 52 39](https://cloud.githubusercontent.com/assets/13066886/20819037/a315b182-b7e6-11e6-9982-f563ee259ea9.png)

![screenshot 2016-12-01 16 52 33](https://cloud.githubusercontent.com/assets/13066886/20819036/a3077c20-b7e6-11e6-8df3-2104e765d6f3.png)

**Comment by rmisio** [comment]
I'm not able to reproduce this, they both look the same to me:

![image](https://cloud.githubusercontent.com/assets/794517/21703223/5d7255aa-d365-11e6-8a65-8729e05eeb69.png)

Maybe it was fixed? If I'm wrong, I will promptly re-open.

**Comment by morebrownies** [comment]
Must have been fixed. Thanks for checking on it 👍

**Comment by jjeffryes** [comment]
I fixed it a while ago and forgot to close the issue.
