### ISSUE TITLE
Show Orders with an ERROR state

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1202]
This is dependent on an enhancement to the server https://github.com/OpenBazaar/openbazaar-go/issues/838

## User Story

The server will sometimes put an order into an ERROR state and not provide it to the client. As a user, I want to know when my orders are in in an error state, so I know they happened and don't think the application is just broken or missing data.

As a user, when I see an order in an error state, I want some guidance on why it happened and what to do to resolve it.

As a seller, if an order has been rejected due to the listing being updated and a stale listing being purchased, I would prefer to have the order go through so I can choose whether to honor it.

## Functional Requirements

- [ ] When an order is stale due to an out of date listing being purchased, the order should work as normal. No indication needs to be given that the order was out of date.
- [ ] When an order has a state of ERROR_PENDING, an "Error" status will be shown.
    - [ ] The buyer can cancel the order the same as if it was in a PENDING state, if it is not moderated.
    - [ ] If the order is moderated, the buyer will have to dispute it to retrieve their funds.
    - [ ] The seller cannot take any action on an order in the ERROR_PENDING state.
    - [ ] The server will return a error_reason parameter, it should be shown in the Order Details.

**Comment by rmisio** [comment]
@morebrownies what state should errored orders map to?

![image](https://user-images.githubusercontent.com/794517/36181419-a3faea66-10d9-11e8-9558-14557760064f.png)

I suppose we could create another filter. If we do that, we may want to consider making another one for the PAYMENT_FINALIZED state, since right now that's "weirdly" mapped to Fulfilled. Maybe adding two would better balance things than adding 1?

**Comment by jjeffryes** [comment]
Maybe we could consolidate the 3 dispute filters into 1? Most people shouldn't have a huge number of disputes. A single "some stage of disputed" filter would probably be fine.

**Comment by morebrownies** [comment]
I tend to agree with what @jjeffryes is suggesting. I was working on designs for this view yesterday on a smaller device and having 3 dispute filters eats up a fair amount of space. I don't think that level of granularity is necessary for 99.99% of users. 

I'd suggest condensing disputes into one filter, which will then open up space for the Error state. @rmisio

**Comment by rmisio** [comment]
@morebrownies ok, it will open up 2 spaces actually. Should I turn PAYMENT_FINALIZED into a separate filter too or just leave it as Fulfilled?

**Comment by morebrownies** [comment]
It's probably fine in Fulfilled for now @rmisio. Not sure if more granularity is actually needed at this point. Notifications will help alert the user that payment has been finalized too.

**Comment by rmisio** [comment]
@morebrownies and the collapsed Dispute filter should just be labeled `Dispute`?

**Comment by morebrownies** [comment]
Probably needs to be plural @rmisio, `Disputes`
