### ISSUE TITLE
Erronious 'insufficient funds' error

### ISSUE THREAD

**Issue by christroutner** [OpenBazaar/openbazaar-desktop#1216]
Brief Description: 
I'm using the BCH wallet in release 2.1.0, server version 0.11.0. I just funded my wallet, had 2 confirmations. I tried to send BCH to another address and I get an insufficient fund error:

![image](https://user-images.githubusercontent.com/9870991/35653923-3e95c5ea-069f-11e8-8481-9a24b540657a.png)

Luckily, I had the debug window open in the Electron app and I was able to catch the API request. One thing I noticed is that the amount requested is 136585. Very weird.

![image](https://user-images.githubusercontent.com/9870991/35654000-9b0ea35a-069f-11e8-9ec2-74bd5ca36550.png)

Operating System (OS and version): Windows 10 Home
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Hardware: Intel i7 processor. 12GB or RAM.

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 

Steps to reproduce:
1. 
2. 
3. 

Observed Behavior:

Expected Behavior:

Additional info (links, images, etc go here):

**Comment by christroutner** [comment]
I checked all the log files on the server and couldn't find anything odd. I also checked and main sure that I could access the fee API at https://btc.fees.openbazaar.org/

Here is the tail of the api.log file:
```
00:13:48.572 [ServeHTTP] [DEBUG] GET /wallet/estimatefee/?feeLevel=NORMAL&amount=67739 HTTP/1.1
Host: p2pvps.net:4002
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US
Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) OpenBazaarDesktopClient/2.1.0 Chrome/58.0.3029.110 Electron/1.7.8 Safari/537.36
X-Devtools-Request-Id: 7332.117
```

**Comment by christroutner** [comment]
[Here is the blockchain confirmation](https://blockdozer.com/insight/tx/3702f99d5f706532fa3585232ab230c849cb11b6bbc2faf84ea27aabaf2b6c4c). Confirmations are showing up accurately in the UI, but I keep getting an insufficient funds error. This smells like an issue with the SPV wallet. 

Here is my wallet address:

`bitcoincash:qza7qtt0y48palduqwzdq3fzsfkvd9v0u5k7k7r6nj`

**Comment by rmisio** [comment]
This looks like a server issue since it's the server api coming back with the insufficient funds issue. It would probably get more visibility from @cpacia if we logged this in the server repo.

**Comment by rmisio** [comment]
> Luckily, I had the debug window open in the Electron app and I was able to catch the API request. One thing I noticed is that the amount requested is 136585. Very weird.

That amount looks correct since it's in Satoshi (2$ worth of BCH in Satoshi ==> `(2 / 1464.29) * 100000000`).

**Comment by rmisio** [comment]
This is a server issue. Would you mind re-opening the issue there?
