### ISSUE TITLE
"See Price In Cart"

### ISSUE THREAD

**Issue by BillStrait** [OpenBazaar/openbazaar-desktop#1226]
As I get set up with distributors I find some products have a 'minimum advertised price (MAP)' which is not the same as the 'minimum price.' For example, a widget might have a MAP of $50, but I might want to sell it for $30. The work around for this is the "See price in cart" listing you'll sometimes notice in online retailers. 

It would be rad if OpenBazaar had this functionality. The implementation might say something like 'See price during checkout.'

**Comment by jjeffryes** [comment]
Thanks for the suggestion. We'll add this to our list of future features to consider.
