### ISSUE TITLE
Error pushing data to peer QmPPg2qeF3n2KvTRXRZLaTwHCw8JxzF4uZK93RfMoDvf2o: failed to find any peer in tabl

### ISSUE THREAD

**Issue by Manidos** [OpenBazaar/openbazaar-desktop#1229]
Brief Description: Can't connect to peers
Operating System:  Ubuntu 16.04
OpenBazaar version:  client 2.1.0, server 0.11.0
Hardware: Laptop
Reproducible: Always

Steps to reproduce:
1. Open terminal
2. type in openbazaar2
3. press enter

Observed Behavior:
First issue, the tab **ob://connected-peers** shows 0 peers.
Second issue, when navigating to a random shop e.g., ob://QmV2xo6De168QB9nkrYYuj6FVJeeczz9KEn1M2YTARLoNb/store/testing-search-albatros, the page is stuck indefinitely in loading state
Third issue, after creating a listing I get a message in the bottom of the window `publishing failed`

Expected Behavior:
Everything should be working

Additional info (links, images, etc go here):
My PC is behind a NAT device (WIFI router)

Any advice?

**Comment by jjeffryes** [comment]
If the terminal is showing 0 peers, your node isn't connecting to the network, which would cause all the other issues. 

This is a problem with the server software, can you close this ticket and open a new one in the server repo? That's the best way to make sure we get the appropriate attention on it.

https://github.com/OpenBazaar/openbazaar-go/issues
