### ISSUE TITLE
Will the address bar not have any border?

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#123]
I find it really hard to figure out where to grab the window when I want to drag it because there's no border on the address bar.

![image](https://cloud.githubusercontent.com/assets/45482/20838218/8e51a1fe-b875-11e6-81f3-242cd95995b5.png)

**Comment by morebrownies** [comment]
Yes, it should have a border.

**Comment by hoffmabc** [comment]
Ok good enough.

**Comment by jjeffryes** [comment]
To be clear, I think Brian means something like below. Is that correct?

![image](https://cloud.githubusercontent.com/assets/1584275/20843530/a6cb077a-b889-11e6-9935-b9575379dd59.png)

**Comment by hoffmabc** [comment]
Yes that's correct @jjeffryes it still isn't like that.
