### ISSUE TITLE
Add List View to Search Page

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1236]
Add a button to toggle the search results to a list format, like they do on the store page.

**Comment by rmisio** [comment]
@jjeffryes Is this one still needed? Was it decided we will not open list view as an option on search. It will only be available for crypto currency listings, where it's required to be on?

**Comment by jjeffryes** [comment]
We can close this. I think it might still be useful at some point in the future, but no need to do it now.
