### ISSUE TITLE
Store.html fails to load with unsupported Currency

### ISSUE THREAD

**Issue by ab10460ef3** [OpenBazaar/openbazaar-desktop#1239]
Issue:
A listing denominated in a currency not listed in data/currencies.js causes the store not to load with the erroneous message: 'Please provide an amount as a number ${amount}', because the price is not loaded in the Store collection.

Given there are a number of vendors selling gold and silver, it would be expedient to allow them to denominate their listings in XAU and XAG (which is _already_ provided by /ob/exchangerates/) without having to continually update listings or price conservatively upward  for volatility.   Users with older clients should be able to see the listings with a graceful warning.

Although an unsupported currency fails gracefully on the search page, with a yellow warning symbol and a nice tooltip, **on Store.html,** the price doesn't load into the collection, causing an exception to be raised about the price _amount._. The store page then spins forever, failing to load.

Swallowing the exemption on line 142 of Store.js brings about the desired behavior, but is probably not the best solution.

**Comment by rmisio** [comment]
> on Store.html, the price doesn't load into the collection, causing an exception to be raised about the price amount.. The store page then spins forever, failing to load.

That's a bug we need to fix. The expectation is that it gracefully fails like the search page.

> Given there are a number of vendors selling gold and silver, it would be expedient to allow them to denominate their listings in XAU and XAG (which is already provided by /ob/exchangerates/) without having to continually update listings or price conservatively upward for volatility.

@morebrownies @jjeffryes Do we want to allow listings to be denominated in Gold and Silver

**Comment by jjeffryes** [comment]
If they wanted to always sell at the market rate, it could be handy, since it would mean you're always selling X amount of gold (or silver) for whatever the exchange rate is for the currency it's being bought in. But is that what vendors want to do?

**Comment by morebrownies** [comment]
It seems like a reasonable request to me. We'd have to consider the details in a bit more depth, but it may layer in nicely to some of the other work we have planned in the near future.
