### ISSUE TITLE
Inventory doesn't seem to work

### ISSUE THREAD

**Issue by BillStrait** [OpenBazaar/openbazaar-desktop#1244]
I'm on Windows 10 with the latest release. 

Reproduce:

1. Create or Clone a listing.
2. Fill out the form as it is displayed.
3. Click the dropdown for 'Inventory Management' and select 'Track Inventory'
4. Press tab and enter a number. Press tab to leave the box or click out of it.
5. Click Save.

Quantity will reset to 0.

Moreover, when an item with quantity of 1 is sold, this listing still appears purchasable to visitors. It may prevent the purchase from going through, I'm not 100% sure.

**Comment by jjeffryes** [comment]
I see the same thing when I test this.
