### ISSUE TITLE
Button stacking leads to display issues on hover event

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#125]
@morebrownies another border issue

![image](https://cloud.githubusercontent.com/assets/45482/20838190/6c6daf2e-b875-11e6-8c89-820eb0cc19ca.png)

and here:

![image](https://cloud.githubusercontent.com/assets/45482/20838306/fcceed6c-b875-11e6-9861-5ae42dc4d027.png)

both message and follow have the issue

**Comment by morebrownies** [comment]
@jjeffryes this isn't a new issue, but it is apparent now that the border color changes on hover. Is this as simple as changing the z-index on hover? Or, is that a really hacky way to fix it?

**Comment by jjeffryes** [comment]
When buttons are part of a button strip, the border on one side is removed. 

The fix is to put the border back on hover, though making that work in all cases without overriding the border still might be tricky. I'll work on it.

**Comment by morebrownies** [comment]
I believe this has been fixed. Can we close this issue @jjeffryes?

**Comment by jjeffryes** [comment]
This was fixed.
