### ISSUE TITLE
Please style the Listing Data Changed <refresh> pop in message.

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-desktop#126]
When on your store and listing data changes, a pop in message appears urging you to refresh. The message is not super visible right now and is easily missed.

It's currently set with fixed positioning. The fixed positioning is important because the user may be scrolled very far down the store when we need to show the message, so having it be fixed will allow it to be at the top of their view no matter what scroll position they're at. Hopefully, the fixed positioning can stay. All else though is probably fair game.

![image](https://cloud.githubusercontent.com/assets/794517/20842945/43811be8-b86e-11e6-84ab-8aa852f6a4f0.png)

**Comment by morebrownies** [comment]
Will do
