### ISSUE TITLE
Missing signatures (SHA256SUMS)

### ISSUE THREAD

**Issue by Kixunil** [OpenBazaar/openbazaar-desktop#1264]
I can't download signatures of releases manually nor using verification script. It gives me error 404. Not sure if this is the right place to ask - please point me at correct place if I'm wrong.

Thank you!

**Comment by jjeffryes** [comment]
@hoffmabc this one's for you, I think.

**Comment by hoffmabc** [comment]
https://openbazaar.org/releases/SHA256SUMS.v2.1.0.asc should be there.

**Comment by Kixunil** [comment]
I've successfully verified it. Thank you!
