### ISSUE TITLE
Seller Has Dispute Button Before Fulfilling order

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1265]
The dispute button is present and clickable for the seller when the order is accepted, but not fulfilled. Attempting to start a dispute shows a server error.

The button shouldn't show when it's not usable, should it?

![image](https://user-images.githubusercontent.com/1584275/37290826-a80e6c76-25e3-11e8-9ac8-7638a8f7001b.png)

![image](https://user-images.githubusercontent.com/1584275/37290841-af95ea28-25e3-11e8-8b9a-e418f7d174ea.png)

**Comment by rmisio** [comment]
I'm not able to reproduce this one. Looking at the code, I'm also not sure how it's possible:

```
    } else if (this.vendorId === app.profile.id) {
      showDisputeOrderButton = this.moderatorId &&
        ['AWAITING_FULFILLMENT', 'FULFILLED'].indexOf(orderState) > -1;
    }
```

**Comment by jjeffryes** [comment]
I can reproduce it 100% of the time. Here are the steps:

1. Buyer buys a listing with moderation, and pays for it.
2. Seller opens the order details modal, and clicks the dispute button.

**Comment by rmisio** [comment]
oh right. It's because the server used to allow disputes on awaiting_fulfillment and it switched that now to be partially_fullfilled. I've fixed this in the escrow timeout PR.

**Comment by jjeffryes** [comment]
This was closed in the escrow timeout PR.
