### ISSUE TITLE
VPN Login via OpenBazaar?

### ISSUE THREAD

**Issue by irishpride44** [OpenBazaar/openbazaar-desktop#1273]
Login to a VPN (Virtual Private Network) server via OpenBazaar app to encrypt  data?

Thoughts?

**Comment by jjeffryes** [comment]
You can connect to a node on a VPS from the client currently, and all traffic is encrypted.

Are you asking how to do that?

**Comment by irishpride44** [comment]
So if you you connect to VPN service such as IPVanish via your web browsers the data is encrypted. OR if you use Hide My Ass VPN app, it works too?

So technically you don't have to uplink the OpenBazaar app to a VPN?

**Comment by jjeffryes** [comment]
I see you edited it from VPS to VPN, which is different. 

A VPN should work with OpenBazaar with no extra steps, but it will depend on how your VPN is set up.
