### ISSUE TITLE
Client sends localized timestamps to server for chat requests. 

### ISSUE THREAD

**Issue by BazaarDog** [OpenBazaar/openbazaar-desktop#1276]
The client is sending localized timestamps in requests to the chat server api.  This breaks all chat functionality in Arabic and presumably many future (as yet unsupported) locales.

Any chat message in Arabic returns a 400.

`{
    "success": false,
    "reason": "parsing time ''٢٠١٨-٠٣-١٦T١٦:١٨:٥٧-٠٤:٠٠'' as ''2006-01-02T15:04:05Z07:00'': cannot parse '٢٠١٨-٠٣-١٦T١٦:١٨:٥٧-٠٤:٠٠'' as '2006'"
}`

reproduce by setting system locale to 'ar' or 

adding the following to main.js

`
    const ua = mainWindow.webContents.session.getUserAgent();
    mainWindow.webContents.session.setUserAgent(ua, 'ar');
`

**Comment by jjeffryes** [comment]
I've validated that this happens when the user sets their language to Arabic. The data sent to ob/chat looks like:

```
{
   "subject":"",
   "message":"",
   "read":false,
   "outgoing":true,
   "peerId":"QmTMnWLbHgxjBNSr5a48yS4LQBhdUud7AvxyHfuRhuU3qj",
   "processedMessage":"",
   "timestamp":"٢٠١٨-٠٥-١٧T١٥:٣٠:٤٤-٠٤:٠٠"
}
```

Maybe we need to format the date in the template, and leave it in the format the server expects in the model?
