### ISSUE TITLE
Option to Remove Search Engine

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1282]
Users should have an option to remove a search engine after adding one.

The remove functionality is currently only accessible when an added search engine fails to return data.

Default search engines should not be removable.

**Comment by BazaarDog** [comment]
![screenshot_2018-03-21_11-07-41](https://user-images.githubusercontent.com/37419204/37718182-877b2834-2cf8-11e8-8ce3-9dedfc9cbb42.png)

**Comment by jjeffryes** [comment]
Ha! I thought that was in there someone when this was requested. It must be too subtle if I missed the feature I added myself when I double checked it.

Thanks @BazaarDog
