### ISSUE TITLE
blockchain.info/address does not support bech32, causes error when viewing payment details

### ISSUE THREAD

**Issue by pinheadmz** [OpenBazaar/openbazaar-desktop#1291]
The `View payment details` link in the moderator view of a dispute opens the contract payment address in blockchain.info, which causes an error if the address is bech32:

https://blockchain.info/address/bc1qfl894qr5f4xs0pczd9vlsrrlulczcc7a069xfsueq6patkdl9pgselad40

I was gunna write you a PR that switched the link to the payment _transaction_ instead but I'm guessing since that txid is not included in the contract, it's not sent to the moderator? 

I'm hope blockchain.info will support bech32 soon for this case it might be worth switching to an explorer that does support bech32 addresses:

https://en.bitcoin.it/wiki/Bech32_adoption

**Comment by rmisio** [comment]
@tyler-smith Am I recalling correctly that you fixed this one recently?

**Comment by tyler-smith** [comment]
@rmisio No, I fixed an issue with the blockdozer URLs being wrong. We might have to do what @pinheadmz said and change to a block explorer that support bech32.

**Comment by jjeffryes** [comment]
This is closed by #1334
