### ISSUE TITLE
Withdrawing everything from your wallet is needlessly hard

### ISSUE THREAD

**Issue by EchterAgo** [OpenBazaar/openbazaar-desktop#1312]
Brief Description: Withdrawing everything from your wallet is needlessly hard. There should be some "withdraw everything" button because otherwise you will have to guess what the minimum fee is to send as much as you can for as low of a fee as possible.

Operating System (OS and version): Windows 10
OpenBazaar version (shown on `About OpenBazaar` page in menu): client 2.1.1
Hardware: Core i7 4770, 16GB RAM, Radeon R9 280X

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Withdraw funds from wallet

Observed Behavior:
You have to guess what the maximum amount you can withdraw is

Expected Behavior:
There should be a simple way to withdraw everything

Additional info (links, images, etc go here):

**Comment by jjeffryes** [comment]
This is something we're planning to add at some point. I've created a server issue for the new API this would require.

https://github.com/OpenBazaar/openbazaar-go/issues/929

**Comment by jjeffryes** [comment]
UI work for this issue is tracked in #1373
