### ISSUE TITLE
There should be an optional refund address

### ISSUE THREAD

**Issue by EchterAgo** [OpenBazaar/openbazaar-desktop#1313]
Brief Description: There should be an optional refund address. If I am not using the included wallet, I want refunds to go back to e.g. my mobile wallet.

Operating System (OS and version): Windows 10
OpenBazaar version (shown on `About OpenBazaar` page in menu): client 2.1.1
Hardware: Core i7 4770, 16GB RAM, Radeon R9 280X

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Order something with funds from external wallet
2. Cancel order

Observed Behavior:
Funds arrive in the internal wallet

Expected Behavior:
Funds should optionally go into an external wallet

Additional info (links, images, etc go here):

**Comment by jjeffryes** [comment]
Closed, we're tracking this in #1433
