### ISSUE TITLE
Give vendor OpenBazaar.com link after a listing is posted

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/openbazaar-desktop#1319]
As soon as a vendor posts a new listing they should be given an OpenBazaar.com link that takes them to their listing on the web.

This will allow vendors to easily share their listings.

**Comment by rmisio** [comment]
What do you think @morebrownies? Should this be a straight link or some type of share bar with popular options?

Is this something you'd like to design?

**Comment by morebrownies** [comment]
Yes we should design something for this feature request @rmisio 

It would be nice to open any link in one click on the web. I'll need to figure out where/how we can layer that type of functionality into the client.

**Comment by rmisio** [comment]
> It would be nice to open any link in one click on the web. I'll need to figure out where/how we can layer that type of functionality into the client.

Ok sounds good. FWIW, I'm really confused as to whether the web version is an OB or OB1 type thing. I'm assuming it's the latter, otherwise it probably wouldn't make to only include a link to an OB1 service.

I guess we could clarify this during a req call.

**Comment by rmisio** [comment]
> The web version is branded as OpenBazaar.com, so we should be fine linking off to it.

I think we might need some clarification since in buy-only meeting earlier a statement was made that the web version is an OB1 product.

**Comment by morebrownies** [comment]
So we're launching a browse-only OpenBazaar.com product? And then a OB1.io buy-only product will be launched?

Yeah, I'm very confused now too. I'm not sure why the branding would need to change when we introduce buying.

**Comment by morebrownies** [comment]
I added a `Needs Requirements` flag to this issue since it's not clear what we're building.

**Comment by morebrownies** [comment]
Something that would be really nice to have is a quick link in the address bar for `View on web`. This link would ideally display when you're viewing: `a listing`, `a store`, `about page`, `followers page`, `following page`, etc. 

There are certain pages where we wouldn't want to display this link, such as: `transactions`, `order details`, etc

<img width="1024" alt="screenshot 2018-05-12 11 06 12" src="https://user-images.githubusercontent.com/13066886/39960273-805dc156-55d4-11e8-8081-9682b9545fb9.png">

**Comment by morebrownies** [comment]
Also, after the user saves a listing, we should display `View in client` and `View on web` links. I changed these to green links so that they stand out a bit better.

<img width="729" alt="screenshot 2018-05-12 11 09 37" src="https://user-images.githubusercontent.com/13066886/39960296-165eda28-55d5-11e8-9404-f7bca1237f69.png">

**Comment by rmisio** [comment]
Have we gotten any clarification on whether the web is an OpenBazaar or OB1 product? I assume if we're doing this, it's the former?

**Comment by hoffmabc** [comment]
OpenBazaar.

**Comment by jjeffryes** [comment]
Requirements for this issue are being tracked in #1372
