### ISSUE TITLE
Not sure if the yellow warning is hoverable but it's blocked

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#1340]
The warning indicator on the right gets blocked by the block and report options.

![image](https://user-images.githubusercontent.com/45482/39783666-cef1aab0-52e3-11e8-80e1-8b76fbb3cf48.png)

**Comment by morebrownies** [comment]
Maybe the buttons could display just to the left of the warning icon @rmisio?

I don't want to open a can of worms, but seems like the buttons displaying 50px more to the left wouldn't be that big of a deal.

**Comment by jjeffryes** [comment]
Maybe we can do another design pass on the no inventory indicator for the 2.2.1 release?

When the listing also doesn't have verified moderators, you get a yellow warning sign on both sides, which feels a little weird to me. 

![image](https://user-images.githubusercontent.com/1584275/39787277-978f267e-52f2-11e8-83c8-9cb1455317e0.png)

**Comment by rmisio** [comment]
Maybe... but keep in mind the yellow icon is not unverified mod thing, it's used in multiple places in the app as a generic warning that something is not right (yellow is generally used for non-blocking warnings, whereas red is used for more critical errors).

> which feels a little weird to me

maybe it will feel less weird one the tooltip is in place?

**Comment by morebrownies** [comment]
hmmm thinking out loud here but what if we swapped out the ⚠️ on the the far right with simple text that says: _Unknown_. Seems like that would be good enough for the short term.

As @jjeffryes mentioned, we should spend more time on the design of this later on, but I do find the double ⚠️ a bit strange too.

**Comment by rmisio** [comment]
> but what if we swapped out the ⚠️ on the the far right with simple text that says: Unknown.

sounds good to me. I think I like that better than moving the overlay buttons a few pixels over just to let an icon be hoverable.

If we follow through with this one, unless we want to wait a couple weeks, I think I'll leave it to @jjeffryes, since I'm about to sign off for a while.

**Comment by jjeffryes** [comment]
@morebrownies should the warning sign be swapped for the word unknown in the listing details and purchase screens too?

**Comment by morebrownies** [comment]
I would be fine with that @jjeffryes. I believe those locations also had tooltips when hovered, which will want to preserve.
