### ISSUE TITLE
Pricing for Cryptocurrencies are unclear

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-desktop#1343]
Brief Description: 
User reports issue of price not matching what is in their inventory. Expected to see fractional inventory represented with actual market value of fractional amount. (Ex: 0.01 ZEC expects to show (market price * 0.01) as the value instead of (market price)).

This might not be an issue of showing value of the whole inventory but instead indicating the price is for a unit of that currency?

![image 1](https://user-images.githubusercontent.com/305332/39821917-5520a486-5377-11e8-8a31-207666704b6b.png)
![image](https://user-images.githubusercontent.com/305332/39821918-5537549c-5377-11e8-979b-9ef0f9aa1516.png)

Context from OpenBazaar slack chat: https://openbazaar.slack.com/archives/C105NUSTC/p1525834068000195

**Comment by morebrownies** [comment]
Adding `(per 1 [coin])` next to the price would help a lot with the confusion here.

<img width="811" alt="screenshot 2018-05-12 10 32 43" src="https://user-images.githubusercontent.com/13066886/39960033-db4ad0f4-55cf-11e8-8f87-3283a306440f.png">

I'll have to think about the grid view more. I'm worried about lack of spacing there.

**Comment by rmisio** [comment]
@morebrownies I assume the suggestion above is no longer applicable given the new designs?

![image](https://user-images.githubusercontent.com/794517/40761905-9c268896-6452-11e8-90b4-fa5bea6ef572.png)

> Expected to see fractional inventory represented with actual market value of fractional amount.

It might just be a matter of having the use the feature once to adjust expectations.

**Comment by morebrownies** [comment]
That sounds correct @rmisio. The upcoming changes should address these issues. 

> It might just be a matter of having the use the feature once to adjust expectations.

Yes, agreed. Closing issue.
