### ISSUE TITLE
Improve the design of the listing card

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#135]
**Changes needed**
- The edit/delete buttons could be simplified (my fault for designing them to be so large)
- Add a slight transition on hover
- ~~Needs border radius~~
- #124 
- Delete confirmation

**OLD**
<img width="249" alt="screenshot 2016-12-02 11 45 36" src="https://cloud.githubusercontent.com/assets/13066886/20847913/da297da4-b884-11e6-841d-3d77b690805c.png">

**NEW**
<img width="243" alt="screenshot 2016-12-02 11 48 17" src="https://cloud.githubusercontent.com/assets/13066886/20848032/3c09f378-b885-11e6-916a-6b7ebb43f4b4.png">

**Comment by jjeffryes** [comment]
Just a note to not forget the deleted state in this PR.

**Comment by rmisio** [comment]
> Just a note to not forget the deleted state in this PR.

We need a design for that.

**Comment by morebrownies** [comment]
noted

**Comment by morebrownies** [comment]
We probably need to add a delete confirmation on click too "Are you sure you want to delete this listing?"

**Comment by morebrownies** [comment]
Hey @rmisio I think you mentioned that you started working on updating the edit/delete button styles on the listingCard. Is that correct? If so, which branch are the changes in?

**Comment by morebrownies** [comment]
I found them in master :)

**Comment by rmisio** [comment]
Correct, I made the JS changes needed to support the new design... so you're good to go to take it the rest of the way.
