### ISSUE TITLE
Request: Will OpenBazaar Create an App for the Librem 5?

### ISSUE THREAD

**Issue by davidpgil** [OpenBazaar/openbazaar-desktop#1351]
I believe OpenBazaar would be a hit on this new FLOSS phone coming out in early 2019 by Purism. Have you/ will you guys looked into it?

**Comment by jjeffryes** [comment]
We haven't heard of that, thank you for bringing it to our attention.

Currently we're focused on building and testing the OpenBazaar reference applications on platforms with wide adoption. If PureOS becomes widely used, they we'd certainly consider providing support for it.

**Comment by davidpgil** [comment]
I think it will be widely used in the circles of people who are into decentralization, FOSS, and cryptos. Have you seen how successful the crowdfund was? You can still get a development board that is coming out this summer. Strike while the iron is hot!

https://puri.sm/shop/librem-5/

**Comment by davidpgil** [comment]
I think you guys should approach Purism and have OpenBazaar be part of the launch suite of apps included with the phone.
