### ISSUE TITLE
[feature] Markup / Price equations for cryptocurrency listings

### ISSUE THREAD

**Issue by premek** [OpenBazaar/openbazaar-desktop#1356]
Sorry if this is a duplicate. Currently you can sell cryptocurrency only for its market value. I don't think this is motivating enough for merchants to do so

Merchants should be able to add fixed or percentage markup to be able to make profit and competition between merchants.

See how it works on localbitcoins.com: https://localbitcoins.com/guides/equation-howto/

**Comment by jjeffryes** [comment]
The current cryptocurrency listing feature is very much a minimal implementation so we can experiment with it. We expect to iterate on it and add features like a markup once we have some feedback (like this issue).

**Comment by jjeffryes** [comment]
I'm closing this issue, we are tracking the requirements for a markup feature in #1371
