### ISSUE TITLE
Coupon Codes are Case Sensitive

### ISSUE THREAD

**Issue by jashot7** [OpenBazaar/openbazaar-desktop#1360]
Link to the issue on the server:
https://github.com/OpenBazaar/openbazaar-go/issues/950

Coupon codes should probably not be case sensitive.

**Comment by rmisio** [comment]
Hmm... I'd be curious to know how other sites work, because I would assume that they should be case sensitive.

**Comment by rhcastilhos** [comment]
This was already discussed in #882

**Comment by jjeffryes** [comment]
Thanks for the reminder @rhcastilhos 

The codes have to be case sensitive or the hashes wouldn't match..
