### ISSUE TITLE
Incorporate CoinMarketCap Coins

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#1361]
Need to increase amount of coins offered to the full suite.

**Comment by morebrownies** [comment]
Yes, please. 1500+ would be amazing

**Comment by rmisio** [comment]
This is really a ticker issue. The client is set-up to handle whatever the ticker has exchange rates for.

Anyhow, our ticker hero @tyler-smith is on it and it should be coming soon.
