### ISSUE TITLE
Storefront improperly displaying unverified moderator badge

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/openbazaar-desktop#1363]
A store with verified moderators shows listings with the unverified moderators badge when viewing the storefront. The correct badge displays on the listings from search and when viewing the listing itself.

![screenshot from 2018-05-17 11-50-59](https://user-images.githubusercontent.com/6955773/40203392-10498e68-59f3-11e8-9e51-eb7ffe843537.png)

![screenshot from 2018-05-17 11-51-08](https://user-images.githubusercontent.com/6955773/40203403-167e9904-59f3-11e8-96a7-6d278bac1f89.png)

**Comment by jjeffryes** [comment]
This turned out to just be due to the store server needing to be updated to the latest release.
