### ISSUE TITLE
Add Markup to Crypto Listings

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1371]
## User Story
As a seller, I want to be able to price my crypto listing above or below the market price.

### Edit Listing
- [ ] Show accepted crypto currency to currency being sold where the title would normally be.
-[ ] The title is not shown, and can not be edited, but should still be saved. It should have the format of `${payment currency code} -> ${currency code for sale}`. For example "BTC -> ZEC'.
- [ ] If the title is changed outside of this client, when it is saved in this client it will be overwritten with the format above.
- [ ] If the coin for sale changes after the listing was saved, and is saved again, the title should be updated. The slug will still be based on the old title, like it is with other listings.
- [ ] The for sale coin select list should be renamed ’Trade’.
- [ ] The for sale coin select list should have coin icons at the start of each coin name option label.
- [ ] A new price modifier input should be added. It is a percentage number field, which can have up to 2 decimal places, and can be negative.
    - [ ] We need to determine how to handle the decimal points when communicating with the server to avoid floating point issues. This is already done with coupon discounts, we can probably use the same pattern that is used there.
    - [ ] The price modifier input value is negative if a minus sign is manually entered in front of the number. It should accept a space or no space between the minus sign and the number. It should also accept a plus sign as positive.
    - [ ] The price modifier cannot be less than -99.99%, and cannot be more than + 1000%.
    - ie: "-0.01," "- 99.99," "10," "+5," and "+ 1000" are all valid values.

### Discovery
- [ ] The design of cryptocurrencies when displayed in a list should be updated (see design).
- [ ] Each listing would show if it is over, at, or under market price and by what percentage.

### Listing Details
- [ ] The title treatment from the edit listing should be shown here.
- [ ] The conversion rate between the buying and selling coins should be shown.
- [ ] The buy button should say Trade Now.
- [ ] The inventory should have a coin icon.
- [ ] This line should gracefully shift to two or more lines if it is too big when it is translated into other languages.

### Purchase
- [ ] The title treatment from the edit listing should be shown here.
- [ ] The amount of the user's coin being spent for the current quantity being bought should be shown under the title.
- [ ] The quantity would have an option to purchase a quantity in fiat, if the user has a fiat currency. For example, purchase $30 of ETH.
    - This is considered a nice to have, and is optional.
- [ ] REVISION: The total inventory available will be shown.
- [ ] The price per coin should be shown with the percentage above or below the market, and color and an icon indicating if it is at, above, or below.
- [ ] The receipt should show the title treatment.

### Transactions
- [ ] Show the title treatment.
- [ ] The purchases, sales and cases APIs will need to be updated to support the data needed.

### Order Details
- [ ] Add the coin icon when fulfilled.
- [ ] Add a coin icon to the payment.
- [ ] REVISION: The icons next to the payment will remain unchanged. The crypto coin icon could be added to the payment amount next to it, but that is considered optional, since that could impact many parts of the app.
- [ ] REVISION: The conversion rate will be removed from the design, due to not having data for the relative prices at the time of the payment.
- [ ] Show the percentage above or below the market, and color code the amount.
- [ ] Show the icon on the payment address.

## Notes
- When multicoin wallets are supported, we will need to decide how to handle that in crypto listings.

## Data
Server changes are documented here:
https://github.com/OpenBazaar/openbazaar-go/issues/962

**Comment by premek** [comment]
just a note on how it works on localbitcoins.com: https://localbitcoins.com/guides/equation-howto/
its more complex than just percentage as it allows to set fixed markup or different markup for different quantity.

**Comment by BazaarDog** [comment]
I feel like this should work...

```
{
	"listing":{
		...
		"metadata": {
			"contractType": "CRYPTOCURRENCY",
			"format": "FIXED_PRICE",
			"coinType": "XMR",
			"pricingCurrency": "XMR",
			"acceptedCurrencies": [
				        "BCH"
				    ],
			...
		}
		"item":{
		...
		"price": 1.05,
		...
		}
}
```

And this should work as a market

```
{
	"listing":{
		...
		"metadata": {
			"contractType": "CRYPTOCURRENCY",
			"format": "FIXED_PRICE",
			"coinType": "XMR",
			"pricingCurrency": "BCH",
			"acceptedCurrencies": [
				        "BCH"
				    ],
			...
		}
		"item":{
		...
		"price": 0.172463,
		...
		}
}
```
