### ISSUE TITLE
Add View on Web Links

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1372]
## User Story

As a seller, I want an easy way to access a web link to my listing. I should be able to click on it to open it in a web browser.

As a user, I want an easy way to access a web link to pages that are available on the web, like store and listing pages. I should be able to click on a link to open it in a web browser, and copy the link so I can paste it when I want to share it.

As a user, it would be ideal if I could easily post web links directly to common social media platforms without needing to copy it.

### Edit Listing
- [ ] When a seller creates or edits a listing, a view in web link should appear next to the current view in store link.
- [ ] If a listing hasn't finished publishing, trying to view it in the web will result in a not found page or an out of date version of the listing (if the user is editing the listing). There should be a tooltip explaining changes may not show up right away on the web, even after they have been published.

### Address Bar
- [ ] The address bar should show an open in web link for some pages.
    - [ ] The user page individual tabs (home, store, followers, following).
    - [ ] Listing pages.
-[ ] When the address bar is active (has focus, the user wants to edit or copy the text), the view on web link is hidden so they have full access to the text.
- [ ] The left side fo the view on web link should have a fade in case the address bar overlaps it (under it).

### Purchase
- [ ] The social sharing buttons at the end of the purchase flow should be changed to use the web link instead of the app link.

## Preliminary Designs
![image](https://user-images.githubusercontent.com/1584275/40425415-48d87ee8-5e66-11e8-8414-0c1e852ef8b4.png)

![image](https://user-images.githubusercontent.com/1584275/40425404-41131362-5e66-11e8-9553-adc91ecbaafb.png)

**Comment by rmisio** [comment]
> The view in web link should have a copy icon or other method to copy the link without having to open it in a browser. This is a nice to have, not a critical requirement.

Personally, I'd opt for not cluttering the UI with this. I'm not seeing why having to the open the link the browser to copy it from the browser's address bar is too heavy of an ask.

**Comment by morebrownies** [comment]
Something to consider: Within the address bar, the URL text may extend long enough to overlap with the `view on web` link. We'll want to handle this nicely, I'm thinking something like below:

![screenshot 2018-05-23 11 08 07](https://user-images.githubusercontent.com/13066886/40442879-992cbd4c-5e79-11e8-8112-6399bcb6ac1e.png)

I have a box behind the `view on web` link with a white background and opacity set to 96%

**Comment by rmisio** [comment]
> Within the address bar, the URL text may extend long enough to overlap with the view on web link.

We'll handle it. I suppose another option is truncating with ellipses.

**Comment by morebrownies** [comment]
Yup, ellipses could work too. I'm fine with either approach.

**Comment by morebrownies** [comment]
Do we have an idea of how quickly new listings get indexed by OB1 and other search providers? 

Creating a listing, saving it and clicking `View on web` may lead to 404 in most cases. I wonder if there is a way to improve the UX here? It would be very nice if you could see that listing on the web almost immediately after saving it. 

Now that I think of it, editing a listing will also be strange if there's lag between saving in client, and seeing new changes live on the web.

**Comment by rmisio** [comment]
> Do we have an idea of how quickly new listings get indexed by OB1 and other search providers?

Tyler might have an idea about OB1, but that's very much a variable thing.

> Creating a listing, saving it and clicking View on web may lead to 404 in most cases. I wonder if there is a way to improve the UX here?

hmmm... I think the simplest thing maybe would be to add a tooltip explaining that it may take some time for the listing to appear/update on the web.

> It would be very nice if you could see that listing on the web almost immediately after saving it.

That's not in our hands really. At least with OB1, we could do our best to make sure the indexing is as fast as possible, but it's never going to be instant.

> Now that I think of it, editing a listing will also be strange if there's major lag between saving in client, and seeing new changes live on the web.

I don't think there's an alternative. Users will need to understand that crawling is not instant. It's not different than the fact that the listing won't show up / update in discover for some time.

**Comment by rmisio** [comment]
> Creating a listing, saving it and clicking View on web may lead to 404 in most cases. I wonder if there is a way to improve the UX here?

This doesn't have anything to do with the search index. I think it has to do with when the publish is complete so the gateway could retrieve it form IPFS. Publishes usually take about 30 seconds or so.

I suppose we could wait until the publish completes until displaying that link, but that gets a little hairy to depend on a socket like that. Plus that state would be a very fleeting thing only when you save the listing. The address bar wouldn't have the state.

I think the easiest thing may be to just put a tooltip that says something to the effect of "there may be a delay before the listing is available / updated on the web".

Although, I would first want to see if there is a delay and how long. If we find the delay is minuscule and infrequent... maybe we find the tooltip isn't even necessary...?

> Now that I think of it, editing a listing will also be strange if there's major lag between saving in client, and seeing new changes live on the web.

I think there always will be a delay. Not only are you waiting for a publish, but I'm pretty sure our web client implements some caching.

**Comment by rhcastilhos** [comment]
I suggest adding a link "view QR code" on the listing page besides "View in client" and "View in web", which would display an exportable QR code image.

Motives:
- there are no @handles yet
- typing/writing down "QmNU2H1S1gNf782s9gvFFV9jUKBSy7uuWU8QtAA2N3bhFZ" takes time
- QR codes are one of the best ways to share a URL in PowerPoint presentations and on printed paper (magazines, folders,...). URL shortener is also an option.

**Comment by morebrownies** [comment]
Added tooltip

![screenshot 2018-06-04 11 37 05](https://user-images.githubusercontent.com/13066886/40935022-a58185a2-67eb-11e8-8a27-0be4973bb74d.png)

**Comment by rmisio** [comment]
@jashot7 You may want to adjust the tip so it's not covered by chat:

![image](https://user-images.githubusercontent.com/794517/40938582-1c09a654-67f7-11e8-9aa1-2da09a58b747.png)

You could either always have the tip like that, or selectively when chat is open (the body gets a `chatOpen` class).

**Comment by jashot7** [comment]
> The social sharing buttons at the end of the purchase flow should be changed to use the web link instead of the app link

Currently, we're not sharing any app link. We're simply sharing 'hey, check out openbazaar.org!' copy with that link.

@morebrownies Do we intend to switch this copy to some regarding sharing the individual listing along with that listing's URL?

**Comment by jashot7** [comment]
<img width="731" alt="screen shot 2018-06-06 at 1 50 43 pm" src="https://user-images.githubusercontent.com/392798/41056642-dc5bcaee-6992-11e8-99be-ed6ee167d9f5.png">

**Comment by jashot7** [comment]
<img width="559" alt="screen shot 2018-06-06 at 2 07 16 pm" src="https://user-images.githubusercontent.com/392798/41056668-f09d90b4-6992-11e8-8b1d-31616ffa2d50.png">

**Comment by morebrownies** [comment]
Hey @jashot7 thanks for pointing that out. What we have in place now is probably fine as is. Embedding the product purchased into this social share seems like it could introduce some privacy concerns. I think we should keep it generic (as it currently is) for the time being.
