### ISSUE TITLE
"Vendor has fulfilled your order" message should not appear when buying crypto

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#1376]
I bought 0.04 units of a cripto but vendor sent only 0.02. However, OB displayed the message "Vendor has fulfilled your order" which is misleading.

Imagine someone is buying 0.8509284092 units and some malicious vendor sends 0.6509284092 units and OB shows "Vendor has fulfilled your order".

I suggest adding a warning: "Coin transfers are not automatic. Always check your wallet to see if you received everything you bought."

**Comment by jjeffryes** [comment]
How is this different from other order types? If a vendor is shipping you a package, it's up to you to check your mail box instead of just accepting it's been delivered when the vendor claims it was fulfilled. The same is true for digital and service orders.
