### ISSUE TITLE
Add "Copy everything to clipboard" function in Order Details

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#1377]
Now only "Order #" and "Ship to" have a "Copy to clipboard" function. 

Some vendors have another person sending items for them, therefore they must send an email each time a sale is made. I'd like to have a function "Copy everything to clipboard".

"Delivery Time" information is also missing on "Order Details" page, and this is something importantto give to the person which will send the items.

So, all the following information should be copied to clipboard:
"
Order #:
Accepted:
Payment Details:
Order Details:
- Listing:
- Ship to:
- Coupons:
- Quantity:
- Moderator:
- Total: 
- Shipping Option:
- Shipping Service:
- Delivery Time: 
- Memo:
- Additional Contact Information:"

**Comment by rmisio** [comment]
We will not be implementing this at this time. If more users request it, we may revisit.
