### ISSUE TITLE
Moderator Title not being translated

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#1378]
Some titles are not being translated, even though they are translated in translation files.

![image](https://user-images.githubusercontent.com/10789865/40518112-44b7dc44-5f8f-11e8-8700-aa6c31387522.png)

![image](https://user-images.githubusercontent.com/10789865/40518158-80b98efe-5f8f-11e8-9824-06ab6310a1f5.png)

![image](https://user-images.githubusercontent.com/10789865/40518149-7468cd72-5f8f-11e8-9414-354f41763830.png)

**Comment by jjeffryes** [comment]
Are you seeing this in the 2.2 release, or in master?

If it's in the release, this is a known issue, it is fixed in master and will be in 2.2.1.

**Comment by rhcastilhos** [comment]
In 2.2 release.

**Comment by jjeffryes** [comment]
Ok. I'm closing this, as it's been fixed in master.
