### ISSUE TITLE
Truncate the transaction ID on the Order Detail screen if it's beyond 5 lines

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-desktop#1387]
Currently there's a `clamp3` class in place, but it doesn't work because the field is inline. The field is `inline` because it should be on the same line as the label and trailing `Copy` link.

A simple fix may be to count how many chars approximately would make up 5 lines and just manually (in js) cap the string to that length and if it had exceeded that length, put the ellipse character after it.

It's not as precise as the CSS truncation method, but the main idea here is to not let ridiculously long transaction IDs break the layout.

(FWIW, it should just be capped in the template. The view should maintain the uncapped one so the uncapped one is copied via the Copy link)

**Comment by jjeffryes** [comment]
The server is limiting the transaction ID to 512 characters (MaxTXIDSize), would that end up taking too much space in the template?

**Comment by rmisio** [comment]
> The server is limiting the transaction ID to 512 characters (MaxTXIDSize), would that end up taking too much space in the template?

Yeah, that's true. I thought the server wasn't limiting it, but 512 makes this issue moot.
