### ISSUE TITLE
Add cryptocurrency codes to quantity fields

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#1390]
![image](https://user-images.githubusercontent.com/10789865/40760845-09c0c4ea-646f-11e8-8255-4d28cded99e0.png)

**Comment by rmisio** [comment]
This has already been designed. Will likely be in the next major release.

![image](https://user-images.githubusercontent.com/794517/40761649-574ea2c2-6451-11e8-9a7a-7b33289f7860.png)

**Comment by rhcastilhos** [comment]
I would like to see "22.50 ZEC" in Order Summary

**Comment by rmisio** [comment]
Thanks for the suggestion, but I don't think we're going to do that. We have space limitations and things are tight as it is. We'll keep an eye for this and if there's enough feedback to add the code, we can revisit.

**Comment by jjeffryes** [comment]
This will be superseded by the design changes being worked on now.
