### ISSUE TITLE
Text editor (Trumbowyg) is not translated

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#1395]
Listing text editor (Trumbowyg) is not being translated. However the editor has language parameters that could be configured (https://alex-d.github.io/Trumbowyg/documentation/#localization)

![image](https://user-images.githubusercontent.com/10789865/40803241-8501475e-64ee-11e8-8843-d8a01c70a356.png)

**Comment by rmisio** [comment]
@jashot7 This could be fun one to dig into since this deals with a third party plugin. The poster shared a link, so they have some type of localization support that we could probably tap into.
