### ISSUE TITLE
Analytics Enhancements

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1407]
Add the following enhancements to the metrics system.

- [x] Add a version tracking system so the opt in can be shown again if the current version of the analytics is updated. For instance, if the user has opted into version 1, and the analytics is now version 2, the opt in should be shown again with changes highlighted.
- [x] Refactor common segmentation like error: none so it doesn't have to be repeated.

### Opt In Modal
- [ ] Add changes to the description, with the release version they were changed in.

### Specific Events
- [x] Discover_SearchError: add segmentation for the provider.
- [x] Purchase_PayFromWallet: can this record if it was done from the purchase or order details screen?
- [x] Purchase_ConfirmBoxInsufficientFunds/Purchase_ConfirmBoxEstimatedFeeFailed: consolidate these into a single start/end event.

### New Events
Edit: Add the following events. Each one will be recorded as an event with no other data, unless segmentation is noted, as standard for our analytics events.
- [x] Searches from the address bar.
- [x] Track events like fulfillment in the order details view.
- [x] Create listing.
- [x] Clone listing.
- [x] Delete listing.
- [x] Edit listing.
- [x] Save listing.
    - type of listing.
    - new or edited.
- [x] Open settings.
    - tab
- [x] Significant buttons in settings/advanced
- [x] Clicking the wallet receive money button.
- [x] Clicking the wallet send money button.
- [x] Opening the feedback modal.
- [x] Clicking on a notification.
- [x] Chat, message sent, message received.
- [ ] If possible, record payment events in a way that shows how common paying with an external wallet vs. the internal wallet is.

### Session Issues
- [ ] Fix bug where the session sometimes ends while the user is still using the app.
- [ ] See if there is a way to record the currently loaded page when the session ends.

**Comment by rmisio** [comment]
> Searches from the address bar.

Yikes. Count me out of any such opt-in!

**Comment by jjeffryes** [comment]
@rmisio this is just a list of events to record, all that's recorded is that the event happened. If any other details are recorded, it's noted.
