### ISSUE TITLE
Make Sure BCH QR Codes Have a Prefix

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1408]
An upcoming server release will remove the prefix from BCH transaction addresses (bitcoincash: for mainnet and bchtest: for testnet).

The client should add the prefix to the QR code text for BCH addresses, but only if it is missing. Old orders may still have the prefix, the address should not end up with duplicate prefixes.

**Comment by jashot7** [comment]
Done. PR merged.
