### ISSUE TITLE
Allow Blocking of Undesired Followers

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/openbazaar-desktop#1409]
Some of my followers sell things I don't agree with. I would like a way to prevent them from following me AND stop seeing their follow in my Followers page. Right now if I Block them, their follow is still visible in my page with a message that says the user is blocked, but what I really want is to also not see that user as a follower as well.  

Is this enhancement in the roadmap?

**Comment by jjeffryes** [comment]
We don't have any plans to add that feature in the foreseeable future.

It could be done, but it would be low priority compared to tasks like adding a multi-cryptocurrency wallet or a browser accessible experience.

**Comment by jjeffryes** [comment]
To clarify, we could hide blocked followers, but we can't easily prevent another user from following anyone.

Currently, no one is aware of your block list, so there isn't a way for other nodes to know if they've been blocked or not.

**Comment by jjeffryes** [comment]
I'm going to close this issue, I don't think it's something we plan on adding in the near future. If there are more requests for it we'll revisit it.
