### ISSUE TITLE
[moderating dispute] Typo? "Vendor's contract has not arrived" when it is the BUYER's contract that has not arrived

### ISSUE THREAD

**Issue by pinheadmz** [OpenBazaar/openbazaar-desktop#1411]
client 2.2.1 (OSX)

server 0.12.0 (Linux, Raspberry Pi)

![screen_shot_2018-06-11_at_8 04 19_am](https://user-images.githubusercontent.com/2084648/41251984-a00965f6-6d70-11e8-997c-78140657009a.png)

**Comment by jjeffryes** [comment]
@pinheadmz is this the same issue as #1412 or is it on a different order?

**Comment by pinheadmz** [comment]
@jjeffryes This is a different issue. I see this buyer/vendor typo on every case I moderate before the buyer's contract arrives.

**Comment by jjeffryes** [comment]
@rmisio can you take a look at this?

**Comment by rmisio** [comment]
@jjeffryes Sure I'll do that today.
