### ISSUE TITLE
[moderating dispute] handle no-show better, don't require both users to be online

### ISSUE THREAD

**Issue by pinheadmz** [OpenBazaar/openbazaar-desktop#1412]
client 2.2.1 (OSX)

server 0.12.0 (Linux, Raspberry Pi)

I have two moderation cases where one party is totally missing-in-action and may never come back online. Is it possible, maybe after a hard-coded time out of 3 days or something, for the moderator to resolve a dispute with only one other party and only that party's contract? Maybe not to avoid fraud, but doesn't the vendor's contract have a buyer's signature on it? Would be great is that was enough.

An alternative would be if the vendor's server could automatically sweep a transaction after the 45 day timeout. I know that branch exists in the bitcoin UTXO script, but I don't know if it's automatically handled by the server, or visible in the GUI yet.

I'm just getting a lot of nervous vendors with stuck BTC.

![screen shot 2018-06-11 at 12 14 12 pm](https://user-images.githubusercontent.com/2084648/41252085-fa66a888-6d70-11e8-9254-04c406df03d5.png)

**Comment by jjeffryes** [comment]
I think you can resolve the dispute 100% for the party you have the contract for. You just can't split it if you don't have both contracts.

We will support the vendor pulling the funds for a transaction 45 days after a dispute has started in the next release.

**Comment by pinheadmz** [comment]
both `buyer amount` and `vendor amount` fields are greyed out:

(css)
```
pointer-events: none;
none.orderDetail .resolveDisputeTab.buyerContractUnavailable .inputBuyerAmountWrap_orderDetail.scss:490
```

**Comment by pinheadmz** [comment]
Ha, ok -- by editing the client CSS in "developer tools" I was able to allow pointer-events, fill in the percentages (0 & 100) and submit!

**Comment by jjeffryes** [comment]
My fault, it used to be possible but we changed it.

@morebrownies in situations where one party in a dispute never comes back online to send their contract, should we allow the mod to settle it 100% in their favor, and show a message that they have that option?

**Comment by rmisio** [comment]
> in situations where one party in a dispute never comes back online to send their contract, should we allow the mod to settle it 100% in their favor, and show a message that they have that option?

@jjeffryes not sure if I'm misunderstanding you, but the server will not allow you to award any funds to a party whose contract it did not obtain.

I will allow you to award fully to the parties whose contract you do have, which @pinheadmz has seemed to do. It looks like the UI was blocking it and if so, that's a bug in the UI, because it should be allowed.

**Comment by rmisio** [comment]
@pinheadmz Would you be able to provide the response of the 'order' api call (e.g. `http://localhost:4302/ob/order/QmTZmYi4ZhRr9JcPmHAiZssMY1QdAiSSnzCjg7jNnpVia2`) on the order where this happened?

It's available via the Network tab and XHR subtab and Response sub-sub tab.

![image](https://user-images.githubusercontent.com/794517/41262029-810fa7c8-6d93-11e8-9517-aa3a25d1cb12.png)

**Comment by rmisio** [comment]
![image](https://user-images.githubusercontent.com/794517/41262094-d0949934-6d93-11e8-96f1-5ed0daed8fde.png)

Oh interesting. @pinheadmz Is it the vendor that you awarded the funds to?

Looks like the vendor had a processing error, which is possibly why the client was not letting you award funds to it. I'm not sure why the vendor would be entitled to the funds if they had a processing error. It means the order would never progress beyond that state. Unless... the vendor fulfilled it offline and outside of the OB flow?

Who opened the dispute? I thought a vendor could not open a dispute when the order is an error state, but if the buyer opened a dispute then you would have their contract.

**Comment by pinheadmz** [comment]
Yeah the vendor opened the dispute because the buyer never confirmed and never responded to messages, including inside the dispute discussion. I'm comfortable making API calls from the command line on the server. The `order` call returned not found, but I called `case` with the order ID and got all the info. Its long! And also might break privacy, should I send it to you on slack instead of public GitHub issue?

**Comment by jjeffryes** [comment]
> @jjeffryes not sure if I'm misunderstanding you, but the server will not allow you to award any funds to a party whose contract it did not obtain.

Right. I was saying award all the funds to the party he did have the contract for.

**Comment by jjeffryes** [comment]
@rmisio when you have time, can you follow up with @pinheadmz and see if you can find out what happened here?
