### ISSUE TITLE
Multicoin Integration - Wallet

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1425]
## User Story
As a multicoin wallet user, I want to be able to see all the coins I use in my wallet, and see the balance and transactions for each one separately.

It should be easy for me to send and receive funds for any coin the multicoin wallet supports manually. My node should be able to handle transactions in any coin the multicoin wallet supports without needing action from me.

As a user, I should not need to worry about adding or removing coins, my experience should be focused on interacting with the coins in my wallet that are active. My wallet should always be able to handle new transactions in coins it supports.

## Functional Requirements
The multicoin wallet will always support all coins it can support. The user won't ever turn coins on or off. If they don't want to use a particular coin they can simply not create listings that accept that coin.

Note: we will eventually support wallet plugins, but there would never be two wallets with the same coin running at the same time. If a plugin wallet handles a coin the multicoin wallet handles, the plugin would be used instead.

- [x] The wallet screen will need a way to select the current coin it is displaying.
- [x] The send and receive buttons should apply to the current coin being viewed.
- [x] There should be some way to see all your wallet balances at once, so you don't have to check them one by one.
    - This could be an "all coins" view, or a sidebar with just the coins and their balances, or the balance could be shown next to each coin name in the control to select a coin screen.
- [x] Add a coin parameter to the API calls detailed below.
- QUESTION: should there be a Shapeshift feature to move funds from one of your coin wallets to another easily, without having to manually get a receive address and enter it into a shapeshift dialog (ie: a quick send X of coin Y to wallet Z)?
    - an example is the Jax wallet, or the Exodus wallet.
- [x] The resync button should be moved to the wallet screen, and apply to one wallet at a time. It should have the same restrictions on once per hour it does now.
- [x] The client config for coins should be updated if there are new coins.

## API Changes
The config will need to return a list of coins/wallets that are available.

The following calls will need a coin parameter in data or the path.
ex: wallet/BTC/address or coin: BTC
- GET wallet/address
- GET wallet/balance
- GET wallet/transactions
- GET wallet/status
- GET wallet/fees
- POST wallet/spend
- POST wallet/bumpfee
- POST wallet/resyncblockchain
- the wallet socket for new transactions will need to send a coin type.
- the wallet socket for first confirmation on a transaction will need to send a coin type.
- the walletUpdate socket will need to return an object of data keyed to coin types or separate socket data would need to be delivered for each wallet.

We might want the following calls to accept an array of coins, so a single call can get the data for multiple coins.
- GET wallet/balance
    - this could be an 'all' parameter or just no coin parameter

**Comment by rmisio** [comment]
> There should be some way to see all your wallet balances at once, so you don't have to check them one by one.

Can we please mirror existing multi-coin wallets on this one to make sure we are not taking on more scope than users are expecting.

For example, the Trezor web wallet does not do this.

I'll also defer to @morebrownies on how critical he thinks this would be.

**Comment by rmisio** [comment]
> QUESTION: should there be a Shapeshift feature to move funds from one of your coin wallets to another?

Would that need to be seperate from our existing shapeshift button. It would accomplish the same thing right?

**Comment by rmisio** [comment]
> Would it be better to have the list of preferred coins in the wallet?

Hmm... that seems like a settings piece of data to me.

**Comment by rmisio** [comment]
Various sockets will need to update:

- The `wallet` socket which comes for new transactions and when a transaction gets it's first confirmation will need the coin type added to it.
- The `walletUpdate` socket which comes on a regular interval and gives us the current block
height which we can use to update the confirmations on a transaction should now return a list of data keyed by coin type so that we could have the current block height of each coin.

**Comment by morebrownies** [comment]
> There should be some way to see all your wallet balances at once, so you don't have to check them one by one.

> I'll also defer to @morebrownies on how critical he thinks this would be

Hey @jjeffryes @rmisio I think this would be nice to have, assuming the overhead isn't extremly complex. Giving a high level view across coins could surface information quicker to users, which is valuable, but I wouldn't say it's a show stopper if we couldn't get it working right away.

**Comment by jjeffryes** [comment]
> Would that need to be seperate from our existing shapeshift button? It would accomplish the same thing, right?

Yes and yes. The idea is it would be a streamlined "send 0.1 BTC to my BCH wallet" button. The same thing could be done by opening a wallet, copying the receive address, then switching to another wallet and pasting it into the send screen. 

So not a requirement, just something I thought could be handy if users want to move coins around in their wallets. It could easily be deferred or made a stretch goal.

**Comment by christroutner** [comment]
I see this issue covers high-level requirements. Is there any documentation/ideas/specifications on the low-level implementation of the web wallet? For example, how it will be implemented in the openbazaar-go server?

**Comment by jjeffryes** [comment]
> I see this issue covers high-level requirements. Is there any documentation/ideas/specifications on the low-level implementation of the web wallet? For example, how it will be implemented in the openbazaar-go server?

Not yet, we're still figuring that part out.
