### ISSUE TITLE
View in web link in address bar should handle potentially long translations.

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-desktop#1437]
![image](https://user-images.githubusercontent.com/794517/42239583-3456ada0-7eb9-11e8-8d95-d5ef7fe8d593.png)

The View On Web link in the address needs to handle potentially longer translations. While 80px works for English, it might be insufficient for other langs. Can it maybe have a default of 80px, but grow up to a reasonable amount (I dunno, maybe 120px) if necessary? If it is longer than that, can it please be truncated with ellipses... since breaking to a second line doesn't look right?

**Comment by jjeffryes** [comment]
@jashot7 is this in progress? I'm just asking so I can update zenhub.

**Comment by jashot7** [comment]
Ah, sorry - I missed this in the influx of notifications, @jjeffryes. I just put in a PR for it.
