### ISSUE TITLE
Inconsistent ordering of transactions items

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#1449]
Transactions page: Sales, Purchases, Cases
Menu: Purchases, Sales, Cases
![image](https://user-images.githubusercontent.com/10789865/42934461-91a7fd0c-8b47-11e8-865b-68a5bf6dbad8.png)

**Comment by rmisio** [comment]
@morebrownies Any objection to this one?

**Comment by morebrownies** [comment]
Nope, sounds good to me.
