### ISSUE TITLE
Followers can be NaN

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1450]
When a node has no followers, the number shows as NaN instead of 0.

After the page was refreshed, it shows as 0.

![image](https://user-images.githubusercontent.com/1584275/42964533-58539732-8b65-11e8-9982-8a846c04e62c.png)

**Comment by jjeffryes** [comment]
This happened on a brand new node, it's possible it only occurs the first time the node is loaded, or only until it has had one follower.

**Comment by rmisio** [comment]
I'm not able to reproduce this. On a new node for me, the followers is blank:

![image](https://user-images.githubusercontent.com/794517/43224092-015daba8-900a-11e8-9554-f61afc27a9f9.png)

Is there something more needed to reproduce it than just a new node?

**Comment by jjeffryes** [comment]
> Is there something more needed to reproduce it than just a new node?

There could be. I haven't seen it again since the first time I ran into it.

**Comment by rhcastilhos** [comment]
I have already seen this bug in Windows 7 64 bits, and it was also a new node.

**Comment by jjeffryes** [comment]
Closed in #1617
