### ISSUE TITLE
Add VendorFinalizedPayment Notification

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1460]
Add a notification type to handle
```
{
            "notification": {
                "notificationId": "QmUMvK1NU3WrZKvgKCkgjSVSj9VXqY7nwdsJzbucqHNDaG",
                "orderId": "QmX1kSBQmh2vbTwvohSWebXvAg3MdWU6d9XgH4G79gfJQV",
                "type": "vendorFinalizedPayment"
            },
            "read": true,
            "timestamp": "2018-07-22T17:39:36-04:00",
            "type": "vendorFinalizedPayment"
        },
```

This indicates the vendor has claimed the payment after it has timed out.

**Comment by rmisio** [comment]
Gonna go with `The vendor has claimed the payment for order #12345.` since `is now complete` is maybe misleading because the order isn't actually complete. It would be complete after the buyer leaves a review.
