### ISSUE TITLE
Memo disappearing after changing payment type

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#1465]
v2.2.2 RC1 win7 64bits

1. Write something on "Memo" text input
2. Select another payment type/moderator or click in "Verified moderators only"
3. "Memo" is erased

**Comment by hoffmabc** [comment]
Yep, this one is confirmed. @rmisio and @jjeffryes this is a definite issue. Thanks @rhcastilhos.
