### ISSUE TITLE
Buyer Can't Complete Resolved Order

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1470]
When an order is disputed and resolved, they buyer no longer gets the complete order form in the order details.

![image](https://user-images.githubusercontent.com/1584275/43209251-2fcce536-8ffa-11e8-983c-e7170d2fcb8d.png)

**Comment by rmisio** [comment]
Has the order been fulfilled? Only fulfilled orders can be completed.

**Comment by jjeffryes** [comment]
You're right. It's working as expected, it's just confusing.
I tested fulfilled disputes, they're working normally.
