### ISSUE TITLE
User page should display complete short description

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#1472]
Short description field supports a maximum of 160 characters. However these 160 characters are never fully displayed, since user card is cut with "..." even on user page. 

Example:
![image](https://user-images.githubusercontent.com/10789865/43215607-e271996a-903c-11e8-9ae0-155381cef9c3.png)

**Comment by jjeffryes** [comment]
@morebrownies that's a good point, if we never actually display all of the short description, should we change the design to fix that, or change the character limit to match the design?

**Comment by rhcastilhos** [comment]
A related bug: "..." has a fixed position on usercard, when resizing window:
![move](https://user-images.githubusercontent.com/10789865/43290003-f278fde4-912c-11e8-96f2-b3ff63516134.gif)
