### ISSUE TITLE
Improve loading screen when attempting to connect to a store or load a listing

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#1494]
The current loading screen is very underwhelming and also difficult to navigate (have to hit the back button in the address bar to leave)

![screenshot 2018-07-30 08 48 29](https://user-images.githubusercontent.com/13066886/43540378-6b7ddec8-957c-11e8-9f28-10b724226ee6.png)

Ideally we would give the user a more polished loading experience, and also provide buttons to 'cancel' or 'retry'.

<img width="1227" alt="screenshot 2018-08-01 11 21 07" src="https://user-images.githubusercontent.com/13066886/43540595-091baab6-957d-11e8-8285-0df6a3b719f7.png">

<img width="1226" alt="screenshot 2018-08-01 11 22 02" src="https://user-images.githubusercontent.com/13066886/43540643-28c35a44-957d-11e8-8efb-267468cc836a.png">

➡️**Prototype here:** https://invis.io/G7NAT28FCKA#/312112604_Openbazaar-2-0-Search

**Comment by morebrownies** [comment]
I updated the design blow. Check it out. Also, I'll provide some examples to display what the experience looks like if the user avatar/store name is unknown. 

![screenshot 2018-08-02 18 05 05](https://user-images.githubusercontent.com/13066886/43618689-a2505edc-967e-11e8-8c70-91417ed861d5.png)
![screenshot 2018-08-02 18 05 12](https://user-images.githubusercontent.com/13066886/43618690-a267b942-967e-11e8-848b-070fb0a16027.png)

**Comment by rmisio** [comment]
@morebrownies as an FYI, Icons like this are not very theme-friendly because they're not theme-able in themselves. So if the theme had a yellow background color, it would wash them out.

![image](https://user-images.githubusercontent.com/794517/43922982-3c4c83a2-9bd5-11e8-97c1-0f9462633edc.png)

It's a moot point now because we don't have any theming implemented, but just wanted to make you aware.

**Comment by jashot7** [comment]
@rmisio Wolf actually updated the designs (see the screens right above your comment)

**Comment by rmisio** [comment]
ah cool. It was more of an FYI anyway. For example, these may not play nice either with a theme-able app. The icon set would probably need some type of background panel.

![image](https://user-images.githubusercontent.com/794517/43928230-01942c5a-9be5-11e8-8cbf-e61010819560.png)

But, as I mentioned, it's all a moot point for now.

**Comment by rmisio** [comment]
@morebrownies What should I use for the Slack icon? We're using ionic icons for the rest, but they don't seem to have a Slack one.

Also, the way the ionic icons work is that they are only a single flat color... which works for most of them here except Slack and Reddit. What color should I use for the reddit one - black, like github?

![image](https://user-images.githubusercontent.com/794517/43932192-7acc6d00-9bf7-11e8-93b5-0f470e489e0a.png)

(I guess we don't have to go the flat color approach, but then it's a matter of us hosting the icons whereas up until now we've been using the Ionic ones.)

**Comment by morebrownies** [comment]
> ah cool. It was more of an FYI anyway. For example, these may not play nice either with a theme-able app. The icon set would probably need some type of background panel.

Thanks for the suggestion @rmisio. I think it's safe to say that themes are years out at this point and I have no idea how we will layer them in. We have things like crypto coin icons too that display all over the UI and we may run into display issues with those too. We'll have to deal with that nugget once we get there.

**Comment by morebrownies** [comment]
> @morebrownies What should I use for the Slack icon? We're using ionic icons for the rest, but they don't seem to have a Slack one.

Could you use the one in the Zeplin file? If ionicons doesn't include them, we'll need to layer in our own icons.

> Also, the way the ionic icons work is that they are only a single flat color... which works for most of them here except Slack and Reddit. What color should I use for the reddit one - black, like github?

Yeah, black works.

**Comment by rmisio** [comment]
> Could you use the one in the Zeplin file? If ionicons doesn't include them, we'll need to layer in our own icons.Could you use the one in the Zeplin file? If ionicons doesn't include them, we'll need to layer in our own icons.

I'm not seeing how to d/l it. Am I missing it? We would need it to be on a transparent background.

Also, as an FYI, the way slack is showing it is pretty small, which would limit our uses of it to that size or smaller and if it is that size, it wouldn't be retina friendly. Maybe once I figure out how to d/l the guy, I'll find that it's much larger than how it's displayed, which would make this a moot point.

**Comment by morebrownies** [comment]
A quick google search returned this. Can we use this one?

https://upload.wikimedia.org/wikipedia/commons/7/76/Slack_Icon.png

**Comment by rmisio** [comment]
Dammit wolf, are you suggesting I take some initiative and be more self-sufficient!?
