### ISSUE TITLE
Button not translatable on completed order page

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#1495]
v. 2.2.3

![image](https://user-images.githubusercontent.com/10789865/43573056-2d861c8c-9641-11e8-991c-57c2ea32f8ae.png)

**Comment by jashot7** [comment]
<img width="730" alt="screen shot 2018-08-08 at 4 40 21 pm" src="https://user-images.githubusercontent.com/392798/43863169-dd78c9cc-9b29-11e8-9dbc-f730a217b3eb.png">

@morebrownies @jjeffryes @rmisio Should we also translate this copy?

**Comment by rmisio** [comment]
Unless those platforms don't support foreign characters, I'd say we should.

**Comment by jashot7** [comment]
Fixed. 
<img width="698" alt="screen shot 2018-08-08 at 4 43 17 pm" src="https://user-images.githubusercontent.com/392798/43863281-3e827150-9b2a-11e8-9922-c7a2b813826d.png">

**Comment by jashot7** [comment]
Nevermind. It's already translatable, its just not translated in the translation file.

**Comment by jashot7** [comment]
<img width="946" alt="screen shot 2018-08-08 at 4 46 22 pm" src="https://user-images.githubusercontent.com/392798/43863432-abbf148a-9b2a-11e8-8bd2-174c61601db5.png">
