### ISSUE TITLE
Fixed moderator fee exceeds transaction amount: but... it doesn't...?

### ISSUE THREAD

**Issue by pinheadmz** [OpenBazaar/openbazaar-desktop#1498]
OSX client 2.2.3, Raspbian server 0.12.0

Order total: $10.22 (₿0.00134698)
My mod policy: $1.00 (+5%)
Dispute resolution was 100% to vendor, so mod fee should be:

`$1.00 + (5% of $10.22 = $0.51) = $1.51`

leaving for the vendor, `$8.71`

https://btc.fees.openbazaar.org/ responds `{"priority":7,"normal":1,"economic":1}`

[Here's the "Payment details"](https://blockchair.com/bitcoin/address/bc1qu8au4yktv0z0hcdv8x7mfsyksc8vg46r0dwevgxxftgt8c6zueas0j3dcw)

**Comment by pinheadmz** [comment]
![screen shot 2018-08-02 at 10 32 16 pm](https://user-images.githubusercontent.com/2084648/43625847-fbdbfbe4-96a3-11e8-9e15-aeb11f795e9e.png)

**Comment by jjeffryes** [comment]
@cpacia @placer14 This is the server returning a 500, could the message be incorrect about the reason the call is failing?

**Comment by jjeffryes** [comment]
Issue moved to [OpenBazaar/openbazaar-go #1084](https://github.com/OpenBazaar/openbazaar-go/issues/1084) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jjeffryes** [comment]
Issue moved to [OpenBazaar/openbazaar-go #1085](https://github.com/OpenBazaar/openbazaar-go/issues/1085) via [**ZenHub**](https://www.zenhub.com/)
