### ISSUE TITLE
Improve unsaved changes modal 

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#1501]
There's a few issues with the unsaved changes modal that we should clean up when we have a chance.

1. Simply providing `Yes` `No` buttons isn't clear enough. We should provide more context in the button label, e.g. `Yes, close` or `No, don't close`.
2. The `Yes, close` button should be on the right side as it implies forward progress, while `No, don't close` takes you back.
3. I cleaned up the styling of the modal a bit (buttons are larger and headline text is smaller). It feels more balanced this way.

**Current**
<img width="838" alt="screenshot 2018-07-31 21 23 41" src="https://user-images.githubusercontent.com/13066886/43603047-ae82c95c-9646-11e8-9cad-617280a2f8b9.png">

**Ideal**
<img width="1225" alt="screenshot 2018-08-02 11 24 23" src="https://user-images.githubusercontent.com/13066886/43603031-a4b664ce-9646-11e8-87ab-b08f78a678c8.png">

**Comment by jjeffryes** [comment]
@morebrownies should this change affect all dialog modals, or only this one?

Our preference is for it to be all, so the design stays consistent, but then we'll need to know what it should look like in the following scenarios:
- there is only one button
- there are many buttons (5, 6, etc.)
- the text in the buttons is too big for one line. Does it wrap inside the button and all the buttons get taller but stay on one row? What if there are 3 or more buttons with very long text that wraps?

**Comment by rmisio** [comment]
For whatever it's worth, I think 90% of the scenarios would use 1 or 2 buttons. I imagine 3 is possible too. I won't say more than 3 is impossible, but IMHO it's unlikely enough, I wouldn't stress it too much.

**Comment by morebrownies** [comment]
> @morebrownies should this change affect all dialog modals, or only this one?

I'm not sure at this point how many different dialogs we have. Can you guys provide a list if possible? I can come up with a design that will work across all of them if I know exactly what I'm designing for.

**Comment by rmisio** [comment]
ok, perhaps @jashot7 could provide a list (search for places where a Dialog view is instantiated).

But... just for some background @morebrownies... anytime we need a relatively simple dialog that consists of a title and body (body is actually optional, but almost alway used) and 1 or more buttons, we use a common component. It would pretty much look like the modal in this ticket, except the text would change and possibly the number of buttons.

**Comment by jashot7** [comment]
<img width="794" alt="blockdata" src="https://user-images.githubusercontent.com/392798/44054465-a4b8b8aa-9f10-11e8-8c0d-4b186c5e99b0.png">
<img width="658" alt="faileddeletelisting" src="https://user-images.githubusercontent.com/392798/44054467-a6af4a3e-9f10-11e8-8ae1-480ea7847e02.png">
<img width="680" alt="followerror" src="https://user-images.githubusercontent.com/392798/44054471-a8aa1e40-9f10-11e8-9eb0-5a70df2ce378.png">
<img width="834" alt="restartlanguage" src="https://user-images.githubusercontent.com/392798/44054476-abaa15d2-9f10-11e8-8f3e-682b31bd593d.png">
<img width="692" alt="retryconfig" src="https://user-images.githubusercontent.com/392798/44054479-aed752d8-9f10-11e8-8b0e-577b32eca0a7.png">
<img width="731" alt="retryfetchsearchproviders" src="https://user-images.githubusercontent.com/392798/44054480-b1ea4b60-9f10-11e8-9918-4518739de3e0.png">
<img width="674" alt="retryfetchstartupdata" src="https://user-images.githubusercontent.com/392798/44054483-b4bf24b4-9f10-11e8-8d2b-bc45c77e11ef.png">
<img width="747" alt="retryonboarding" src="https://user-images.githubusercontent.com/392798/44054487-b7b69bf2-9f10-11e8-9bf5-c3eb4aa90867.png">
<img width="700" alt="searchfail" src="https://user-images.githubusercontent.com/392798/44054497-badc7be4-9f10-11e8-8093-a77b38695ecc.png">
<img width="694" alt="updateready" src="https://user-images.githubusercontent.com/392798/44054506-bf6eda94-9f10-11e8-9a6d-42f3e4c10e2d.png">

**Comment by jashot7** [comment]
@morebrownies See above images. This should be representative of all of our dialogs. I didn't see any instances of more than 2 buttons or any other variations that weren't redundant for illustrative purposes.

**Comment by morebrownies** [comment]
thank you for gathering those screens @jashot7.

I'll provide more examples of ideal designs for dialogs later this week.

**Comment by morebrownies** [comment]
Actually this may be enough to get you guys started. Let me know if you need designs for specific dialogs, otherwise these should probably do:

**Single button**
<img width="700" alt="screenshot 2018-08-13 13 49 50" src="https://user-images.githubusercontent.com/13066886/44057351-c60ece24-9eff-11e8-9ee0-3d10d630df12.png">

**Two buttons**
<img width="655" alt="screenshot 2018-08-13 13 50 16" src="https://user-images.githubusercontent.com/13066886/44057352-c627e67a-9eff-11e8-9400-b660169cd175.png">

**Comment by jashot7** [comment]
@morebrownies I'm posting a few things for your design consideration following this message. Feel free to check out the PR and look through the update live and let me know if you prefer any changes.

**Comment by jashot7** [comment]
@morebrownies The loading spinner for error loading verified mods with this new visual update applied now looks like this when the user presses retry. I don't see an issue with this - just wanted to point it out since you may not be able to easily invoke this dialog.

<img width="713" alt="screen shot 2018-08-16 at 5 27 54 pm" src="https://user-images.githubusercontent.com/392798/44286711-06c14d80-a238-11e8-8ab1-3ca919ca64cb.png">

**Comment by jashot7** [comment]
I discussed updating the look of this modal below with @jjeffryes and we decided to remove the HRs to fit your updated design. 

Original:
<img width="789" alt="screen shot 2018-08-17 at 3 18 20 pm" src="https://user-images.githubusercontent.com/392798/44286839-80f1d200-a238-11e8-8a82-a83ceb81ea56.png">

The double hrs don't work here:
<img width="813" alt="screen shot 2018-08-17 at 3 15 51 pm" src="https://user-images.githubusercontent.com/392798/44286864-923ade80-a238-11e8-90de-545bddbbf73a.png">

Removing just the bottom hr also doesn't work:
<img width="828" alt="screen shot 2018-08-17 at 3 22 15 pm" src="https://user-images.githubusercontent.com/392798/44286881-a252be00-a238-11e8-8125-33b09d2af6cf.png">

This is what I decided on to match your update. This does affect the design language, so you'll want to consider it and let me know if you'd like any changes.

<img width="794" alt="screen shot 2018-08-17 at 3 25 38 pm" src="https://user-images.githubusercontent.com/392798/44286898-b1397080-a238-11e8-906f-2b9769514bd9.png">

**Comment by jashot7** [comment]
@morebrownies I did not update the dialog below. If we would like to update this, it needs some consideration for placement of the message on the left, etc.

<img width="668" alt="screen shot 2018-08-17 at 3 36 02 pm" src="https://user-images.githubusercontent.com/392798/44287036-4b99b400-a239-11e8-9659-f4c14b4faeb6.png">

**Comment by jashot7** [comment]
@morebrownies (actual) final thing to consider:

I did not update Onboarding. You'll need to consider the HR change above in relation to this and let me know if you'd like me to make that update with onboarding.

for reference:
<img width="789" alt="screen shot 2018-08-17 at 4 30 13 pm" src="https://user-images.githubusercontent.com/392798/44287682-a9c79680-a23b-11e8-8859-99c853e6ba0d.png">

If you like, I can just remove the HRs as I did for the modal above and it mostly works, but its a design language issue for your consideration.

**Comment by morebrownies** [comment]
Ok thanks @jashot7 I'll catch up on this when I can. Hang tight

**Comment by morebrownies** [comment]
@jashot7 sorry for the delay. Tested this PR today and overall it's looking really great. Only suggestion I have is to flip the buttons on the `restart` dialog.  (`Restart now` should be on the right side)

![screenshot 2018-08-22 11 11 47](https://user-images.githubusercontent.com/13066886/44482269-b9a8f700-a5fc-11e8-8f8c-37211e457889.png)

The `OpenBazaar Wallet Setup` screen will be going away soon so I'm fine with the HR changes there. Keeping onboarding as is works for me too. 

👍
