### ISSUE TITLE
Increase the amount of search results that display per page

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#1504]
Currently search only displays `24` results per page and it requires a lot of clicking to see more listings. On web, we display `66` results per page and it feels much much better.

Could we increase the # of results per page from `24` to `66`?

**Comment by jjeffryes** [comment]
Should we also add the ability to choose how many results display as in #1111? For users on slow connections, 66 may be too many.

We could default to 66.

**Comment by rmisio** [comment]
> For users on slow connections, 66 may be too many.

Do you really think so? I'd be curios to see the difference in the size of the payload between 24 and 66. I have a feeling it's really really small.

**Comment by jjeffryes** [comment]
I'm thinking in terms of the images loading from IPFS.

**Comment by morebrownies** [comment]
> Should we also add the ability to choose how many results display as in #1111? For users on slow connections, 66 may be too many.

Probably not necessary, unless there is a serious hit on performance.
