### ISSUE TITLE
Can't complete order

### ISSUE THREAD

**Issue by miboediono** [OpenBazaar/openbazaar-desktop#1505]
Just bought some ZEC using bitcoin. Seller sent me my ZEC outside of OpenBazaar, and fulfilled the order. I received a notification that my order has been fulfilled, and I can see the fulfillment details/transaction ID, but the order is not being moved into `fulfilled` state, so there's no way for me to complete the order (see screenshot below).

Operating System: **MacOS Sierra 10.12.5**
OpenBazaar version: **Version 2.2.3**
Hardware: **MacBook Pro (Retina, 13-inch, Early 2015)**

<img width="1276" alt="screen shot 2018-08-04 at 12 24 51 pm" src="https://user-images.githubusercontent.com/39143653/43691179-657ef922-98cd-11e8-9c72-7ba056855f2c.png">

**Comment by miboediono** [comment]
@rmisio I think this should be it. Let me know if you need anything else!

> "contract": {
>         "vendorListings": [
>             {
>                 "slug": "zcash-zec-for-bitcoin-btc",
>                 "vendorID": {
>                     "peerID": "QmaW2iTEkAMhDCEm1pKtD2DXhivCvrHmkbnbwLBdsK1ccS",
>                     "handle": "",
>                     "pubkeys": {
>                         "identity": "CAESII6fFoykUYoOHRjug56VRZRqP2Wn6c3WTImexZJigDer",
>                         "bitcoin": "Arwv4quWW/XgJ7DU8SA4RBpRkaCIeBnRziGvyzzq4JyM"
>                     },
>                     "bitcoinSig": "MEUCIQCS8ODN8tMImxRGeyHFPEtZak+teKx77+J2vko0yEC+9wIgdO9IH3Wa0JVLPlGhIi76BIz3Uph2X+6TtP1BldBqlPk="
>                 },
>                 "metadata": {
>                     "version": 4,
>                     "contractType": "CRYPTOCURRENCY",
>                     "format": "MARKET_PRICE",
>                     "expiry": "2037-12-31T00:00:00.000Z",
>                     "acceptedCurrencies": [
>                         "BTC"
>                     ],
>                     "pricingCurrency": "",
>                     "language": "",
>                     "escrowTimeoutHours": 1080,
>                     "coinType": "ZEC",
>                     "coinDivisibility": 100000000,
>                     "priceModifier": 0
>                 },
>                 "item": {
>                     "title": "BTC-ZEC",
>                     "description": "<p>Freshly mined, untainted Zcash.</p><p>Buy with confidence with  the moderator of your choice.</p><p><br></p><p>Mobile wallet for Android or iOS (<span>tested to be compatible with the latest update)</span><span>: </span></p><p><a href=\"https://coinomi.com/\" rel=\"nofollow\">https://coinomi.com/</a><br></p><p>Full Zcash node:</p><p><a href=\"https://z.cash/download.html\" rel=\"nofollow\">https://z.cash/download.html</a></p><br><p></p>",
>                     "processingTime": "",
>                     "price": 0,
>                     "nsfw": false,
>                     "tags": [
>                         "zec",
>                         "zcash",
>                         "crypto",
>                         "privacy",
>                         "coin"
>                     ],
>                     "images": [
>                         {
>                             "filename": "zec.jpg",
>                             "original": "zb2rhfLfMaC9PfBCjBPH6ERQE3Na5JbCpShP6CQR3oyyPR4hx",
>                             "large": "zb2rhdRks8QU9QkGnMd6R8fU5VWVahjjrwqkjhNQjwbhnY9J3",
>                             "medium": "zb2rhZMFy4MavBwEjto9G93Fo5hKUqhnPp4GXyArtJZAaE2Wb",
>                             "small": "zb2rhnzy4GX46rdjiQVNz2n6am2KLDqW9vTSbu2GEjFA8pAKw",
>                             "tiny": "zb2rhbTy4LQFzyCt1hfSGZkduv2E81262MH1Wby9fuGGg983h"
>                         }
>                     ],
>                     "categories": [
>                         "cryptocurrency"
>                     ],
>                     "grams": 0,
>                     "condition": "",
>                     "options": [
>                     ],
>                     "skus": [
>                         {
>                             "productID": "",
>                             "surcharge": 0,
>                             "quantity": 0
>                         }
>                     ]
>                 },
>                 "shippingOptions": [
>                 ],
>                 "coupons": [
>                 ],
>                 "moderators": [
>                     "QmZ8pAsnSoLNJkMVGoLrtG4qq9GeTEWBFHkwyjugPtbH4y",
>                     "QmduBPTQNaXYWivhjNEs8fx5psgazDpH4x1DJqtTcVXhPs",
>                     "QmZQ1etBmR8GXGey4h5xUoLtddF8yQsjVS3NgQ4FFLkGfb",
>                     "QmUkQuY5ChYhutKuy4qmgqg6HPzqYvG4xSJtPHY7RCAcMQ",
>                     "QmVFNEj1rv2d3ZqSwhQZW2KT4zsext4cAMsTZRt5dAQqFJ"
>                 ],
>                 "termsAndConditions": "",
>                 "refundPolicy": ""
>             }
>         ],
>         "buyerOrder": {
>             "refundAddress": "1AGEzcmZdkcatiD8JEzMdTpHWkf13Pjcsz",
>             "refundFee": 1,
>             "shipping": {
>                 "shipTo": "",
>                 "address": "",
>                 "city": "",
>                 "state": "",
>                 "postalCode": "",
>                 "country": "NA",
>                 "addressNotes": ""
>             },
>             "buyerID": {
>                 "peerID": "QmegBGkKCgMY6J2GWJweqzDd2UQNugdGwWuEX7wKmWv1sq",
>                 "handle": "",
>                 "pubkeys": {
>                     "identity": "CAESIEdjm6Cmyn0NBp/KXWCmRILphmXksskAOxFW+oZ2vJ54",
>                     "bitcoin": "Au2s8/f24lEke9vYdWTd7iC6LNQ37RNLLyfSU+fVvHVM"
>                 },
>                 "bitcoinSig": "MEQCICsJLSQ4wXX93hr4LMXACAFXY1fq1mBMPpmCoM3KIhBqAiBWxwmAM+NbKgBP5ALsnCREqG+7EtdBpIfctvPX2LZheQ=="
>             },
>             "timestamp": "2018-08-03T23:14:20.644928937Z",
>             "items": [
>                 {
>                     "listingHash": "zb2rhXNHQqhEyNB4RQn8hCjLbY9rU7kTVDe5PPQaQGHRxQbBn",
>                     "quantity": 0,
>                     "quantity64": 100000000,
>                     "memo": "",
>                     "paymentAddress": "t1ZuGzHjGeSxtXgsb9VCE1wZZfh4q5gRZJB"
>                 }
>             ],
>             "payment": {
>                 "method": "MODERATED",
>                 "moderator": "QmZ8pAsnSoLNJkMVGoLrtG4qq9GeTEWBFHkwyjugPtbH4y",
>                 "amount": 2499801,
>                 "chaincode": "02db989e5a0788d2e172357751306312de48027568f3dc1c987873a012480fca",
>                 "address": "bc1qrlkxzcsxus82rdk262wg8ct8jzggn4ygmrkhm6el7yn78kpxmxmqvucnt7",
>                 "redeemScript": "6352210366ffea1f460ca05d9408160dabba1133d3ac37e959fe20ff7ceb5e624d7816562103427608e205459057410320f2f8bdbcf5eebdbfd7854387be47aefc7d976af57c2102ffa554a1d28ed4e4eb5da4400ed44e3d849e74cea78a0239ba285655783f545f53ae67025019b2752103427608e205459057410320f2f8bdbcf5eebdbfd7854387be47aefc7d976af57cac68",
>                 "moderatorKey": "Av+lVKHSjtTk612kQA7UTj2EnnTOp4oCObooVlV4P1Rf",
>                 "coin": "BTC"
>             },
>             "ratingKeys": [
>                 "A87Fub43ssmIqYRk/PP9kdcdz/pfOq5mhqUpCGxYFedr"
>             ],
>             "alternateContactInfo": "",
>             "version": 2
>         },
>         "vendorOrderConfirmation": {
>             "orderID": "QmctDA9zxMPPZftxdpGFCdKWhGGQerzmACn1RsYRnELesJ",
>             "timestamp": "2018-08-04T19:03:07.344395901Z",
>             "paymentAddress": "bc1qrlkxzcsxus82rdk262wg8ct8jzggn4ygmrkhm6el7yn78kpxmxmqvucnt7",
>             "requestedAmount": 2499801,
>             "ratingSignatures": [
>                 {
>                     "metadata": {
>                         "listingSlug": "zcash-zec-for-bitcoin-btc",
>                         "moderatorKey": "Av+lVKHSjtTk612kQA7UTj2EnnTOp4oCObooVlV4P1Rf",
>                         "listingTitle": "BTC-ZEC",
>                         "thumbnail": {
>                             "tiny": "zb2rhbTy4LQFzyCt1hfSGZkduv2E81262MH1Wby9fuGGg983h",
>                             "small": "zb2rhnzy4GX46rdjiQVNz2n6am2KLDqW9vTSbu2GEjFA8pAKw",
>                             "medium": "zb2rhZMFy4MavBwEjto9G93Fo5hKUqhnPp4GXyArtJZAaE2Wb",
>                             "large": "zb2rhdRks8QU9QkGnMd6R8fU5VWVahjjrwqkjhNQjwbhnY9J3",
>                             "original": "zb2rhfLfMaC9PfBCjBPH6ERQE3Na5JbCpShP6CQR3oyyPR4hx"
>                         }
>                     },
>                     "signature": "mpSE6BNgPy0/n28D+TrvoLHwasT6dkC1Roc0wncRYREO8zqNb63SO2Yn/VQQWwFNrPbLSWGwF7FBZJXjXVmbAw=="
>                 }
>             ]
>         },
>         "vendorOrderFulfillment": [
>             {
>                 "orderId": "QmctDA9zxMPPZftxdpGFCdKWhGGQerzmACn1RsYRnELesJ",
>                 "slug": "zcash-zec-for-bitcoin-btc",
>                 "timestamp": "2018-08-04T09:19:31.305996771Z",
>                 "payout": {
>                     "sigs": [
>                         {
>                             "inputIndex": 0,
>                             "signature": "MEQCICiCRQP0Rzp5qNohaQYnt0NzpPYJ0shefZ+b9zzJZuc4AiBRj+zeBdHNAF9XFTDr/rUDZHCABQsHetiJ8SudZC2wFQE="
>                         }
>                     ],
>                     "payoutAddress": "1HMydKmvHVhy6ekhcx7ebX7iiDhmybqtZw",
>                     "payoutFeePerByte": 1
>                 },
>                 "ratingSignature": {
>                     "metadata": {
>                         "listingSlug": "zcash-zec-for-bitcoin-btc",
>                         "ratingKey": "A87Fub43ssmIqYRk/PP9kdcdz/pfOq5mhqUpCGxYFedr",
>                         "listingTitle": "BTC-ZEC",
>                         "thumbnail": {
>                             "tiny": "zb2rhbTy4LQFzyCt1hfSGZkduv2E81262MH1Wby9fuGGg983h",
>                             "small": "zb2rhnzy4GX46rdjiQVNz2n6am2KLDqW9vTSbu2GEjFA8pAKw",
>                             "medium": "zb2rhZMFy4MavBwEjto9G93Fo5hKUqhnPp4GXyArtJZAaE2Wb",
>                             "large": "zb2rhdRks8QU9QkGnMd6R8fU5VWVahjjrwqkjhNQjwbhnY9J3",
>                             "original": "zb2rhfLfMaC9PfBCjBPH6ERQE3Na5JbCpShP6CQR3oyyPR4hx"
>                         }
>                     },
>                     "signature": "lH+cfvULQrhDXSvo1aJA3Maj/snpd7HqowdZwQd2C05D5FCpizcygAPDbBee+k3/P2UnpGPUc6DQ7xBNKKi4Bw=="
>                 },
>                 "note": "Your ZEC is sent. Thank you for your purchase!",
>                 "cryptocurrencyDelivery": [
>                     {
>                         "transactionID": "226ad30af2ab73a5c22aee106a3b0c57762cd6491a7633e765f6d87413d43eb7"
>                     }
>                 ]
>             }
>         ],
>         "signatures": [
>             {
>                 "section": "LISTING",
>                 "signatureBytes": "gUUgn/Oj2Q1z5RwqKqtCCsNBwyPVAUkY53wjfYJ8MFs4bBeqxnxGs2ZeDTeKLWgjCUFTlCDepRDCl2M7d6b0CQ=="
>             },
>             {
>                 "section": "ORDER",
>                 "signatureBytes": "Oqo3EDWePiY9B3oUFbxDh0n0AJZwmmMcG00bCgNsz52VDfnLQ/kX1xDUjQ7YFsiWkJNS+5rR//qFTfRnPWRtAA=="
>             },
>             {
>                 "section": "ORDER_CONFIRMATION",
>                 "signatureBytes": "4WetSu3uu5guIwZklh/J9zf0KOw7MexpEFzzy+06jYEt+kvosCrKOOPNusTZw5gGhBR9mYIR5Twy7pvCbBGgBA=="
>             },
>             {
>                 "section": "ORDER_FULFILLMENT",
>                 "signatureBytes": "OOo9wZcuXQTWlsNM+nG/lDVJtVqiosaU+AuiBROhJv8RBAZIy+Us8uYunnbkIST23fOHi9bKgylLmcKbscrTCA=="
>             },
>             {
>                 "section": "ORDER_CONFIRMATION",
>                 "signatureBytes": "uFbq5V3oMPR9diDW2vaeoYUcdKIjAXAt2qidoPfloINAY2S++QDaQi6J5HL70ThKKndDFwed3Q/JUjfBilHbDQ=="
>             }
>         ]
>     },
>     "state": "AWAITING_FULFILLMENT",
>     "read": true,
>     "funded": true,
>     "unreadChatMessages": 0,
>     "paymentAddressTransactions": [
>         {
>             "txid": "f29cf2bf903699a710a7adc407a72bc18971dbcde63e910ddf45f209b7eebb22",
>             "value": 2499801,
>             "confirmations": 456,
>             "height": 535077,
>             "timestamp": "2018-08-03T23:15:42.875208702Z"
>         }
>     ]
> }

p.s. Thanks for the detailed instructions + screenshot. Never would've found it otherwise......

**Comment by rmisio** [comment]
Thanks @miboediono!

**Comment by rmisio** [comment]
Closing as this looks to be a server issue where the order state is not properly progressing:
https://github.com/OpenBazaar/openbazaar-go/issues/1069
