### ISSUE TITLE
No Connection after OB

### ISSUE THREAD

**Issue by atmotraxx** [OpenBazaar/openbazaar-desktop#1506]
Brief Description: 
Chrome says ERR_NAME_NOT_RESOLVE after (sometimes while) using OB

Operating System:  Windows 10 Home
OpenBazaar version:  2.2.3 / 0.12.2
Hardware: Samsung Laptop (tested on two different machines 32Bit, 64Bit)

Reproducible: 
Always

Steps to reproduce:
1. Open OB2
2. Do something
3. Close OB2

Observed Behavior:
After using OB no more WLAN/LAN DNS resolution: Chrome says ERR_NAME_NOT_RESOLVE
It does not matter if it is a wired connection or wifi(wlan).

Expected Behavior:
All Internet connectivity should be untouched and working

Additonal:
Even after a restart the connection problems are present. My solution is: restart laptop, power off/on router

Kind regards 
Erik

**Comment by jjeffryes** [comment]
Issue moved to [OpenBazaar/openbazaar-go #1083](https://github.com/OpenBazaar/openbazaar-go/issues/1083) via [**ZenHub**](https://www.zenhub.com/)
