### ISSUE TITLE
Some translations require plural for word "found"

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#1510]
v2.2.3

Some languages require two different translations (singular and plural) to word "found" in messages:
"1 listing found" and "2 listings found".

In spanish it should be:
"1 listado encontrado" and "2 listados encontrados".

This is needed in Store page and in Orders page:
![image](https://user-images.githubusercontent.com/10789865/43884728-29ff797a-9bb7-11e8-8162-19cf35b0c1e3.png)

![image](https://user-images.githubusercontent.com/10789865/43912489-afcbe0ca-9c02-11e8-8e21-70d012fa2d5a.png)

**Comment by rhcastilhos** [comment]
@jjeffryes 
Fix is not working.

I've set "countListingsFound": "%{smart_count} encontrado |||| %{smart_count} encontrados", in translation file, but it is displaying this way:
![image](https://user-images.githubusercontent.com/10789865/44254794-30608180-a204-11e8-9e50-b99ac2f394c0.png)

But it should be "1 anúncio encontrado" and "51 anúncios encontrados"

**Comment by jjeffryes** [comment]
That's a bug in the data being sent for that translation, I found the issue and will be putting in a patch for it. 

Thank you for catching that!
