### ISSUE TITLE
Dispute "n days remaining" based on dispute start time, not payment confirmation in blockchain

### ISSUE THREAD

**Issue by pinheadmz** [OpenBazaar/openbazaar-desktop#1519]
I have a dispute that informs me:
```
The buyer is disputing this order.
You have 43 days to process the dispute and make a decision.
```
...but the actual blockchain transaction was mined 14 days ago, hence the CSV timeout for the vendor to sweep without moderation is actually 31 days from now. I'm not sure how it looks on the vendor's end once the CSV is satisfied, but the discrepancy could be used as a fraud vector.

**Comment by jjeffryes** [comment]
The timer starts over when a dispute is started, and is 45 days from the dispute.

That might not be obvious from the messaging we're providing, we can take a look at that.

**Comment by pinheadmz** [comment]
Here's the address and redeem script from the contract:
```
"address": "bc1qkczn9xqwwpf04qeqhs3lht6y9akglfhyzgqx7pfjwumr4peygskqwpalhn",
"redeemScript": "6352210231260eba4c9e08622b193d8c0fdc6f656bc42afdbba034e7f647dd4b28c293e32103cf26cecbd1b54772a920263e60e0c92db8443d445df6df6cbdcb2dd86209b7152103d608a7f72861e8e2784ad5fcb56a87ec56c692aa03b316da86d8cd844e15b81953ae67025019b2752103cf26cecbd1b54772a920263e60e0c92db8443d445df6df6cbdcb2dd86209b715ac68",
```
Here's the transaction in the blockchain:
https://blockchair.com/bitcoin/transaction/332722734#o=1

It was mined on Aug 4 (ten days ago). The CSV is set for 6480 blocks:
```
$ bitcoin-cli decodescript 6352210231260eba4c9e08622b193d8c0fdc6f656bc42afdbba034e7f647dd4b28c293e32103cf26cecbd1b54772a920263e60e0c92db8443d445df6df6cbdcb2dd86209b7152103d608a7f72861e8e2784ad5fcb56a87ec56c692aa03b316da86d8cd844e15b81953ae67025019b2752103cf26cecbd1b54772a920263e60e0c92db8443d445df6df6cbdcb2dd86209b715ac68
{
  "asm": "OP_IF 2 0231260eba4c9e08622b193d8c0fdc6f656bc42afdbba034e7f647dd4b28c293e3 03cf26cecbd1b54772a920263e60e0c92db8443d445df6df6cbdcb2dd86209b715 03d608a7f72861e8e2784ad5fcb56a87ec56c692aa03b316da86d8cd844e15b819 3 OP_CHECKMULTISIG OP_ELSE 6480 OP_CHECKSEQUENCEVERIFY OP_DROP 03cf26cecbd1b54772a920263e60e0c92db8443d445df6df6cbdcb2dd86209b715 OP_CHECKSIG OP_ENDIF",
  "type": "nonstandard",
  "p2sh": "3DmMmoqcRNxEzVG8ciXZnGoQz9GGbSe3eM"
}
```
Maybe I misunderstand how `OP_CSV` works, but that 6480 block timeout is 45 days FROM THE DATE THIS TX WAS MINED. That means in 35 days the vendor can spend this output by himself. Yet the UI on my (the moderator) end says I have 41 days to resolve the dispute.

> The timer starts over when a dispute is started, and is 45 days from the dispute.

How is that possible without an additional on-chain `OP_CSV` transaction, extending the timeout an additional 45 days?

**Comment by jjeffryes** [comment]
@pinheadmz you're correct. 

To elaborate, it is possible the seller could still pull the funds while a dispute is active. the only thing preventing that is the server doesn't allow it. If a vendor knows how to spend the output without using the OB server, they could.

We know that's not a perfect situation, but we considered it an acceptable tradeoff. The alternative was to create a new transaction when the dispute was started and subtract more fees from the order.

**Comment by pinheadmz** [comment]
Just got a reminder notification about a dispute where the deadline is way off according to the blockchain. This is a dispute that violates my policy, so I will not act on it. Still, the timeline in the UI, the actual 45-day CSV transaction, and the deadline in the notification aren't really consistent. By today, I think the vendor can sweep the funds. I definitely do not have 30 more days to act.

Order Details May 20, 2019 3:42 PM
Accepted May 21, 2019 8:29 AM
Fulfilled May 22, 2019 1:36 AM
Dispute Started Jun 28, 2019 12:31 AM

Today (Jul 13, 2019) I get: The buyer is disputing this order. You have 30 days to process the dispute and make a decision.

**Comment by jjeffryes** [comment]
@pinheadmz the timeout resets at 45 days when a dispute is filed.

The 45 timeout on the transaction itself is still there, but the OB software doesn't allow it to be claimed until 45 days have passed after the dispute starts.

That's there to prevent situations where a dispute is started and the seller claims the funds while the moderator is trying to settle the dispute.

**Comment by jjeffryes** [comment]
@pinheadmz that looks correct.

A new 45 day timer is started when the dispute starts, to prevent the vendor from claiming the funds while the dispute is being settled by the moderator.

If the dispute was started on June 28th, there would be 30 days left on July 13th.
