### ISSUE TITLE
Unable to open case. Order is too old to dispute.

### ISSUE THREAD

**Issue by surfcapmgmt** [OpenBazaar/openbazaar-desktop#1524]
Brief Description: 

Like the title says, I have been trying to dispute an order, because the seller claims to have not received funds on his end (although block explorer shows 600+ confirmations.)

When I try and dispute the order, I get the following error message "Unable to open case. Order is too old to dispute."

This puzzles me because the invoice says I have 49,317 blocks to dispute the order and 49,317 > 600 confirmations.

Even more puzzling, it seems as if the client is stating there are 4.3billion (?) confirmations of my payment. Perhaps this glitch explains why I am not able to start the dispute.

Operating System (OS and version): Windows 10 
OpenBazaar version (shown on `About OpenBazaar` page in menu):  client 2.2.3, server 0.12.2
Hardware: PC

Additional info (links, images, etc go here):
![ob question](https://user-images.githubusercontent.com/42395652/44127148-01d41c60-a00a-11e8-9618-d5b7c8d84e91.png)

**Comment by jjeffryes** [comment]
@surfcapmgmt can you ask the seller to go to Settings, Advanced, and click the Reload Transactions button?

That should fix the problem with the seller not receiving their payment.

@cpacia do you know why the timeout would say 343 days? There seems to be something wrong with the block count here.

**Comment by rhcastilhos** [comment]
I also got the same block count error for the last 2 days, but it was gone yesterday. My wallet was displaying -2.000 confirmations for some transactions. I guess it was corrected by reloading transactions.

**Comment by placer14** [comment]
I guess 4.3b could be if we had an int underflow. @surfcapmgmt Could you also share your server debug logs (or your ob.log found in the data directory for OB).

**Comment by surfcapmgmt** [comment]
@placer14 is that "debug.log" found in %appdata%?

**Comment by placer14** [comment]
@surfcapmgmt It's found in the folder described in this article: https://openbazaar.zendesk.com/hc/en-us/articles/115002761312-How-do-I-backup-my-store-

it may be labeled w `bitcoincash` on the end if you're using BCH instead of BTC.

**Comment by surfcapmgmt** [comment]
[ob.log](https://github.com/OpenBazaar/openbazaar-desktop/files/2290482/ob.log)

@placer14

**Comment by placer14** [comment]
@surfcapmgmt Nothing in your logs jumps out at me either. It could be that your wallet is reporting negative confirmations in the scenario that it was stuck or incompletely synched. If the steps recommended in https://github.com/OpenBazaar/openbazaar-desktop/issues/1524#issuecomment-413075034 didn't do it for you, try this:

0. Stop the server and ensure it's no longer running.
1. Find the data folder as I mentioned previously. (Create a backup of this folder if you don't already have one.)
2. Remove (or rename) the `headers.bin` file located there. This is the cache of all downloaded blockchain headers. Changing the name will cause the file to be rebuilt by the wallet on next startup.
3. (option) Remove (or rename) the `logs/bitcoin.log` file. You can watch the bitcoin.log to ensure the synch is progressing/completing properly.

Reload the view once the wallet has completed synching up and report back.

**Comment by rhcastilhos** [comment]
Now I'm getting negative confirmations in wallet and 4.2b in order again:

![image](https://user-images.githubusercontent.com/10789865/44161401-7f4fcf00-a0bd-11e8-8ee3-f447f3204537.png)


Here is my new bitcoin.log (after deleting the previous):
[bitcoin -.log](https://github.com/OpenBazaar/openbazaar-desktop/files/2291026/bitcoin.-.log)

**Comment by placer14** [comment]
Your log shows the highest block is 484736 which is well below the current block height. You need to wait for it to indicate `Chain download complete`.

**Comment by surfcapmgmt** [comment]
@placer14  I've redownloaded headers.bin and logs/bitcoin.log, and it took about 90 mins (port 4001 is open). The purchase invoices are now showing correct # of block confirmations. however, vendors are still seeing unpaid invoices.

**Comment by placer14** [comment]
@surfcapmgmt That's good news. It's possible your vendor's wallet is also stuck. Feel free to offer them this link to see if it helps them as well. Your dispute should open as usual now. Let me know if that's not the case.
