### ISSUE TITLE
Currency with code not displaying on translations

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#1526]
v.2.2.4 RC1

![image](https://user-images.githubusercontent.com/10789865/44133849-47d85f34-a062-11e8-992f-dedafa653355.png)

![image](https://user-images.githubusercontent.com/10789865/44133865-5cbac522-a062-11e8-9595-64415245aa9a.png)

**Comment by jjeffryes** [comment]
Good catch, I forgot to update the other language files.
