### ISSUE TITLE
Ex-moderators still display "Verified moderator" badge

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#1528]
v.2.2.4 rc1

Users that are not moderators anymore are still displaying the "Verified moderator" badge in their user pages.

Example:
ob://QmeSyTRaNZMD8ajcfbhC8eYibWgnSZtSGUp3Vn59bCnPWC/home
![image](https://user-images.githubusercontent.com/10789865/44159929-24b47400-a0b9-11e8-9d66-648d2ac1a47b.png)

![image](https://user-images.githubusercontent.com/10789865/44160964-4c590b80-a0bc-11e8-815d-d785a7c177d5.png)

**Comment by jjeffryes** [comment]
This is due to the verified moderators list being out of date. We're working on updating it. 

We could put a check in on the user card.

**Comment by rhcastilhos** [comment]
Yeah, it's strange because it doesn't display the moderator box below, but display the verified moderator badge.

![image](https://user-images.githubusercontent.com/10789865/44252913-250a5780-a1fe-11e8-8903-d4707dfe7c36.png)
