### ISSUE TITLE
Change pagination buttons in Discover

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#1541]
**Current**
![screenshot 2018-08-23 22 53 04](https://user-images.githubusercontent.com/13066886/44567456-5071d280-a727-11e8-9dd4-a73ddbdca838.png)

**Ideal (matches OpenBazaar.com)** 
![screenshot 2018-08-23 22 51 40](https://user-images.githubusercontent.com/13066886/44567439-3d5f0280-a727-11e8-8c8b-42bd7da815e7.png)

**Comment by jjeffryes** [comment]
Closed by #1573
