### ISSUE TITLE
Contract copying in the UI should not first require unfolding every key

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-desktop#1545]
Brief Description: When copying a contract for support purposes, I must expand every section first. Either expand them by default or offer a way to expand/collapse them all easily. Or allow a "click to copy contract" button to do the heavy lifting. Bonus points for making the copy of the contract on the clipboard NOT include the (+) and (-) nodes which the user clicks to expand/collapse the JSON key.

Motivation: As a developer, I would prefer the contract copy always included every key's contents so I wouldn't have to ask the user to resubmit the contract because they forgot to expand an important section before copying.

Bonus Motivation: As a developer, I would love to format/lint/have-valid-syntax in my JSON locally without having to clean it of the (+) and (-) icons in the body.

**Comment by rmisio** [comment]
Those suggestions are probably do-able without too much pain. Mostly a matter of what @morebrownies prefers.

(@placer14 In the meantime, you could also have them grab the contract (free of pluses and minuses!) from the network tab of the developer tools... although that would take a little more upfront time to explain to them where it is (screenshots help a lot))

**Comment by jjeffryes** [comment]
This was added in #1613
