### ISSUE TITLE
Header Image in User Card Seems Misaligned

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#155]
![image](https://cloud.githubusercontent.com/assets/45482/20897795/cf2ecc0a-baf1-11e6-8906-2efbf43eb5b1.png)

**Comment by hoffmabc** [comment]
It's aligned properly in the hero image.

![image](https://cloud.githubusercontent.com/assets/45482/20897821/eb4e969a-baf1-11e6-9101-ec7bebe8fa43.png)

**Comment by morebrownies** [comment]
@hoffmabc what is your GUID?

**Comment by hoffmabc** [comment]
QmU7EGgAqmA5aEE5H5FS2MwDpGykNAYSc37PmTNJHavDYM/home

**Comment by morebrownies** [comment]
I can't reach your node for some reason. 🤔

The user card background-image is set to display background-size: cover, which seems correct, so something else may be causing the display issue.

**Comment by hoffmabc** [comment]
I think it also needs a background-position: center.
