### ISSUE TITLE
Remove BlockBooth from Search Providers

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1569]
The BlockBooth search endpoint is currently not meeting our requirements for a search provider in several areas:

1. It doesn't return data for crypto listings in the proper format.
2. No report button has been implemented.
3. Listings that are illegal are not being removed in a timely manner.

They should be removed from the list of default search providers.

**Comment by SamPatt** [comment]
I've been in contact with Blockbooth and they've taken the following steps:

1. Implemented a report button,
2. Reviewed existing listings and removed illicit listings based on their legal jurisdiction,
3. Begun work fixing the crypto listings.

I recommend revisiting this issue in the next few weeks and if Blockbooth isn't appropriately responding to reports or hasn't finalized the crypto listing results then removing them as a default search provider.

**Comment by SamPatt** [comment]
BlockBooth now returns crypto listings in the proper format.

Since they've implemented reporting and are removing illicit listings based on their legal jurisdiction, I recommend they stay a default provider and this issue is closed.

If we find they are unresponsive to reports in the future we can reopen the issue.

**Comment by jjeffryes** [comment]
The following nodes selling illegal drugs were reported on December 17th and 20th, 2018, and are still available via BlockBooth:
Qma6bw36bkBCEv8PoWRagoHskfsouA8AiuoDG4gNszAZnF
QmUk4YRNA3W23cJ7udMEf3gckWUtGv9zsvnDdQw5f8hHV7
QmXXVayXbFboBzPTe4UXQZDrJ8EknD5aQUutL9azaTGtVL

**Comment by fire-pig** [comment]
Maybe include a link to a page where one could obtain Blockbooth (and other search engines)?   That way, the user is made aware that other search engine providers exist (such as Blockbooth, and others with more liberal listing policies), but the onus is on the user to install them.

**Comment by SamPatt** [comment]
Blockbooth's website and search service have both been inaccessible for several days, and they haven't responded to inquiries either. Removal from the client at this point is warranted.

I agree with @fire-pig's suggestion that having a page with search providers would be nice, but it's probably better run by someone in the community instead of the developers, since this inherent problem of "does inclusion mean endorsement?" keeps coming up.

**Comment by bitcoin4cashqc** [comment]
Why not make a NSFW tag instead removing "illegal" listings

**Comment by placer14** [comment]
This action doesn't remove listings from the network. It is to remove a default search provider in the client.

**Comment by bitcoin4cashqc** [comment]
But you are saying ob defaults search providers should not have illegal listings right

**Comment by jjeffryes** [comment]
3rd parties are free to create whatever search services they wish, and users are free to add them manually to their own instances of the app. 

Search services that we include as defaults, however, must abide by our guidelines, which includes having a reporting system for illegal and/or offensive listings, and acting promptly on those reports.

**Comment by placer14** [comment]
To echo @jjeffryes thoughts... as a United States-based company, we need to conform and uphold regulations to which we are bound. If the OpenBazaar project is going to make recommendations about specific search providers to use, and our company is the primary maintainer of the project, we (and by extension, the project which we have majority influence over) will act within the structure and confines of the law. That said, we have designed the software to give the user choices... you are certainly free to continue using Blockbooth on your own.

**Comment by bitcoin4cashqc** [comment]
Yikes
