### ISSUE TITLE
OB depends on libxss1 on debian, but does not list it as a dependency.

### ISSUE THREAD

**Issue by Ashaman-** [OpenBazaar/openbazaar-desktop#1570]
It should probably be added to the list of deps, since OB will not start if libxss1 

Brief Description: I installed the OB .deb along with all the dependencies it demanded, however it would not start. I investigated why in a terminal and saw that it wanted libXss.so.1

Operating System (OS and version): Whonix Workstation 14
OpenBazaar version (shown on `About OpenBazaar` page in menu): OpenBazaar2_2.2.5_amd64.deb
Hardware: virtual

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 

Steps to reproduce:
1. Install OB2 deb in brand new whonix-ws-14
2. Try to start it. Observe nothing happen.
3. Try to start it from a terminal, observe error loading shared library.

Observed Behavior:
user@host:~$ openbazaar2 
openbazaar2: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

Expected Behavior:
It should launch without my having to launch it from the terminal to troubleshoot why it's not launching.

Additional info (links, images, etc go here):
I have a very strong suspicion that this will also be reproducible in any debian-derived distro if libxss1 is not installed.

**Comment by jjeffryes** [comment]
Thanks for letting us know about this @Ashaman- 

Currently we're only targeting Ubuntu for releases, but if someone wants to submit a PR to make things work on other distros we'd welcome it.

**Comment by jjeffryes** [comment]
As a followup here, I've reproduced this issue, it's happening because libXScrnSaver is a dependency for Electron. There are a number of other Electron projects that have reported the same problem.

As a workaround, if you install libXScrnSaver you should be able to run the OpenBazaar client normally.
