### ISSUE TITLE
Typo in Dispute Prompt

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-desktop#1572]
Brief Description: 
> There is a typo in the prompt when you Dispute in Order to Change the Status to Fulfill. Thank you OB1!

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce):  Always

No additional information offered.

**Comment by rmisio** [comment]
@placer14 Can we not link to private links in a public repo? Can we instead just paste the relevant info into the issue?

**Comment by rmisio** [comment]
@jjeffryes Are you understanding the issue here? Otherwise, I'm going to close this as having too vague a description, since I can't figure it out.

**Comment by jjeffryes** [comment]
No, I don't know what the typo is either. @placer14 do you know what this was referring to?

**Comment by rmisio** [comment]
gonna close... if we get more details we can re-open.
