### ISSUE TITLE
Shipping Bug in Bitcoin Cash Client

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#1590]
Brief Description: Shipping costs do not show up in the purchase screen.

Operating System (OS and version): OSX
OpenBazaar version (shown on `About OpenBazaar` page in menu): 2.2.5
Hardware: iMac

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Open app in BCH mode.
2. Visit [ob://QmXFvx9Hjw2EDcNECRQXpSybKVdZRLEHjC4CnJFr6bCCfh/store/bitcoin-cash-for-everyone-art-print](url)
3. Try to purchase and select a shipping option

Observed Behavior: Shipping is always $0.00

Expected Behavior: Shipping amount is updated, total amount updated.

Additional info (links, images, etc go here):
![image 1](https://user-images.githubusercontent.com/45482/47728347-8dc97380-dc34-11e8-947f-7650f6aff732.png)

**Comment by jjeffryes** [comment]
This was fixed in #1597
