### ISSUE TITLE
Dispute guidelines link in settings not working

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-desktop#1601]
There is no hover state, and nothing happens when you click:

![image](https://user-images.githubusercontent.com/794517/48223859-cb797b00-e35d-11e8-8db6-0b74eb88ecfa.png)

**Comment by rmisio** [comment]
(this may be limited to the `multi-wallet-order` branch)

**Comment by jjeffryes** [comment]
Closed in #1603
