### ISSUE TITLE
The disabled text in the cryptoCur component should not be disabled when the element is

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-desktop#1615]
![image](https://user-images.githubusercontent.com/794517/48739835-d1ebda80-ec1a-11e8-9e6d-aef01d2a3496.png)

**Comment by rmisio** [comment]
Also, the disabled element should not get the hand cover state... but now it does.

**Comment by jjeffryes** [comment]
This was fixed in #1618
