### ISSUE TITLE
Electron app takes too long to load.

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-desktop#162]
There's too long of a delay between when we launch the app to when the  nice looking shell of the app is on the screen with a loading indicator:

![image](https://cloud.githubusercontent.com/assets/794517/20906893/491032b8-baff-11e6-8ac4-17a245564763.png)

In the meantime, we have a empty grayish screen.

Please decrease (as much as possible) the time before our nice looking HTML is loaded. This [article](https://blog.dcpos.ch/how-to-make-your-electron-app-sexy) has some really good ideas, notably breaking up start.js so modules that aren't immediately needed are loaded later so they don't hamper the initial load.

**Comment by rmisio** [comment]
I will very happily circle back to this one.

**Comment by hoffmabc** [comment]
I think this is an area that Slack code should provide some interesting insight.

**Comment by rmisio** [comment]
Yeah, that article I linked to gave a lot of good insight.

**Comment by morebrownies** [comment]
@rmisio Do we have any control over the view when it is first starting up? It displays a completely white screen for a few seconds. Is it possible to put a branding / splash screen up until the app loads?

![screenshot 2016-12-05 15 32 35](https://cloud.githubusercontent.com/assets/13066886/20906989/11b2241a-bb00-11e6-9728-2d36f4860597.png)

**Comment by rmisio** [comment]
I believe we have control over the color and if we could match the color of that initial screen to the ultimate color of the page, I think that would go a long way.

The complication is that the color of the ultimate page may be user defined. We do store what page to land on, so we could also store the bg color of that page, which would work in the vast majority of cases. The time it wouldn't work would be if the owner of the page changes their BG color from the time we store to when we load that page.

Another improvement that article suggests is using a CSS animation to fade the page in rather than just having plop in.

But... I think the biggest improvement would be decreasing the time until the HTML is fully loaded (at least to were we have a page nav and loading spinner)... and I think we could improve that a long way by lazy loading some of the stuff in start.js. Really, only a fraction of that stuff is needed to show the nav bar and spinner.

**Comment by morebrownies** [comment]
Ok, thank you. I like the idea of the fade in + reducing the time it takes to see some minimal UI.

**Comment by jjeffryes** [comment]
@rmisio are you still seeing this issue?

I do get the blank loading screen, but usually not for very long.

**Comment by rmisio** [comment]
I think it might be that running in dev takes a while an prod doesn't, which would make this a not super important issue.

Anyhow, in 1.5 years we haven't heard much of a complaint about this, so I don't think it's an issue.
