### ISSUE TITLE
Add orderID to spend POST

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-desktop#1629]
When calling POST `/ob/orderspend` to pay for an order, the client should set the `orderID` field to the orderID. 

This is needed for ethereum (but should be done for all coins regardless).

Dependent on https://github.com/OpenBazaar/openbazaar-go/issues/1319

**Comment by placer14** [comment]
Fixed to use new endpoint. Dependent on https://github.com/OpenBazaar/openbazaar-go/issues/1319

**Comment by placer14** [comment]
Updated description to show dependency.

**Comment by placer14** [comment]
@rmisio Would you mind always passing in order ID into the `orderID` arg regardless of the coin?

**Comment by rmisio** [comment]
> Would you mind always passing in order ID into the orderID arg regardless of the coin? (Of course, this is assuming it is for an order, other wallet spends do not require the field.

No, I don't think that's a problem.

But since it sounds like we're getting seperate APIs, I guess you'll know the intent. We'll definitely pass in the orderId where the server requires it, which I assume is at least ETH.

**Comment by placer14** [comment]
Yeah, we'll be able to protect the request with the right expectations now. Thanks!

**Comment by placer14** [comment]
And here's an endpoint spec: https://api.openbazaar.org/#64413188-0b5f-46d0-99fb-2bb3d89519e2

**Comment by jjeffryes** [comment]
Closed in #1634
