### ISSUE TITLE
Wire up resync blockchain button

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-desktop#1630]
Still need to add the button which resyncs the blockchain. Or in the case of a server based wallet it just triggers the wallet to call the server to update the state. 

Ideally it would be one button per coin. And you'd call it by `/wallet/resyncblockchain/ltc`

**Comment by rmisio** [comment]
This was moved to the top right corner of the transactions list in the Wallet for each coin. There is a `resync` link.

(FWIW, we're still only allowing 1 resync per hour, like in the SPV days. This probably isn't necessary for the API version, but the client is not aware whether a coin is SPV or API based)
