### ISSUE TITLE
Handle Multiple Node Migration

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1632]
## User Story
- As a user with multiple current nodes, when 2.3 is released I want to be able to migrate all of them without losing any data or losing the ability to use any of my nodes.
- After my nodes have migrated, I still want the option to switch between them like I currently do.

## Functional Requirements
- [ ] When a 2.3 client starts a node, instead of passing the coin it should pass a --dataDir (or -d) flag to the server to tell it what data directory to use.
    - Old directories will be updated in place, and won't move. We can use the former coin data to construct the name of the new folder (ie: "OpenBazaar2.0-bitcoincash" will be used if that is the old folder).
    - If the default directory is being used, we don't have to pass a -d flag, though it may be better to just always pass one.
    - Brand new nodes will use the new default directory (OpenBazaar, .openbazaar all lowercase with a period on Linux).

OPTIONAL/STRETCHGOAL: Should we also give the user the ability to specify a path for new nodes? This might be nice if users want to run multiple stores from the bundled app, they could name the folders something that is easy to remember, like "ShoesStore" and "HatsStore".

**Comment by placer14** [comment]
Looking at:
> This should cause the server to migrate that old node to the new data directory.

@jjeffryes Assume a user has an existing `bitcoin` installation at the default install location and wants to install their setup at `/abc`. What does the 2.3 UI pass into the server on the first startup (which would initiate the migration) so it knows which directory to import from and to export the migrated data to?

**Comment by jjeffryes** [comment]
> Assume a user has an existing bitcoin installation at the default install location and wants to install their setup at /abc. What does the 2.3 UI pass into the server on the first startup (which would initiate the migration) so it knows which directory to import from and to export the migrated data to?

@placer14  Thanks, that was an oversight in my description. We need the -d flag to tell the server what the *from* directory is, so we'd need some new flag for the *to* directory, right?

So if you start with -d=bitcoin and -n=abc (I'm using n as the new directory flag, it can be whatever), it would read the data from /bitcoin and write the migrated data to /abc?

**Comment by cpacia** [comment]
> We need the -d flag to tell the server what the from directory is, so we'd need some new flag for the to directory, right?

I think it's way easier to just migrate the existing directory if the -d flag is passed rather than specifying another directory.

**Comment by placer14** [comment]
Why don't we do this: Since we already agreed on using the "connection manager" approach in the bundled setup, why don't we just convert BTC, BCH and ZEC into separate connections in the manager with their associated datadir as the default paths. This would make their install location clear to the user and allow them to manage them as the separate identities they are. And instead of starting the server using `--bitcoincash` the UI would just pass the `-d`. Then the server would just migrate the store as it normally would (into the new multiwallet) using that store's id.

**Comment by jjeffryes** [comment]
This was done.
