### ISSUE TITLE
New Articles are not findable in search

### ISSUE THREAD

**Issue by Franselbaer** [OpenBazaar/openbazaar-desktop#1661]
Brief Description: 

Operating System (OS and version): OSX 10.13.6
OpenBazaar version (shown on `About OpenBazaar` page in menu): 2.2.5
Hardware: iMac

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Create a new listing
2. Wait
3. Search for it

Observed Behavior: Ist not findable

Expected Behavior: Is findable

Additional info (links, images, etc go here):

PeerID: QmWr5spvVUgbyVrPxW1BxuNGzePtHC6mAPhr5dm8YoCxYR

**Comment by Franselbaer** [comment]
### I tested around a bit and changed location in config file and did a restart...

![snap1](https://user-images.githubusercontent.com/11044625/50559122-0d86c380-0cf4-11e9-8b34-34badde64f3f.png)
Change came up in ob1 search listing immediately....


### But products....

![snap2](https://user-images.githubusercontent.com/11044625/50559125-0eb7f080-0cf4-11e9-845a-61d8db91dba3.png)
still not....

**Comment by jjeffryes** [comment]
@Franselbaer I'm unable to reach your node from my test nodes, if the search indexer has the same issue that would explain why your listings aren't appearing.

Can you follow the guide below to forward your 4001 port, and see if that changes anything? It will take the search indexer a while to find and index your node after you make any changes.

https://openbazaar.zendesk.com/hc/en-us/articles/360000282912-How-to-forward-ports-for-OpenBazaar

**Comment by Franselbaer** [comment]
Tanks for looking into. I'll double check. Next year. 😂😁

-- 
Sent from my mobile device

Am Mo., 31. Dez. 2018, 16:17 hat Josh Jeffryes <notifications@github.com>
geschrieben:

**Comment by Franselbaer** [comment]
Tested. The port is open since a long time.

```
root@server-docker:~# nc 212.86.57.86 4001
/multistream/1.0.0
```


Am Mo., 31. Dez. 2018 um 16:17 Uhr schrieb Josh Jeffryes <
notifications@github.com>:

**Comment by jjeffryes** [comment]
I've been able to access your node, but not from all of my test nodes. We're in the middle of releasing v2.3, once we have that out I'll have the rest of the team take a closer look at this.
