### ISSUE TITLE
Problem opening links from Digital Goods orders

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/openbazaar-desktop#1675]
Brief Description: When clicking on a link (example: www.google.com) from a fulfilled digital goods order, it opens the browser but navigates to the following URL instead of the correct one:

http://file///C:/Users/X/AppData/Local/OpenBazaar2/app-2.3.0/resources/app.asar/.tmp/www.google.com

Operating System (OS and version): Windows 10
OpenBazaar version: 2.3 RC9

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 

Steps to reproduce:
1. (As vendor) Fulfill a digital good order with a valid link.
2. (As buyer) Click on link

Observed Behavior: Invalid link opens in browser.

Expected Behavior: Valid link displays in browser.

**Comment by jjeffryes** [comment]
Closed in #1676
