### ISSUE TITLE
Update Websocket Docs

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1694]
This is a tracking issue for work to document the web sockets so the mobile team and other people building compatible services have the guidance they need.

**Comment by rmisio** [comment]
Isn't this an ob-go thing? We're talking about documenting the websocket api in ob-go, right?

**Comment by jjeffryes** [comment]
Yes, that's what that is. It should really be an issue in the docs repo, but I'm working on it right now and wanted a way to track it in the project quickly.
