### ISSUE TITLE
Missing dispute Resolve button for ZEC orders

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-desktop#1707]
Brief Description: When a moderator views a dispute for an order using ZEC, a Resolve button is missing to proceed the dispute forward.

Operating System (OS and version): N/A
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Hardware: N/A

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Create a moderated order with ZEC as the payment
2. Either buyer or seller can dispute the order.
3. The moderator opens the dispute and finds the missing button in the UI.

Observed Behavior:
Resolve button is missing

Expected Behavior:
Expected the Resolve button to be present.

**Comment by rmisio** [comment]
@placer14 Can you please provide the payload of the `ob/case` call?

**Comment by pinheadmz** [comment]
@rmisio This was my issue that I chatted with @placer14 on slack about, I may be able to get you those details from my OB server if you can help me track it down. I sent Mike my complete OB log and the JSON contract from the purchase in question as well.

**Comment by rmisio** [comment]
@placer14 @pinheadmz Actually I think it might not be necessary. Looks like some code had been blown away that shouldn't of been. For coins that don't support an escrow timeout (currently only zec), the Resolve button should appear in the Dispute Started section.
