### ISSUE TITLE
Wrong notification "Order has expired"

### ISSUE THREAD

**Issue by rating89us** [OpenBazaar/openbazaar-desktop#1720]
Today is Mar 14 and I have just received this notification for an order the had been fulfilled 2 hours before: "Order has expired. Once fulfilled, you may claim your payment". Despite the wrong notification, everything is working as expected. The order details are below:

Fullfiled : Mar 14, 2019
Accepted: Mar 12, 2019
Payment: Mar 12, 2019
Order: Jan 26, 2019

**Comment by rmisio** [comment]
@rating89us Thanks for reporting this. Would you mind posting this in the server repo?

https://github.com/OpenBazaar/openbazaar-go

The client gets the notification from the server, so it's really the server erroneously sending it.
