### ISSUE TITLE
18:01:44.815 [ERROR] [core/func1] dial backoff

### ISSUE THREAD

**Issue by MRDO5** [OpenBazaar/openbazaar-desktop#1725]
Brief Description: 

Operating System (OS and version): centos7
OpenBazaar version (shown on `About OpenBazaar` page in menu):  openbazar 2
Hardware: kvm-vm

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 

Steps to reproduce:
1. connect to second local user and send message 

Observed Behavior:

Expected Behavior:

Additional info (links, images, etc go here):

**Comment by jjeffryes** [comment]
Can you give some more details here? Do you mean you're running two nodes, and attempting to send a chat message between them?

What behavior do you see in the client?

**Comment by jjeffryes** [comment]
We don't have enough information for this issue, and it's on an OS we don't support, so I'm closing it.
