### ISSUE TITLE
Icon for cryptocurrency missing

### ISSUE THREAD

**Issue by seanPhill** [OpenBazaar/openbazaar-desktop#1755]
Brief Description: How can I submit the official logo for inclusion in the cryptocurrency drop down list? Veil is already on the list and I have created some listings, bu the icon does not show up in that list.

Additional info (links, images, etc go here): Here is a link to the "press kit" which includes the official icons for Veil.

https://veil-project.com/press/

**Comment by jjeffryes** [comment]
We update the icons from coinmarketcap.com each release, it looks like they have your current icon, you should see it updated with 2.3.3, which will be coming out in the next week or so.

**Comment by seanPhill** [comment]
Excellent! Thanks.
