### ISSUE TITLE
Blocked users can still send message

### ISSUE THREAD

**Issue by 24thsaint** [OpenBazaar/openbazaar-desktop#1756]
Brief Description: 

Operating System (OS and version): Windows 10
OpenBazaar version (shown on `About OpenBazaar` page in menu): client 2.3.2, server 0.13.2
Hardware: AMD

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Client A sends a message to Client B
2. Client B blocks Client A
3. Client A sends another message to Client B
4. Client B still receives the message

Observed Behavior: Messages from blocked users can still be received

Expected Behavior: Messages from blocked users should not be received anymore

**Comment by jjeffryes** [comment]
Thank you for reporting this, @24thsaint 

This is a server issue, we're planning on fixing it in the next release. The chat messages are currently still blocked, but not until the connection to the blocked user is severed. The easiest way to do that is to restart your node.

After it's fixed the chat messages will be blocked immediately.

I'm closing this issue, we're tracking it in the server repo here:
https://github.com/OpenBazaar/openbazaar-go/issues/820
