### ISSUE TITLE
Update Chat Timestamps to Match New Server Code

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1759]
The server PR below changes the format of the timestamps coming from the server to provide more granularity on the time a chat message arrives. We should update the client to match that format so timestamps have the same format in both directions.

https://github.com/OpenBazaar/openbazaar-go/pull/1549

**Comment by rmisio** [comment]
I think we just throw the timestamp into the Moment.js constructor, which may very well handle it already if it's a standard format.

**Comment by jjeffryes** [comment]
This is working without any changes needed.
