### ISSUE TITLE
Enable Non-Developer Mode for Users Installed from Source

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#176]
Whenever the BrowserSync alert is shown on the app (why it's even there I do not understand) it blocks the User's avatar and main menu access. It's fairly short but just a weird function to begin with. Maybe I'm misunderstanding the purpose.

EDIT: We will amend this issue to request the ability to disable development related code when running from source.

**Comment by jjeffryes** [comment]
This only happens in development environments when you're changing the code.

**Comment by rmisio** [comment]
It's just to give you a visual indicator that the app (the browser part) has been auto-refreshed after a code change. That's something browser sync automatically does (not sure how configurable it is).

Anyhow, this illuminates another issue. If there are users who will be running from source (i.e. from the repos), but really have no desire to change the code, we could have a command line option to disable some of the dev related watchers (browser-sync, sass, etc...). It would probably lighten the processing load a bit.

**Comment by jjeffryes** [comment]
That's a good point, I forgot that users running from source will still see it on every start up.

Either a flag to disable dev related code, or a flag to enable it (so anything dev related is off unless you add --dev at start up) would be a good idea.

**Comment by hoffmabc** [comment]
Ok I'll modify this issue to be more of that.

**Comment by rmisio** [comment]
This was actually already in place and non-dev mode can be initiated by starting the app via `npm run start-app` as opposed to `npm start` which starts it in dev mode (launches client + multiple dev processes).
