### ISSUE TITLE
Don't Show Listing Loading View If It's Very Fast

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1762]
With the new IPFS loading, listings load really fast. The loading screen is just a flash, too fast to be seen clearly.

We should consider some way to make it less distracting, like maybe only showing it if the listing takes longer than a second or two to load.

**Comment by rmisio** [comment]
> We should consider some way to make it less distracting, like maybe only showing it if the listing takes longer than a second or two to load.

it's a slipper slope though, because if we delay it a second, what if the listing takes 1.001 seconds to load?

Also " listings load really fast" varies for different people on different network conditions.

**Comment by jjeffryes** [comment]
I think there's probably some better way to do it other than a hard cutoff timer, or a binary show/don't show, I am just not clever enough to think of how yet. :)

**Comment by jjeffryes** [comment]
I'm closing this as too low priority.
