### ISSUE TITLE
barter/ barter exchange

### ISSUE THREAD

**Issue by test2a** [OpenBazaar/openbazaar-desktop#1764]
can we use openbazaar as a barter exchange? 
for example, i can list item A with a value of $ 100 and someone else also has a item B of value $ 100. we should be able to trade. 

next would be a case with me wanting to buy product A with a value of  $100 and i have two products of value $60 and $ 40. i should be able to trade them.

we can look up how established exchanges deal with this and also any taxation involvement that may be there...

**Comment by jjeffryes** [comment]
Thanks for the suggestion. We don't have any plans to include bartering in the future.

Users can arrange barters on their own using the OpenBazaar chat, but the transaction system for tracking orders requires a cryptocurrency to be spent.
