### ISSUE TITLE
Chrome OS Linux beta blank startup screen

### ISSUE THREAD

**Issue by jurjendevries** [OpenBazaar/openbazaar-desktop#1776]
Brief Description: When starting Openbazaar I got an blank window, nothing seems to happen

Operating System (OS and version): Chrome OS 74.0.3729.159 (Official Build) (64-bit)
OpenBazaar version: 2.3.3
Hardware: Google Pixelbook chromebook

Reproducible: Always

Steps to reproduce:
1. Turn on Linux Beta on a Pixelbook (maybe at other Chrome OS devices too) as described at https://support.google.com/chromebook/answer/9145439
2. Download openbazaar2_2.3.3_amd64.deb
3. Open the Linux terminal and browse to the download directory
4. sudo dpkg -i openbazaar2_2.3.3_amd64.deb
5. Start Openbazaar by the Chrome OS launcher
6. You'll get an blank openbazaar window, nothing seems to happen for minutes/hours , but top command shows openbazaar2 with PID and is using around 50% CPU

Observed Behavior:
Blank screen

Expected Behavior:
Functional app

Additional info (links, images, etc go here):

**Comment by jjeffryes** [comment]
We don't currently support Chrome OS. I'm afraid we can't really offer much help with it.

**Comment by jurjendevries** [comment]
> We don't currently support Chrome OS. I'm afraid we can't really offer much help with it.

Hi 'jjeffryes', thanks for your quick reply. What do you mean with 'we'? As I do understand from https://openbazaar.org/blog/troubleshooting-and-how-to-help-with-development-on-openbazaar/ "As the development leaders of this marketplace, we at OB1 are focused on providing a quality user experience within the app but also want to ensure users are empowered outside of it as well so they can troubleshoot issues and help the platform keep growing". Not sure if you are part of OB1, and mean 'we' with that, but it will be great as described at the blog that others that will be helping with this issue can do that.

**Comment by jurjendevries** [comment]
Update: after 4 times trying it seems working. I don't know why it was not working for the first 3 times.

**Comment by jjeffryes** [comment]
I'm the lead UI dev for OB1, by "we" I mean OB1.
