### ISSUE TITLE
Security report

### ISSUE THREAD

**Issue by DaniellMesquita** [OpenBazaar/openbazaar-desktop#1777]
Vulnerabilities were pointed.
Please see the attached HTML file.
[openbazaar-security_report.html.zip](https://github.com/OpenBazaar/openbazaar-desktop/files/3294699/openbazaar-security_report.html.zip)

**Comment by DaniellMesquita** [comment]
Reference: https://github.com/OpenBazaar/openbazaar-desktop/issues/1654

**Comment by DaniellMesquita** [comment]
@jjeffryes

**Comment by placer14** [comment]
@DaniellMesquita Thanks for your report.

These appear to be the concerns the report is raising?
https://github.com/doyensec/electronegativity/wiki/CSP_GLOBAL_CHECK
https://github.com/doyensec/electronegativity/wiki/LIMIT_NAVIGATION_GLOBAL_CHECK
https://github.com/doyensec/electronegativity/wiki/PERMISSION_REQUEST_HANDLER_GLOBAL_CHECK

**Comment by jjeffryes** [comment]
This error appears to be related to using the wrong version of ESLint. It's not a security problem as far as I can tell, nor does it affect the tests we use.
