### ISSUE TITLE
The "Ships To" Input disappears If you search "Trade" first

### ISSUE THREAD

**Issue by apothan** [OpenBazaar/openbazaar-desktop#1782]
Brief Description: 
The "ship to" input does not appear and the "accepted currencies" are all un-checked on the filter column if you [see al]l of the "Trade" category before making another search.

Operating System (OS and version): Ubuntu 18.04
OpenBazaar version (shown on `About OpenBazaar` page in menu): 2.3.3
Hardware: i5 Laptop

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Click the "Discover" button on the OB broswer
2. Click the "OB1" button link
3. Scroll down to the bottom of the "Trade" table and click "See All"
4. Click on "Books" in the "Suggestions" bar below the OB1 search bar
5. Look at the filter column below the "Suggestions". 

Observed Behavior:
The filter column on the OB1 search is missing the "Ships To" input that is usually at the top.
Also the "Accepted Currencies" are all unchecked which makes the next search more difficult

Expected Behavior:
We should be able to see the "Ships To" input and having the "Accepted Currencies" all checked makes the next search easier similar to having the default settings.

Additional info (links, images, etc go here):

**Comment by jjeffryes** [comment]
Thank you for reporting this, @apothan I've confirmed the bug, and have a good idea of what's causing it.
