### ISSUE TITLE
Cache dose not actually get removed when use "Purge Files"

### ISSUE THREAD

**Issue by shellaaaron** [OpenBazaar/openbazaar-desktop#1783]
Brief Description: 
Delete cached files you are sharing with others by Purge Files dose not get removed files stayed.

Operating System (OS and version):  Ubuntu 16.04.6 LTS
OpenBazaar version (shown on `About OpenBazaar` page in menu): 2.3.4 Using Deb Version
Hardware: 
Processor		: 4x Intel(R) Xeon(R) CPU E3-1240 v3 @ 3.40GHz
Memory		: 4194MB (2088MB used)
Operating System		: Ubuntu 16.04.6 LTS
Resolution		: 1368x768 pixels

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
I did update to the latest version 

Steps to reproduce:
1. wget https://github.com/OpenBazaar/openbazaar-desktop/releases/download/v2.3.4/openbazaar2_2.3.4_amd64.deb
2. dpkg -i openbazaar2_2.3.4_amd64.deb
3.  run the software and test it again the same issue, and files located 
home/user/openbazaar2.0-clientData/Cache

also, there is more cache, it's better to have the option to delete all cached files.
openbazaar2.0-clientData/GPUCache

Observed Behavior:

Expected Behavior:

Additional info (links, images, etc go here):

**Comment by jjeffryes** [comment]
I'm closing this issue because it's based on a misunderstanding. The purge files button will purge the IPFS files stored in your server directory, not the client's cached browser files.
