### ISSUE TITLE
Desktop loading Haven listing (Phsyical Good, Used) shows placeholder for Condition value

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-desktop#1785]
Brief Description: Desktop loading Haven listing (Phsyical Good, Used) shows placeholder for Condition value

Operating System (OS and version): Mac
OpenBazaar version (shown on `About OpenBazaar` page in menu): v2.3.4

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce):  Always

Steps to reproduce:
1. Create Used Physical Listing in Haven 
(Example: https://openbazaar.com/store/QmWjUvxugYHZ1qKKZVt7qRHdFzWG5PzL6GUo35TiiuwQLQ/test-textiles or ob://QmWjUvxugYHZ1qKKZVt7qRHdFzWG5PzL6GUo35TiiuwQLQ/store/test-textiles)

Observed Behavior:
Placeholder for the "used" text.

Expected Behavior:
Just the word "used" or similar.

Additional info (links, images, etc go here):
https://www.dropbox.com/s/084otbu7hlxofkv/screen%20shot%202019-07-20%20at%203.19.22%20pm.png?dl=0

**Comment by rmisio** [comment]
@mg I can't get that listing to load. Would you mind posting a screenshot of how it looks on desktop, I'm not sure what you mean by placeholder?

Also if you could post the payload of `http://localhost:4002/ob/listing/QmWjUvxugYHZ1qKKZVt7qRHdFzWG5PzL6GUo35TiiuwQLQ/test-textiles`.

Thanks.
