### ISSUE TITLE
Slow Loading on Followers is Weird

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#181]
This experience is a little weird. I'm not sure exactly what I'm asking to be done here, but perhaps there's a way to make this a little less frustrating. One suggestion might be to have the user card faded out a little if it's still loading? Also is there any way to like sort them so the unloaded ones are always last in the list by any chance? Just curious.

![image](https://cloud.githubusercontent.com/assets/45482/21075108/e68483ec-bed7-11e6-9d53-902e000b94b0.png)

**Comment by jjeffryes** [comment]
The loading message is a placeholder. We need to create a loading state, and a failed to load state.

**Comment by hoffmabc** [comment]
Jon so should we close this or leave it for that?

**Comment by jjeffryes** [comment]
Who's Jon?

Leave this open as a todo for loading and failed states.

**Comment by jjeffryes** [comment]
@morebrownies we'll still need a design for a loading and failed state for usercards. The same design could apply to listingcards as well (in card and list view).

**Comment by morebrownies** [comment]
Ok, on my list. Did we ever find out who Jon is? 😂

**Comment by hoffmabc** [comment]
We don't have a way to figure out to Jon is.
