### ISSUE TITLE
Eth-Precision Variants Table Off By One

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1816]
When filling in the information for variants, the columns are off by one, making the headers appear at the top of the wrong columns.

The second variant column seems to be missing (it should have red, green, and blue in it).

![image](https://user-images.githubusercontent.com/1584275/67024054-c37b9c80-f0d1-11e9-8fda-9e3ae23fd0e7.png)

**Comment by jjeffryes** [comment]
If I remove the second option, the variant section displays correctly, just FYI.

![image](https://user-images.githubusercontent.com/1584275/67024798-00945e80-f0d3-11e9-981d-c80a21f664a0.png)

**Comment by rmisio** [comment]
This is now fixed in the `eth-precision` branch.
