### ISSUE TITLE
Eth-Precision Quantities in Order Details are Zero

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1819]
I made 2 orders, the first with a quantity of 1, the second with a quantity of 2, but both are showing a quantity of zero.

![image](https://user-images.githubusercontent.com/1584275/67503479-b3c20200-f655-11e9-9243-e9089cd55219.png)

**Comment by rmisio** [comment]
This is due to:

https://github.com/OpenBazaar/openbazaar-go/issues/1814

Once that's fixed, it should just work for the client.

**Comment by jjeffryes** [comment]
Lol. I was just coming here to post the same thing and close the issue after looking at the list of server errors. :)
