### ISSUE TITLE
Allow address on the server configuration besides IP

### ISSUE THREAD

**Issue by adhoc-zone** [OpenBazaar/openbazaar-desktop#1823]
Previous openbazaar-desktop versions allowed the input of an address in the server configuration. On it's current version, `2.3.5`, openbazaar-desktop only accepts IP addresses:

![ob-forces-ip-small](https://user-images.githubusercontent.com/54063966/67594220-c45ca000-f75b-11e9-83d4-763fee65acb8.png)

Please fix this regression and get it back to accepting addresses, as those are much useful, specially when the underlying IP changes often.

The (not so) funny part about this regression is that old server configurations, saved on previous openbazaar-desktop versions, before addresses were disallowed, still work on `2.3.5` and connect through the address. Furthermore, even when creating new configuration on `2.3.5`, we can trigger it to connect through the address by clicking `Save` and then `Cancel`. It seems that the interface tries to accept only IPs, but fortunately, the underlying backend still accepts addresses.

**Comment by rmisio** [comment]
@adhoc-zone It's probably we upgraded a validation lib and it previously considered the text addresses as valid IPs and no longer does. We should be able to tweak things to restore the previous behavior

**Comment by adhoc-zone** [comment]
Thanks, that would be much helpful.

Meanwhile, do you know in which file does openbazaar-desktop store that field? I've looked all around `~/.config/OpenBazaar Desktop Client` but couldn't find it.
I would like to change it directly to put an address in there. Right now I have to use that tedious `Save` and `Cancel` trick in order to connect to my openbazaar-go instance.

**Comment by rmisio** [comment]
It's in local storage, so you'd have to muck with JSON serialized local storage content. Probably safer to use the `Save` and `Cancel` trick (<--- really a bug!).
