### ISSUE TITLE
Eth-Precision Price Rounding in Fiat is Inconsistent

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1825]
When a listing is priced at less than 0.01 of fiat currency, it's displayed with unexpected rounding in the purchase flow.

For example, if the price is displayed as $0.003, and the quantity is 2, the total is shown as $0.01.

I'd expect the use of 3 digits to be consistent, and the price displayed as $0.006.

I saw something similar with $0.00003 x3 displayed as $0.0001 instead of $0.00009.

Below are the listings I saw that behavior on, if you want to check them:

ob://QmcF2eG2tpRCZddxi8oCnpk5E8pHyRGp3nFbFzPMBGpyGt/store/test-inventory-surcharge-for-eth-precision

ob://QmcF2eG2tpRCZddxi8oCnpk5E8pHyRGp3nFbFzPMBGpyGt/store/test-phys-eth-precision

![image](https://user-images.githubusercontent.com/1584275/67690712-c4cf8380-f973-11e9-9847-33238a63c63b.png)

**Comment by rmisio** [comment]
I could see if there's low-ish hanging fruit that would help with this one.

Is this the only place in the receipt where we multiply or are there other places this same behavior could be a problem?

**Comment by jjeffryes** [comment]
I think this is the only place we do math on separate amounts. Everywhere else that I can think of we just use the actual payment.

**Comment by rmisio** [comment]
Also, what are the expectations for this scenario?

first item shipping .003
second item shipping .00009
total .01

would you want .003009?

**Comment by jjeffryes** [comment]
Maybe the simple solution is to put a * next to the total with "* rounded up to the nearest 0.01, actual price in [crypto code] may be different." under it?

**Comment by rmisio** [comment]
I'd run that suggestion by the design team. It seems stranger to me than leaving things as is.
