### ISSUE TITLE
Validate to prevent FIXED_PLUS_PERCENTAGE moderator fees of 0%

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1834]
The server is being updated to disallow setting a fixed plus percentage moderator fee with 0 as the percentage, and will throw an error if such a fee is saved.

Since we validate the other values and show an error before they're saved, we should do the same for that case.

**Comment by rmisio** [comment]
The server no longer imposes this validation.
