### ISSUE TITLE
When viewing your own Profile client retrieves profile via IPNS

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#190]
Instead of retrieving your own profile data directly the client retrieves the profile data from the IPNS call, which results in stale data when updating your avatar and other information.

![image](https://cloud.githubusercontent.com/assets/45482/21119323/14f61146-c090-11e6-8e9e-164156b1f1a8.png)

1) Change avatar in Settings -> Page
2) Save
3) View your page
4) Ctrl+r or Cmd+r refresh the page

Avatars will then revert to the previous settings.
![image](https://cloud.githubusercontent.com/assets/45482/21119382/5408c306-c090-11e6-911f-46d7c7347f4c.png)

**Comment by rmisio** [comment]
This one is blocked by: https://github.com/OpenBazaar/openbazaar-go/issues/268
