### ISSUE TITLE
Global shipping

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-desktop#192]
When a user creates a listing, they cannot select 'Global' or 'everywhere' to create simple categories such as:

- Global free shipping
- Global standard vs express shipping

As far as I can tell, they have to select all the countries in order to do this. A global option should be right at the top of the country drop-down, along with other shipping regions that I know we wanted to support.

**Comment by jjeffryes** [comment]
This has been resolved with the "All" option.
