### ISSUE TITLE
Bug: New listings aren't displaying in the Store page

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-desktop#195]
I can create a new listing in the client and it saves correct... ie:

- The server correctly saves the listings
- I can retrieve the newly created listing by hitting the API directly
- The client even says that it saves, and when I click the bottom notification to view the listing, it shows the listing

*BUT*... when I go to the store page, the listing isn't there.

**Comment by morebrownies** [comment]
I can confirm, I have the same issue.

**Comment by drwasho** [comment]
Yay, I'm not crazy!

See @jjeffryes I told you... I told you!

![0](https://media.giphy.com/media/KWzzTbkhDvmQU/giphy.gif)

**Comment by jjeffryes** [comment]
It does confirm it's a bug that exists, I believe Rob has already found it and had a fix.

On the other hand, it does not confirm you aren't crazy in a general sense, only in this specific instance.
