### ISSUE TITLE
Settings: Color Options

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-desktop#196]
<img width="727" alt="screen shot 2016-12-13 at 9 44 39 am" src="https://cloud.githubusercontent.com/assets/3887694/21121538/d9da09e4-c118-11e6-954a-b4689d53a8b0.png">

Suggestion: display the colors in a shape (circle or square) under the 'primary, secondary, or text color' headings... because unless you're a developer, no one knows what these codes mean.

**Comment by morebrownies** [comment]
Yeah, I agree. Something like this would be great. 

![screenshot 2016-12-13 19 14 38](https://cloud.githubusercontent.com/assets/13066886/21168388/6a363d4c-c168-11e6-85f8-45721d71e1af.png)

**Comment by srhoulam** [comment]
![ob-color-preview](https://cloud.githubusercontent.com/assets/7725148/22759457/8740e560-ee20-11e6-8312-5fecaff68e53.png)

Not as pretty as @morebrownies, but it gets the point across.
