### ISSUE TITLE
Settings: Text misaligned

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-desktop#197]
<img width="512" alt="screen shot 2016-12-13 at 9 47 00 am" src="https://cloud.githubusercontent.com/assets/3887694/21121611/2cf731ba-c119-11e6-82c5-61565e319d55.png">

Needs some polishing

**Comment by morebrownies** [comment]
I think this has been resolved @drwasho. Can you close if it looks better now?

**Comment by jjeffryes** [comment]
I believe this has been fixed.
