### ISSUE TITLE
Home: Font color

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-desktop#199]
<img width="288" alt="screen shot 2016-12-13 at 9 50 54 am" src="https://cloud.githubusercontent.com/assets/3887694/21121727/b9ae75b4-c119-11e6-88be-855d24542a2b.png">

Need a similar tweak that we have for OBv1 so that the text is easily visible irrespective of the image color.

**Comment by morebrownies** [comment]
I'll take this one
