### ISSUE TITLE
Sometimes user card never gets timed out Loading...

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#202]
If a user card eventually times out or can't be reached it needs an unreachable state.

![image](https://cloud.githubusercontent.com/assets/45482/21150374/c60e1220-c12c-11e6-9dbc-54c9e19c9e73.png)

**Comment by hoffmabc** [comment]
I see this seems resolved in the listingDetail screen @jjeffryes

**Comment by hoffmabc** [comment]
If so, I can close this.

**Comment by jjeffryes** [comment]
@hoffmabc I don't think anything was changed with this in the listing details PR?

**Comment by jjeffryes** [comment]
This is a duplicate of #117
