### ISSUE TITLE
Advanced Settings: Mouse-over weird behavior

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/openbazaar-desktop#204]
https://youtu.be/LliOE7XMgyY

OS: macOS Sierra

**Comment by jjeffryes** [comment]
Unforeseen interaction between the form buttons and the button highlight. Should be easy to fix.

**Comment by morebrownies** [comment]
I swear I fixed this on one of my branches. Must have gone missing :(

**Comment by jjeffryes** [comment]
This is addressed in #175 and #212

**Comment by jjeffryes** [comment]
This was fixed.
