### ISSUE TITLE
Set Shipping Filter To User's Country by Default

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#210]
On the store page, the shipping filter should default to the country of the user's first saved address, or the country set in the Settings/General tab if they have no saved addresses. 

This is a sub-task from #80.

**Comment by rmisio** [comment]
In a discussion with @morebrownies , we decided the default Ships To should be `(Any country)`, otherwise the default view of the store is a filtered result set. The thinking was it's less than ideal if for someone to see all the listings in a store, they would need to clear some filter(s).

**Comment by jjeffryes** [comment]
Ok. I'll update #80 to reflect that.
