### ISSUE TITLE
When the Category Field Loses Focus, It is Cleared

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#211]
In the edit listing view, when text is added to the category field, and the field loses focus, the text disappears and is not saved when the save button is pressed.

**Comment by rmisio** [comment]
This is not specific to the Category field. It is the default Select2 behavior for tagging fields. I'm not sure if Select2 offers us a way to configure this or what type of effort it would be to "macGyver" it.

**Comment by jjeffryes** [comment]
Ah. I didn't realize that was a select2 field. I know I've brought up adding whatever text is in the field when it loses focus previously. 

This is a pretty big gap for select2, both selectize and taggle have it out of the box as an option.

**Comment by jjeffryes** [comment]
This was fixed a while back.
