### ISSUE TITLE
There isnt a way to easily change my primary photo or re-order my photos on a Listing

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#216]
The photos currently display in the order they were uploaded. It would be great if you could drag and drop photos to change the order. We're also going to need to display an indicator on the primary photo.

<img width="706" alt="screenshot 2016-12-15 12 58 09" src="https://cloud.githubusercontent.com/assets/13066886/21241780/2b17989a-c2c6-11e6-846e-496fc3c25f20.png">

**Comment by rmisio** [comment]
@morebrownies The indicator is really easy and can be done via CSS targeting the first photo. Do you have a design for that?

**Comment by morebrownies** [comment]
We can reuse the Free Shipping badge, but with the word **Primary**

![screenshot 2017-01-05 15 56 58](https://cloud.githubusercontent.com/assets/13066886/21702305/9b62f758-d35f-11e6-9a47-8870bc30417b.png)
