### ISSUE TITLE
Wrapping on User Menu looks odd

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#218]
Are we really doing it this way for wrapping?

![image](https://cloud.githubusercontent.com/assets/45482/21242837/36808322-c2e4-11e6-9dd4-47c0a6a2395a.png)

**Comment by morebrownies** [comment]
We definitely need to truncate that text. I'll fix it

**Comment by jjeffryes** [comment]
Just put the .noOverflow class on it.
