### ISSUE TITLE
The store name and avatar isn't displaying in the listing detail modal

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#238]
@rmisio and I discussed this earlier today...

When viewing a listing, the store name / avatar isn't displaying anywhere within the modal. We need to output this information so that shoppers aren't required to close the modal to see what store they're looking at.

![screenshot 2016-12-23 16 38 47](https://cloud.githubusercontent.com/assets/13066886/21464317/4dd20e60-c92e-11e6-8937-88f237a7926a.png)

**Comment by rmisio** [comment]
If you view a listing from the store, we already have this data, so it wouldn't be a problem to add this in.

But, if you will view a listing from search or channel, we will not have any profile data and I would be really hesitant to have to make a call to the profile api for each listing. It would mean each listing would require 2 calls (profile api + listing api) and we've already seen how slow profile calls can be.

@cpacia Since this requires a very small set of data, what do you think of embedding profile.name and profile.avatarHashes inside each listing?

**Comment by cpacia** [comment]
I'd nack that. Would require changing every listing every time the profile changes and trying to keep everything in sync. Then you'd lose the caching of each listing each time you made a profile change.

**Comment by rmisio** [comment]
Well then we need to have a larger discussion on this issue because the alternative, as I mentioned, is a profile call for every listing accessed outside of a store. On the one hand we're siting the importance of caching, but out the other end we're doubling our server requests to show a listing.

**Comment by cpacia** [comment]
It seems like the only situation where you don't already have that data is if someone direct links to a listing. So that should be the only time in which you would need to make a separate call. And in that case the length of time needed to return the profile call would be the same as it takes to return the listing  so I'm not sure there would be any problem with one part of the data loading faster than another.

**Comment by rmisio** [comment]
> It seems like the only situation where you don't already have that data is if someone direct links to a listing.

That is not true. The only place we have that data is if the user is viewing the listing from the Store. When clicking a listing from Search or Channel, we will not have profile data for each listing there and if we need it (to satisfy this request), we would need to fetch it.

> And in that case the length of time needed to return the profile call would be the same as it takes to return the listing so I'm not sure there would be any problem with one part of the data loading faster than another.

That's a complete assumption. Right now profile calls mysteriously, and fairly regularly take 10+ seconds to come back.

If we're forced to do a profile fetch in addition to a listing fetch to show a listing, we're either a.) going to risk introduce latency before a listing is loaded b.) we could lazy load the profile part, but that's arguably bit tacky to have such a prevalent part of the design come later.

**Comment by cpacia** [comment]
> When clicking a listing from Search or Channel, we will not have profile data for each listing there and if we need it (to satisfy this request), we would need to fetch it.

Doesn't the search designs have the profile information in the search results? I thought it displays the avatar and name of the store. 

> Right now profile calls mysteriously, and fairly regularly take 10+ seconds to come back.

It's ipns calls that take a while. Which is what would be made when fetching a listing from a direct link. So it would take as long as a profile call.

**Comment by rmisio** [comment]
> Doesn't the search designs have the profile information in the search results? I thought it displays the avatar and name of the store.

Oh, you're right. At least the avatar is needed in Search & Channel for the listing preview. We would totally need that data provided with the results set. It would be madness to have to make a separate profile and / or listing call for each little preview.

I'm really not sure how Channel would work. Once again, if we architect it where for each little preview we need to make 1 or more API calls, we're really running the risk of making a really clunky slow page of spinners.

**Comment by rmisio** [comment]
@jjeffryes I can't find the document you made for @tyler-smith with the data that should be returned by 3rd party search. If the store name and avatar aren't there, can we include them in?

**Comment by jjeffryes** [comment]
It's in there. Here's the expected data:
```
totalResults: x (total number of results found),
listings: [
    {
       "hash": "QmZ7VRovdDVNrwKxnMMRgJ32R4kgfR3FLYFtNjhu5SDgJX",
       "slug": "test",
       "title": "test22",
       "category": [],
       "contractType": "PHYSICAL_GOOD",
       "description": "\u003cp\u003etest description\u003c/p\u003e",
       "thumbnail": {
           "tiny": "Qmd2st8EHRbTN8cEqVnJs7cmYfW3fDEsmKFTLnY4N1gAUM",
           "small": "QmNT9BtxLeaF9q5Z4RVagDHe2YN1uGRncZj3LMXBs9M8hm",
           "medium": "QmXNp4qCcaRaotpcz9A8BBgL78jn3eJwRYS3em3b5Q5cjj"
           },
       "price": {
           "currencyCode": "USD",
           "amount": 12312300
           },
       "shipsTo": [
           "ALAND_ISLANDS",
           "AFGHANISTAN",
           "AMERICAN_SAMOA",
           "UNITED_STATES",
           "UNITED_KINGDOM"
           ],
       "freeShipping": [
           "UNITED_STATES"
           ],
    “countryOfOrigin”: “UNITED_STATES”,
    “rating”: 4.1,
    “totalRatings”: 52,
    “condition”: “Like New”,
    “NSFW”: false,
    “lastCrawled”: timestamp of the last time this was crawled, 
           “seller” : {
        “guid”: guid,
        “handle”: handle,
        “name”: name,
        “avatar”: {
            “tiny”: hash,
            “small”: hash
            }
        }
    },
]
```

Channels should have similar data.
