### ISSUE TITLE
Inconsistent modal navigation header.

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-desktop#239]
Modals with a left-hand navigation block have inconsistent headings. One has no heading, another has the type of modal (settings) as the heading, and others have a generic 'MENU' heading. Do we want to make these more consistent with each other?

![image](https://cloud.githubusercontent.com/assets/794517/21505513/e99e356c-cc1c-11e6-9eeb-7ede20b9f976.png)

![image](https://cloud.githubusercontent.com/assets/794517/21505534/0daddcaa-cc1d-11e6-955e-43cad4a98215.png)

![image](https://cloud.githubusercontent.com/assets/794517/21505554/3951ae36-cc1d-11e6-9ca1-b45ab14ce05b.png)

![image](https://cloud.githubusercontent.com/assets/794517/21505562/48261708-cc1d-11e6-980e-998fa375dd25.png)

**Comment by jjeffryes** [comment]
I think it would be good to be consistent here. This is probably just something that changed and didn't get updated in the old designs.

**Comment by jjeffryes** [comment]
The designs have been updated, all of the menus should have "MENU" in all caps with the text color at the top.

**Comment by hoffmabc** [comment]
I am closing this because it's a design request. If you'd like to open up issues related to actually making these changes please do but otherwise consider this issue finished.
