### ISSUE TITLE
Chat features

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#250]
openbazaar-go now has support for chat, allowing peers to exchange strings. Duo Search is now implementing chat, and I am interested in knowing which chat features the reference client will have. That is, how will the reference client interpret the chat strings that are exchanged? In particular,

1. Will the reference client support links in the chat box?
2. Will the reference client allow for sharing inline images in the chat box?
3. Will the reference client allow for sharing inline videos in the chat box?
4. Will the reference client allow for any other chat features (e.g. markdown, link unfurling, HTML, voice recording, etc.) in the chat box?

**Comment by morebrownies** [comment]
1. Yes, links will be clickable
2. Probably not in 2.0
3. Probably not in 2.0
4. Probably not in 2.0

**Comment by jjeffryes** [comment]
We may support images and video tags, so long as the media source is external.
