### ISSUE TITLE
Following font is jagged. 

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-desktop#253]
Probably rendering bad on a non-retina screen

![image](https://cloud.githubusercontent.com/assets/4504708/21623148/0ec481a4-d1cf-11e6-82c0-e121e46be166.png)

Same for Store, Home, and Followers.

**Comment by jjeffryes** [comment]
What resolution are you using?

I tried my monitor at 1440 x 900 and 800 x 600, but didn't have any jaggedness. 

What OS is this on? You may not have font smoothing activated.

**Comment by cpacia** [comment]
3440 x 1440 ubuntu.

**Comment by jjeffryes** [comment]
That would be considered retina resolution, so it's not a resolution issue. 

Do you have font smoothing turned on?

**Comment by jjeffryes** [comment]
I'm labeling this as a question until we can determine if it's an app issue or a systems settings issue.

**Comment by morebrownies** [comment]
I'm still thinking about this one. Haven't come up with a better solution yet, but I agree that it can be improved.
