### ISSUE TITLE
Add Moderation Tab to Settings Modal

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#254]
![image](https://cloud.githubusercontent.com/assets/1584275/21624305/803f348c-d1d4-11e6-8b98-71919182e1ae.png)

The Moderation tab is the section in the Settings Modal that allows a user to set their status as being available as a moderator or not, along with their moderator settings. 

## Functional Requirements

- [x] A control to set moderation status to on or off. This control also shows the current status.
- [x] A drop down to select fee options.
    - Percentage of order
    - Fixed fee,
    - Fixed fee + percentage
- [x] An input to set the percentage
- [x] An input to set the fixed fee. 
- [x] A select to set currency of the fixed fee, defaulted to the user's currency if not set yet.
- [x] A text area to set the description. The limit is 300 characters. 
- [x] A text area to set the terms. The limit is 10,000 characters. This box should be stretchable if this can be vertical stretching only.
- [x] A checkbox to confirm the user has read the OpenBazaar Dispute Resolution Guidelines.
- [ ] A link to the OpenBazaar Dispute Resolution Guidelines that opens in an external browser.
- [x] A checkbox to confirm the user understands the requirements to offer dispute resolution.
- [x] A "I agree to offer dispute resolution to anyone that requests my moderation services".
- [x] A save button.

## Data

The data for this modal comes from the Moderator API 
- moderator: boolean, true means this user is a moderator
- moderation_fee: a number, up to two decimal places, it is a percentage of the transaction being moderated

The following parameters do not currently exist in the API:
- type of fee
- either another field for a fixed fee, or moderation_fee acts as a fixed price when the fee type is not percentage
- moderator description, a string
- moderator terms, a string
- languages, an array of language codes

TODO: put moderator data in Profile, and Profile API instead of moderator API
- set description limit to 300 characters
- set terms limit to 10,000 characters
- move languages to the page tab (UI and Backend)
- validate language codes on the server

**Comment by rmisio** [comment]
> An input to set the fixed fee in BTC. The current value of the fee in the user's currency (if not BTC) should be shown. The BTC value will be saved.

The value will not be saved in BTC. The API includes the currency code with the amount, so the value will be saved in whatever currency code we include in the Save call, which I assume would be the user's selected currency.

**Comment by rmisio** [comment]
>  A tagged select box to set languages spoken (this may be moved to the Page tab).

Yeah, that's odd to me that this data would live here (both in the UI and in the Moderators API). I would think this should live on the Page tab and in the Profile API.
