### ISSUE TITLE
Chat "Typing..." feature

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#258]
A common feature for chat client is for the receiver to have a notification (e.g. "Typing...") when the sender is typing. Is that something the reference client is looking to implement?

It's actually possible to implement this using the current `CHAT` messages, where empty messages can be interpreted as "is typing now". cc @cpacia

**Comment by JustinDrake** [comment]
This was implemented by @cpacia in [this commit](https://github.com/OpenBazaar/openbazaar-go/commit/9a72c7872e1b960557081757f04df5c374256e93). Very fast! 👍

**Comment by morebrownies** [comment]
@rmisio is in the process of adding this to the client too

**Comment by jjeffryes** [comment]
This was added some time ago.
