### ISSUE TITLE
Update API urls

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-desktop#260]
- [ ]  ipns/[peerID]/profile -> /ob/profile/[peerID]

- [ ] ipns/[peerID]/listings/index.json -> /ob/listings/[peerID]

- [ ] ipns/[peerID]/followers -> /ob/followers/[peerID]

- [ ] ipns/[peerID]/following -> /ob/following/[peerID]

- [ ] ipfs/[imageHash] -> /ob/images/[imageHash]

More to come

**Comment by JustinDrake** [comment]
I missed the discussion on this. What's the rational for the change?

**Comment by rmisio** [comment]
I think the main reason was to wrap IPFS calls, because then the server could validate that data obtained from IPFS is valid. Otherwise, if we directly get it from IPFS, which is essentially from someone's file system, it's susceptible to being manipulated.

**Comment by hoffmabc** [comment]
Any updates?
