### ISSUE TITLE
Body scrolling when focused in a select2 input doesn't work

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#276]
I'm focused in the **Category** input and can't scroll the body 

![screenshot 2017-01-09 13 44 45](https://cloud.githubusercontent.com/assets/13066886/21784764/cb7faafc-d671-11e6-9e9d-873c2d6c31a5.png)

**Comment by rmisio** [comment]
closing as duplicate of #113
