### ISSUE TITLE
Change deliverySpeed rating to delivery

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#281]
One of the five star ratings is "Delivery speed". There are several important aspects of delivery other than speed, such as wrapping and packaging quality. Moreover, the delivery speed will largely be determined by the shipping option chosen by the buyer.

As such, I think the "Delivery speed" star rating should be generalised to "Delivery".

**Comment by JustinDrake** [comment]
FYI, I am implementing the ratings for Duo, and this is my current labels for the five ratings:

- Overall
- Quality
- As advertised
- Delivery
- Service

I have opted for generality and conciseness of labels.

cc @morebrownies, @jjeffryes

**Comment by morebrownies** [comment]
@drwasho thoughts?

**Comment by morebrownies** [comment]
@JustinDrake I applied these language changes to the latest transaction designs. @drwasho feel free to veto if you have different thoughts. Closing issue. 

![screenshot 2017-02-17 13 12 45](https://cloud.githubusercontent.com/assets/13066886/23083496/ca17d27e-f512-11e6-9026-5a39d5c49049.png)
