### ISSUE TITLE
Decouple "Release funds" from "Review"

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#282]
At the moment (in openbazaar-go) the review process has to happen at the same time as order completion (to release funds). This means the buyer cannot first release funds and then post a review. It also means the buyer cannot post a review without releasing the funds (e.g. in the case of a refund).

Would it make sense to decouple the process to release funds from the review?

cc @cpacia

**Comment by morebrownies** [comment]
I've worked this request into the designs:

![screenshot 2017-02-17 12 49 34](https://cloud.githubusercontent.com/assets/13066886/23082750/8f63b97a-f50f-11e6-9b5d-35c7332536cd.png)

**Comment by JustinDrake** [comment]
@morebrownies Awesome! Can I confirm that:

1. A review can be left after the order is completed
2. A review can be left before the order is completed

I believe this logic hasn't been implemented in openbazaar-go. Would you mind opening an issue?

**Comment by cpacia** [comment]
I don't think they should be able to leave a review without closing the order. The vendor wants to get the funds as soon as possible. More likely people will forget if that is allowed.

**Comment by morebrownies** [comment]
There is more to think about than just getting funds to the Vendor quickly though. For example, if a Vendor never fulfills my order (on a direct payment), how/when would I have an opportunity to leave negative feedback? 

I'm also thinking most transactions will end in the funds getting released automatically (via the timed release). Once the release happens, and the order status advances to complete, we should send a notification to the buyer encouraging them to leave feedback. 

It feels like a much healthier experience on both sides.
