### ISSUE TITLE
We are unable to connect to the API websocket (2.0.1)

### ISSUE THREAD

**Issue by misog** [OpenBazaar/openbazaar-desktop#288]
Brief Description: 

Operating System (OS and version): Windows 10 64bit
OpenBazaar version (shown on `About OpenBazaar` page in menu): 2.0.1

Steps to reproduce:

0. Run openbazaar-go-windows-4.0-amd64.exe start
1. Run OpenBazaar2-2.0.0-Setup-64.exe or OpenBazaar2.exe

OR

1. Run OpenBazaar2-2.0.0-Setup-64.exe or OpenBazaar2.exe

Observed Behavior:

> Socket connection failure
> We are unable to connect to the API websocket.

In addition, the release is 2.0.1 but the file is named as OpenBazaar2-2.0.0-Setup-64.exe [https://github.com/OpenBazaar/openbazaar-desktop/releases](https://github.com/OpenBazaar/openbazaar-desktop/releases)
![obrazok](https://cloud.githubusercontent.com/assets/6667651/21862918/8a96e25a-d83b-11e6-8855-8e4aea324265.png)

**Comment by misog** [comment]
yes, there is a guid

**Comment by rmisio** [comment]
This is a problem if you are using the latest server which runs on port 4002 with an older client which is trying to connect on 8080.

We have a UI feature coming soon where you will be able to change the port the client is using.

For now, to work around the issue you could update the port in the server config file to use the old port. In `config` change `"Gateway": "/ip4/127.0.0.1/tcp/4002",` to `"Gateway": "/ip4/127.0.0.1/tcp/8080",`.

**Comment by misog** [comment]
@rmisio where is the config file located?

**Comment by misog** [comment]
it works now, thanks
