### ISSUE TITLE
Add Tor Controls in the Client

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#315]
## User Story
As a user, I want to be able to use TOR, and have the client give me the option to use TOR when it is available. I should be able to control which connections use TOR, and when.

### All Bundled Startups
- on startup, the client will use the status message process to start and stop the server and get an error code indicating if the server can access TOR.

### New Bundled Connection Startup
- if the server can use TOR, and the current connection has never had the "use TOR" flag set, the Manage Servers modal will open, with the current connection edit modal open. 
- a message will be shown asking the user if they want to set this connection to use TOR.
- there will be a "Use TOR" checkbox.
- there will be a "TOR SOCKS5 Proxy" text input field. It will be pre-filled with the detaul value.
- the proxy input may be hidden if the "Use TOR" checkbox is not checked.
- when the connection is saved, it will attempt to start the server with the TOR flag set.

### Existing Connection Startup
- if the server can use TOR, and the current connection has been set to use TOR, the client will start the server with the TOR flag set.
- if the server cannot use TOR, and the current connection has been set to use TOR, the client will show the Manage  Servers modal, with an error message stating that the server cannot be started in TOR mode. 
- the user can edit the connection to not use TOR, create a new connection to a different server, use a different existing connection, or fix the issue with the server and try again.

### Editing a Connection
- any time the Use TOR value is changed for a connection, a warning should be shown explaning that any account that has been used in non-TOR mode has associated its IP Address with its peerID. If the same server is used in TOR mode later, that association can be used to match their TOR activity with their IP address. 

### TOR Mode
- while using TOR, there should be a visual indicator that the client is in TOR mode.
- while using TOR, all connections from the client to other servers should go through the connected server node or through the TOR SOCKS 5 proxy (for example, externally hosted images in a field that allows HTML code).
- when a user in TOR mode clicks on a link that will be opened in an external browser, ideally a warning with cancel and confirm buttons (and maybe a "don't show this warning again" checkbox) would be shown, since the link may not open in their TOR browser.
    - it would be nice if the warning had an option to copy the href of the link so it can be examined and pasted in a TOR browser if safe.

**Comment by cpacia** [comment]
I imagine the modal asking if they want to use Tor can also show the tor port. Probably a better experience to combine into one modal.

**Comment by jjeffryes** [comment]
@cpacia that's how I have it.
