### ISSUE TITLE
Ships To filter on Store Page Filtering Out Valid Listings

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#320]
On main screen by default (Any Country) I see multiple listings.
<img width="968" alt="screen1" src="https://cloud.githubusercontent.com/assets/45482/22034081/fae6f050-dcb8-11e6-9771-7724832114bb.png">

If I choose a specific country they all go away.
<img width="982" alt="screen2" src="https://cloud.githubusercontent.com/assets/45482/22034110/156ca23a-dcb9-11e6-818b-7850d2785452.png">

**Comment by jjeffryes** [comment]
It appears that @drwasho has somehow saved physical goods with no shipping information?

That should get rejected, unless he's using one of his experiments to populate his listings.

@cpacia do we validate that on the server? The server should be rejecting any listings with a type of physical good but no shipping options.

**Comment by jjeffryes** [comment]
This feature works correctly with listings that have the expected data.

**Comment by jjeffryes** [comment]
This has been fixed on the server.
