### ISSUE TITLE
User card location overflows out of the card

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#327]
![image](https://cloud.githubusercontent.com/assets/45482/22115198/1921c7b6-de3a-11e6-8fd3-6c435fb313ba.png)

**Comment by rmisio** [comment]
@morebrownies Do we just want to add ellipses to solve this?

![image](https://cloud.githubusercontent.com/assets/794517/22311386/1dbc6c4a-e308-11e6-9df5-78ce4a03c0c2.png)

becomes

![image](https://cloud.githubusercontent.com/assets/794517/22311395/2c90d0d0-e308-11e6-87ab-5e9e7b437237.png)

FWIW, there's no way to add a location via our UI. I think these must be @tyler-smith dummy nodes adding these in. I guess location is a completely free form field.
