### ISSUE TITLE
Add Reddit in social media accounts

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#33]
A lot of the early OpenBazaar adopters are Bitcoiners which are active on Reddit. I thing complementing Twitter and Facebook with Reddit would enrich the vendor profiles.

**Comment by rmisio** [comment]
oops, closed by mistake. re-opening.

**Comment by rmisio** [comment]
We are re-working the UX for social accounts in v2. There will likely be a drop-down of available social accounts types. I'm not sure if Reddit will be one of the options, but Other will be one of the options, so it can always be represented that way. I believe it's still to be determined what the full set of options will be, so Reddit may just make it in.

**Comment by JustinDrake** [comment]
Using "Other" is probably to right way forward for stuff like LinkedIn, Reddit and future social media platforms.
