### ISSUE TITLE
Design the User Not Found page

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-desktop#349]
We need a design for the User Not Found Page:

![image](https://cloud.githubusercontent.com/assets/794517/22669983/ffa77aba-ec7b-11e6-9cc6-d97112a0f459.png)

The most common ways this would happen is if you enter a guid or handle in the address bar that does not correspond to a user.

**Comment by morebrownies** [comment]
@rmisio can you provide me a list of all the "___X___ not found" error states that need designs? Would a generic 404 Page Not Found type of error be better in these cases? For example, If someone typed @store/blog we'd have to throw an error in that scenario too.

**Comment by hoffmabc** [comment]
Ping @rmisio on this. Any updates for @morebrownies ?

**Comment by rmisio** [comment]
This was completed. Josh beefed up the look and content of the not found pages.
