### ISSUE TITLE
Moderation Tab (Fixed + %)

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#350]
Right now the moderation tab gives you inputs for % and fixed fee but I think the inputs should be reversed. 

We call it Fixed Fee + Percentage but the inputs are Percentage and then Fixed Fee.

![image](https://cloud.githubusercontent.com/assets/45482/22709342/77a20f78-ed47-11e6-93be-1e1a9e01ef43.png)

**Comment by jjeffryes** [comment]
This was closed in #352.
