### ISSUE TITLE
Listing prices not displaying in the default currency I set

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#357]
When I visit QmUy1RVNx8prZbz9DodfjULZ16q2nBGuK6R9p4dq9ZD5SY I'm seeing prices in BTC instead of USD (I set my currency to display in USD within settings) 

![screenshot 2017-02-08 14 11 19](https://cloud.githubusercontent.com/assets/13066886/22759792/98712ba0-ee08-11e6-94db-7a27f2e695a8.png)

**Comment by jjeffryes** [comment]
I'm unable to reproduce this. Did you change your settings, and then not click the refresh bar that appeared in the store? Until you do that, the listing cards won't refresh with the new currency.

**Comment by morebrownies** [comment]
Yeah still an issue. When I visit QmaLCqEoHZ842um5Z4wnFpKhfsFaMQXjMEyd25U2HVmtjY I see prices in BTC. When I visit my store, I see prices in USD.

![screenshot 2017-02-17 13 19 34](https://cloud.githubusercontent.com/assets/13066886/23083699/d671bc0a-f513-11e6-821b-3ada3ff512ef.png)
![screenshot 2017-02-17 13 20 14](https://cloud.githubusercontent.com/assets/13066886/23083700/d6729f80-f513-11e6-84a4-0201bcfea4ca.png)

**Comment by rmisio** [comment]
@morebrownies I'm not able to reproduce this one. Since it was from so long ago, I'll assume it was fixed and will close for now. If you see it again, please feel free to re-open.

**Comment by morebrownies** [comment]
Seems good now, thanks.
