### ISSUE TITLE
Hide Follow button on own User Card

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-desktop#358]
![image](https://cloud.githubusercontent.com/assets/794517/22799887/4a0e5276-eebc-11e6-9bfd-28e2cfaf3ef4.png)

Rather than just being a no-op, the Follow button should, IMHO, be hidden on your own user card.

**Comment by morebrownies** [comment]
+1

**Comment by morebrownies** [comment]
This is actually a duplicate of #106

**Comment by jjeffryes** [comment]
Closing as a duplicate.
