### ISSUE TITLE
Less than character breaks page settings

### ISSUE THREAD

**Issue by xbbricker** [OpenBazaar/openbazaar-desktop#360]
Brief Description: 

If a non-space character follows a literal  '<' in the page settings, only the text up to the '<' can be saved.

Operating System (OS and version): 10.12.3
OpenBazaar version: 1.1.11, server version 0.2.5

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:

1. Open Settings
2. Open "Page" tab
3. Enter "1<2. QED" without quotes into the Short Description field
4. Save Changes

Observed Behavior:

The Short Description field now reads: "1"

Expected Behavior:

The Short Description should read: "1<2. QED"

**Comment by jjeffryes** [comment]
This is a bug in the openbazaar-client, which is a different repo.
