### ISSUE TITLE
Is the project looking for translators? 

### ISSUE THREAD

**Issue by gustavohmsilva** [OpenBazaar/openbazaar-desktop#366]
Brief Description: Is the whole texts present in OpenBazaar-desktop 2 centralized on "js/languages/en-US.json"? If so, I'm volunteering for translating it to my native language if the software has a language selector feature (otherwise there'll be no reason for translating it right now).

Operating System (OS and version): Debian Jessie
OpenBazaar version (shown on `About OpenBazaar` page in menu): 2.0
Hardware: Acer R11

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Open Software
2. Search for language options
3. Don't find it.

**Comment by jjeffryes** [comment]
The language file won't be complete for a while yet, once it is, we'll be adding the project to Transifex for translation. We don't want to start translating now when we're still adding new phrases and changing old ones. 

Once we have most of the text ready and it's on Transifex, we'd love to have your help!

**Comment by gustavohmsilva** [comment]
Great! Count me in for Brazilian Portuguese and European Portuguese.

**Comment by jjeffryes** [comment]
Closing this issue as resolved.
