### ISSUE TITLE
Make color square clickable

### ISSUE THREAD

**Issue by srhoulam** [OpenBazaar/openbazaar-desktop#371]
Brief Description: The color preview square in the settings screen can't currently be interacted with. 

Operating System (OS and version): Ubuntu 16.04
OpenBazaar version (shown on `About OpenBazaar` page in menu): 2.0.0

Observed Behavior:
Clicking the color square triggers no behavior.

Expected Behavior:
Present a color picker on click, ultimately removing the color code input.

Additional info (links, images, etc go here):
https://projects.invisionapp.com/share/RC9Q3H5X8#/screens/211105705_Openbazaar-2-0-Page-Store-Customize-Advanced-Picker

**Comment by jjeffryes** [comment]
We could do a two-step implementation here. An initial, and very easy, fix, it to use the native HTML color input. 

Later, if/when we implement a custom color selector for the customize user page story, we can also use that color selector here.

**Comment by rmisio** [comment]
This is done (at least a simple version using the native HTML color input).
