### ISSUE TITLE
Chat messages should be sanitized.

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-desktop#373]
For example, potentially malicious tags like 'script' need to be handled and not output by the app literally.

The chat head would need a similar treatment.

As of now, the server is not sanitizing, but probably should be.

**Comment by rmisio** [comment]
Logged a server issue (https://github.com/OpenBazaar/openbazaar-go/issues/398).

This is actually a much bigger issue than just chat. Any user entered data needs to sanitized.

If there server does implement this globally, it does become redundant to also do it on the client and it's up for debate whether it would be needed client-side as well.

**Comment by hoffmabc** [comment]
I think that if we consider the server and client as being two independent softwares it makes sense to do it in both places. Perhaps the server is not protected against certain attacks at least the client may proactively prevent issues. I think either side should be skeptical that all issues are being handled by the other.
