### ISSUE TITLE
Should chat timestamps update in real-time?

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-desktop#374]
Since we are using relative timestamps for chat... do they need to update in real (or semi-real) time?

![image](https://cloud.githubusercontent.com/assets/794517/23472778/d3171656-fe62-11e6-8dee-6b0762e65468.png)

For example, after a minute, 'a few seconds ago' would become 'a minute ago'.

**Comment by rmisio** [comment]
I would think that, yes, they should update. But... I would probably mark this as a nice-to-have and worry about it post release. If we keep trying to implement every little chat detail, it's going to keep dragging on a while.

**Comment by jjeffryes** [comment]
This is a tough call. If it's easy to do, we should do it. If it's hard... it could be really weird if we defer it, as you could get a bunch of messages that all say "a minute ago" even though the older ones aren't a minute old any more.

**Comment by rmisio** [comment]
I don't think it's super hard to do... I just need to be mindful of performance, since there could potentially be dozens or hundreds of messages in view. I need to do a little research to find out how expensive multiple setIntervals are and also be smart about on re-rendering a message if the timestamp actually changed.

My guess is it's probably 4 hours of work.

An alternative is just using the absolute date / time, like in v1 (e.g. Mar 1st, 2017 9:33pm) which would be a few minute switch and then later on circling back and doing the relative time properly.

Just depends on how important having the relative time is right now.

**Comment by jjeffryes** [comment]
Let's just use absolute time, and add an issue to go back and make it relative later.

**Comment by morebrownies** [comment]
Would it be useful to mark some of these smaller tasks with "Help Wanted" @jjeffryes? This seems like a good one for the community to work on.

**Comment by hoffmabc** [comment]
Great suggestion.

**Comment by jjeffryes** [comment]
@morebrownies yes, that would be good.

**Comment by rmisio** [comment]
This was completed.
