### ISSUE TITLE
Add Sounds to UI

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#387]
This is a tracking issue for all the sounds needed for the client.

- when a new chat message arrives
- when a new notification arrives (catch all for notifications not listed below)
- you have been followed
- you have made a sale
- a purchase has been completed
- a purchase has been disputed
- a dispute has been resolved

**Comment by cpacia** [comment]
Received bitcoins

**Comment by rmisio** [comment]
this was fixed.
