### ISSUE TITLE
Links should be clickable in chat conversations

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#389]
We should make web and OpenBazaar links clickable in chat. Currently they display as plain text.

![screen shot 2017-03-09 at 2 00 06 pm](https://cloud.githubusercontent.com/assets/13066886/23772683/c5c4bb2e-04d0-11e7-96ec-ee98fcf5703b.png)

**Comment by rmisio** [comment]
if web links are prefaced with http:// https:// or www., then we could handle those.

if ob links are prefaced with ob://, then we could handle those.

In the screenshot above, I don't think we could reasonable make that into an ob link. Without the ob:// preface, it would very likely require some complicated (and potentially expense - performance-wise) logic to determine that is an ob link.

**Comment by morebrownies** [comment]
That should be fine @rmisio. Once we have #110 in place, more people will copy and paste valid OpenBazaar URLs.
