### ISSUE TITLE
Slack-style chat formatting

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#390]
Is it planned to add Slack-like chat formatting?

![screen shot 2017-03-10 at 09 43 54](https://cloud.githubusercontent.com/assets/731743/23790249/3e14e842-0576-11e7-82b5-bf949ca74b60.png)

Simple, powerful, idiomatic.

**Comment by jjeffryes** [comment]
If you mean markdown, no, there is no plan to add that right now. We may do so in the future.
