### ISSUE TITLE
Profile schema refactor

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-desktop#394]
Changes and discussion is here https://github.com/OpenBazaar/openbazaar-go/pull/388

**Comment by rmisio** [comment]
@jjeffryes Can we get a JIRA story for this? I think this could be a couple days of work.

**Comment by jjeffryes** [comment]
I've added this to Jira.

**Comment by hoffmabc** [comment]
Linking JIRA would be nice.
