### ISSUE TITLE
tmp directory not generated when running electron app

### ISSUE THREAD

**Issue by bearbin** [OpenBazaar/openbazaar-desktop#397]
Brief Description: As title.

Operating System (OS and version): debian 9.0
OpenBazaar version (shown on `About OpenBazaar` page in menu): N/A
Hardware: N/A

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. git clone https://github.com/OpenBazaar/openbazaar-desktop.git
2. npm install
3. npm run start-app

Observed Behavior:

.tmp directory not generated and electron generates the error:

    Not allowed to load local resource: file://[]/openbazaar-desktop/.tmp/index.html

Expected Behavior:

..tmp directory generated and electron app runs fine.

Additional info (links, images, etc go here):

**Comment by rmisio** [comment]
I'll look into this. For now, if you want to run the app `npm start` should work.

**Comment by jjeffryes** [comment]
@rmisio did you look into this? I don't think it's ever happened again.

**Comment by jjeffryes** [comment]
I am closing this issue as non-reproduceable.
