### ISSUE TITLE
Don't Duplicate a Listing on Save

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#403]
Brief Description: 

When saving a new listing, if the save button is clicked rapidly it will save duplicate versions of the listing, each one with an incremented slug (test, test1, test2, etc.).

This should be prevented from happening. 

It appears to only happen with new listings.

Operating System (OS and version): Win10

Reproducible Always

Steps to reproduce:
1. click the save button in the edit listing screen to save a new listing
2. immediately click save again, one or more times
3. close the edit listing modal and refresh the store page.

Observed Behavior:
Multiple copies of the same listing are created, with incremented slugs.

Expected Behavior:
Only one copy of the listing should appear.

![image](https://cloud.githubusercontent.com/assets/1584275/24116953/bfcca9dc-0d7e-11e7-9201-60e5049bcd6c.png)

**Comment by rmisio** [comment]
this was fixed.
