### ISSUE TITLE
GUID is being deprecated in favor of Peer ID

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#412]
I believe this was discussed, but if we are in agreement on this, the UI will need to be updated globally for this and is a substantial task.

**Comment by JustinDrake** [comment]
I think both "OpenBazaar ID" and "Peer ID" are acceptable nomenclature to present to users.

**Comment by rmisio** [comment]
This is done. The client in places does use variable names 'guid', but any references in the UI should be to "Peer ID" and any references to 'guid' in data obtained from APIs should have switch to 'peerId' (or 'peerID' - servers not always consistent... lol).

**Comment by JustinDrake** [comment]
The correct name on the server is `peerID` (not `guid`, not `peerId`)

cc @cpacia
