### ISSUE TITLE
Product Photo Auto-Crop is Off

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#413]
I created a listing with a wide photo
![image](https://cloud.githubusercontent.com/assets/45482/24214219/3e2b02a0-0f0b-11e7-9504-8c4203f0a388.png)
![image](https://cloud.githubusercontent.com/assets/45482/24214234/463be4a0-0f0b-11e7-9d72-2a5daa5d707e.png)

for a listing and it auto-cropped it to:
![image](https://cloud.githubusercontent.com/assets/45482/24214206/33d45284-0f0b-11e7-9a83-0eb2c8aea664.png)

I think it should probably be a centered crop? Right now it seems to be a left aligned crop.

**Comment by morebrownies** [comment]
+1

**Comment by jjeffryes** [comment]
The client doesn't control the crop, can you file this as an issue in the server repo?

**Comment by jjeffryes** [comment]
(to elaborate, the actual image is square, so the client can't do anything to show a centered version of the image, it's showing everything available already)

**Comment by hoffmabc** [comment]
How come the larger square crop looks fine and the smaller one is left centered @cpacia?
