### ISSUE TITLE
Delete Button Needs a Confirm Step/State

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#414]
This delete button just goes ahead and nukes the listing with no confirmation. Probably not a great approach unless we can back out of it somehow.

![image](https://cloud.githubusercontent.com/assets/45482/24214481/053bf2fa-0f0c-11e7-9fe9-946a9365035d.png)

**Comment by jjeffryes** [comment]
@morebrownies I'll add this to the backlog as a design task as well as a UI task. We should probably have a general purpose confirm state for things, either a two-step button or a tooltip like we have in the transaction designs.

**Comment by rmisio** [comment]
I'm pretty sure this was designed already and it's essentially the same as is already in place when trying to delete a server config:

![image](https://cloud.githubusercontent.com/assets/794517/24220668/6c0c97c2-0f08-11e7-9c07-9567897bbadb.png)

So.. i imagine some code could possible be re-used.

Also... I have a feeling there may already be a big for this.

**Comment by jjeffryes** [comment]
The zeplin project for editing listings is closed, can you find the design and paste a screenshot here?

**Comment by morebrownies** [comment]
Yeah it is the same thing, as @rmisio pointed out. I can re-open the zeplin project.

**Comment by morebrownies** [comment]
![screenshot 2017-03-22 14 09 08](https://cloud.githubusercontent.com/assets/13066886/24220841/29349f0c-0f09-11e7-9f00-893a11d07ea4.png)

**Comment by jjeffryes** [comment]
Cool. Thanks.
