### ISSUE TITLE
import / export of shop listings

### ISSUE THREAD

**Issue by i5heu** [OpenBazaar/openbazaar-desktop#420]
Is there a easy way to import / export the item list of my shop?

**Comment by jjeffryes** [comment]
Currently there is no way to import or export listings.

We have the ability to import listings on our roadmap, it will be added eventually.

**Comment by jjeffryes** [comment]
Importing was added, we don't have plans to add a listings export for now.

**Comment by yevhen-kulihin** [comment]
can't find any import features
