### ISSUE TITLE
Moderator Fees

### ISSUE THREAD

**Issue by anyone-ob** [OpenBazaar/openbazaar-desktop#439]
Moderators are very important for a decentralised marketplace like openbazaar. In order to keep the moderator market healthy, we should update the fee model to make it more interesting to become a moderator.

This is a good example:

![unbenannt](https://cloud.githubusercontent.com/assets/26906061/25178173/f9db866e-2504-11e7-8950-445affc9839f.png)
![unbenannt2](https://cloud.githubusercontent.com/assets/26906061/25178448/2a84a6d2-2506-11e7-9449-1c2f61fd6281.png)

Screenshot from https://www.bitrated.com

**Comment by cpacia** [comment]
Right now you can do a fixed fee per dispute, a percentage of each dispute, or a fixed fee plus a percentage. 

There isn't an option to require fees on non-disputed orders though. It's actually not that difficult to do except I'm not sure that bitcoin can handle outputs that small. Presumably the moderator fee would only be like a few pennies per tx if _all_ orders are expected to pay a fee (disputed or not) but sending a few pennies to a bitcoin output would basically leave that output undependable give the fees today.

**Comment by jjeffryes** [comment]
I don't see any benefit to having the moderator charge for a non-disputed fee. If a transaction is not disputed, it's invisible to the moderator. It requires no effort or resources from them, they don't even know it happened.

**Comment by hoffmabc** [comment]
I understand why moderators might want to charge for the service no matter what and that letting them decide for themselves is not an unreasonable request, but I'm with @jjeffryes in that I don't know what users would be paying for unless it's like assistance that doesn't get compensated. 

There could be a scenario where they're helping a buyer or merchant through something, they figure it out and then just cut the mod out of any kind of fee.

**Comment by jjeffryes** [comment]
We don't have any plans to implement a feature like this, so I'm closing this issue.
