### ISSUE TITLE
Warnings about unsecure and deprecated nodejs modules

### ISSUE THREAD

**Issue by M0Rf30** [OpenBazaar/openbazaar-desktop#44]
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**Comment by hoffmabc** [comment]
These are not directly called by our application so these must be upstream dependencies and will have to be reported to those projects to have updated. I'm closing this as it's not going to result in action in this repo. Thanks for reporting though.
