### ISSUE TITLE
Add Transactions Section

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#440]
## User Story
As a user, I want to be able to view a screen that has a list of all my transactions, purchases, sales, and disputes I am moderating (cases). This screen should let me filter and search my transactions. I should be able to take an action to see the details of a transaction, and take further action if needed (see the requirements for the Transaction Details screen).

### Tab Bar
- [ ] there should be a tab bar at the top of the screen.
- [ ] the tab bar should have the viewing user's avatar, name, and other information, identically to the user page tab bar (it may be a good idea to create a small reusable view for both).
- [ ] the tab bar should have 3 tabs (Sales, Purchases, Cases). Clicking on a tab will show the transactions associated with that tab.
- [ ] each tab should have a number next to it, this number is the total number of transactions for each.

### Search and Filters
- [ ] there should be a search bar. It is activated by pressing the enter key while it has focus.
- [ ] on activation, any text in the search bar is searched for in the transactions type currently active (sales, purchases, cases).
- [ ] the search is applied to the order number, title, id, handle, shipping address (name of other party if that's available). 
- [ ] there are 8 filters, each of which represent one of the possible statuses of a transaction. By default Purchasing (an unfunded order) is unchecked, and the rest are checked.
- [ ] the displayed results are filtered by the checked filters (as an OR).

Filter : Status

New order, has not yet been accepted by the vendor (direct pay, offline)
Purchasing, PENDING   = 0;

Vendor has accepted the order and is awaiting payment (direct pay)
Purchasing, CONFIRMED = 1;

Buyer has funded the order
Ready to Process, FUNDED    = 2;

Vendor has shipped the item/sent the digital good
Fulfilled, FULFILLED = 3;

Buyer has completed the order, released the funds, and left a review
Completed, COMPLETE  = 4;

Contract is under active dispute
Disputed, DISPUTED  = 5;

The moderator has resolved the dispute and we are waiting for the winning party to accept the payout.
Dispute Closed (this text should be updated), DECIDED   = 6;

The winning party has accepted the dispute and it is now complete. After the buyer leaves a review the state should be set to COMPLETE.
Dispute Resolved, RESOLVED  = 7;

Vendor refunded the order
Refunded REFUNDED  = 8;

Buyer canceled the order (offline order only)
Completed, CANCELED  = 9;

Vendor declined to confirm the order (offline order only)
Completed, REJECTED  = 10;

### List of Transactions
- [ ] the currently retrieved transactions are shown in a list.
- [ ] clicking on the date header will change the order from ascending to descending by date
- [ ] REMOVE: the drop down to change the currency. 
- [ ] ADD: the price in BTC in parenthesis after the fiat price, if the price is in fiat.
- [ ] if the user changes their currency in the settings, this page will show a refresh pop up or refresh the screen. 
- [ ] if the status of the order has an action required, that action is shown in the status column, with the appropriate buttons.
- [ ] if the transaction is marked as unread, it is bold and has a green bar.
- [ ] if the transaction has unread messages, a number in a green bubble is shown next to the buyer id/handle.
    - if the status is PENDING(0), the buyer may cancel the order. The seller must confirm or reject the order.
    - if the status is CONFIRMED(1), the buyer must fund the order.  
    - if the status is FUNDED(2), the seller must refund the order or fulfill it (this will open the details screen).
    - if the status is FULFILLED(3), the buyer must complete the transaction (this will open the details screen).
    - if the status is DECIDED(6), either the buyer or seller must accept the decision (this will open the details modal).  
- [ ] show pagination controls at the bottom of the page.

## Data
The following APIs will be used for this functionality:

- ob/purchases
- ob/sales
- ob/cases

To meet all of the requirements above, the APIs for sales, puchases and cases would need something similar to the following parameters:

ob/[purchases/sales/cases]?
limit: [int],
offsetId: [int],
sortBy: [string], (optional, we may want to just always use date)
descending: [boolean] (if true, sort in descending order, if false ascending) 

To meet all of the requirements above, the APIs for sales, purchases, and cases would need to return additional data similar to that below:

total: int

For loading the avatars, we would want an API that allows the client to request an avatar with the peerID and size as parameters (in the url, as a GET). This call should return cache headers so that the results are cached for a long time, to prevent the network from making a large number of calls in a short period of time.

**Comment by rmisio** [comment]
this is done.
