### ISSUE TITLE
Show error on failed listing image upload.

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-desktop#441]
When you attempt to upload a listing image and it fails, there's no indicator that an error occurred other than the image not appearing.

dev note: I believe there was (is?) code in place to show an error either inline or in a modal. If I'm not mistaken, it also accounted for the fact that the user may have chosen to upload multiple images in one go and only one may fail.

**Comment by jjeffryes** [comment]
Do you know why, specifically, the image is failing? If you try to upload an image with an invalid file name, the failure handling code fires as expected, and shows the error. 

Maybe there's a fail case we're not handling?

![image](https://cloud.githubusercontent.com/assets/1584275/25202827/c34edbd0-2524-11e7-858c-075c7c462bd2.png)

**Comment by rmisio** [comment]
It's failing on the server with 'too many open files', so... it looks like we're handling client side errors, but not server ones.
