### ISSUE TITLE
Make peers without profiles still messageable

### ISSUE THREAD

**Issue by jackkleeman** [OpenBazaar/openbazaar-desktop#448]
Brief Description: 
Currently a peer without a profile can't be clicked on in 'connected peers' and can't be looked up. I think this could be handled a little differently - some peers may not have profiles, but they should still be messageable, eg browser peers using openbazaar.chat. These currently show up as greyed out in 'connected peers'.

I think a peer without a profile should be clickable, and you will then reach an empty profile, which notes they don't have one, but still has a message button. This could be called the '404 profile'. I think this should also be the screen if you look up a peer id in the search bar without a profile.

This would really improve the communication with non-standard peers, like browser clients.

cc @JustinDrake

**Comment by rmisio** [comment]
hmm... I need to chew on this one a bit more, but my first thought is that the Connected Peers page is just a dummy placeholder page. Eventually, you're only going to discover other users by our different "discover" experiences (channels, search, etc...).

So... I guess the only instance where you'd see a non-standard peer is if you enter their peerId in the search bar.

But, to show a user page, the first thing we do is fetch the profile. So, to satisfy this, I guess the profile API would need to differentiate between a 404 because the node doesn't exist versus it being a node without a profile. You'd have to talk to @cpacia about the feasibility of that change.

I think there would be a good amount of scope here for us on this one.

From a UX perspective, why would a user, using the v2 client want to message a non-standard peer?

Wouldn't it be better for parties that want something like that to set-up a standard peer (with an avatar, description, about, etc...) that acts as a gateway to the non-standard peer?

**Comment by rmisio** [comment]
Or even simpler, why not just give the non-standard peer a profile?

**Comment by JustinDrake** [comment]
> So... I guess the only instance where you'd potentially see a non-standard peer is if you enter their peerId in the search bar.

You are missing a couple of important instances:

1. The node receives a chat message (e.g. one sent from openbazaar.chat). This opens connection.
2. The node receives an order from a node without a profile. The vendor surely will want to talk to the buyer regardless of profile.

**Comment by rmisio** [comment]
Why can't those nodes have a profile? I would think a user would feel weird receiving a message or an order from a faceless peer.

**Comment by JustinDrake** [comment]
> Why can't those nodes have a profile?

I've addressed this [here](https://github.com/duosearch/openbazaar.chat/issues/3#issuecomment-296219320). It's for privacy and protection against spam.

**Comment by rmisio** [comment]
I'm not sure I see how having a dummy profile limits your privacy or exposes you to an increased likelihood of spam.

The fact of the matter is that our desktop client has never considered the case of users having to interact with a node / user that doesn't have a profile. There's many places where we would be fetching the profile and / or an avatar. An example is on the transactions screen (which I'm coding up now):

![image](https://cloud.githubusercontent.com/assets/794517/25297302/b622ee1e-26a1-11e7-8bfa-a023af05be1f.png)

Without an avatar / profile that buyer column will be empty or just contain a peerId. I'm not sure how a vendor would feel about such an order.

In this particular instance, I'm pretty sure our app would gracefully handle the situation, but there's probably other situations where without a profile we may just show an error message and not allow the user to proceed. We simply never intended to be able to chat, sell stuff to, etc... to nodes without a profile and I don't know what the scope would be at this point to handle that case.

It seems like you are trying to use the protocol in a way it wasn't intended and I would definitely weigh the privacy / spam concerns you have with the fact that such nodes (without rework on our part) may be incompatible with the desktop client.

**Comment by morebrownies** [comment]
> I've addressed this here. It's for privacy and protection against spam.

@JustinDrake I wonder if privacy controls would be a better alternative. If this is about blocking incoming chat spam, maybe more chat privacy controls would suffice?

**Comment by JustinDrake** [comment]
> chat privacy controls would suffice?

Yes, my thinking was half baked. Another alternative is transient buyer identities (e.g. generate a new identity for every transaction).

**Comment by tyler-smith** [comment]
> Yes, my thinking was half baked. Another alternative is transient buyer identities

Perhaps I'm misunderstanding, but do you mean transient identities at the client layer or the protocol layer? I.E. Alternative clients like Duo could provide/utilize transient identities but the protocol handles them like normal? Or do you mean a change to the protocol to always use transient identities?

Personally I think I would tackle the openbazaar.chat problem by creating short-lived transient identities on your side, with a profile, for each chatter. If at some point you have some sort of persistent account mechanism you could keep a profile for each user and use that.

**Comment by JustinDrake** [comment]
> do you mean transient identities at the client layer or the protocol layer?

client layer

**Comment by jackkleeman** [comment]
I think we will try and make some default profiles, thanks for all your suggestions.
