### ISSUE TITLE
Search provider policy

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#449]
The [latest developer release](https://blog.openbazaar.org/openbazaar-2-0-new-developer-release-2-0-3/#.WPzM6lPysxg) includes search by OB1 (congrats to the OB1 team!):

> Search has been added to the reference client. It defaults to use the OB1 search service (this can be changed in the user’s settings).

OB1 is the default for the developer release and I was wondering how users will pick their search engine for the full release of OpenBazaar. I am expecting the signup flow to include a pane for the user to pick her favourite engine. This would avoid setting a hard default.

<img width="595" alt="screen shot 2017-04-23 at 16 59 09" src="https://cloud.githubusercontent.com/assets/731743/25315025/38d7557a-2846-11e7-94ce-76219638e03d.png">

For neutrality the ordering of the various search providers displayed could be randomised.

Does the OB1 have any thoughts on the search provider policy for the full release? Will the OB1 default be removed in favour of a more neutral process?

**Comment by hoffmabc** [comment]
We obviously intend to allow users to select the engine of their choice. We haven't finalized how that will be done. Random is not a good choice however as all search engines will not be considered as safe to recommend as a default.
