### ISSUE TITLE
Standardise sub-categories

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#45]
Below are examples of how the `category` free text field is been used by current online vendors:
- `Yard Sale - Electronics`
- `Corn, Pumpkin, Melon etc.`
- `6. Tools/Misc.`
- `Cedar oils / essential / resin`
- `Hobby &amp; Sports`
- `Coins & Paper Money :: Bullion :: Silver :: Bars & Rounds`
- `Shoe Care & Accessories › Shoelaces`

As you can see, vendors have been creative with separator fragments (using `-`, `,`, `/`, `;`, `&`, `::`, `›`) to make a hierarchy of subcategories. It would be helpful if the client front-end (and backend, cc @cpacia) could have better support for a path of sub-categories instead of a single flat monolithic category field.

**Comment by JustinDrake** [comment]
As described [here](https://blog.duosear.ch/instant-categories-3078de589f48#.38snexp3l), Duo Search has spent a lot of time "fixing" listing categories. CC'ing @morebrownies @jjeffryes for their thoughts on this issue for improvement categories.

cc

**Comment by jjeffryes** [comment]
We're not going to be implementing this in the foreseeable future.
