### ISSUE TITLE
Shorter default names

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#463]
When a new node is created and no name is specified, it looks like the reference client is creating a random name of the from `ob ` + a random string.

![screen shot 2017-04-26 at 13 18 26](https://cloud.githubusercontent.com/assets/731743/25434116/f13848fc-2a82-11e7-882e-962cd5f9c1d9.png)

The random string is very long, so much so that we had to clip it on www.openbazaar.chat. We would appreciate it if the random part could be kept short, e.g. 6 characters long. The random string uses lowercase letters and digits, so 6 characters yields (26+10)^6 = 2,176,782,336 possibilities (two billion!).

**Comment by hoffmabc** [comment]
I think that's probably reasonable barring any technical reason for the extra long string. @cpacia?

**Comment by JustinDrake** [comment]
Cool. While we're at it maybe replace `ob ` by `OB ` (uppercase) 👍

**Comment by jjeffryes** [comment]
There's no particular technical reason for it, it's arbitrary. We picked something long because people can type in long names, and any system showing names should be able to display a name at least that long, or handle the overflow gracefully (clipping is a perfectly acceptable solution for that).

**Comment by JustinDrake** [comment]
I think this has been fixed. Thanks :)
