### ISSUE TITLE
Add Transactions Details

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#466]
## User Story
As a user, I want to be able to take an action on the Transactions screen #440 to see the details of a transaction. I should be able to see what stage the transaction is in, take actions to move the transaction to the next stage if appropriate, and start a dispute. I should be able to send and receive chat messages specific to that transaction.

## Functional Requirements
The Transactions Details screen is shown as a modal, and has several sections.
- [ ] If the close button is clicked, the modal will close.
- [ ] If the "return to x" link is clicked, the modal will close.
- [ ] the text on the return link should be appropriate to the section the modal was launched in (sales, purchases, cases).

### Other Party Section
- [ ] The other party (buyer or seller. The moderator sees the party that opened the dispute) information is shown in this section at the top left.
- [ ] The other party's avatar, name, location, and any social links are shown.
- NOTE: this probably requires a profile call, and may be asynchronous (loads after the rest of the screen).

### Menu
- [ ] The menu has several links.
- [ ] Summary Link: shows the summary of the order.
- [ ] Discussion Link: shows the discussion. The number of unread discussion messages is shown in a bubble next to the link.
- [ ] Contract Link: shows the contract in JSON format.
- [ ] Below the links is an action button. If the viewing user can take an action based on the stage of the transaction, the button is shown with the appropriate text. Clicking it will trigger the action. 
- The action button in this section should always be the primary action. The secondary action, if any, is not shown here.

### Summary
The summary shows the details of the order.
- [ ] The order ID is shown. 
- [ ] There is a copy link next to the order ID. Clicking it or any other part of the order ID will copy the order ID to the clip board, and show the standard "copied" notifier. 
- [ ] There is a progress bar that shows which stage the order is in.
- the revised stages are Pending, Accepted, Paid, Fulfilled, Complete
- when an order is disputed, the stage will remain at the last stage. The data should be available to determine this from the stage details shown lower on the page.
- [ ] As each stage of the transaction is completed, a section for that stage is added to the summary, in order of most recent at the top to oldest at the bottom.
- [ ] There is a details section. It shows information about the transaction.
    - The name of the listing.
    - The quantity.
    - The variants. The variants will vertically stack if there are more than one (this may change, Mike is considering this).
    - The ship to information if it's a physical listing. The address has a copy button, and a link to open the address in Google maps (in an external browser).
    - The coupons if any (there can be any number).
    - The moderator if any (there can be a max of 1).

### Summary Stages
- [ ] PENDING (0): This was an offline order that hasn't been funded
    - Actions (Buyer): Pay
    - Stage: None
    - Data: show the total value of any payments that have been made, so if partial payment has been made the user can see that the order is not fully funded yet. **DESIGN NEEDED**
- [ ] UNCONFIRMED(?): This was an offline order, the buyer has paid for it, the seller must accept it.
    - Actions (Seller): Accepted (moves to Funded), Reject (only on direct orders, not on moderated orders)
    - Actions (Buyer): Cancel (this returns the buyer's payment. Only on direct orders, not on moderated orders)
    - Stage: None
    - Data: 
- [ ] CONFIRMED (1): The buyer made the order when the vendor was online, but has not paid for it yet.
    - Actions (Buyer): Pay
    - Stage: None
    - Data: show the total value of any payments that have been made, so if partial payment has been made the user can see that the order is not fully funded yet. 
- [ ] FUNDED (2): The buyer has funded the order.
     - Actions (Seller): Fulfill or Refund. Fulfill opens the fulfillment screen. Refund shows a confirmation tooltip with a cancel and a confirm button.
    - Actions (Buyer): Dispute
    - Stage: Paid
    - Data: Amount paid, number of confirmations. 
    - [ ] Clicking on the number of confirmations should open information on the transaction in an external web page (blockchain.info).
If a partial payment has been made, show it with the total that needs to be paid. **DESIGN NEEDED**
- [ ] FULFILLED (3): The seller has sent the listing.
    - Actions (Buyer): Complete or Dispute. When completing the order, the user can submit a review. When disputing an order, the user can send a message.  
    - Stage: Fulfilled
    - Data: If physical, Shipping information (if any), Tracking Number (if any) with a copy link, Note if any sent.  if digital url and password (if any). If the transaction is a service, there is no form to fill out.
- [ ] COMPLETE (4): The buyer has completed the order.
    - Actions: none
    - Data: show the review.
- [ ] DISPUTED (5): The buyer or seller has disputed the order.
    - Actions (Moderator): Resolve Dispute
    - Data: the name of the party disputing the order, and the dispute message (truncated?). 
- [ ] DECIDED (6): The moderator has issued a decision on the dispute.
    - Actions (Buyer and Seller): Accept Payment. This will show a confirmation tooltip.
    - Data: The payout to each party, including to the moderator, and the moderator resolution message. 
- [ ] RESOLVED (7)
    - Actions (Buyer): Complete (the buyer can leave a review at this point, the same as the normal complete action). 
    - Data: None. 
- [ ] REFUNDED (8): The seller has refunded the buyer's funds.
    - Actions: none
    - Data: the amount refunded, the number of confirmations
    - NOTE: when the status is refunded, the progress bar changes to show only Pending and Refunded.
- [ ] CANCELED (9): the buyer canceled the offline order before it was accepted.
    - Actions: none
    - Data: none
    - NOTE: when the status is refunded, the progress bar changes to show only Pending and Canceled. 
- [ ] REJECTED (10): the seller rejected the offline order.
    - Actions: none
   - Data: none
   - NOTE: when the status is refunded, the progress bar changes to show only Pending and Rejected. 

### Pay for Order Section
**DESIGN NEEDED**

### Open Dispute Section
- [ ] The user must enter a message for the other party.
- [ ] There is a submit button that triggers the dispute and sends the message.
- [ ] there is a Back to summary link that returns to the summary.
- [ ] there is a Cancel link that returns to the summary.

### Fulfill Order Section
The Fulfill section is shown when the seller clicks the fulfill button. 
- [ ] If the transaction is a physical transaction, there are fields for shipping carrier (required), tracking, and note. The note is a text area. 
- [ ] if the transaction is a digital transaction, there are fields for the url (required), password, and comment.
- [ ] there is a button to add emojis to the comment.

### Leave Review Section
The Leave Review section appears when the buyer leaves a review.
- [ ] There is a text area where the buyer can enter plain text. It has a max character limit of 3000.
- [ ] There are star buttons. They default to 5. The user can click on a star to set the rating to that number (ie: clicking on star 3 sets the rating to 3). The rating should grey out non-selected stars. The text showing the rating (x/x) should update when the stars are selected.
- [ ] There is a submit button. It will submit the review.
- [ ] After the review has been submitted the Show Review section should be shown.
- [ ] There is a checkbox. which is checked by default. If it is checked when the submit button is clicked, the user's name will be saved to the review.

### Show Review Section
After a review has been left, It should be shown to both the buyer and seller. Ideally, it will use the same code as the review in the listing screen.

### Discussion Section
The discussion section shows chat messages associated with this transaction (they are not shown anywhere else). 
- [ ] The functionality should be the same as the sidebar chat, but the layout is wider.

### Resolve Dispute Section
The moderator can view this section when they are resolving a dispute.
- [ ] The total funds in the transaction are shown.
- [ ] An input for the amount paid to the buyer.
- NOTE: this should be a percentage. If possible, show the amount the percentage translates to in real time.
- [ ] An input for the amount paid to the seller.
- NOTE: this should be a percentage. If possible, show the amount the percentage translates to in real time.
- [ ] The amount paid to the moderator (calculated automatically from their fee settings).
- [ ] A text area for a comment.
- [ ] A submit button. Clicking it will show a confirmation tooltip.

### Contract Section
This section shows the JSON for the contract.
- [ ] ideally it will be formatted nicely, and have other functionality like code folding, but only if this can be done easily (such as with a JSON formatting library). 

### Data
- can we add a web sockets call that provides updates to the order state, so the modal can do live updates?

**Comment by morebrownies** [comment]
> There is a progress bar that shows which stage the order is in.
QUESTION: the stages shown don't match how stages work on the server. This will need to be discussed. When would an order be in the "Accepted" state? It appears Accepted and Paid should swap places, and Accepted would only apply to offline orders?

This leads to a UX issue that I brought up with Chris a while back. If i'm purchasing from an offline vendor, the progress bar won't display that I paid for the order until after the vendor has come online and accepted it. 

As a buyer, that's extremly confusing. I already paid, yet the progress bar does not show that I paid. Did my payment go through? Why doesn't the progress bar display paid? Do I need to pay again?

**Comment by morebrownies** [comment]
> There is a copy link next to the order ID. Clicking it will copy the order ID to the clip board, and show the standard "copied" notifier.
QUESTION: should clicking on any part of the order ID also copy it?

Yeah, definitely.

**Comment by morebrownies** [comment]
> QUESTION: how is an order in dispute shown? It appears the bar should show whatever the last stage is, but that data will not be available.

I intentionally left dispute steps out of the progress bar to reduce scope. Notice the progress bar displays that it is between fulfilled and complete. Also, directly below the progress bar I output a "Dispute started" section. I felt this was probably good enough for the time being.   

![screenshot 2017-04-27 11 10 19](https://cloud.githubusercontent.com/assets/13066886/25497636/20ed94e6-2b3a-11e7-92b2-9980fc7fc5b0.png)

**Comment by morebrownies** [comment]
> QUESTION: there doesn't seem to be a pay screen to allow a buyer to fund an order they haven't paid for. We will need that to be designed. Ideally it can reuse the payment module created for the purchase screen (note: we'll need to make sure that piece is easily reusable).

Ah, yeah I missed that. I'll work on designs for it.

**Comment by morebrownies** [comment]
> QUESTION: if an offline order is funded already, does accepting it move it directly to fulfill, or does it start at status 2?

@cpacia will need to weigh in here. I think once the vendor comes online and accepts the order, it would advance to status 2.

**Comment by morebrownies** [comment]
> CANCELED (9): the buyer canceled the offline order before it was accepted.
Actions: none
Data: none
NOTE: when the status is refunded, the progress bar changes to show DESIGN NEEDED.

Is this the same thing as triggering a refund? I believe the only difference it is buyer initiated instead of vendor initiated? 

If that's right, the design would look exactly like below, but we'll probably want to replace "Refunded" with "Canceled" in the progress bar and directly below the progress bar. 

<img width="1025" alt="screenshot 2017-04-27 11 23 58" src="https://cloud.githubusercontent.com/assets/13066886/25498234/0e989370-2b3c-11e7-8757-56b6bf1e50be.png">

This raises another UX concern... If paid is NOT the first step in the progress bar, what would the progress bar look in this scenario? I don't think we could display a progress bar in this scenario because canceled would be the only step that is triggered. 🤔

That seems very strange. Maybe I'm missing something?

**Comment by morebrownies** [comment]
>  COMPLETE (4): The buyer has completed the order.
Actions: none
Data: show the review, if one was left. If no review was left DESIGN NEEDED

Hey @jjeffryes what design is missing here? I believe this should cover it?

<img width="1023" alt="screenshot 2017-04-27 11 33 04" src="https://cloud.githubusercontent.com/assets/13066886/25498570/55e72dee-2b3d-11e7-94c7-0c2641542d78.png">

**Comment by jjeffryes** [comment]
>This leads to a UX issue that I brought up with Chris a while back. If i'm purchasing from an offline vendor, the progress bar won't display that I paid for the order until after the vendor has come online and accepted it.

>As a buyer, that's extremly confusing. I already paid, yet the progress bar does not show that I paid. Did my payment go through? Why doesn't the progress bar display paid? Do I need to pay again?

I agree. We'd have to show some kind of state on the progress bar that makes it clear things are waiting for the vendor to come on line, but it looks to me like there's no way to tell if the buyer has paid or not.

> I intentionally left dispute steps out of the progress bar to reduce scope. Notice the progress bar displays that it is between fulfilled and complete. Also, directly below the progress bar I output a "Dispute started" section. I felt this was probably good enough for the time being.

The issue is you can start a dispute after the Paid or Fulfilled step. Once the dispute is started, the only data we have is that the status is Disputed, there's no way to tell what step things were in before that, so the progress bar would be blank, or it would need a "Disputed" state.

That also raises the question of whether we could show the step by step data below the progress bar when a transaction is disputed. Maybe we could extrapolate which steps had been completed before the dispute by looking at what other data is available? (ie: if shipping data is available, it must have been fulfilled). 

>If that's right, the design would look exactly like below, but we'll probably want to replace "Refunded" with "Canceled" in the progress bar and directly below the progress bar.

That sounds right to me.

> This raises another UX concern... If paid is NOT the first step in the progress bar, what would the progress bar look in this scenario? I don't think we could display a progress bar in this scenario because canceled would be the only step that is triggered. 🤔

I think the progress bar would have to have steps like this:

Step 1: Pending (this covers PENDING and CONFIRMED if the order was offline, and Unpaid if the order was online or offline but isn't paid for yet)
Step 2: Paid (FUNDED)
Step 3: Fulfilled (FULFILLED)
Step 4: Complete (COMPLETE)

Then if an order is cancelled, rejected, or refunded, the progress bar only has 2 steps, Pending and whatever the final step is (cancelled etc.).

> Hey @jjeffryes what design is missing here? I believe this should cover it?

If the order was completed, but no review was left, what is displayed below the words "Order Complete"?

Or is a review always left? It seems like the API always expects a review, so if that's automatic there's no issue here.

**Comment by morebrownies** [comment]
> RESOLVED (7)
Actions (Buyer): Complete (the buyer can leave a review at this point, the same as the normal complete action).
Data: DESIGN NEEDED

There are a few perspective to consider at this step.

**Vendor perspective** (does not leave order feedback, but has ability to accept payout)
![screenshot 2017-04-27 11 47 48](https://cloud.githubusercontent.com/assets/13066886/25499134/5b47df02-2b3f-11e7-91da-a37dc6ca31b0.png)

**Buyer perspective** (accepts payout and leaves feedback at the same time)
![screenshot 2017-04-27 11 50 02](https://cloud.githubusercontent.com/assets/13066886/25499268/b2827160-2b3f-11e7-92af-5f7291ce6405.png)

**Comment by morebrownies** [comment]
>  REJECTED (10): the seller rejected the offline order.
Actions: none
Data: none
NOTE: when the status is refunded, the progress bar changes to show DESIGN NEEDED.

I believe this design will work here:

<img width="1025" alt="screenshot 2017-04-27 11 23 58" src="https://cloud.githubusercontent.com/assets/13066886/25499493/83b82e1e-2b40-11e7-8311-c3b292097b0f.png">

**Comment by morebrownies** [comment]
> I agree. We'd have to show some kind of state on the progress bar that makes it clear things are waiting for the vendor to come on line, but it looks to me like there's no way to tell if the buyer has paid or not.

Well, that raised another potential issue. It sounds like orders I paid for where the vendor happens to be offline will display within the "Purchasing" filter instead of "Ready to process" filter. Is that right? If so, that's going to be very difficult to explain to users.

![screenshot 2017-04-27 12 00 40](https://cloud.githubusercontent.com/assets/13066886/25499716/3521ecd0-2b41-11e7-90b7-bce34418c0ed.png)

**Comment by morebrownies** [comment]
> The issue is you can start a dispute after the Paid or Fulfilled step. Once the dispute is started, the only data we have is that the status is Disputed, there's no way to tell what step things were in before that, so the progress bar would be blank, or it would need a "Disputed" state.

That also raises the question of whether we could show the step by step data below the progress bar when a transaction is disputed. Maybe we could extrapolate which steps had been completed before the dispute by looking at what other data is available? (ie: if shipping data is available, it must have been fulfilled).

Interesting. Yeah that doesn't sound ideal. Hopefully there's a work around, otherwise that's going to be a pretty strange experience.

**Comment by morebrownies** [comment]
> I think the progress bar would have to have steps like this:

> Step 1: Pending (this covers PENDING and CONFIRMED if the order was offline, and Unpaid if the order was online or offline but isn't paid for yet)
Step 2: Paid (FUNDED)
Step 3: Fulfilled (FULFILLED)
Step 4: Complete (COMPLETE)

> Then if an order is cancelled, rejected, or refunded, the progress bar only has 2 steps, Pending and whatever the final step is (cancelled etc.).

Ok let's break this down further. Progress bar for the following scenarios:

**1. Unpaid order for an online vendor** (I hit buy now, but never funded the order)
✔️ Pending > ✔️ Accepted > ✖️ Paid > ✖️ Fulfilled > ✖️ Complete

**2. Unpaid order for an offline vendor** (I hit buy now, but never funded the order)
✔️ Pending > ✖️ Accepted > ✖️ Paid > ✖️ Fulfilled > ✖️ Complete

**3. Paid order for an offline vendor** (I hit buy now and funded the order)
✔️ Pending > ✖️ Accepted > ✖️ Paid > ✖️ Fulfilled > ✖️ Complete

_I  paid for this, but the progress bar will not reflect that, so yeah a unpaid order is identical to a paid order with an offline vendor. This leads back to my UX concerns_

**4. Paid for an offline order that I canceled** (I hit buy, funded the order and then cancel)
✔️ Pending > ✔️  Canceled 

**5. Unpaid order that I canceled** (I hit buy and then canceled the order)
✔️ Pending > ✔️  Canceled 

_The progress bar would be identical to the scenario above with a payment._

**6. Paid for an order that was refunded by the vendor** (I hit buy now, funded the order and then refunded)
✔️ Pending > ✔️ Accepted > ✔️ Paid > ✔️  Refunded

There's definitely some weirdness in scenario 3, but the rest are probably fine.

**Comment by morebrownies** [comment]
I just realized I'm missing designs for what Opening a dispute looks like too. I'll add that to my todo list too.

**Comment by jjeffryes** [comment]
For the progress bar, I think we could leave the Accepted step off, since the only time it would matter is if the order was offline and not paid for yet (if it's paid for, it goes directly to Paid when the seller accepts it). In that case I think showing it as pending and not yet Paid would be enough. 

The buyer would have an action button telling them the next step is to fund the order in that situation.

**Comment by rmisio** [comment]
This has been completed.
