### ISSUE TITLE
Add "No returns" as a suggestion for "Return policy"

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#47]
One of the observed trends from the Duo Search data is that free-text fields lead to "messy" situations, despite the bulk of the cases being "organised". Return policy is a good example, presented below.

I've collected all the different return policies that Duo Search has scraped since the beginning. It's available [here](http://pastebin.com/uPS5B91a) for your perusal. There are 1813 distinct return policies, but when you look into them there are literally hundreds of duplicates for "No return" (small sample shown below):

```
    "No Returns.",
    "no refunds.",
    "no returns.",
    "All sales final.",
    "No returns.",
    "There is no way back!",
    "There is no way back...!",
    "No Returns on digital items.",
    "Returns are a no-go.",
    "No returns. No tradeback. Nothing.",
    "no refunds, will resend once if not recieved",
    "no returns, if u dont recieve will resend once",
    "no returns, if you don't recieve will resend once.",
    "no returns, if you don't recieve, will resend once.",
    "No Returns",
    "No returns",
    "no refunds",
    "No returms",
    "No return",
    "No refunds on digital items",
    "No refund",
    "No warranty and no returns.",
    "No returns or refunds",
    "Returns accpeted.",
    "No returns on food items.",
    "No return policy",
    "No Refund",
    "NA",
    "N/A",
    "Non Refundable",
    "No Return",
```

In an effort to make free text fields more consistent across OpenBazaar stores (and more machine readable) having pre-set options for the return policy would help. My suggestion would be to a have few preset options, plus a "Custom" field for those that require free text. For example:
- "No returns"
- "Full refund available"
- "Full refund available, minus shipping costs"
- "Custom..."

This hybrid strategy could work for many fields, including `condition`, `weight`, `refundPolicy` and `category`.

**Comment by rmisio** [comment]
The v2 designs call for a free form field:

![image](https://cloud.githubusercontent.com/assets/794517/18257305/2306d9c6-7376-11e6-8fab-33a2adceb474.png)

@morebrownies Do you have any thoughts on this issue? Would it make sense to have a drop down with the most common options and then 'Other' would enable the free form text field?

**Comment by morebrownies** [comment]
I really like this suggestion. Thank you @JustinDrake for digging up the data.

@rmisio I can get you a design on this when I get a chance, but what you described sounds like a good solution. Add a drop down with the most common options and display a textarea when 'Other' is selected. 

Don't forget we need to translate these choices into all languages as well. If the translations do not exist in a specific language, we may have to fallback to the textarea?

**Comment by rmisio** [comment]
> If the translations do not exist in a specific language, we may have to fallback to the textarea?

hmm.. In every other part of the app, if text is not translated, it appears as english. (which is a really good impetus for a translator to get on top of that)

I'm not sure I'd want to open up the can of worms of alternate behavior if translations are not available, when we don't do that anywhere else.

What do you think @jjeffryes ?

**Comment by morebrownies** [comment]
That actually should be fine.  It's not the best experience, but it should hopefully guide people to fill in the translations.

**Comment by JustinDrake** [comment]
@morebrownies: I'm glad you like the suggestion. I think a similar dropdown also works brilliantly for "Condition":

- New
- Used, in good condition
- Used, in bad condition
- Refurbished
- Other

**Comment by rmisio** [comment]
That's already in place:

![image](https://cloud.githubusercontent.com/assets/794517/18290693/6192f5f8-7439-11e6-80f6-f7b71db44e5a.png)

**Comment by JustinDrake** [comment]
@rmisio I don't see "Other" in that screenshot. My suggestion is to add a free text "Other" for Condition.

**Comment by rmisio** [comment]
out of curiosity, what is a condition that would not be encompassed by the non-other choices available?

**Comment by JustinDrake** [comment]
I wouldn't underestimate the creativity/diversity of OpenBazaar. Off the top of my head:

* New - With original unsealed packaging
* New - With a factory defect
* New - Non-original packaging
* Refurbished - Excellent
* Refurbished - Good
* Frozen (referring to food)
* Freshly baked on demand (referring to pastries)
* Matured 10 years in oak barrels (referring to whisky)
* Cut on demand (referring to hair for a wig)

**Comment by jjeffryes** [comment]
Just chiming in that showing English for missing translations is fine IMHO.

Having a limited number of pre-defined options for the returns policy sounds good too. Between 3 and 5 seems right.

I think the current drop down options on condition are good, if there are specific details they can go in the description.

**Comment by hoffmabc** [comment]
I think we should opt for simplicity for now. Description should suffice. But we'll keep the discussion open @JustinDrake

**Comment by jjeffryes** [comment]
This issue hasn't seen activity for over a year, I think it's safe to conclude we're probably not going to be addressing it.
