### ISSUE TITLE
Variant surcharges do not seem to be added on listing detail / checkout

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#508]
![screenshot 2017-06-02 17 16 32](https://cloud.githubusercontent.com/assets/13066886/26748891/63bb9c5c-47b7-11e7-9722-df506f85eec1.png)

I set Size: Medium to cost **$40**

![screenshot 2017-06-02 17 16 56](https://cloud.githubusercontent.com/assets/13066886/26748908/7ffab038-47b7-11e7-92af-7230ea2165c3.png)

When I select the option on the listing detail screen, the price stays set to **$20**

![screenshot 2017-06-02 17 17 03](https://cloud.githubusercontent.com/assets/13066886/26748912/8ac856be-47b7-11e7-870f-446a2c5b0ff6.png)

I then add it to my cart and it is still priced at **$20**

**Comment by jjeffryes** [comment]
The variant price is added to the receipt on the right, like shipping is. It wasn't called out in the design, so I assumed that's how it would work. 

I can change it to add to the unit price at the top instead.

**Comment by jjeffryes** [comment]
This was done.
