### ISSUE TITLE
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (57)

### ISSUE THREAD

**Issue by Giszmo** [OpenBazaar/openbazaar-desktop#524]
Brief Description: 

Operating System (OS and version): 

    $ uname -a
    Linux codex 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

OpenBazaar version (shown on `About OpenBazaar` page in menu): 

    $ git log -n 1
    commit 3ee2d54a898c3c2cdfd4f0f9cbbb2043505ae5c4
    Merge: a6a85b8 2b63a5f
    Author: Josh Jeffryes <jjeffryes@gmail.com>
    Date:   Wed Jun 21 16:25:02 2017 -0400
    
        Merge pull request #502 from jjeffryes/purchasing-payment
        
        Purchasing payment

Hardware: 

HP Pavilion Gaming

Reproducible: Always

Steps to reproduce:

1.  git clone https://github.com/OpenBazaar/openbazaar-desktop
12701.  cd openbazaar-desktop/
12709.  curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
12710.  sudo apt-get install -y nodejs
12712.  npm install
12713.  npm start

Observed Behavior:

		$ npm start

		> openbazaar-desktop@2.0.4 start /home/leo/openbazaar-desktop
		> cross-env NODE_ENV=development npm-run-all sass:build process-index --parallel sass:watch index:watch browsersync start-app

		> openbazaar-desktop@2.0.4 sass:build /home/leo/openbazaar-desktop
		> node-sass --source-map true --include-path styles styles/main.scss .tmp/styles/main.css

		/home/leo/openbazaar-desktop/node_modules/node-sass/lib/binding.js:13
		      throw new Error(errors.unsupportedEnvironment());
		      ^

		Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (57)
		For more information on which environments are supported please see:
		https://github.com/sass/node-sass/releases/tag/v3.13.1
		    at module.exports (/home/leo/openbazaar-desktop/node_modules/node-sass/lib/binding.js:13:13)
		    at Object.<anonymous> (/home/leo/openbazaar-desktop/node_modules/node-sass/lib/index.js:14:35)
		    at Module._compile (module.js:569:30)
		    at Object.Module._extensions..js (module.js:580:10)
		    at Module.load (module.js:503:32)
		    at tryModuleLoad (module.js:466:12)
		    at Function.Module._load (module.js:458:3)
		    at Module.require (module.js:513:17)
		    at require (internal/module.js:11:18)
		    at Object.<anonymous> (/home/leo/openbazaar-desktop/node_modules/node-sass/bin/node-sass:11:10)
		npm ERR! code ELIFECYCLE
		npm ERR! errno 1
		npm ERR! openbazaar-desktop@2.0.4 sass:build: `node-sass --source-map true --include-path styles styles/main.scss .tmp/styles/main.css`
		npm ERR! Exit status 1
		npm ERR! 
		npm ERR! Failed at the openbazaar-desktop@2.0.4 sass:build script.
		npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

		npm ERR! A complete log of this run can be found in:
		npm ERR!     /home/leo/.npm/_logs/2017-06-24T18_48_44_116Z-debug.log
		ERROR: "sass:build" exited with 1.
		npm ERR! code ELIFECYCLE
		npm ERR! errno 1
		npm ERR! openbazaar-desktop@2.0.4 start: `cross-env NODE_ENV=development npm-run-all sass:build process-index --parallel sass:watch index:watch browsersync start-app`
		npm ERR! Exit status 1
		npm ERR! 
		npm ERR! Failed at the openbazaar-desktop@2.0.4 start script.
		npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

		npm ERR! A complete log of this run can be found in:
		npm ERR!     /home/leo/.npm/_logs/2017-06-24T18_48_44_138Z-debug.log

Expected Behavior:

to see openbazaar staring

**Comment by hoffmabc** [comment]
Have you tried 

npm rebuild node-sass

**Comment by Giszmo** [comment]
npm rebuild node-sass did have some effect but for now I guess I give up and use the precompiled build :/

	$ npm start

	> openbazaar-desktop@2.0.4 start /home/leo/openbazaar-desktop
	> cross-env NODE_ENV=development npm-run-all sass:build process-index --parallel sass:watch index:watch browsersync start-app


	> openbazaar-desktop@2.0.4 sass:build /home/leo/openbazaar-desktop
	> node-sass --source-map true --include-path styles styles/main.scss .tmp/styles/main.css

	Rendering Complete, saving .css file...
	Wrote CSS to /home/leo/openbazaar-desktop/.tmp/styles/main.css
	Wrote Source Map to /home/leo/openbazaar-desktop/.tmp/styles/main.css.map

	> openbazaar-desktop@2.0.4 process-index /home/leo/openbazaar-desktop
	> cross-env NODE_ENV=development babel-node ./bin/processIndex.js


	> openbazaar-desktop@2.0.4 start-app /home/leo/openbazaar-desktop
	> cross-env NODE_ENV=development electron .


	> openbazaar-desktop@2.0.4 index:watch /home/leo/openbazaar-desktop
	> nodemon -w index.html -x "npm run process-index"


	> openbazaar-desktop@2.0.4 browsersync /home/leo/openbazaar-desktop
	> browser-sync start --no-ui -f 'js, .tmp/**/*.css, .tmp/**/*.html, !.tmp/test/**/*'


	> openbazaar-desktop@2.0.4 sass:watch /home/leo/openbazaar-desktop
	> nodemon -e scss -x "npm run sass:build"

	/home/leo/openbazaar-desktop/node_modules/electron/index.js:9
	  throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
	  ^

	Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
	    at Object.<anonymous> (/home/leo/openbazaar-desktop/node_modules/electron/index.js:9:9)
	    at Module._compile (module.js:569:30)
	    at Object.Module._extensions..js (module.js:580:10)
	    at Module.load (module.js:503:32)
	    at tryModuleLoad (module.js:466:12)
	    at Function.Module._load (module.js:458:3)
	    at Module.require (module.js:513:17)
	    at require (internal/module.js:11:18)
	    at Object.<anonymous> (/home/leo/openbazaar-desktop/node_modules/electron/cli.js:3:16)
	    at Module._compile (module.js:569:30)
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! openbazaar-desktop@2.0.4 start-app: `cross-env NODE_ENV=development electron .`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the openbazaar-desktop@2.0.4 start-app script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /home/leo/.npm/_logs/2017-06-24T20_43_39_316Z-debug.log
	ERROR: "start-app" exited with 1.
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! openbazaar-desktop@2.0.4 start: `cross-env NODE_ENV=development npm-run-all sass:build process-index --parallel sass:watch index:watch browsersync start-app`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the openbazaar-desktop@2.0.4 start script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /home/leo/.npm/_logs/2017-06-24T20_43_39_384Z-debug.log
	$ rm -rf node_modules/electron/
	$ npm install

	> electron@1.6.11 postinstall /home/leo/openbazaar-desktop/node_modules/electron
	> node install.js

	module.js:487
	    throw err;
	    ^

	Error: Cannot find module 'extract-zip'
	    at Function.Module._resolveFilename (module.js:485:15)
	    at Function.Module._load (module.js:437:25)
	    at Module.require (module.js:513:17)
	    at require (internal/module.js:11:18)
	    at Object.<anonymous> (/home/leo/openbazaar-desktop/node_modules/electron/install.js:9:15)
	    at Module._compile (module.js:569:30)
	    at Object.Module._extensions..js (module.js:580:10)
	    at Module.load (module.js:503:32)
	    at tryModuleLoad (module.js:466:12)
	    at Function.Module._load (module.js:458:3)
	npm WARN The package babel-preset-es2015 is included as both a dev and production dependency.
	npm WARN The package babel-preset-stage-1 is included as both a dev and production dependency.
	npm WARN The package babel-register is included as both a dev and production dependency.

	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! electron@1.6.11 postinstall: `node install.js`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the electron@1.6.11 postinstall script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /home/leo/.npm/_logs/2017-06-24T20_44_08_342Z-debug.log
	$
