### ISSUE TITLE
Default the currency in the Settings > Moderation tab to use the user's local currency

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-desktop#525]
Currently, it's defaulting to BTC even though my local currency is USD.

![image](https://user-images.githubusercontent.com/794517/27552534-a58faecc-5a5c-11e7-8353-d8eaf76e349e.png)

**Comment by jjeffryes** [comment]
When you say local currency, how is that determined?

**Comment by rmisio** [comment]
From the user's settings.

**Comment by jjeffryes** [comment]
Ok. I though you were saying auto detect it from the user's computer.
