### ISSUE TITLE
Order details avatar spinning

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-desktop#526]
![image](https://user-images.githubusercontent.com/4504708/27556495-cef8855a-5a83-11e7-8039-cd65430b1225.png)

My personal preference would be to show a default avatar in the top left while the profile loads rather than a spinner. The spinner is pretty distracting and looks out of place. 

Also, is it using the `usecache` flag for the profile?

**Comment by rmisio** [comment]
> Also, is it using the usecache flag for the profile?

It is absolutely is. This is related to something Josh, Sam and I have all been observing. I don't think the caching is working correctly on the server, because profiles I know I've fetched still keep taking a really long time to fetch.
