### ISSUE TITLE
[Request] Add external links out to getting Bitcoin from businesses

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#532]
It would be interesting to have links out to Coinbase, Unocoin, localbitcoins, wherever people might could go to get Bitcoin directly from the wallet. Similar to what is in the mobile application.

Maybe between the transactions panel and the wallet? Just an idea.

![image](https://user-images.githubusercontent.com/45482/27610980-7416cad0-5b5e-11e7-86c4-7271bc9ecada.png)

**Comment by hoffmabc** [comment]
I was going to explore this further but I think in lieu of this we can just leave the current link to get bitcoin as the option.

**Comment by jjeffryes** [comment]
We should leave this open, the current link doesn't go anywhere but the home page of openbazaar.

At minimum it should link to a page that has information about getting bitcoin.

**Comment by jjeffryes** [comment]
The need bitcoin link was added, and goes to a page that has options for getting bitcoin.
