### ISSUE TITLE
The Pay button in the Purchase flow is not advancing to the next state

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-desktop#533]
When you purchase an item, the PAY button does not change state:

![image](https://user-images.githubusercontent.com/794517/27649607-1941e67e-5be7-11e7-942a-d6cb866a452a.png)

Clicking it again will get you this fun scenario:

![image](https://user-images.githubusercontent.com/794517/27649624-26138cb8-5be7-11e7-9ec0-b8b4d5803957.png)

**Comment by jjeffryes** [comment]
@rmisio I can't reproduce this issue. Can you send a link to a listing that causes it?

**Comment by rmisio** [comment]
I can't reproduce it either. Maybe I wasn't on the latest master.

Now, once the purchase goes through, the button becomes 'Pending' and when you click it, it changes to 'Close' and then works as a close button. Is that correct? (it seems kind of odd)

**Comment by jjeffryes** [comment]
I think this bug was in your order details PR, I left a review about it just now.

The button should say pending, but it shouldn't be clickable, I'll fix that in my patch PR I'm working on.

**Comment by rmisio** [comment]
this was fixed.
