### ISSUE TITLE
Add Resync Button

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#538]
## User Story
As a user, if I am a vendor I want an indicator that I may need to resync my wallet when necessary, and a way to easily do so.

### Transactions
- [ ] In the transactions screen, in the sales tab, if the last transaction is more than 24 hours old and is still unfunded, show a message with a link that will open the Settings on the Advanced Tab.
- [ ] The message: "You may need to resync your wallet to receive payments for one or more unfunded orders. [link]Open Settings and click the Resync button.[/link]"

### Settings
- [x] In Settings/Advanced, there should be a Resync button.
- [x] Clicking the button will call (POST) the /wallet/resyncblockchain API with no parameters.
- [ ] Clicking the button will save a timestamp in local storage.
- [ ] If the saved timestamp is less than an hour old, the Resync button should be disabled.
- [x] The Resync button should have text next to it "Resyncing the wallet can take several minutes."
- [ ] After it is clicked, the Resync button should have text near it "Check your transactions for updates in a few minutes. You can only resync once an hour."

**Comment by rmisio** [comment]
AFAIK, this was done.

**Comment by jjeffryes** [comment]
The transactions part of this wasn't completed, I think we should leave it open to track that, unless we don't plan on doing that any more?

**Comment by jjeffryes** [comment]
Unless that part was done, and I just don't remember it. :)

**Comment by rmisio** [comment]
No, that hasn't been done.

**Comment by rmisio** [comment]
It also looks like the part about limiting the ability to press the resync button to once per hour isn't done either.

**Comment by morebrownies** [comment]
FYI: If the common outcome (majority of the time) is nothing updates after `Resync` is clicked, the user may lose trust in clicking the button and possibly start dismissing/ignoring it on future occasions. This may lead us back to the same issues with orders not getting updated.

Ideally, orders would update automatically, without user action required. Something we can work towards in the future.
