### ISSUE TITLE
Settings Store tab does not properly add two mods to the UI

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-desktop#539]
Start with 3 fresh nodes (oh my!)

- set up node A as a mod
- set up node B as a mod
- in the Settings > Store tab of Node C, use the Find bar to locate both nodes from above and check each of them.

![image](https://user-images.githubusercontent.com/794517/27665046-d0935e10-5c1f-11e7-828a-d5160388d74a.png)

- click Save

In the UI, only one of the mods are added to the Selected box:

![image](https://user-images.githubusercontent.com/794517/27665069-ea3482ea-5c1f-11e7-8228-0e28454faf55.png)

- refresh the app and go back to the Settings > Store tab

Both mods were indeed saved, but the UI had only showed 1.

![image](https://user-images.githubusercontent.com/794517/27665086-02a7a5a0-5c20-11e7-9436-46a3f7ac9840.png)

**Comment by jjeffryes** [comment]
This was fixed during one of the moderators refactors.
