### ISSUE TITLE
Apply the Fee Type from Settings in Purchase

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#540]
Settings/Advanced has a fee type which is saved to local storage, that type needs to be applied to the purchase.

Change the language to reflect the default, which is high, instead of suggesting average.

Consider showing the current estimated fee for each if possible.

**Comment by rmisio** [comment]
> Settings/Advanced has a fee type which is saved to local storage, that type needs to be applied to the purchase.

If we update the spend() function in the wallet/Spend.js model as follows, then it would use the local storage fee type for any wallet spends (i.e. both from the Wallet and from Purchasing):

```
  const attrs = {
    currency: app && app.settings && app.settings.get('localCurrency') || 'BTC',
    feeLevel: app && app.localSettings && app.localSettings.get('defaultTransactionFee') || 'high', 
    memo: '', // this could be removed
    ...fields,
  };
```
