### ISSUE TITLE
Hidden stores still visible

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-desktop#546]
![image](https://user-images.githubusercontent.com/4504708/27765329-5c46dcbc-5e7c-11e7-8632-6626f8be8874.png)

**Comment by jjeffryes** [comment]
We haven't worked on blocking hidden stores yet. I don't think that's on the roadmap for launch, unless we want to do a very simple version of it.

**Comment by jjeffryes** [comment]
@morebrownies do we have a design for what happens if you try to look at a hidden store?

**Comment by cpacia** [comment]
Should probably just take you to the home tab

**Comment by hoffmabc** [comment]
Yeah whatever you do if you enter a non existent store I would think.

**Comment by jjeffryes** [comment]
Now that I think of it, we can have it use the same code for the vendor=false stores, and give you a page not found message.

**Comment by morebrownies** [comment]
So there are probably two ways we could handle this scenario:

1) We can redirect the user to the home tab, but we should inform the user why they're being redirected. Blindly being redirected without a reason could be confusing. _Why am I on the home tab? I keep trying to visit the store tab._

2) We could display exactly what is in the screenshot below, but without the listings, category list and number of listings found. The text of the message would need to change a bit to: "🔒 This store is currently inactive and hidden from public view."

![image](https://user-images.githubusercontent.com/4504708/27765329-5c46dcbc-5e7c-11e7-8632-6626f8be8874.png)

I'm leaning towards option 2 as it is close to what we output to the store owner when their store is inactive.

**Comment by jjeffryes** [comment]
Hold on, is this just a miscommunication?

@cpacia if you are looking at your own store, and Vendor is set to false, everything is working as intended.

If you are looking at someone else's store, then something is wrong, but I can't reproduce it.

There is no "hidden" flag for stores as far as I know. There was a hidden field for listings in v1, but we haven't implemented that in v2.

**Comment by jjeffryes** [comment]
Ok, I can reproduce the bug now. Something is causing the view that should only be for the user to appear to other nodes.
