### ISSUE TITLE
Coupon code shouldn't be returned in "listing" call

### ISSUE THREAD

**Issue by mariodian** [OpenBazaar/openbazaar-desktop#547]
Nowadays validity of coupon codes is checked against local data retrieved by /ob/listing API call. Anyone with the dev console open can go through the returned JSON and find coupons in `listing.coupons`.

This obviously allows anyone to purchase items with a discount even without getting the coupon code from the vendor.

Instead, the validity of a coupon code should be checked on the server side. If the coupon code is valid, Coupon model could be updated with the coupon itself (or its hash) and then later used in the final step as a last validity check before the buyer is requested to pay.

**Comment by jjeffryes** [comment]
The listing api returns the hashes of the coupon, but the purchase api requires the unhashed coupon codes, which are checked on the server like you suggest.

Knowing the hash only lets you confirm if the entered coupon code matches the hash after you hash it, which makes an extra trip to the server unnecessary. It doesn't tell the user what the correct coupon code is.

**Comment by mariodian** [comment]
Thanks for clearing that up. I couldn't find any listing with coupon codes so I was just (wrongly) assuming the code is plain text as I didn't see any call that was checking against the server.

Closing.

**Comment by jjeffryes** [comment]
What happens is when the user enters the coupon code the client hashes it and checks it against the hashes in the listing, so the user can be told if it's a valid code before sending it to the purchase API. 

A different implementation could skip that, and just send the entered coupon code, which would return an error from the purchase API if it wasn't a valid code.

**Comment by rmisio** [comment]
Another thing of note is that I think when you are on your own node and calling /ob/listing for your own listing, then it will return the plain text codes. If you do the same for another node's listing, it will only return the hashes.
