### ISSUE TITLE
Notes on Installation of OpenBazaar Clientv2 (openbazaar-desktop) on Ubuntu 16.10 with Brief Test Results and Comments

### ISSUE THREAD

**Issue by ABISprotocol** [OpenBazaar/openbazaar-desktop#549]
**Notes on installation of OpenBazaar Clientv2 (openbazaar-desktop) on Ubuntu 16.10.**  
(Note, for libuuid currently is 2.28.2-1ubuntu1.1, not 1.2 yet, but still, the OS is good.) 

Went through steps as recommended at https://github.com/OpenBazaar/openbazaar-desktop

After the npm-install, got errors as follows:

_npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
npm WARN prefer global node-gyp@3.6.2 should be installed with -g_

It then performed install and threw another few errors:

_npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2_

Ignoring this, proceeded to npm start

Apparent error and began to eat lots memory as it proceeded to start up.  Memory hogging seemed to be issue on startup at least.  Hogging diminished somewhat after full launch.

Errors thrown (in terminal just prior to startup):

_Gtk-Message: Failed to load module "overlay-scrollbar"
[BS] Copy the following snippet into your website, just before the closing </body> tag
<script id="__bs_script__">//<![CDATA[
    document.write("<script async src='http://HOST:3000/browser-sync/browser-sync-client.js?v=2.18.12'><\/script>".replace("HOST", location.hostname));
//]]></script>_

The thing then launched Developer tools then launched OB 2.0.  

OK, **I am trying to look at this as would someone who had never signed up for something like this experience before.**  Assuming the installation went well, all of a sudden they are hit with trying to figure out what to put in for the IP (it’s not intuitive and the instructions are unclear).   If you are a first-time user and you figure it out (e.g. /ip4/xx.xxx.xx.xxx/tcp/4002), then you have to figure out what the user name and password are.  And a reference to a 2013 document with obscure references to how to create certificates probably is not incredibly attractive.  This deters ordinary humans from wanting to go any further.

An accidental “Ctrl-C” as an example from a user attempting to copy a snippet to make something work (e.g. _<script id="__bs_script__">//<![CDATA[
    document.write("<script async src='http://HOST:3000/browser-sync/browser-sync-client.js?v=2.18.12'><\/script>".replace("HOST", location.hostname));
//]]></script>_ as suggested by Gtk-Message)  causes OB 2.0 to quit from terminal.  This is user error, but it suggests how it is not yet easy to get the application off the ground for various users.

The objective here needs to be to make it easier for the user who makes it through the installation process, to actually be able to connect and run the application without incident.

**TESTING SPECIFIC**:  (for openbazaar-desktop@2.0.4 test)

npm run test (from openbazaar-desktop folder)

The following result:  (redacted somewhat, not enough time to provide more testing and comments as I would have preferred  at least not at the moment..)

Summary:  Various fails in coupon, image, item, listing, metadata, service, shipping, fee, fixed fee, and moderator.  All have various fails on testing. Results below

_> mocha --compilers js:babel-core/register --recursive_

  _the Follows collection_
    ✓ uses a local url if given the user guid and the type followers
    ✓ uses a local url if given no guid and the type followers
    ✓ uses a ipns url if given a non-user guid and the type followers
    ✓ turns a plain guid into a model
    ✓ turns 3 follow objects into 3 models

  _the Listings collection_
    has a categories getter
      ✓ that returns a combined and sorted list of categories from all the listings in the collection
      ✓ that returns a list of categories without duplicates

  _the Results collection_
    ✓ sets a total parameter based on the parsed results
    ✓ sets a morePages parameter based on the parsed results
    ✓ will create 3 listings if 3 listings are in the results
    ✓ will use the listingCard model for listing results, and the profile model for profile results

  _the country data module_
    ✓ returns a country by dataName

  _the language data module_
    ✓ returns a language by code

  _the regions data module_
    ✓ has regions which comprise of only countries that are represented in the countries module

  _the base model_
    manages nested attributes
      ✓ by setting attributes on the nested instances when they are set on the parent
      ✓ by creating a new instance for any nested attributes the first time they are set via the parent
      ✓ by ensuring a call to toJSON() on the parent embeds and returns the results of toJSON() of each of the children

  _the Coupon model_
    ✓ fails validation if the title exceeds the maximum length
    ✓ fails validation if a discount code is not provided
    ✓ fails validation if the discount code is not unique
    ✓ fails validation if you don't provide either a price or percentage discount
    ✓ fails validation if you provide both a price or percentage discount
    ✓ fails validation if you provide the price discount as something other than a number
    ✓ fails validation if you provide the percentage discount as something other than a number
    ✓ fails validation if you provide a price discount less than or equal to zero
    ✓ fails validation if you provide a percent discount less than or equal to zero
    ✓ fails validation if you provide a percent discount greater than 100

  _the Image model_
    ✓ fails validation if a filename exceeds the max length

  _the Item model_
    ✓ fails validation if a title is not provided
    ✓ fails validation if the condition is not one of the available types
    ✓ fails validation if the description is not provided
    ✓ fails validation if the description is not provided as a string
    ✓ fails validation if the number of tags exceeds the maximum allowable amount

  _the Listing model_
    ✓ throws an error if you attempt to fetcha listing without a guid set. (801ms)
    ✓ throws an error if you attempt to fetch without a slug set on the nested listing model
    ✓ does not throw an error if you attempt to fetch with a guid and slug both set (51ms)
    ✓ changes a hash in the response to a hash in parse
    ✓ converts fiat prices from integer to decimal format in parse
    ✓ converts BTC prices from Satoshi to BTC format in parse
    ✓ fails validation if the refund policy is not provided as a string
    ✓ fails validation if the refund policy exceeds the maximum length
    ✓ fails validation if the terms and conditions are not provided as a string
    ✓ fails validation if the terms and conditions exceed the maximum length
    ✓ fails validation if, for a physical good, at least one shipping options is not provided
    ✓ fails validation if the coupon count exceeds the maximum allowable amount
    ✓ fails validation if a coupon price exceeds the listing price

  _the Metadata model_
    ✓ fails validation if the contract type is not one of the available types
    ✓ fails validation if a date in the past is provided
    ✓ fails validation if a date beyond 2038 is provided
    ✓ fails validation if a pricing currency is not one of the available ones

  _the Service model_
    ✓ fails validation if a name is not provided as a string
    ✓ fails validation if an estimated delivery is not provided as a string
    ✓ fails validation if a price is not provided as a number

  _the Shipping Option model_
    ✓ fails validation if the type is not one of the available types
    ✓ fails validation if a name is not provided as a string
    ✓ fails validation if at least one region is not provided
    ✓ fails validation if at least one service is not provided when the type is not "LOCAL_PICKUP"

  _the Fee model_
    ✓ fails validation if the fee type is invalid
    ✓ fails validation if the fee type is not set
    ✓ fails validation if the percentage is not set
    ✓ fails validation if the feeType is percentage and the percentage is not a number
    ✓ fails validation if the feeType is fixed plus percentage and the percentage is not a number
    ✓ fails validation if the feeType is percentage and the percentage is less than zero
    ✓ fails validation if the feeType is percentage and the percentage is over 100
    ✓ fails validation if the feeType is percentage and the percentage has more than 2 decimal places

  _the Fixed Fee model_
    ✓ fails validation if the amount does not exist
    ✓ fails validation if the amount is not a number
    ✓ fails validation if the currency code does not exist
    ✓ fails validation if the currency code is not a string
    ✓ fails validation if the currency code is not a known code

  _the Moderator model_
    ✓ fails validation if no description was set
    ✓ fails validation if the description exceeds the maximum length
    ✓ fails validation if no terms and conditions were set
    ✓ fails validation if the terms amd conditions exceed the maximum length
    ✓ fails validation if the language array is empty

  _the Shipping Address model_
    ✓ defaults name to an empty string
    ✓ defaults company to an empty string
    ✓ defaults addressLineOne to an empty string
    ✓ defaults addressLineTwo to an empty string
    ✓ defaults state to an empty string
    ✓ defaults postalCode to an empty string
    ✓ defaults addressNotes to an empty string
    ✓ fails validation if a name is not provided
    ✓ fails validation if a country is not provided

  _the currency utility module_
    ✓ correctly converts a fiat amount from an integer to decimal
    ✓ correctly converts a BTC price from an integer to a decimal
    ✓ correctly converts a fiat amount from a decimal to an integer
    ✓ correctly converts a fiat amount from a decimal to an integer rounding to the hundreds place.
    ✓ correctly converts a BTC price from a decimal to an integer
    ✓ correctly formats a non-BTC price to 2 decimal place
    ✓ correctly formats a BTC price up to 8 decimal places without any insignificant zeros
    has a function to localize currency (formatCurrency) that
      ✓ throws an error if you don't provide an amount as a number
      ✓ throws an error if a currency is not provided as a string
      ✓ throws an error if a locale is provided as something other than a string
      ✓ properly localizes a fiat amount (649ms)
      ✓ properly localizes a BTC amount
      ✓ properly localizes a BTC amount with the correct bitcoin units
    has functions that involve converting between currencies
      like convertCurrency
        ✓ which will convert between two fiat currencies
        ✓ which will convert from a fiat currency to BTC
        ✓ which will convert from BTC to a fiat currency
        ✓ which correctly handles being called with the samefiat currency for both the from and to currency
        ✓ which correctly handles being called with BTC as boththe from and to currency
      like convertAndFormatCurrency
        ✓ which will convert between two fiat currencies properly localize the resulting value
        ✓ which will convert between a fiat currency and BTC and properly localize the resulting value
        ✓ which will convert between BTC and a fiat currency properly localize the resulting value

  our index utilities
    have a splitIntoRows utility that
      ✓ requires an array of items to be passed in
      ✓ requires itemsPerRow to be provided as a number
      ✓ returns an array split into sub arrays based on the itemsPerRow value

  loading a template
    ✓ for the first time, reads the template from the file system (58ms)
    ✓ after the first time, returns a cached template

  the number utility module
    ✓ correctly limits a number to a given number of decimal place and returns a string

  the string utility module
    ✓ correctly capitalizes a string

  the status bar
    has a pushMessage method
      ✓ which throws an error if you do not pass it a message as a string or object
      ✓ which throws an error if you pass in a type, but not one of the available ones
      ✓ does not throw an error if you pass in a type that is one of the available ones
      ✓ which throws an error if you pass in a duration, but not as a number
      ✓ does not throw an error if you pass in a duration as a number
      ✓ throws an error if you pass in a View that is not a descendant of the StatusMessage view
      ✓ doesn't throw an error if you pass in a View that is a descendant of the StatusMessage view
      ✓ which results in a new status message being added to the DOM
      ✓ which results in a new status message being added to the DOM with the given text
      ✓ which returns an object with a method to update the text of the status message

I am looking forward to testing and examining how this newer version works in Tor and so on but I see it as vital that people be able to easily install and launch it (as they were in the earlier and now deprecated version) before I test the Tor function.  I hope this commentary has been of some help.

**Comment by jjeffryes** [comment]
Thank you for this, @ABISprotocol. It's very useful. We develop the desktop client on Windows and Mac, and test it on a subset of Linux. 

We may need to update some of our packages. That could be what's causing some of the tests to fail for you.

The fsevents error is ok, that's only needed on Mac (and only works on Mac as far as I know). There are some other known issues with some of the tests on Windows, but that is separate from what you're seeing.

@cpacia @SamPatt do either of you get the same installation issues?
