### ISSUE TITLE
Add a "Sold out" flag

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#55]
It is a standard marketing trick to mark certain listings as sold out. As of writing, there are several vendors that use [this trick](https://duosear.ch/?q=sold), e.g.
- [Hot Gadgets for You](https://duosear.ch/0a6ec4cd4cabeb9000854d953905b2e66e95987e/listing/f952e91f791cda013ee48755b03bf84ee99b1dfb)
- [Tom Woods Jewelry](https://duosear.ch/@tomwoods_nh_jewelrymaker/listing/d029844a1630f21e01ede194da052227921aed8e)
- [Refur](https://duosear.ch/@refurs/listing/c9a29dde1ccbd15a01bbf29d30721b3aaed8f4b9)
- [TaiwanTea](https://duosear.ch/@taiwantea)

Each of those vendors use the listing title to mark the item as sold out. My suggestion is to add a flag in the listing object instead so that these can be machine readable (for better searching, filtering and display).

**Comment by hoffmabc** [comment]
@morebrownies ?

**Comment by jjeffryes** [comment]
This will be handled by the inventory system improvements we are expanding to all listings after cryptocurrencies.
