### ISSUE TITLE
Show Max Payment on Dispute Submit

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#553]
On the dispute submission screen (screenshot below), show a message that warns the user that the estimated transaction fee and the current moderator fee will be taken out of any settlement, and show both those values and the final estimated maximum settlement. This will help prevent disputes with zero payout.

Ex: "The maximum estimated settlement you can receive from this dispute is X. The moderator's fee is Y, and the estimated transaction fee is Z."

@morebrownies do you think this needs a design, or would just putting text above the Moderator line (or below the Reason, so it's closer to the submit button) in bold work?

![image](https://user-images.githubusercontent.com/1584275/27925572-477e28f0-6253-11e7-933c-0f17f9c02789.png)

**Comment by morebrownies** [comment]
I think adding the new text above the "Opening a dispute will..." text would work well.

So it would look something like:

> The maximum estimated settlement you can receive from this dispute is **X**. The moderator's fee is **Y**, and the estimated transaction fee is **Z**.
> 
> Opening a dispute will notify and invite the moderator into the order to help resolve any conflicts.

**Comment by jjeffryes** [comment]
If the estimated payout is zero, do you think we should put a more noticeable warning?

**Comment by jjeffryes** [comment]
(there's also the situation where the moderator gives you a percentage that is less than the fee, but that's a separate thing)

**Comment by morebrownies** [comment]
> If the estimated payout is zero, do you think we should put a more noticeable warning?

Setting the maximum estimated settlement to red/bold text could help here.

**Comment by rmisio** [comment]
I had a discussion with @cpacia at one point about the client being able to calculate a dispute payout on the client and apparently it's not a super easy thing to do:

> It's not easy to calculate. I more or less use the outpoint section from the dispute to determine how much the inputs are.

> But in the event that the buyer and vendor have a different set of outpoints I have an algorithm for choosing which one to use.

So... if we do this on the client, it would probably be a rough estimate at best.

**Comment by rmisio** [comment]
> The maximum estimated settlement you can receive from this dispute is X. The moderator's fee is Y, and the estimated transaction fee is Z.

One thing to keep in mind is that the transaction fee is split into 3 amongst all parties. Does the message as worded above play nice with that fact?

**Comment by jjeffryes** [comment]
> One thing to keep in mind is that the transaction fee is split into 3 amongst all parties. Does the message as worded above play nice with that fact?

If the purchase was $10, the fee is $3, and the moderator cut is $1, then the total possible payout (if the dispute submitter gets 100%) is $6, isn't it?

**Comment by rmisio** [comment]
> If the purchase was $10, the fee is $3, and the moderator cut is $1, then the total possible payout (if the dispute submitter gets 100%) is $6, isn't it?

Sounds right, but I think @cpacia could better answer that.

**Comment by cpacia** [comment]
The fee is divided proportionally. Buyer gets $9 - ($3 * ($9/$10)).

**Comment by jjeffryes** [comment]
@cpacia does that mean in the above scenario, the moderator would get zero ($1 - $1) and the seller would pay a $1 transaction fee for zero settlement, effectively making it a $1 penalty for the dispute?

We should probably spell that out somehow, given how high fees have gotten, that's going to surprise people.

**Comment by rmisio** [comment]
> and the loser that was awarded 0% of the settlement would pay a $1 transaction fee, effectively making it a $1 penalty for the dispute?

Isn't it really the buyer that would be funding that since the fees are coming out of money which the buyer put in. So, if the buyer is the "loser" in this scenario, then yes it would be "effectively making it a $1 penalty for the dispute".

**Comment by jjeffryes** [comment]
> Isn't it really the buyer that would be funding that since the fees are coming out of money which the buyer put in. So, if the buyer is the "loser" in this scenario, then yes it would be "effectively making it a $1 penalty for the dispute"

That's my question. If the fees are paid out of the original transaction, I don't see how they're split across the users if one of the users is awarded 0%. 

If the split was $10 100% to the buyer, with a 10% moderator fee and a $3 transaction fee, if the seller has to pay $1 of that transaction fee where does it come from? 

If in that scenario the buyer gets $8 ($10 - $1 mod fee - $3/3), the moderator would get 0 ($1 - $3/3) and the seller somehow gets negative one dollar (0 - $3/3), which doesn't make any sense.

Can you explain, @cpacia ?

**Comment by jjeffryes** [comment]
Now that Chris has explained it to me, this is how it works:

1. Assign percentages of the original transaction to each party (or translate fixed mod fee to a percentage).
2. The transaction fee is subtracted from each payout according to the percentage it is of the total. A party that receives 90% would pay 90% of the transaction fee.
3. If a party gets 0%, they pay 0% of the transaction fee. 

Is that correct, @cpacia ?

**Comment by cpacia** [comment]
correct

**Comment by jjeffryes** [comment]
I'm going to close this, it would be complicated and possibly misleading to calculate the fee at the time of the dispute, since the fee that matters is the one at the time of the settlement.

We may still need a better explanation of how fees work in disputes, but that can be addressed separately from this issue.
