### ISSUE TITLE
Tooltip over the User Card icons

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#554]
![image](https://user-images.githubusercontent.com/45482/27931994-1072e550-626a-11e7-8ccf-c18d87a26e33.png)

Can we get some tooltips on these bad boys?

**Comment by rmisio** [comment]
@morebrownies what should the tooltips say?

**Comment by morebrownies** [comment]
Ideally there would be multiple states on the tooltips:

- Follow (default state)
- Unfollow (when you already follow them)

- Add as moderator (default state) 
- Remove as moderator (when you already have them set as a moderator)

**Comment by morebrownies** [comment]
![screenshot 2017-07-21 12 46 33](https://user-images.githubusercontent.com/13066886/28479751-ab814858-6e12-11e7-806a-0252e01f23e6.png)

Can we add some tooltips to these buttons as well @rmisio?

Edit listing
Delete listing
