### ISSUE TITLE
On a PC with git installed, how does one get past the "Could not read from remote repository" in order to get 2.0 installed? This must be documented for people like me who stumble on to it.

### ISSUE THREAD

**Issue by DonGateley** [OpenBazaar/openbazaar-desktop#56]
Brief Description:  Can't install 2.0 on a PC

Operating System (OS and version): Windows 7
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Hardware: Lenovo Y570

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Open directory in CMD the target directory.
2. Run "git clone git@github.com:OpenBazaar/openbazaar-desktop.git"
3. Stay with your frustration to get an answer as to why.

Observed Behavior:fatal: Could not read from the remote repository.

Expected Behavior:???

Additional info (links, images, etc go here):

**Comment by jjeffryes** [comment]
Try 

`git clone https://github.com/OpenBazaar/openbazaar-desktop.git`

**Comment by hoffmabc** [comment]
Closing for abandonment.
