### ISSUE TITLE
Calculation error in the checkout process 

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#562]
Not sure if this is a server or front end issue, but I'm attempting to purchase a listing that costs $10.08

ob://QmZXGKrRRe5RTDhvzhZfSTe8vYBDGV7HBoNz5FS3U9FnUa/store/troll-face-tshirt

And, the balance due in bitcoin is 4,000 BTC, which currently equals: $9,559,960 🤔🤔

![screen shot 2017-07-12 at 9 53 09 am](https://user-images.githubusercontent.com/13066886/28129479-4ec80d94-66e8-11e7-87f8-87406c111501.png)

**Comment by rmisio** [comment]
You sure all this contentious HF drama didn't finally tank BTC?

**Comment by rmisio** [comment]
@morebrownies are you able to reproduce this consistently? Any special steps you took?

I'm not able to reproduce it:

![image](https://user-images.githubusercontent.com/794517/28129875-de7b69b2-66e9-11e7-8fbd-4039ba5f3765.png)

**Comment by morebrownies** [comment]
> You sure all this contentious HF drama didn't finally tank BTC?

Sure as hell hope not!!

I realized my server was outdated, so I pulled and unfortunately ran into the same issue:

![screen shot 2017-07-12 at 10 11 37 am](https://user-images.githubusercontent.com/13066886/28130084-9a6698b8-66ea-11e7-8739-6a6acbc1de34.png)
 I ran into the same issue:

**Comment by morebrownies** [comment]
![screen shot 2017-07-12 at 10 13 21 am](https://user-images.githubusercontent.com/13066886/28130132-c0e56898-66ea-11e7-96d7-5f579786c78e.png)

**Comment by rmisio** [comment]
Hmmm.... why in the heck would it happen for you and not me? You are on the latest client master, right?

**Comment by jjeffryes** [comment]
I can't reproduce this either.

**Comment by morebrownies** [comment]
Yeah I'm on the latest master for the client and server. I'm going to try some other listings to see if the calculation is also off.

**Comment by morebrownies** [comment]
I just tried the fish asshole listing and it appears to calculate correctly. The listing above still calculates 4,000 btc though each time I try. So strange.

![screen shot 2017-07-12 at 10 19 36 am](https://user-images.githubusercontent.com/13066886/28130482-a2808634-66eb-11e7-8bbd-bc8c47ca1b12.png)

**Comment by jjeffryes** [comment]
@morebrownies when you make the order that comes back wrong, can you look in the network tab for the purchase call, and see what the response is?

It should look like
```
{
    "amount": 400000,
    "orderId": "QmNbCkiDVUJ4EYBSTup9nRvvdvCW7vcHpJsdttEpjjynkT",
    "paymentAddress": "2N1SAm8N6sCjHYdYT4JuNwgUUBoMp6uLd2D",
    "vendorOnline": false
}
```
If the amount comes out as something different, it's a server issue, if not, it's a client issue.

**Comment by morebrownies** [comment]
![screen shot 2017-07-12 at 10 49 08 am](https://user-images.githubusercontent.com/13066886/28131752-c1023608-66ef-11e7-8ca0-0735a5593888.png)

**Comment by rmisio** [comment]
Ok, looks like this is a server issue. @cpacia

**Comment by jjeffryes** [comment]
I believe this was fixed.
