### ISSUE TITLE
Search Enhancements

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#569]
## User Story
As a user, when I am viewing the search page I want to be able to easily switch to other default search providers. I should be able to switch back to my default provider, and manually entered search providers should not be lost by switching. I should also be able to manually enter new providers here, and see the results.

### Provider Selector
- [x] There is a OB logo, with the text "OpenBazaar" and "Discover". It is just for display, and does not have interactivity (or it switches to the browse experience).
- [x] There is a series of square buttons for search providers.
- [x] The list should be composed of the default providers, and the current default search provider if it is not on that list. Each provider should have:
    - title
    - url to their logo
    - url for the search query
    - url for Tor search (optional)
- [x] If the client is in Tor mode and the provider has a Tor url, use the Tor url.
- [x] We will manually limit the number of providers to fit horizontally.
    Each one:
    - [x] Has the logo for the search provider if available.
	- [x] If the logo is not available or doesn't load, a default should be shown.
	- [x] The currently active provider should be marked with an underline.
    - [x] Clicking on a search provider will start a blank search with that provider.
- [x] There should be an add provider button. 
NOTE: the plus should stay a plus, 
    - [x] When clicked, a tool tip is shown with a text input for the new search provider.
    - [x] There is a cancel button that will close the tooltip.
    - [x] There is an add button that will apply this provider to the current search parameters. If it returns valid data, it will be added to the list of providers.
    - [x] If the logo url is returned, save it for that provider.
    - we will save the list of custom providers locally, and add it on the fly to the default providers.
    - We will limit the maximum number of search providers that can be added so they don't exceed the horizontal space.
    - [x] If the provider entered is not a valid URL, an error should be shown.	
- [x] There is a button for Transactions.
- [x] There is a button for My Page.
- [x] The currently selected provider only applies to the on-page search input, not the address bar.
- [x] There is a remove provider link for manually added providers only.

### Search Suggestions
- [x] There should be a row of suggestions under the search bar.
- [x] This may still need to be implemented yet on the search server.
    Each suggestion:
	- [x] When clicked, will search for that term (or is it a full url with parameters?)
- [ ] If more suggestions are provided than fit in the horizontal space, there should be a More link that will show the rest in a tool tip. (if the more link is problematic, it can be truncated instead)

### Report Buttons
- [x] The server will provide an optional report URL
- [x] If the URL is present, all results will have a report button.
- [x] Clicking the report button will call that URL with the result ID (peerID/slug).
- [x] The button should have a clicked state after it is clicked. If it succeeds, disable the button.

### Initial Experience
If the user arrives by pressing the search button, the experience should be different in several ways.
- [ ] No filters or sorting should be shown.
- [ ] A hard coded set of suggestions should be shown.
- [ ] N number of sets of 8 results should be shown, 2 rows of 4 across. N is to be determined (we need to test how a larger N affects the speed). 
    Each set:
    - [ ] Is created by loading the results for one of the suggestions.
    - [ ] Uses the suggestion as a title
    - [ ] Has a "See All" button that when clicked will fire a normal search for that suggestion, the same as clicking on the suggestion link.
- [ ] If the server does not deliver any suggestions, a normal blank search is shown instead.

### Tor Search
- [x] add a Tor Default Search Provider field in settings

### Badges (Optional)
Badges would be server-defined graphics and/or text that can be overlaid on the search results. This allows each search provider flexibility in adding features to the results data.
- [ ] The simplest version of this would be a single emoji that can be overlaid.
- [ ] Each result would have a badge field that had a single emoji character.

**Some simple wireframes to illustrate the action buttons and badge ideas:**

![artboard 1-80](https://user-images.githubusercontent.com/1584275/28326222-2e8a472a-6bae-11e7-9429-9c2dd52f4c25.jpg)

**Comment by morebrownies** [comment]
Here are a few other small details we should try to clean up, if possible:

1. Search input needs a placeholder value (e.g. Enter a keyword or #tag…)
2. I noticed the Free shipping filter is missing. Anyway we can add this in?
3. The sort by input is massive (Can we make it the same size as Sort by input on the user store page?)
4. Searching from the address bar vs the search input on the search page returns different results (Rob opened an issue for this)

**Comment by i5heu** [comment]
I am sure that some search engines let pay you for a higher position, so maybe its good if there is a advertise content indicator.

eg. like in ebay - the first 2 results are marked as advertised

**Comment by jjeffryes** [comment]
We're planning to add something like that in the near future.

**Comment by hoffmabc** [comment]
@i5heu it's also important to note that different search engines may do different things with their search results and choose not to conform to this even if we make it easy to implement.

**Comment by jjeffryes** [comment]
The plan is to allow search providers enough flexibility they can present the returned data in several ways. There will be combinations of options that can be used to make some of the results grouped in a promoted section, or marked as promoted. But it's up to the provider to choose to use those option.

**Comment by jjeffryes** [comment]
This has been completed.
