### ISSUE TITLE
Inconsistent search results

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-desktop#573]
If I search for "ski" from the address bar I get different results than if I search for "ski" from the input on the search page.

Looks like the two kick of different server queries:
![image](https://user-images.githubusercontent.com/794517/28341253-b55291ea-6bc7-11e7-9033-d99189a860a6.png)

**Comment by rmisio** [comment]
It looks like the search from the input on the search page includes the default filters on that page. I imagine for the searches to sync up, we'd want to include the default filters into the query from the address bar.

On a side note, the default shipping for me is Canada. Have no idea where it's getting that from. I have no location set.

![image](https://user-images.githubusercontent.com/794517/28341399-6219f008-6bc8-11e7-84ea-7d30c1b0724b.png)

**Comment by morebrownies** [comment]
I also see my shipping location being set to Canada, not sure why either.

**Comment by morebrownies** [comment]
My location is set to Seattle, Wa

**Comment by rmisio** [comment]
Ok, if I set my Rating to 1 star and shipping to Worldwide, then the results match. Looks like the defaults aren't being set ideally and then we need the address bar search to make use of those.
