### ISSUE TITLE
`Cannot read property css of undefined` in the first screen, Select Language

### ISSUE THREAD

**Issue by lekevicius** [OpenBazaar/openbazaar-desktop#579]
Brief Description: Clicking next on the very first onboarding screen doesn't work because `this.accWin` is undefined.

Operating System (OS and version): macOS 10.12.5
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.1.11
Hardware: Macbook Pro 2016

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Install app
2. Launch, See "Select Your Language" with English preselected
3. Click "Next >"

Observed Behavior:
Nothing happens. Opening developer tools shows this error every time "Next >" is pressed:
<img width="553" alt="screen shot 2017-07-22 at 21 38 34" src="https://user-images.githubusercontent.com/218656/28494441-b439de82-6f26-11e7-93c1-18b2762b64f2.png">

Expected Behavior:
I move to the next screen of onboarding

**Comment by jjeffryes** [comment]
It looks like this is a bug in v1, I've moved this issue to the v1 repo.  

https://github.com/OpenBazaar/OpenBazaar-Client/issues/1865
