### ISSUE TITLE
Consider simplifying moderator flexibility across listings

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#58]
As of writing for the 270 online stores, 264 have exactly one "combination" of moderators across their listings and 6 have exactly two combinations of moderators. (Since different listings can have a different set of corresponding moderators, a given store can many have several moderator combinations.)

The empirical data suggests that stores do not make much use of the flexibility in picking a different set of moderators across listings. I suggest removing that flexibility altogether. This would allow for a store to have a well-defined set of moderators that could be displayed on the store page.

Clearly communicating moderator options at the store level is something we are trying to do at Duo Search, and this simplification would help.

**Comment by jjeffryes** [comment]
Moderators are not chosen per listing, they are chosen at the store level, and apply to all listings. 

This issue appears to be based on either a bug in the v1 code, or incorrect data. We'll check the v1 code to make sure things are working as intended.

**Comment by JustinDrake** [comment]
Not incorrect data. For future reference, problematic GUIDs at the time of writing are

```
b3df09bd79a27f54cbfd007e6237c41884377612
cbd7522f7b5e11d7738a1f3f01d13c163fc7d7c1
ee20fe376c5a86adc79ef48669cbe2a4638f314b
94132351aed151eba7192d433e6807a2184f7877
2cbdf9142837d0f6d523da03c65bf65fa4ee62ee
1faac23f969845b80c62ce8628a7240089ab0456
```

**Comment by jjeffryes** [comment]
I've posted a v1 server issue for this at https://github.com/OpenBazaar/OpenBazaar-Server/issues/488
