### ISSUE TITLE
problem with shop Following/Follower indicator

### ISSUE THREAD

**Issue by i5heu** [OpenBazaar/openbazaar-desktop#593]
On Chris Pacia's OB shop ¹  is writen Following 1 and Followers 2, but if i open the following/followers page there is no one to see:   
 "No One is Following Chris Pacia Yet"

client 2.0.4, server 0.7.0

¹ - ob://QmVeRAZHYKR6fSAgiykKizC3UMzdgy6N5iT3hdSvXTUMtU/following

**Comment by jjeffryes** [comment]
This is a duplicate of #200
