### ISSUE TITLE
Photo cropping doesn't work well for book listings

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#594]
Cover gets cropped and users cannot read text on header or bottom.
![thumbnail crop](https://user-images.githubusercontent.com/10789865/28759256-63e14276-7571-11e7-8841-e963f7828083.png)

**Comment by jjeffryes** [comment]
This is working as intended. The listing images are always square, so the image in them is fit into that square space by making the smallest dimension 100% and centering the image. There's no way to make that work for every possible image.

For now, the answer is to edit your images to be square, with a background color to the left and right side of the book image, so the entire image is square.

We have some plans to add a more sophisticated image upload tool in the future that includes the ability to crop images or make them square with a background fill, but that won't happen for a while.
