### ISSUE TITLE
Make Address Name Bold

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#596]
Name in Shipping Addresses page should be displayed in **bold**
![bold name](https://user-images.githubusercontent.com/10789865/28759873-74b7327a-7578-11e7-8f5c-1c6cdd4331b2.png)

**Comment by rmisio** [comment]
@morebrownies Do you agree with this change?

**Comment by morebrownies** [comment]
Yeah sounds fine
