### ISSUE TITLE
Fill Gap Between Tooltip and Delete Button

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#598]
OB 2.0.5 win7

1) There is a thin gap between opened confirm dialog and listing photo. When mouse cursor moves to this area, dialog is hidden.

![redline](https://user-images.githubusercontent.com/10789865/28806742-0a851022-7648-11e7-8f77-1f9c625f6e08.png)

2) Tooltips for edit and delete buttons should not show on background when confirm dialog is open.

![backdialog](https://user-images.githubusercontent.com/10789865/28806795-50775950-7648-11e7-97d8-d9189367fec6.png)

**Comment by rhcastilhos** [comment]
I don't see this bug anymore on 2.0.10 win7 64bits

**Comment by jjeffryes** [comment]
This was fixed.
