### ISSUE TITLE
Terms of Service -> Unable To Save Your Profile

### ISSUE THREAD

**Issue by i5heu** [OpenBazaar/openbazaar-desktop#599]
By finishing the first start dialog (pressing the Button "I Agree") a error appears:

```
Unable To Save Your Profile
File Write Error: no such column: proof
```
by clicking it away (the X on top of the modal) the Terms of Service appear again.
so im stuck between this Terms of Service screen and the error modal.

after a few tries the error is now: 

```
Unable To Save Your Profile

Profile already exists. Use PUT.
```

- after a restart the client is working properly

**Comment by jjeffryes** [comment]
@i5heu did you install OB with the command line, or with an installer?

If you installed with the command line, that error should mean you're using an outdated database. You will need to erase your data folder and update your server.

**Comment by i5heu** [comment]
i have had the client 2.0.4 version, removed it witf `apt autoremove openbazaar2` and installed the new version with `apt install ./openbazaar2_2.0.5_amd64.deb`
- im on Ubuntu 17.04

**Comment by hoffmabc** [comment]
I believe there was a db upgrade so you'd probably have to blow that away. Is that correct @cpacia ?

**Comment by jjeffryes** [comment]
@i5heu after deleting your data, and updating everything, does this error still happen?

**Comment by i5heu** [comment]
I updated the client 2.0.5 to  2.0.6 with `apt-get autoremove` and  `apt install` - no problems appeared at this time

**Comment by jjeffryes** [comment]
Closing this, it looks like it was fixed by updating.
