### ISSUE TITLE
message button on product page

### ISSUE THREAD

**Issue by i5heu** [OpenBazaar/openbazaar-desktop#600]
it would be great to have a message button on the store page, for easy interaction.

![auswahl_001](https://user-images.githubusercontent.com/22565269/28867305-e08d6df8-7775-11e7-88a9-1802c0939e23.png)

**Comment by jjeffryes** [comment]
What do you think about this suggestion, @morebrownies ? 

There's a message button on the store page under the listing modal, but I can see the argument that it would be nice to be able to start a dialog with the vendor when you're looking at the listing you want to talk about.

Maybe we could do something with the chat bar, so any time you're looking at a user's page, the chat bar has a button to start a conversation with them (or continue an old one)?

**Comment by rmisio** [comment]
> Maybe we could do something with the chat bar, so any time you're looking at a user's page, the chat bar has a button to start a conversation with them (or continue an old one)?

FWIW, it would be a whole lot less scope to put a message button on the Listing Detail overlay.

**Comment by morebrownies** [comment]
Yeah a **message** button on the listing detail overlay seems helpful. I'll put together a design for this today.

**Comment by ekerstein** [comment]
I was about to open an issue for this too. I was browsing a store and had a question about a listing. To ask a question I had to leave the listing, scroll up to the top of the store, and click message.

A message button inside each listing with something like "Ask a question" would improve UX. 

This "ask" button could even pre-fill a message to the vendor letting them know which item and a link. And maybe the vendor could be given the option to add the question/answer to the listing page (similar to Amazon).
