### ISSUE TITLE
National Flags on "Origin" not loaded 

### ISSUE THREAD

**Issue by i5heu** [OpenBazaar/openbazaar-desktop#601]
URL: default search page

client 2.0.5, server 0.7.1
![auswahl_002](https://user-images.githubusercontent.com/22565269/28867869-d4581068-7777-11e7-9118-ca7cde6fda88.png)

**Comment by jjeffryes** [comment]
I can't replicate this, all the flags load for me. @i5heu what OS are you on?

**Comment by rmisio** [comment]
@jjeffryes Hmmm... since these should be being pulled from images, the OS shouldn't matter. Unless @i5heu is on an old client, I have no idea how this could be happening.

**Comment by jjeffryes** [comment]
Yeah, I am mostly grasping at straws with the OS. The only thing I can think of is there is some local issue where some of the images are missing or blocked.

**Comment by i5heu** [comment]
I have searched canada-emoji "1f1e8-1f1e6" in the github [repo](https://github.com/OpenBazaar/openbazaar-desktop/tree/master/imgs/emojis/72X72) its not there. 

![auswahl_003](https://user-images.githubusercontent.com/22565269/28892815-80cb615e-77cf-11e7-8469-cb5a11a7f94c.png)

i use `client 2.0.5, server 0.7.1` on Ubuntu 17.04

**Comment by jjeffryes** [comment]
@i5heu the latest search code should no longer have the origin filter. Do you see all of the icons in the shipping filter?

**Comment by i5heu** [comment]
on the main search at `client 2.0.5, server 0.7.1`

![auswahl_004](https://user-images.githubusercontent.com/22565269/29134044-c2b4e9da-7d35-11e7-950d-68a845c551b4.png)

**Comment by jjeffryes** [comment]
Ok, I notice that our repo does have the files, but they are in the 72x72 folder, with a lower case x, and not in the 72X72 folder.

My local only has the lower case folder, but the link is to the upper case folder, I think in my case Windows is ignoring the case. 

There should be only one folder, I'll try and figure out how we ended up with two.
