### ISSUE TITLE
Weird thumbnail issue in Purchases

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#602]
On Milestone 3 I'm seeing possibly a bad crop thumbnail of the order.

I'm not sure if this image is the avatar or the item, but it's clearly neither at the moment.

![image](https://user-images.githubusercontent.com/45482/28882854-78b1f15e-777a-11e7-8042-e06e2ac70810.png)

**Comment by rmisio** [comment]
This is a product of auto-cropping. You need to choose where to crop (center, top-left, top-right, etc...). No matter where you choose, it's not going to work for all images.

At some point we could look into integrating a cropper into the Create Listing modal, so the user could choose the cropping, but there's some scope there. That's an already super complicated screen.

Also, I'm not sure we have one specific target dimension. For example, if the user crops to a certain dimension, can that dimension be used in all the places we need a listing image (store, search, listing detail, order detail, etc...) -or- do we need to have the user choose multiple crops? If it's the latter, then the server would need to updated to store additional versions of a listing image.

I don't think this is something we will solve by launch.

**Comment by rmisio** [comment]
Ok... this might be a bug in the cropping algorythm on the server. While auto crop isn't going to be perfect, it should be better than what that screenshot depicts. It looks like the image is overhanging (by a large amount) over both dimensions and it should at most overhang on one.
