### ISSUE TITLE
Show number of incoming/outgoing connections

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#61]
A common issue for vendors in OB1.0 is that their store seems online to them (they can see their storefront) but actually they are not visible to the outside world.

Similar to other P2P software (e.g. BitTorrent clients, or Bitcoin Core), it would be useful to show the number of connected peers, detailing the number of incoming and outgoing connections.

This would help vendors know when their store is not visible to the outside world, or when their store is being flaky. It may also be "exciting" for store owners to see people connect to their node.

**Comment by jjeffryes** [comment]
We don't have a design up for this, but our plan is to include an area with details on your local network, a list of nodes you're connected to, etc. 

It's definitely useful, both for debugging and just to see what's going on.

**Comment by hoffmabc** [comment]
Related: https://github.com/OpenBazaar/openbazaar-desktop/pull/103
