### ISSUE TITLE
Change Wallet Retry Text

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#610]
![wallet retry](https://user-images.githubusercontent.com/10789865/28953699-512f9e60-78b0-11e7-8d93-a6773e22fa7d.png)

The text for retrying payments in the wallet is confusing, and doesn't reflect what the user is actually doing. It should be improved by changing it to something like the following:

"Retry Payment" should be changed to "Bump Fee" or "Increase Fee".

"X* will be added to retry the payment" should be changed to "Add X* to the fee and rerun the transaction."

**Comment by jjeffryes** [comment]
@morebrownies thoughts on the text?

@cpacia is the description above accurate as to what is actually happening?

**Comment by morebrownies** [comment]
Yeah I like:

**Increase Fee**
"Add X* to the fee and republish the transaction"

**Comment by jjeffryes** [comment]
Is the transaction republished? Resubmitted? I'm not sure what the right word for resending a Bitcoin transaction is.

**Comment by jjeffryes** [comment]
@hoffmabc @SamPatt what is the right word for submitting a transaction with a bumped fee? Republish, resend, resubmit, etc.?

**Comment by hoffmabc** [comment]
Resubmitted I believe.
