### ISSUE TITLE
Can't Leave Review on Decided Order

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#614]
On an order where I was the buyer, I created a dispute, and the dispute was decided and accepted by the other party. When I clicked Accept Payout, I got the message that the order will be complete when I leave a review, but there is no way to leave a review. 

![image](https://user-images.githubusercontent.com/1584275/28997159-bdc330a6-79db-11e7-9a12-fa1062e3e9f3.png)

**Comment by rmisio** [comment]
In order for the complete order form to show up 2 conditions must be met:
1.) The order must be in a state of `resolved`.
2.) The order must contain a `disputeAcceptance` object.

Looking at the screen, #2 is satisfied, but #1 is not - the order looks to still have a state of `decided`, but after a payout has been accepted, it should be `resolved`.

This is a server issue, which already had a bug:
https://github.com/OpenBazaar/openbazaar-go/issues/600

**Comment by jjeffryes** [comment]
Ah, ok. Thanks.

That explains why it was stuck.
