### ISSUE TITLE
Add tooltips to all icons in the title bar

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#615]
I attempted to get this working but ran into a lot of issues when using the tooltip class. It seems tooltips aren't playing friendly with `<a>` objects. 

Below is the text the tooltips should display on hover:

![screenshot 2017-08-06 11 25 56](https://user-images.githubusercontent.com/13066886/29005894-15d389a8-7a9a-11e7-9970-abad187547c0.png)

1. Close
2. Minimize
3. Maximize
4. Back
5. Forward
6. Refresh

![screenshot 2017-08-06 11 25 59](https://user-images.githubusercontent.com/13066886/29005893-15d2905c-7a9a-11e7-99d7-b427626e96ad.png)

1. Discover
2. Wallet
3. Notifications
4. Navigation

**Comment by jjeffryes** [comment]
I added this to #617, it was kind of tricky!

The main thing is icons are inserted as a :before element, and the tooltip also uses :before and :after, so you can't put a tooltip directly on an icon.

Instead, you have to wrap the icon in another element, and put it on that. In this case, I put the tooltip on the <a>, and moved the icon class to a <i> inside the link element (plus a bunch of other stuff to make the alignment work out).
