### ISSUE TITLE
Multiples charges for the same purchase

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#619]
v. 2.0.6
This occurs on Purchases page (when user first close the purchase window and returns later).
It is possible for the user to click many times on the "Yes, Pay" button, and he gets charged on the wallet many times for the same purchase.

![multiple chargtes](https://user-images.githubusercontent.com/10789865/29007942-4ecb7c26-7ae4-11e7-825f-cd2b011158cd.png)

**Comment by jjeffryes** [comment]
How are you clicking on the Yes, Pay button multiple times?

When it is clicked, a spinner should immediately appear and disable the button, and when the spinner is done, the button vanishes an the screen changes to the paid state.

I can't reproduce this, even with a connection throttled to a very low speed. What OS are you on?

**Comment by rhcastilhos** [comment]
Win7 64bits 2.0.6

It occurs only when paying on purchase page (after closing the purchase the first time). Screen is not updating to paid and shows qr code and yes pay button again.

**Comment by rmisio** [comment]
@jjeffryes I think rhcasilhos is observing this on the Order Detail overlay. It's possible the view is being re-rendered and the spinner state is being lost... although I'm not sure what would cause it to re-render there other than it becoming funded, in which case the whole pay section would go away. I need to try and reproduce it to see what could be happening.

**Comment by jjeffryes** [comment]
@rhcastilhos can you post a screenshot of exactly where you see this happening?

**Comment by rhcastilhos** [comment]
Here is how to reproduce:

First cancel order
![ob01](https://user-images.githubusercontent.com/10789865/29051762-53f0cb70-7bbb-11e7-82ce-884e25496382.png)
Go to purchases page
![ob02](https://user-images.githubusercontent.com/10789865/29051735-27189d62-7bbb-11e7-8273-d75bca45bc2b.png)
Click on pay from wallet
![ob03](https://user-images.githubusercontent.com/10789865/29051739-2a9e2a2e-7bbb-11e7-9b23-b5789ba017ff.png)
1. Click on "Yes, Pay"
2. Before payment is complete, click out of the small dialog which contains "Yes, Pay" button. Screen with QR code won't go away.
![ob4](https://user-images.githubusercontent.com/10789865/29051742-2e6946de-7bbb-11e7-9120-729132dab0e5.png)
Multiple charges are done
![ob6](https://user-images.githubusercontent.com/10789865/29051749-3470fc2a-7bbb-11e7-99ed-e446a92a0522.png)

**Comment by jjeffryes** [comment]
@rhcastilhos that's very helpful, thank you.

**Comment by tophensen** [comment]
I ran into the same issue and now have 3 orders (2 awaiting payment, 1 paid + awaiting fullfillment) for the same item. How can I remove/cancel those orders? 
![screenshot](https://user-images.githubusercontent.com/5727580/31574760-37c36a2a-b0d6-11e7-9786-f62442cda924.png)

Thanks!
