### ISSUE TITLE
Special price units

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#64]
Some services require more advanced pricing, like price in BTC per minutes, hours (language classes) or words, characters (translation).

OpenBazaar should have special price units in order to facilitate price comparison. This way third-party search engines could better categorize services, for example "English teachers starting at 0.1 BTC/45 min" or "Translators from English to Spanish: starting at 0.001 BTC/character".

**Comment by jjeffryes** [comment]
That's an interesting idea. Right now the protocol only allows per-transaction pricing, so doing something by the hour would either have to take place outside of OpenBazaar, or it would need to be sold by the increment (ie: you sell 1 hour of service per transaction, not service by the hour).

**Comment by jjeffryes** [comment]
Sellers can emulate this with quantity, for instance by selling X per minute, with a quantity of 1 being a minute. I don't think we need to add explicit functionality for it.
