### ISSUE TITLE
Clicking on name / avatar within the transaction overlay should take you to the user's page

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#652]
**Sam test 3** and his avatar should be clickable here.

![screenshot 2017-08-10 12 43 30](https://user-images.githubusercontent.com/13066886/29188926-93c77b1c-7dc9-11e7-8280-bfd8ab726abc.png)

**Comment by rhcastilhos** [comment]
This is duplicate of #622

**Comment by morebrownies** [comment]
Good call, I'll close this one
