### ISSUE TITLE
First menu item text is not clickable

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#655]
v.2.0.6 w7 64 bits

Page's name menu item is not clickable. I believe it should link to "Home" page.
![menu item](https://user-images.githubusercontent.com/10789865/29252072-404a3d1a-8037-11e7-823a-7f088b98c5e8.png)

**Comment by jjeffryes** [comment]
@morebrownies what do you think about making your name in the nav menu go to your home page?
