### ISSUE TITLE
Page stats goes to zero after updating page settings

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#656]
v.2.0.6 w7 64 bits

Go to Settings > Page, change any setting (like description) and save. Go back to your page and all your stats will be zero.

![zero followers](https://user-images.githubusercontent.com/10789865/29252173-b7170332-8038-11e7-88b6-ebca201dc569.png)

**Comment by rhcastilhos** [comment]
This is still present in 2.0.8, even after #676 
But now Following doesn't goes to zero, only Store and Followers do.

**Comment by hoffmabc** [comment]
Where we at with this one @jjeffryes?

**Comment by jjeffryes** [comment]
This is still a live bug.

**Comment by dsmurrell** [comment]
I'm seeing broken but different behaviour here too.

I've created one listing and when I refresh the URI at the top for one stat the other stats go to zero.

After clicking on 'Store 1':
<img width="1440" alt="screen shot 2017-10-20 at 14 36 30" src="https://user-images.githubusercontent.com/4035854/31823467-301e0b22-b5a4-11e7-925c-6ae975729db7.png">

After clicking on 'Following 0':
<img width="1440" alt="screen shot 2017-10-20 at 14 37 52" src="https://user-images.githubusercontent.com/4035854/31823528-4de226ca-b5a4-11e7-814b-c51ba9a91d57.png">

After refreshing the page (enter on URI ob://QmZuTqFBi2cWFAREajSTxKf8YLZJ1fKzSG2q5xD9NdhaLe/following):
<img width="1440" alt="screen shot 2017-10-20 at 14 38 49" src="https://user-images.githubusercontent.com/4035854/31823580-6b77fb10-b5a4-11e7-81b6-941ac4d0764c.png">
