### ISSUE TITLE
Ability to change details of an order with pending payment

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#657]
Buyer should be able to change details (quantity, shipping address, e-mail, coupon code and memo) of an ongoing order with pending payment.

This happens when buyer closes the order when QR code for payment is being shown and access it later through Menu > Purchases (orders with "Awaiting Payment" status). 

Maybe first-time buyers will close the order window when they see QR code, buy some bitcoins and return later, but wanting to change shipping address or quantity. Maybe buyer doesn't want to rewrite all his long memo instructions again.

![orderdetails](https://user-images.githubusercontent.com/10789865/29252391-8adfd510-803c-11e7-853e-c0a6ee37cad9.png)

**Comment by jjeffryes** [comment]
At this point I don't think the transaction is changeable. Is that correct, @cpacia ?

**Comment by rhcastilhos** [comment]
If contract can't be changed at this point, at least there should be an option to create a new order of that listing (with a new order #), which would import Discussion (chat with vendor) and Details (address, coupons, moderator, quantity and memo) of the previous order.

**Comment by jjeffryes** [comment]
How would that be different from just making a new order, other than pre-selecting a few options? That seems like an edge case to me. 

If there is a minor issue with the order, you could use the built in order discussion to clear it up with the seller.

**Comment by rhcastilhos** [comment]
You could avoid the hassle of typing a long memo/coupon code again, or searching a moderator again. 

All discussion would be in the same place. 

Buyers that change address won't have to pay more if price goes up after purchase (original purchase had a discount).

When buying multiple listings on same order is implemented (shopping cart), users won't have to search all listings and set its quantities again.

**Comment by jjeffryes** [comment]
I'm closing this issue, contracts are intentionally not changeable.
