### ISSUE TITLE
Written memo is not being displayed on order details 

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#658]
v.2.0.6
w7 64 bits

It always displays as "n/a" regardless of what is written.
![memo](https://user-images.githubusercontent.com/10789865/29252430-850badde-803d-11e7-9970-3dc528eef3e9.png)

**Comment by rmisio** [comment]
@jjeffryes I don't think the memo is being set in the right place when calling the purchase api. I'm guessing the memo should be set at the item level.

![image](https://user-images.githubusercontent.com/794517/29684847-49712f68-88c8-11e7-9672-9c7650e42bb2.png)
