### ISSUE TITLE
Email address should be displayed on order details

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#659]
Email address given by buyer should be displayed on order details.

![emailorder](https://user-images.githubusercontent.com/10789865/29252507-016f1e28-803f-11e7-98e5-7b055d0bdca8.png)

**Comment by rmisio** [comment]
@morebrownies Space is kind of tight here. Do you think the e-mail should be displayed? If yes, where do you think it should go?

**Comment by morebrownies** [comment]
We'll have to output email somewhere since the user is entering it during checkout. I've added it to my queue of things to look at.

**Comment by morebrownies** [comment]
Hey @jjeffryes we could output the email address here: 

![screenshot 2017-09-03 08 19 46](https://user-images.githubusercontent.com/13066886/30004255-b5e40264-9080-11e7-9ffa-6f20d80a916a.png)
