### ISSUE TITLE
Wrong sum of rounded items on Order Summary

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#660]
Total order price should sum all rounded items (in this case should be 107.99).

Also fix the typo "Plese".

![round](https://user-images.githubusercontent.com/10789865/29252601-0a8f73d4-8041-11e7-893c-3043dafae2eb.png)

**Comment by jjeffryes** [comment]
I think this is a result of each of those numbers being changed from the vendor's currency to bitcoin and then to your currency, but the total being added up in the original currency, then changed.

That makes it possible for rounding differences to creep in.
