### ISSUE TITLE
Update Listing to Free Shipping and Store Page Does Not Update

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#664]
- Created a listing with a shipping cost.
- Edited to have free shipping 

Result: 
Listing Detail screen shows free shipping tag
![image](https://user-images.githubusercontent.com/45482/29279251-40f4d050-80e5-11e7-8d45-aa898b9f81ec.png)

but Store page does not.
![image](https://user-images.githubusercontent.com/45482/29279237-385bf6f8-80e5-11e7-841c-fec0d60ab122.png)

**Comment by rmisio** [comment]
What is the listings api returning for you for that listing in the freeShipping field?

![image](https://user-images.githubusercontent.com/794517/29283253-7960d6f4-80eb-11e7-8f66-56fcc5c7a297.png)

freeShipping is a list of countries the listing ships free to. It is managed by the server. If it's empty for you, this is a server issue. If not, then I'll have to dig deeper and figure out why the client isn't showing the badge.

**Comment by rmisio** [comment]
@hoffmabc When I update the listing, the store gets the `Listing data has changed. <refresh>` pop in message.

![image](https://user-images.githubusercontent.com/794517/29642576-863f6824-881e-11e7-932c-4155208a7754.png)

Once I click "refresh" on that (or I refresh the page in another way), the listing gets updated with the Free Shipping badge. Is that not happening for you?

**Comment by hoffmabc** [comment]
I don't recall seeing the refresh box. I'll have to retest.

**Comment by rmisio** [comment]
I believe this was fixed. It was a matter of the Store not recognizing the 'All' shipping region.
