### ISSUE TITLE
Chat Badge Getting Cut Off

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#666]
![image](https://user-images.githubusercontent.com/45482/29281247-3d50c196-80ec-11e7-9824-2826e7f22dbf.png)

**Comment by jjeffryes** [comment]
It turns out you can't have overflow visible in one direction, and auto in a different direction.

https://www.w3.org/TR/css3-box/#overflow-x

I'm going to have to see if there's a tricky way around that.

**Comment by rmisio** [comment]
Wouldn't the really easy fix (at least for now) be to just move the badge over a few pixels?

**Comment by jjeffryes** [comment]
> Wouldn't the really easy fix (at least for now) be to just move the badge over a few pixels?

That's the simplest, yes. What do you think, @morebrownies ?

I have a solution at the jsfiddle above, by adding a wrapper, but we're just talking about a few pixels difference.

**Comment by morebrownies** [comment]
Yeah bumping it over a few pixels should be fine @jjeffryes

**Comment by jjeffryes** [comment]
This is what that would look like:

![image](https://user-images.githubusercontent.com/1584275/29378767-4ab22160-828e-11e7-9d53-2d7431a2071a.png)

**Comment by morebrownies** [comment]
Why does it need to be pushed over that far to the right? @hoffmabc screenshot shows about 5px being cut off.

**Comment by jjeffryes** [comment]
My fault, I just took the left property off instead of setting it to zero.

How about this?

![image](https://user-images.githubusercontent.com/1584275/29379024-1751781a-828f-11e7-8648-bd1fc2100bd5.png)

**Comment by morebrownies** [comment]
cool, looks better 👍
