### ISSUE TITLE
renderjson doesn't work in installed app

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#672]
In the installed version of the client, the renderjson.js library fails with this error:

Uncaught ReferenceError: renderjson is not defined at renderjson.js:58

That line is:
(_module || {}).exports = renderjson = function () {

When the client is run from the command line, it works normally.

**Comment by hoffmabc** [comment]
What does this library even do?

**Comment by rmisio** [comment]
@hoffmabc It's the plugin we use to make the contract be collapsable / expandable:

![image](https://user-images.githubusercontent.com/794517/29371178-3cb889da-826d-11e7-910f-571d52d85a45.png)

**Comment by hoffmabc** [comment]
Ah ok. I think I saw contracts not showing up in the installer version and didn't think about this. Good catch.
