### ISSUE TITLE
Add version of store to the "Information" box

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#678]
The "Information" box has the peer ID. I suggest adding the version of the store, as stored in the [`user_agent` file](http://gateway.duosear.ch/ipfs/zdj7Wjt81j8CeiX9Tda2u5HmXAskgAQfanyuD5Tav9KR6xyLh/user_agent). This will greatly help for debugging.

![screen shot 2017-08-18 at 10 36 50](https://user-images.githubusercontent.com/731743/29453345-30a5a0c0-8401-11e7-9394-fcfe63dc0365.png)

**Comment by jjeffryes** [comment]
We currently show this for your own server in the about modal.

Are you asking that it be shown for other users?

@cpacia would there be any issue with exposing that data in profile instead (or in addition to) settings?

**Comment by JustinDrake** [comment]
Yes, I'm asking that it can be shown for other users. Because I imagine some issues will only arise when different clients have different versions.

**Comment by jjeffryes** [comment]
I'm going to close this issue as stale. I don't think we're planning on implementing this.
