### ISSUE TITLE
Cannot follow stores

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#680]
When trying to follow stores I get the following two errors in succession:

![screen shot 2017-08-18 at 10 45 42](https://user-images.githubusercontent.com/731743/29453696-71ab3106-8402-11e7-82fa-9cd1e30952d0.png)

![screen shot 2017-08-18 at 10 45 48](https://user-images.githubusercontent.com/731743/29453701-72b2e38c-8402-11e7-8e6d-b312d87cb300.png)

**Comment by hoffmabc** [comment]
You have a really old database I think. You'll need to wipe it so you have the new schema.

**Comment by JustinDrake** [comment]
I don't think so. I'm running master for openbazaar-go, and the OpenBazaar 2.0 was cleared today.

**Comment by hoffmabc** [comment]
Ok maybe there is something else going on.

**Comment by JustinDrake** [comment]
Reopen?

**Comment by jjeffryes** [comment]
It's probably an issue with the other nodes being out of date.
