### ISSUE TITLE
Cannot buy stuff (escrow timeout must be 1080 hours)

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#681]
I get the following error when trying to buy stuff:

![screen shot 2017-08-18 at 10 47 55](https://user-images.githubusercontent.com/731743/29453770-b628d478-8402-11e7-8d85-1eb3b686a2c0.png)

**Comment by hoffmabc** [comment]
Ooch that's a new one. @cpacia or @rmisio?

**Comment by rmisio** [comment]
This should really be a bug in the server repo. The server is kicking back an error. It may be a situation where this is a listing in an outdated and unsupported format.

@JustinDrake Can you log this in the server repo?

**Comment by hoffmabc** [comment]
What's the listing? It's hard to reproduce when there are no steps here.

**Comment by JustinDrake** [comment]
You are in the Slack discussion where examples listings were given https://openbazaar.slack.com/archives/G06KJ7QQ1/p1503069857000208?thread_ts=1503065927.000006&cid=G06KJ7QQ1

For example ob://QmaL4AJ3GeHSFndeWnYEFntEbwUFE3fyJhdGzPa4qKzLp6/store/coin-center-to-the-moon-t-shirt

**Comment by hoffmabc** [comment]
That's my store and I've got like over 20 sales successfully completed from different buyers. Not sure what's happening for you.

**Comment by hoffmabc** [comment]
![img_4214](https://user-images.githubusercontent.com/45482/29525649-624694ba-8661-11e7-8d5d-ed594770b55e.JPG)

This is from a couple days ago.

**Comment by rmisio** [comment]
Closing this as it's either a server bug or probably a result of an outdated server.
