### ISSUE TITLE
Following count and /following page inconsistent

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#682]
See the screenshot below. There's an inconsistency between "Following 10" and "Decker is Not Following Anyone Yet"

![screen shot 2017-08-18 at 10 48 49](https://user-images.githubusercontent.com/731743/29453849-0216a19e-8403-11e7-8317-37b0467fdfa2.png)

**Comment by hoffmabc** [comment]
We have a refactor for this coming today. Pinging @rmisio as he worked on this.

**Comment by jjeffryes** [comment]
This is a duplicate of #593 and #200
