### ISSUE TITLE
Unbrowsable search engine results 

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#685]
The `test` search query returns `ob://QmNya1TkdojhwaURg2rci55rhxLXWh5x2xeus8eCiTos6S/store/test-listing` as a result, but that listing is unbrowsable for me.

**Comment by hoffmabc** [comment]
This is more of an OB1 search engine issue I think rather than OpenBazaar, but @tyler-smith can look into the purge process for dead listings.

**Comment by jjeffryes** [comment]
I've opened an issue in our search repo.

**Comment by JustinDrake** [comment]
Is the search repo issue tracker public?

**Comment by jjeffryes** [comment]
No, it's a private repo.
