### ISSUE TITLE
Other Party in Chat Gets Your Avatar

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#687]
![image](https://user-images.githubusercontent.com/1584275/29462902-db505608-83fe-11e7-98bf-cd8bd40bd3b6.png)

1. open an old chat conversation
2. the other party's avatar is correct
3. send a message to them
4. their avatar updates to be your avatar at roughly the same time your message appears in the chat

**Comment by rmisio** [comment]
I'm having difficulty reproducing this one. What's in that screen shot looks right... what am I missing? It's the Koala's node and he sent two messages to the Test node. The outgoing messages are on the right and should have the Koala icon.

**Comment by jjeffryes** [comment]
The first message isn't from the koala node, it's from the TEST node. When I replied, the incoming message turned into an outgoing one. 

But now when I load that conversation, the second message gets a SQL error, and the server says the first message is outgoing.

Maybe this is a server issue with outdated nodes. The node I was sending to was old and not online any more.
