### ISSUE TITLE
Error when creating listing

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#696]
I tried to creating the most basic listing. See screenshot below for error. "file already closed"

<img width="650" alt="screen shot 2017-08-19 at 16 23 35" src="https://user-images.githubusercontent.com/731743/29488034-e039b572-84fa-11e7-9164-06f8279e317f.png">

**Comment by jjeffryes** [comment]
@cpacia this looks like a issue with saving, do you know what this means?

**Comment by rmisio** [comment]
@JustinDrake Please log this in the server repo. This is a server error preventing the listing from being saved. (fwiw - I have no clue what it means)

**Comment by JustinDrake** [comment]
I figured out the problem. I was using Go 1.9, and IPFS is broken for Go 1.9.

See https://github.com/ipfs/go-ipfs/issues/4097

**Comment by hoffmabc** [comment]
@juatindrake we should file a server issue to keep track of this. I'll do it.
