### ISSUE TITLE
Pagination is not displayed in the URI for the discover page

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#702]
The discover page (from OB1 search) currently has 124 listings. When I page through, the pagination is not displayed in the top URI link. The link is just `ob://search?providerQ=https%3A%2F%2Fsearch.ob1.io%2Fsearch%2Flistings%3Fq%3D*%26p%3D2%26ps%3D12`.

I'm also curious to know how these listings are ordered. Is it newest listings first?

**Comment by rmisio** [comment]
@JustinDrake The page is in there. `https%3A%2F%2Fsearch.ob1.io%2Fsearch%2Flistings%3Fq%3D*%26p%3D2%26ps%3D12` decodes to `https://search.ob1.io/search/listings?q=*&p=2&ps=12`. The page comes in the `p` param and is 2 in this case.

FWIW, the url to the search endpoint is embedded within the url to the Discover page (`ob://search`), which requires the embedded url to be encoded.

> I'm also curious to know how these listings are ordered. Is it newest listings first?

This is driven by the `Sort by` drop down:

![image](https://user-images.githubusercontent.com/794517/29573902-fddfb498-8714-11e7-988d-4249cac86789.png)

If you're asking what the secondary sorting is for those sort options, I'm not sure. I think you'd need to ping Tyler or Chris.

**Comment by rmisio** [comment]
Sorting also is embedded in the search query. You don't see it for `relevance` because that must be the default. Here's an example of sorting by descending price:

`https://search.ob1.io/search/listings?q=*&sortBy=price-desc&p=2&ps=12`
