### ISSUE TITLE
Chat Badge Not Clearing

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#703]
Brief Description: If someone has left a message for you causing a chat badge in the sidebar and you view it and/or reply, the badge still stays on the chat head.

Operating System (OS and version):  OSX
OpenBazaar version (shown on `About OpenBazaar` page in menu): 2.0.7 binary

Steps to reproduce:
1.  Other user sends chat message to cause badge
2. Click on chat head to view message
3. Reply

Observed Behavior: Badge does not clear

Additional info (links, images, etc go here):
![image](https://user-images.githubusercontent.com/45482/29494703-1789b6b6-857e-11e7-9a84-000b7a48620d.png)

**Comment by hoffmabc** [comment]
Ok I figured out that you must click on another chat head and then go back to it to cause it to mark as read.

**Comment by rmisio** [comment]
I'm not able to reproduce this. As soon as I click on a chat head with an unread message, the badge is cleared. Are there some specific steps beyond the ones in the description that would cause this?
