### ISSUE TITLE
RELEASES-x64 - huh?

### ISSUE THREAD

**Issue by BuckminsterEmptier** [OpenBazaar/openbazaar-desktop#704]
Brief Description: 

Go to this page:
https://github.com/OpenBazaar/openbazaar-desktop/releases/tag/v2.0.7

What is the RELEASES-x64 page supposed to be?  I expected a list of sha256 sums for all of the 64 bit files (like openbazaar2_2.0.7_amd64.deb)  Instead I see:
`
<U+FEFF>00F54AC85BFF6088344091347D74750F5C4359B3 OpenBazaar2-2.0.7-full.nupkg 141298996`

Also don't you sign these files with PGP?

**Comment by hoffmabc** [comment]
The <U+FEFF> is the BOM mark for UTF-8 and must be appended by electron-windows-installer package we use to create Windows builds. The RELEASES files are only for Squirrel on Windows and for use in the auto-updater. 

Release will be pop signed and we have a new way to verify binaries if you choose to do so in the /verify folder located here. https://github.com/OpenBazaar/openbazaar-desktop/tree/master/verify

I'm going to close this as I don't see this as an actionable bug at this time.
