### ISSUE TITLE
"Message for vendor" not being displayed on Discussion

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#721]
v2.0.8 (already seen on older versions)

![no first message](https://user-images.githubusercontent.com/10789865/29738323-ff213578-89f5-11e7-915b-4f52c0627850.png)

On some stores, "Message(s) for vendor" is/are not being shown on Discussion tab on Order Details, as expected. I don't know if they arrived or not. I've seen this problem on some stores, but not every store.

**Comment by jjeffryes** [comment]
If you close the app, then open it again and look at the same order, do the messages appear?

When the message was sent, were both the seller and buyer online? Or only the buyer?

**Comment by rhcastilhos** [comment]
No, they don't appear after restarting.

Buyer was online. Seller I don't know, but I believe they were offline.

I see this behavior on the following stores:
QmSbxq9EA3y3ye4EV8hpzCdN9KHS7wGK7wRV5h9fWrwdLe
QmTJrqtMZXvUts7Ta5Wa9cBDcRTfwmPQ8eYxx85ET9XSA9

**Comment by jjeffryes** [comment]
This is working correctly, it just takes a while for the server to return the message. 

The delay is being tracked as a server issue here:

https://github.com/OpenBazaar/openbazaar-go/issues/669
