### ISSUE TITLE
Order Summary doesn't inform who opened a dispute

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#725]
Either buyer or vendor can open a dispute. Order Summary doesn't inform who opened a dispute.

![whodisputed](https://user-images.githubusercontent.com/10789865/29747134-dc78928e-8ac5-11e7-94a3-fa0c79afae31.png)

**Comment by rmisio** [comment]
I believe the designs have this in place and I thought this was already happening. Might be a bug. I'll look into it.

**Comment by morebrownies** [comment]
Yeah let's make sure the text includes the party that opened the dispute:

![screenshot 2017-09-11 10 12 48](https://user-images.githubusercontent.com/13066886/30287411-d0120c9e-96d9-11e7-86e4-52d108808649.png)

**Comment by rmisio** [comment]
This is due to the server not sending the relevant data.

https://github.com/OpenBazaar/openbazaar-go/issues/684
