### ISSUE TITLE
About OpenBazaar page not opening on first load

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#726]
When program is loaded for the first time, about OpenBazaar page doesn't open when clicking on its link in menu. If program is closed and reopened, it starts working.

V. 2.0.9

**Comment by jjeffryes** [comment]
We haven't been able to reproduce this.

**Comment by rhcastilhos** [comment]
I have reproduced it again on 2.0.10 on Windows and MacOs. 

You have to do a clean install, create a store, go to menu and click on "About OpenBazaar" item.

When you start the software for the second time, it doesn't happen.
