### ISSUE TITLE
Free shipping filter not working

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-desktop#740]
Looks like the client might not be detecting ALL in the free shipping field in the index

**Comment by rmisio** [comment]
Are you talking about on people's store?

**Comment by cpacia** [comment]
yeah

**Comment by drwasho** [comment]
### Listing has free shipping
<img width="979" alt="screen shot 2017-09-07 at 12 51 09 pm" src="https://user-images.githubusercontent.com/3887694/30143956-b4364960-93cb-11e7-8563-1160f2033111.png">

### No free shipping label in the 'Store'
<img width="792" alt="screen shot 2017-09-07 at 12 51 15 pm" src="https://user-images.githubusercontent.com/3887694/30143975-d41c5bde-93cb-11e7-8ed1-a25edfc60a07.png">

### Listing isn't filtered
<img width="977" alt="screen shot 2017-09-07 at 12 51 18 pm" src="https://user-images.githubusercontent.com/3887694/30143984-e82686cc-93cb-11e7-936b-4d7fdb49b19d.png">

**Comment by rmisio** [comment]
I started on this one earlier today and got sidetracked. I'll look to get back to it tomorrow.

**Comment by jjeffryes** [comment]
This is fixed.
