### ISSUE TITLE
Thousands separators in numbers [several places]

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#747]
I've noticed thousands separators missing on some numbers in the UI.

User Page Header
![image](https://user-images.githubusercontent.com/45482/29971585-ca99e88a-8ef6-11e7-9e21-52c914dbe0e3.png)

Search Results
![image](https://user-images.githubusercontent.com/45482/29971599-d5ba7b44-8ef6-11e7-8521-bce2220ded76.png)

**Comment by morebrownies** [comment]
+ 1

**Comment by rmisio** [comment]
@morebrownies What the heck is that? ^^^

**Comment by hoffmabc** [comment]
+1

**Comment by morebrownies** [comment]
Apparently typing `+ 1` with a space makes it a bullet

**Comment by rmisio** [comment]
Dev note:

For the the numbers in the tabs, we should run them through the `abbrNum` utility function, which will ensure they never get too long (e.g. 10, 345 would display as 10k, 450,123, 445 would display as 450m).

For the store listing count, we should display it with the separator in a localized way.
