### ISSUE TITLE
Notification says someone has purchased seconds ago, but it was days ago

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#757]
v.2.0.9

This happens when a sale is done with vendor offline.

When vendor goes online again the following notification appears: 
![notification](https://user-images.githubusercontent.com/10789865/30000679-12dbcd2a-904b-11e7-8c5e-8440ee3b6908.png)

I understand that it means that notification has just arrived a few seconds ago, but when you read the sentence it seems that someone has just bought something. On this case, customer had bought 4 days before.

![pokemon](https://user-images.githubusercontent.com/10789865/30000684-379e9322-904b-11e7-98a3-9dce90e648f5.png)

**Comment by rmisio** [comment]
This is really a server issue and should be filed as a suggestion in the [server repo](https://github.com/OpenBazaar/openbazaar-go). The timestamp is set on the server.

**Comment by rhcastilhos** [comment]
ok. I opened in #664 in server repo

**Comment by rmisio** [comment]
Thanks @rhcastilhos.
