### ISSUE TITLE
Allow for free listings

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#76]
(This was briefly discussed in the partners call.) There are several use cases for allowing vendors to list listings that do not cost any Bitcoin. These include:
- Free samples
- [Freecycling](https://en.wikipedia.org/wiki/Freecycling)
- Super low barrier-to-entry testing
- (possibly) Barter

Free listings, not having a corresponding Bitcoin payment, do not need a moderator to moderate a Bitcoin transaction. Free listings would follow the same purchase flow as paid listings, with buyer orders being immediately 'funded'.

The buyer and seller would still be able to make use of OpenBazaar infrastructure around transactions, including ratings, chat, transaction history, channels, etc.

**Comment by morebrownies** [comment]
Free listings could especially be useful for digital goods too. Offering some music/content for free, while also having premium content seems like a pretty solid use case for this feature.

**Comment by jjeffryes** [comment]
This has been discussed a few times, but we've always concluded it's not something we want to add to the product. I'm closing this issue for now.
