### ISSUE TITLE
Cleanly separate out vendors and moderators

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#77]
In the current OB 1.0 setup, a node can simultaneously be a vendor and a moderator. In practice, nodes that are both a vendor and a moderator are either:
- A great vendor, but a 'below-average' moderator
- A great moderator, but an amateur vendor

It is so easy for a vendor to say "sure, I'll be a moderator, my fee is X%". They will usually neglect their moderator duties, such as having a moderator policy, advertising its moderator services, deal with disputes promptly, stay online 24/7, etc. It is also confusing for buyers to see the vendor information and moderator information mashed up into a single page.

Take a great store, [Yabisi Kakaw](https://duosear.ch/@yabisikakaw). It is also a moderator node, but neither the Description nor the About section has any mention of it, or the moderator policy. Indeed, such moderator information would distract prospective buyers. Yabisi Kakaw is an example of an "accidental moderator".

I also feel that the design of moderator nodes has to be tailored to moderators. Take our most professional moderator, [BazaarGuard](https://duosear.ch/@bazaarguard). It has hijacked the "About" section to stuff its moderator Terms and Conditions. Notice also that BazaarGuard has no listings, as that would be confusing.

**Comment by michaelfolkson** [comment]
There's a few questions here:
1) Should a node be able to simultaneously be a vendor and a moderator? I'm leaning towards yes as I don't think a store should have to spin up a new node if someone wants to use their moderator services.
2) Should it be this easy to sign up to be a moderator? I definitely think no. The list of moderators is full of examples that will most likely not carry out their moderator duties as seriously as say BazaarGuard.
3) Should there be separate pages presented to the viewer depending on whether they are wanting to look at the vendor profile or the moderator profile of say, Yabisi Kakaw? I think Yes. Or at the very least much better separation of the descriptions on the same page. An empty moderator page would show that Yabisi Kakaw, though signed up, isn't devoting too many resources to their role as a potential moderator.

**Comment by michaelfolkson** [comment]
Re 1) I'm undecided. Perhaps in long term independence / clean separation between vendors and moderators would be good feature. However, in short term I think a vendor being able to bootstrap their reputation as a trusted seller to sell moderator services is beneficial to the network.

**Comment by wds4** [comment]
On 1) and 3) I would think of two alternatives: 1) a node can be simultaneously a regular user, vendor, and / or moderator, with different layouts for each one; or 2) a node cannot be all of them simultaneously; but in this case, I would want the ability to link my various nodes via some sort of handshake mechanism (which I imagine would not be too difficult) so that I can bootstrap reputation from one to the other

**Comment by wds4** [comment]
On 2) This highlights the need for a reputation system for moderators. Users need easy to use tools to stratify the serious moderators from the not-serious ones who just signed up and forgot about it. In the meantime while that is being built, how would you make it harder to sign up?

**Comment by morebrownies** [comment]
We definitely haven't nailed the experience around multiple user roles quite yet. There are however a few improvements coming in 2.0:

1) It is more difficult to become a Moderator in 2.0. There are more required form inputs to fill out and we also have the user double confirm they understand what it takes to become a high quality moderator (with a link to more info on OpenBazaar.org). The additional friction should deter casual users from becoming moderators. 

2) On the user's about page, if they are a Moderator, we now output a section with their price, tos and add as moderator button.

This should help a bit in the short term, but we'll also need to circle back once we have more time.

**Comment by jjeffryes** [comment]
I think we've resolved these issues as much as we plan to within the 2.0 release.
