### ISSUE TITLE
Maybe Fulfill Order Password Field Should be Viewable/Require Confirmation

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#778]
This is more of a tweak, but we require the merchant to enter a password that is obscured and not confirmed/validated. They could easily type a bad password and not even know if it was typed properly. This could just be a nuisance. I'd suggest we either show the password or have an option to view it to confirm.

![image](https://user-images.githubusercontent.com/45482/30088196-d885f77a-9272-11e7-961a-948dbe052bc4.png)

**Comment by hoffmabc** [comment]
Ironically we actually show it clear text on the next page.
/facepalm

![image](https://user-images.githubusercontent.com/45482/30088225-f942be94-9272-11e7-998f-151af37d289b.png)

**Comment by rmisio** [comment]
@morebrownies Should we just show it in the clear on the form?

**Comment by rmisio** [comment]
> Ironically we actually show it clear text on the next page.
> /facepalm

It's also in the contract and viewable by the moderator. /facepalm

**Comment by morebrownies** [comment]
> Ironically we actually show it clear text on the next page.

ah, let's change the input to plain text for now.  We can circle back and improve on this if people report it being an issue.
