### ISSUE TITLE
Clicking the "Browse Moderators" button causes the server to panic

### ISSUE THREAD

**Issue by tyler-smith** [OpenBazaar/openbazaar-desktop#784]
Brief Description: When clicking the button the server dies and the client disconnects

Operating System (OS and version): OSX
OpenBazaar version (shown on `About OpenBazaar` page in menu): v2.0.10
Hardware: macbook pro

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce):  Always

Steps to reproduce:
1. Go to Settings > Store
2. Click "Browse Moderators"

Observed Behavior:

Server dies

Expected Behavior:

Server doesn't die

**Comment by rmisio** [comment]
Would you mind reporting this in the server repo? I think it would be helpful if you included the server stack trace.

**Comment by jjeffryes** [comment]
I'll close this as soon as it's opened as a server issue.

attn: @tyler-smith

**Comment by jjeffryes** [comment]
This is being tracked on the server https://github.com/OpenBazaar/openbazaar-go/issues/670
