### ISSUE TITLE
New Minimum Size Needed for App (Resizing Cuts off UI Elements)

### ISSUE THREAD

**Issue by jashot7** [OpenBazaar/openbazaar-desktop#787]
Currently, resizing the app window to its smallest size cuts off various UI. Here are two examples, but there are others.

- [ ] Search Button Gets Cut Off
![search_cuts_off](https://user-images.githubusercontent.com/392798/30144076-0c1a8a6c-9357-11e7-986b-62f476dab4b3.gif)

- [ ] Triple Dot 'More' Menu Disappears
![triple_dot_disappears](https://user-images.githubusercontent.com/392798/30144090-1cd0b02a-9357-11e7-98c9-c6afcd663045.gif)

**Comment by morebrownies** [comment]
In the future, we'll want to add a responsive grid to avoid these type of issues. For the time being, it seems relatively low risk to keep as is.

**Comment by jjeffryes** [comment]
I'll close this since it's not a serious problem. Users aren't stopped from using anything they need and they can easily fix it by stretching the app to be bigger.

**Comment by morebrownies** [comment]
Yeah or they could temporarily close the chat panel
