### ISSUE TITLE
'Beta' Shows as a Button and Does Nothing

### ISSUE THREAD

**Issue by jashot7** [OpenBazaar/openbazaar-desktop#789]
![beta_button_does_nothing](https://user-images.githubusercontent.com/392798/30144135-4aceaa36-9357-11e7-92fc-4cb2cefa7852.gif)

**Comment by rmisio** [comment]
It's not supposed to do anything. It's just an indicator. @morebrownies Do you think others would also get tripped up by this?

**Comment by morebrownies** [comment]
Could we add a tooltip to it on hover/click with the text below?

"OpenBazaar 2.0 is currently in beta. Don't risk large amounts of Bitcoin and be sure to backup your wallet"
