### ISSUE TITLE
Notification Spam

### ISSUE THREAD

**Issue by jashot7** [OpenBazaar/openbazaar-desktop#792]
This has been confirmed to lead to a notification each time it occurs. 

![i_will_destroy_notifications](https://user-images.githubusercontent.com/392798/30145339-b540f480-935e-11e7-98d3-c2072f595774.gif)

**Comment by jjeffryes** [comment]
That's working as designed, though it's a poor design decision.

This is a server bug though, even if we prevented multiple short term clicking on the client a script could still run infinite loops of follow/unfollow.

**Comment by jjeffryes** [comment]
I've opened a server bug here. https://github.com/OpenBazaar/openbazaar-go/issues/668
