### ISSUE TITLE
You can run JS in Chat

### ISSUE THREAD

**Issue by jashot7** [OpenBazaar/openbazaar-desktop#793]
![run_js_in_chat](https://user-images.githubusercontent.com/392798/30145421-21756e92-935f-11e7-9a0d-56eb184ac6e0.gif)

**Comment by rmisio** [comment]
FWIW, I'm pretty sure the server sanitizes chat. It's just that your own message doesn't come from the server until you refresh. So.... yes, in this limited scenario you can run JS, but you'll only affect yourself.

**Comment by jjeffryes** [comment]
We should still prevent that, I think, so people don't tell other people "paste this code into your chat to get a discount on your order" and it does something malicious.
