### ISSUE TITLE
Chat Emoji Causes Borking

### ISSUE THREAD

**Issue by jashot7** [OpenBazaar/openbazaar-desktop#794]
On Mac, open the character viewer with command-control-space and enter non standard characters. Its easy to bork chat by entering them.

![sep-07-2017 00-03-13](https://user-images.githubusercontent.com/392798/30145551-fae294ac-935f-11e7-8fd0-511799d50854.gif)

**Comment by rmisio** [comment]
@jashot7 Is there a specific emoji you are using to cause this? I've tried a bunch of them (including some seemingly obscure ones) and I can't reproduce this.

@morebrownies Fellow OSser, does this happen for you?

**Comment by hoffmabc** [comment]
i haven't found one that does it

**Comment by jjeffryes** [comment]
We determined that this bug wasn't related to chat emojis, I'm going to close it until we can reproduce it and/or figure out what it was.
