### ISSUE TITLE
Improve the design of the installation splash screen

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#803]
Currently it looks something like this

<img width="770" alt="screen_shot_2017-09-06_at_9 48 54_pm" src="https://user-images.githubusercontent.com/13066886/30178426-b8502290-93bd-11e7-83cc-0e59b5ddeaef.png">

**Comment by morebrownies** [comment]
@hoffmabc do you know what dimensions the background image should be?

**Comment by morebrownies** [comment]
I can get you something new for it later today

**Comment by hoffmabc** [comment]
https://github.com/mongodb-js/electron-installer-dmg/blob/master/resources/mac/background.png

**Comment by rmisio** [comment]
for me, there's also a white vertical line on the left edge:

![image](https://user-images.githubusercontent.com/794517/30179048-eb4319ee-93bf-11e7-87d8-3f34c2434566.png)

**Comment by morebrownies** [comment]
Let's try this @hoffmabc 

![background](https://user-images.githubusercontent.com/13066886/30182092-712f573e-93ca-11e7-8119-141ae3185642.png)
