### ISSUE TITLE
Open in Wallet does not pre-populate the donation address

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#805]
This should pre-populate the TO: field I think.

![image](https://user-images.githubusercontent.com/45482/30183068-0d3d4746-93e7-11e7-8366-ecf00e26dbe9.png)

![image](https://user-images.githubusercontent.com/45482/30183089-1e6c28f2-93e7-11e7-8de3-c9cd4f48d828.png)

**Comment by rmisio** [comment]
@morebrownies Should we just make the wallet "to:" field always have the donation address filled in by default? It would simplify things, right? ;)

**Comment by morebrownies** [comment]
🤑 🤑 🤑 🤑 🤑 🤑
