### ISSUE TITLE
Bring in a bitcoin font.

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-desktop#81]
Bring in a micro-font that will give us the Bitcoin symbol, a la:
http://www.righto.com/2015/02/how-to-display-bitcoin-symbol-using_14.html

**Comment by cpacia** [comment]
ACK

**Comment by rmisio** [comment]
According to internetslang.com:

![image](https://cloud.githubusercontent.com/assets/794517/19707627/8a46a21e-9acd-11e6-98b9-051fc9d3aaff.png)

So, I really don't know what that response means, lol.

**Comment by hoffmabc** [comment]
hahaha disgust frustration?

**Comment by rmisio** [comment]
I like the Nice to Have label. It will come in handy in making sure we are working on issues in priority order.
