### ISSUE TITLE
Missing Bitcoin URI in QR codes of wallet and listing

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#819]
QR codes for payment (listing) and receiving bitcoins (wallet) should have a link pointing to a Bitcoin URI (like: bitcoin:12A1MyfXbW6RhdRAZEqofac5jCQQjwEPBu)

**Comment by jashot7** [comment]
PR is in for this: https://github.com/OpenBazaar/openbazaar-desktop/pull/1380

**Comment by jashot7** [comment]
This was fixed, but its just come to the team's attention that not all coins implement [BIP21](https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki).  This is only really useful for BCH and isn't supported by all coins, so we're going to hold off on merging this 'fix'.

**Comment by jjeffryes** [comment]
Per Jason's comment above, we will not be fixing this issue in the near term.
