### ISSUE TITLE
Display default search provider first in search bar

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#823]
This issue is about displaying the default search provider in the search bar of the discover pane first. (When there is no default selected, the default order is OB1, Duo, etc. The order is only updated when the user revisits the discover pane the next time.)

Showing the default search provider first in the search bar is only natural from a user experience point of view, especially as the list of providers grows over time. It is also a step towards fair handling of the search providers in the reference client (to avoid constantly prioritising OB1) and was agreed upon in a private discussion with @hoffmabc on August 31st.

**Comment by hoffmabc** [comment]
Maybe I'm confused but I'm not sure how this would be done differently right now.

![image](https://user-images.githubusercontent.com/45482/30241026-9bb404f2-9549-11e7-8ac1-609a7b5a74d2.png)

**Comment by hoffmabc** [comment]
Clearly none is selected and no default selected which is what we agreed to is it not?

**Comment by rhcastilhos** [comment]
He means that DUO icon always stays on the right side of OB1 icon, even if it has been selected as default.

I think that when there is no default selected yet, their order of display should be randomized (just like web browsers do when they show their available search providers).

**Comment by hoffmabc** [comment]
We've already discussed the randomization piece. So the order will remain fixed. I'm not sure I see the value of moving the icons after selection since we already have a selected indicator.

**Comment by hoffmabc** [comment]
Icons are clearly greyed out and the default one is brought to forefront. Seems very confusing if the icons are switching around.

**Comment by rhcastilhos** [comment]
I agree that randomization on search page is confusing.

It would be better to do as web browsers do: user selects his default search provider on onboarding, and the onboarding list of providers is randomized.

**Comment by hoffmabc** [comment]
Just to catch you up the idea at this point in time is that realistically there are only two search engines and only two reliable ones at the moment so randomizing especially once we start adding in lower tier less trustworthy sources would be bad for users. 

We won't rehash the argument about leveling the playing field for all comers over OB1. We've already done this and the short-term compromise was to do it this way. 

My only issue here with this request is that it seems silly to make a big deal of switching two icons and kind of a waste of time to develop this when there are more important pressing issues.

**Comment by JustinDrake** [comment]
The issuis is about what happens once a selection has happened, not before the selection has happened. Here is the relevant part of the private Slack discussion with @hoffmabc. (Happy to share more about this discussion if the screenshot does not provide enough context.)

<img width="378" alt="screen shot 2017-09-10 at 10 14 50" src="https://user-images.githubusercontent.com/731743/30247664-37a3bade-9611-11e7-9c71-600fd880bef6.png">

I understood that the search bar would follow the user's selection once the selection has been made.

**Comment by tyler-smith** [comment]
I'm not a UX guy but having the selected provider first in the list seems most natural to me as a user. Gray the others out too, but have the selected one first. Just my 0.00000002btc

**Comment by hoffmabc** [comment]
@jjeffryes just change it to whatever he wants so we can move on. I'm tired of the little change requests to this.

**Comment by jjeffryes** [comment]
I think the current design is fine. We can put considering changes to it in the backlog, and schedule that along with other features we need to work on.
