### ISSUE TITLE
Feature Request: Full Screen on Maximize

### ISSUE THREAD

**Issue by ekerstein** [OpenBazaar/openbazaar-desktop#824]
This is a minor user interface annoyance. The standard behavior on mac os is that the green "maximize / full screen" button takes you directly into full screen view.

![maximize](https://user-images.githubusercontent.com/6055508/30238148-58085864-950f-11e7-8c6b-a640644a6057.png)

However, on OB clicking the green button simply expands the window without taking you to full screen. You have to go to View -> Toggle Full Screen to do that.

This deviates from standard mac behavior and may be a minor annoyance to new users, as it was for me.

**Comment by jjeffryes** [comment]
This was closed by #905
