### ISSUE TITLE
Feature Request: Shipping option being applied according to the number of items on purchase

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#828]
Now, since there is no shopping cart, there is no way to buy two different products on the same purchase (unless vendor creates a listing with multiple products).

Also, buying multiple items of the same listing charges multiple shipping fees (unless vendor creates special shipping options, like "Shipping in USA for 3 items").

Selling of multiple products on the same purchase should be facilitated.

There could be a new field on shipping option ("Apply this shipping option to sales with N items") that considers that shipping option valid only when sale has N items.

This way vendor can create a shipping option that sets free shipping (to countries X, Y and Z) when more than 5 items are bought on the same purchase. Or vendor can set a 50% discount in shipping when 3 items are bought.

This is related to #694.

**Comment by jjeffryes** [comment]
We have  some of the code in place to handle complex shipping rules like this, and plan to add the rest in the future. 

Since this is already on the roadmap, I'm going to close this issue.
