### ISSUE TITLE
Cosmethic Issue: Tray Icon looks as doubled in Gnome tray bar

### ISSUE THREAD

**Issue by M0Rf30** [OpenBazaar/openbazaar-desktop#829]
Brief Description: On application start, tray icon looks strange as in attached image

Operating System (OS and version):  Arch Linux
OpenBazaar version (shown on `About OpenBazaar` page in menu):  2.0.11-git
Gnome version: 3.24.2 

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always I think

Steps to reproduce:
1. Install the package
2. Start the app

Additional info (links, images, etc go here):
![Gnome tray](https://user-images.githubusercontent.com/491117/30248259-87fe8208-9624-11e7-9239-39d6f22b6722.png)

 And a question: will defaultListing.png be added? because for now debug console shows a missing image and I could open another issue

**Comment by jjeffryes** [comment]
@hoffmabc do you know what could cause this?

@M0Rf30 good catch on the missing defaultListing.png image. It was renamed to defaultItem, and we missed changing it in one file. That will be fixed.

**Comment by M0Rf30** [comment]
As concerning the icon I will investigate as soon as possible and give you back feedbacks

**Comment by hoffmabc** [comment]
I can check on this one.

**Comment by hoffmabc** [comment]
What's your screen resolution?

**Comment by M0Rf30** [comment]
1920x1080
I've tried other resolutions and same issue (both on Wayland and X sessions). I've noticed that there is a reference only for openbazaar-mac-system-tray.png in main.js code

**Comment by hoffmabc** [comment]
It is testable without building but we may have to decode the asar that the app uses. I'll check it out.

**Comment by M0Rf30** [comment]
extract|e <archive> <dest> 

just as remainder

**Comment by M0Rf30** [comment]
I've tried to replace openbazaar-mac-system-tray.png with with icon.png and it works very well
![schermata del 2017-09-13 13-53-21](https://user-images.githubusercontent.com/491117/30376000-ee0decce-988a-11e7-9e79-49758d785f7b.png)

**Comment by M0Rf30** [comment]
Same error for task manager icon
main.js reference to openbazaar-icon.png that doesn't exists. So gnome task manager shows a generic and ugly icon

**Comment by hoffmabc** [comment]
ok thanks. i'll submit a fix for that.
