### ISSUE TITLE
XSS from search provider

### ISSUE THREAD

**Issue by m33964zkrh** [OpenBazaar/openbazaar-desktop#832]
The client will execute JavaScript provided by the search API.

Example:
```
"options":{
  "test":{
    "label":"<script>alert(\"test\");</script>"
    }
}
```

This may or may not have security implications for the user. Could it be used to deanonymize Tor users?

Tested on v2.0.11.

**Comment by tyler-smith** [comment]
Thank you for the report. I will make sure we follow up ASAP.

**Comment by cpacia** [comment]
Definitely should not be allowed but I'm not sure how a properly working search API would get unsanitized data to start with if it's getting it from the openbazaar-go server.

**Comment by tyler-smith** [comment]
It would require the search provider to be either malicious or compromised, but that's still pretty bad. Ideally people would require 0 trust in providers.
