### ISSUE TITLE
moderator formatting

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-desktop#840]
Some (not all) display like this 

![image](https://user-images.githubusercontent.com/4504708/30295746-b0fcc476-970f-11e7-905d-fe240984efee.png)

**Comment by jjeffryes** [comment]
That image is displaying correctly, it's centered and fills the circle.

Here's the full image:

![image](https://user-images.githubusercontent.com/1584275/30297509-fbd0feb2-9715-11e7-97a0-82818080ac11.png)

**Comment by cpacia** [comment]
I wasn't referring to the image in the circle but rather that it overlaps with the name and description.

**Comment by cpacia** [comment]
Example of one that is formatted correctly 
![image](https://user-images.githubusercontent.com/4504708/30297640-6ac7ce72-9716-11e7-922d-edc632ac2c80.png)

**Comment by cpacia** [comment]
I think it's long descriptions that cause the text fields to shift to the left.
