### ISSUE TITLE
Overall user rating is not updating

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#846]
I have a listing that received one 5 star rating.

![screenshot 2017-09-11 17 05 57](https://user-images.githubusercontent.com/13066886/30302080-90da4764-9713-11e7-9d17-6d16f224b726.png)

My overall user rating is still displaying 0 though

![screenshot 2017-09-11 17 05 18](https://user-images.githubusercontent.com/13066886/30302085-9812e23e-9713-11e7-8e23-3a2365ca2131.png)

I've seen the same issue across multiple stores.

**Comment by morebrownies** [comment]
Displays 0 on the user card as well

![screenshot 2017-09-11 17 08 12](https://user-images.githubusercontent.com/13066886/30302121-cfa6325a-9713-11e7-8aa7-ab12db91e110.png)

**Comment by jjeffryes** [comment]
Have you published since then?

The only ratings that are available are the ones since the last time that node was published to the network.

**Comment by morebrownies** [comment]
Yes, no luck.

`[[OB-SERVER]] [STDOUT] [0m17:47:57.945 [Publish] [INFO] Published zdj7WmxRjsSqYhJpLctUGx4YaJJyvBPVp5GUdE5wTESmB4fcH to IPNS`

**Comment by rmisio** [comment]
@jjeffryes Do you know whether this is a server or client issue? If the former, I think we could close this.

**Comment by jjeffryes** [comment]
It's a server issue, tracked here:
https://github.com/OpenBazaar/openbazaar-go/issues/696
