### ISSUE TITLE
The "data has changed" alert doesn't stand out enough from other elements. People are missing it and not knowing they need to refresh.

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#851]
Here's how it currently looks:

![screenshot 2017-09-12 10 12 34](https://user-images.githubusercontent.com/13066886/30339139-e93e0528-97a2-11e7-9c41-7043ce6a5e2b.png)

**Comment by morebrownies** [comment]
These small changes will help the alert stand out more:

1. Add icon to left of text
2. Bold the text
3. Make the refresh link green

![screenshot 2017-09-16 22 30 00](https://user-images.githubusercontent.com/13066886/30523047-f8385ee4-9b8e-11e7-80c0-61c68fd82ed9.png)

**Comment by jjeffryes** [comment]
Can the border be darker than the borders behind it? That would really help separate it from the background, I think.

**Comment by rmisio** [comment]
@morebrownies Should we use the flat ionic icon instead?

![image](https://user-images.githubusercontent.com/794517/30757287-fbdfae06-9f82-11e7-93d8-e32d1d1ca5ed.png)

What you have there is not theme-able unless you provide it as an SVG, in which case it's probably theme-able with a little work.

**Comment by morebrownies** [comment]
We could use that @rmisio 

It is possible to color the icon yellow, right?

**Comment by jjeffryes** [comment]
It's possible to color the icon, yes.

**Comment by rmisio** [comment]
> It is possible to color the icon yellow, right?

Yes, we could color the ionic one a flat color. Now that I think of it, I think that's what I'm doing in the wallet (maybe on a stuck transaction)... so I'll match that.
