### ISSUE TITLE
Feature Request: Use System Window Decorations

### ISSUE THREAD

**Issue by prof7bit** [OpenBazaar/openbazaar-desktop#854]
Brief Description: 

Operating System (OS and version): 
  Kubuntu 16.04, KDE with dark theme and dark oxygen decoration.

OpenBazaar version
  client 2.0.11, server 0.9.1

Hardware: 
AMD 64

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Observed Behavior:
Client produces its own ugly and incomplete window decorations, turning off normal Window manager decorations.

Expected Behavior:
Client should behave like any other application too, should not sabotage the desktop look & feel and let the window manager do its job.

Fixing this would enable proper and native window functionality and look&feel on the desktop (move, resize, fold, pin, stay-on-top, system menu, etc.) and it would also make it fit into the desktop theme much nicer instead of being completely out of place and causing only problems. It would also allow the developers to concentrate on the real problems instead of spending time trying to half-bakenly re-implement what would already be there and perfectly working on every desktop environment. 

If for some reason you cannot entirely remove this ergonomic abomination because the dev team has already lost eyesight, thinks it looks nice and insists on keeping it then please at least give the users the **option** to disable it in the settings and let us use our own properly working window decorations instead.

Thank you.

**Comment by hoffmabc** [comment]
I appreciate your feedback, but most likely this would be extremely low priority and is not one of the goals of this repository as a reference implementation. If we have to somehow support every single look and feel on Linux distros we'll be supporting that and nothing else. We don't currently use a rendering framework that would easily enable us to implement this either.

It is FOSS though so if you want to take a stab at it we would be glad to take a look at the Pull Request.

Thanks!

**Comment by prof7bit** [comment]
I think there is a misunderstanding.

I am **not** asking to implement any different look and feel, actually I'm asking for the exact opposite: I'm actually asking to please **stop** trying to impose a fixed look and feel onto the window borders and title bar, instead remove this and all associated code entirely, lean back and let the Window manager handle all this like it is supposed to be and every other application does so too. 

Doing so would free up developer resources while at the same time drastically improve usability and acessibility without having to write and maintain a single line of code because drawing window borders and title bars, handling mouse and keyboard(!) events to interact with the window and its titlebar buttons is already implemented and perfectly working somewhere else: Its implemented in the window manager! There is no need to implement it again with less functionality and suboptimal desktop integration. Please just remove the borderless flag and use a normal desktop window with title bar and resize border and don't try to re-implement all this yourself, you can't mimic the behavior of every desktop, so just don't even try it, remove all this code and let the desktop environment handle all this instead.

PS: why is it marked as "help wanted"? I actually would categorize this as "feature request"

**Comment by rmisio** [comment]
So we understand... is that gray top-bar the extent of what you're looking for?

![image](https://user-images.githubusercontent.com/794517/30386956-01127f22-9860-11e7-817e-f8b695f3221e.png)

**Comment by hoffmabc** [comment]
Yeah I mean I think the overall reason we didn't do this was that we have a custom menubar so we had to incorporate the window management controls in there too. He's asking us to abstract out the windows controls and let the OS take care of it.

**Comment by rmisio** [comment]
After talking to the team, the reason we don't show the native app bar is primarily for aesthetic reasons. The feeling is that it looks and feels nicer to have the controls embedded into our custom app bar. (of course, that is debatable)

Also, from our UX dev:

> Very few apps on mac seem to be using the standard native title bar at this point. Chrome doesn't use it. Spotify doesn't use it. Slack doesn't use it. Sketch doesn't use it. At the minimum, we should ensure we have the basic functionality covered that the standard title bar provides, but I don't think there is any reason we must use it beyond that.

Going to close this as `won't fix`. If you really want it, you could run the client from source and comment out the `frame: false` line in main.js when creating the BrowserWindow instance. (I understand that may be a bit of a pain to do)
