### ISSUE TITLE
Ampersand in Shipping Option Title Makes Listing Unpurchaseable

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#857]
Brief Description: 

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce):  Always

Steps to reproduce:
1. Create a listing with shipping option called "North America & South America"
2. Have someone try to purchase the listing

Observed Behavior:
![image](https://user-images.githubusercontent.com/45482/30384342-0d227eb8-9872-11e7-84c2-0921fbdb0f44.png)

Expected Behavior:
I can purchase the listing.

**Comment by jjeffryes** [comment]
@cpacia in the data returned from ob/listing, the ampersand is \u0026amp; instead of &.

That doesn't seem to happen with other characters I've tried.

Can that be fixed in the API? My assumption is that's what causes the error, when it's sent it's sent as &amp;

**Comment by jjeffryes** [comment]
This was fixed on the server.
