### ISSUE TITLE
User link in Dispute Notification says undefined

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/openbazaar-desktop#858]
![image](https://user-images.githubusercontent.com/45482/30389058-d1d3767e-987f-11e7-9a87-4bf03935e46d.png)

Clicking the peer ID of the user in these notifications gives you undefined.

![image](https://user-images.githubusercontent.com/45482/30389079-e2e7e5f8-987f-11e7-85c8-7cf6276cfa02.png)

**Comment by jjeffryes** [comment]
@rmisio can you take a look at this?
