### ISSUE TITLE
Avoid silently ignored errors

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#86]
As a general comment, the OB1.0 client has been misleading with silently ignored errors. For example, if there was an error loading listings from a store, the client would say "No listings". But there is a huge semantic difference between "No listings" and "Cannot load listings".

Exposing errors to users achieves two valuable things:

- It is good communication with users
- It makes issues/bugs bubble up faster, and easier to report

![screen shot 2016-11-08 at 11 49 06](https://cloud.githubusercontent.com/assets/731743/20097993/5eb090ba-a5a9-11e6-9354-dfed196eaeaf.png)

**Comment by rmisio** [comment]
Yeah, I agree with that and point noted. Going to close this issue as it's a bit too broad. However, should you notice a specific case where we are doing this poor practice, be it v1 or v2, please log a specific issue for that case.
