### ISSUE TITLE
Change required input asterisks from green to red across the application

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#860]
A few users have reported issues seeing which fields are required, possibly because the asterisks are green. Red is more common and will stand out more.

**Comment by rmisio** [comment]
You sure this is what you want?

![image](https://user-images.githubusercontent.com/794517/30398184-4f22aa56-9884-11e7-8d8b-f68a4bc9ceaf.png)

**Comment by morebrownies** [comment]
Yes sir. We should do it across all forms too.
