### ISSUE TITLE
Implement New Fee API [Draft]

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#865]
## User Story
As a user, I want to see an accurate estimate of the fee I will need to pay before paying from my internal wallet. If the purchase plus the fee is more than I have in my wallet, I want to be prevented from making the purchase instead of waiting for an error from the server. 

## Functional Requirements
- [ ] The way the client handles fee estimates will be updated to match the new API.
- [ ] The total estimated fee for that transaction would be shown.
- [ ] If the wallet doesn't have enough for the purchase (not counting the fee), show the user a message that they must add X plus the estimated fee to their wallet (without specifying the fee). 
- [ ] If the wallet has enough for the purchase, but the API returns an insufficient funds error, tell them they need to add enough to cover the fee (without specifying the fee).
- [ ] if the wallet returns a dust limit error, show a message explaining to the user they transaction is below the dust limit.
- [ ] in the receipt area before the pay button is clicked, show the current fee level. Clicking on the fee level will open settings to the fee level so they can change it.
- [ ] add the same functionality to the wallet when sending funds.

![image](https://user-images.githubusercontent.com/1584275/30445278-7cfbdc3e-9953-11e7-89ee-1588a45b11d2.png)

## Suggested API Changes
Send: 
```
{
  amount: 1000 // in satoshis or btc?
  feeLevel: priority/normal/economic  // send one of these
}
```

Receive: 
```
{
  fee: the fee in satoshi
}
```

Fail: http code 500
```
{
  reason: 'insufficient funds' // or any other reason
  errorCode: 123456 // six-digit error code. 
}
```

**Comment by rmisio** [comment]
You would also need to send in the fee level in addition to the amount if you want to get the transaction size, since that would affect the total amount and potentially the number of inputs.
