### ISSUE TITLE
[Request] Publish File Hashes for Official Releases

### ISSUE THREAD

**Issue by danielmcclure** [OpenBazaar/openbazaar-desktop#868]
Brief Description: 

If you also signed md5/sha256 hashes along with your compiled releases users could be sure that they have downloaded an official release of the software and it hasn't been tampered with or corrupted in any way which is important when working with ecommerce data. 

This is common practice for cryptocurrency focused applications dealing with sensitive data as seen below for:
- Bitcoin 14.2 Hashes
https://bitcoincore.org/en/2017/06/17/release-0.14.2/
- Ethereum Github Hashes
https://github.com/ethereum/mist/releases

**Comment by hoffmabc** [comment]
Check out the README here, we use the verify method used for Bitcoin https://github.com/OpenBazaar/openbazaar-desktop/tree/master/verify

You can validate the hashes here.

**Comment by hoffmabc** [comment]
I'm going to close this unless you need to open it back up.
