### ISSUE TITLE
User website url not wrapping onto two lines

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#869]
![screenshot 2017-09-13 19 05 43](https://user-images.githubusercontent.com/13066886/30408903-9fab1b5c-98b6-11e7-8635-641b77c18755.png)

**Comment by jjeffryes** [comment]
It should probably truncate, like the PeerID. I don't think people are going to be manually copying it, they'll click to open it.

**Comment by morebrownies** [comment]
good call
