### ISSUE TITLE
Create About Modal

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#87]
![image](https://cloud.githubusercontent.com/assets/1584275/20278313/3903182e-aa72-11e6-9fc0-8e3b3a875c66.png)

The About Modal is a modal that should be shown when 
- [x] the About link in the page navigation list is clicked. 
- [x] it is programmatically opened  (we don't have a use case where this would be triggered other than the About link currently, but it should still work).

Currently, there is no plan to have functionality to open the About modal to a specific tab.

When the About Modal is open, it does not change the address shown in the address bar. Like most modals, the About Modal is not recorded in history. 

**The About Modal should show the following elements:**
- [x] the current value of one Bitcoin in the user's fiat currency..
    - [x] if the user has selected BTC as their currency, the current value element is not shown.
- [x] a tab menu with the following tabs:
    - The Story
    - Contributors
    - Donations
    - Licensing
- [x] clicking each tab will show that tab section, and put an active indicator on the tab element.
- [x] The headline of the currently active tab.
- [ ] The version number of the client and server, in the format ("client X.X, server X.X"). The client version number can be retrieved from package.json. The server version should be in the settings data (an issue has been posted for this).
- [ ] A "Check for Update" button. This will activate the update code, and update the app if an update is available (stub this in for now, the functionality is not yet available). 
- [x] The logo of OpenBazaar, along with the text "OpenBazaar" and some icons. This is visual only, and has no functionality.
- [x] A close button. This will close the modal. The Escape key should also close the modal (these are both built-in functions of the base modal view).

**The tabs have the following elements/functionality:** 

**The Story**
- [x] The headline, "The Story of OpenBazaar". 
- [x] The main text in the modal (content TBD). This will be static formatted HTML text. (check with Jenn for this text)

**Contributors**
- [x] The headline, "Contributors". 
- [x] The main text area in the modal will have some text, and a list of the contributors to OpenBazaar.
- [ ] TODO later: when we implement an endpoint on openbazaar.org with dynamic contributor data, this section can be updated to pull from that endpoint instead.

**Donations**
- [x] The headline, "Donations". 
- [x] A QR code for the address to send donations to the OpenBazaar project. This can be supplied by Sam.
- [x] The same address in plain text.
- [x] Clicking on the address will add it to the user's clipboard. If the user clicks on the address and it is added to their clipboard, a message should be shown, similar to when the guid on the about tab of the user page is clicked (the same styles can be used).
- [x] A "Copy Address" button. Clicking on it will add the BitCoin address to the user's clipboard.
- [ ] A "Open in Wallet" button. Clicking on it will open the transaction in the app's internal wallet. (stub this in if the internal wallet hasn't been built. As of 12/12/16, work has not yet begun on the internal wallet).
- [x] A static text area is at the bottom.

**Licensing**
- [x] The headline, "Licensing". 
- [ ] The main text in the modal includes the MIT license, and a list of the libraries being used. 
- [ ] A link to our github repo.
- [ ] A list of the major libraries we use (look at package.json for a basis).

![image](https://cloud.githubusercontent.com/assets/1584275/20281842/1ec146ee-aa80-11e6-9910-1e17a933c8f0.png)

![image](https://cloud.githubusercontent.com/assets/1584275/20281862/35c871b4-aa80-11e6-9491-0191d0f585f3.png)

![image](https://cloud.githubusercontent.com/assets/1584275/20281803/edc88c78-aa7f-11e6-8636-516746e22504.png)

**Comment by rmisio** [comment]
> the current value of one Bitcoin in the user's fiat currency.
> if the user has selected BTC as their currency, the current value element is not shown.

This is done by obtaining the user's local currency from app.settings and then (if the local isn't BTC) obtaining the "value of one Bitcoin in the user's fiat currency" from getExchangeRate() in the currency.js module.

**Comment by rmisio** [comment]
For discussion:

> The version number of the app. It's assumed that the client and server will have the same version number, so only one needs to be displayed. The version number can be retrieved from package.json.

> A "Check for Update" button. This will activate the update code, and update the app if an update is available.

Should these things happen for all versions of the app, or just the bundled ones? A new wrinkle in v2, is that we have a client only bundle (as of now the client code has no way to detect that specific guy).

**Comment by jjeffryes** [comment]
That's a good point, we should probably do like we do in v1 and have the server version returned by the settings API and shown separately. That way people with remote servers will know if they are using a server that is out of sync with the client version.
