### ISSUE TITLE
Display a spinner when listing photos are loading

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/openbazaar-desktop#875]
When a listing photo is loading, it displays as an empty white card, and it's not clear if it's loading or doesn't have a photo

![screenshot 2017-09-14 12 50 11](https://user-images.githubusercontent.com/13066886/30452669-54619c9e-994b-11e7-9fcc-ba13bbfcbd3a.png)

**Comment by jjeffryes** [comment]
A very simple way to do this would be to set the default background to an animated gif of a spinner. 

Then when the listing background is loaded it would cover it.

Currently the default background is blank.

**Comment by rmisio** [comment]
> A very simple way to do this would be to set the default background to an animated gif of a spinner.

That sounds easy enough, but wouldn't it be just as easy to have our standard svg spinner embedded in there (stacked below the photo)? That would keep the spinner consistent and it's also theme-able. Without theme-ability, there's a chance someone would choose a background color that would obscure the spinner if it's similarly colored.

**Comment by rhcastilhos** [comment]
Why do the listing photos take so long to load? Shouldn't they be downloaded from the search provider?

**Comment by rmisio** [comment]
> Why do the listing photos take so long to load? Shouldn't they be downloaded from the search provider?

No, they are downloaded for each node. We're wouldn't want to centralize the images and give the search provider the responsibility of hosting and serving them.

**Comment by rmisio** [comment]
In order to implement this in the way we've proposed above, we'd need to be quite sure we don't want to support transparent images or if we allow them in, we give them a solid background... which sounds reasonable. @morebrownies @jjeffryes What do you think?

**Comment by morebrownies** [comment]
I would think we would add a solid white background over the spinner after the photo loads @rmisio 

Is that possible without major scope changes?

**Comment by rmisio** [comment]
> I would think we would add a solid white background over the spinner after the photo loads 

That's not necessary because we could just specify a background color for the listing image, which would be easier than having to bind to image load events.

Sounds like we're not seeing a need to support image transparency, which means the semi-easy proposed solutions are a go.

**Comment by morebrownies** [comment]
Yeah that sounds good 👍

**Comment by jjeffryes** [comment]
Yeah, detecting when an image has finished loading is a lot more complicated than it sounds. We tried that and decided it wasn't worth it in v1. Solid backgrounds makes it easy.

@rmisio you don't think the spinner would keep repainting if it's covered up, do you? I don't think it would, but if it did for some reason that could be a performance issue.

**Comment by rmisio** [comment]
> @rmisio you don't think the spinner would keep repainting if it's covered up, do you? I don't think it would, but if it did for some reason that could be a performance issue.

hmmm.... I don't know. I would assume it did unless I had clear evidence it didn't'. And if it does, it's a problem.

I think we should probably have a chat on this one and see how important it is, since it could be a rabbit hole to do it the right way.

**Comment by morebrownies** [comment]
> I think we should probably have a chat on this one and see how important it is, since it could be a rabbit hole to do it the right way.

The current experience needs to be improved. Let's figure out level of effort required and we can build it into our backlog.

**Comment by rmisio** [comment]
ok, getting some performance thoughts from the community:
https://stackoverflow.com/questions/46333377/will-hidden-obscured-svg-animations-still-cause-browser-repaints-and-or-perfor
