### ISSUE TITLE
Coupon codes should not be case sensitive

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#882]
They are not a password.

**Comment by jjeffryes** [comment]
@cpacia the coupon codes have to be case sensitive because we're comparing hashes, right?

**Comment by rhcastilhos** [comment]
The software should at least create hashes for the coupon code in lowercase and upercase.

**Comment by jjeffryes** [comment]
This is working as intended, and we don't plan to change it, so I am closing this issue.
