### ISSUE TITLE
Nothing happens if user types coupon code and forgets to click "Apply"

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#883]
If user types a valid coupon code, forgets to hit enter/click in "Apply" and then click on Pay, the purchase proceeds with no warnings. Coupon code validation is not even tried.

**Comment by morebrownies** [comment]
The experience we provide is on par with how Amazon handles the coupon input. I just tested Amazon and they processed my order even though I didn't hit **apply** next to the coupon input. No warning or anything.

I agree there is probably some room for improvement here, but seems extremly low priority. 

Closing for now, we can revisit later in necessary. 

![screenshot 2017-09-20 16 01 23](https://user-images.githubusercontent.com/13066886/30671679-13f9b0f2-9e1d-11e7-87db-ae6cf0308070.png)
