### ISSUE TITLE
Offline chat messages are not received in order

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#885]
Win7 64 bits v2.0.11

From client A (online) I sent to client B (offline):
"A"
"B"
"C"
"D"

Client B received the following when connected:
"B"
"A"
"D"
"C"

**Comment by rmisio** [comment]
This is a server issue. The client displays them in the order they are received from the server. @rhcastilhos Would you mind logging this on the server?

**Comment by rhcastilhos** [comment]
Sure..
https://github.com/OpenBazaar/openbazaar-go/issues/690
