### ISSUE TITLE
Antivirus software false positive?

### ISSUE THREAD

**Issue by danielduckworth** [OpenBazaar/openbazaar-desktop#893]
Brief Description: Emsisoft antivirus sees the installer as a virus.

Operating System (OS and version): Windows 10
OpenBazaar version (shown on `About OpenBazaar` page in menu): 2.0.11
Hardware: 

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Execute installer with Emsisoft antivirus

Observed Behavior: False positive, file gets quarantined

**Comment by jjeffryes** [comment]
This is due to the Squirrel auto-updater, sometimes anti-virus software flags it as a virus.

It's a known issue, we haven't found a way around it yet.
