### ISSUE TITLE
"I Just Bought Something on OpenBazaar" Social Media Sharing Tool

### ISSUE THREAD

**Issue by jenncloud** [OpenBazaar/openbazaar-desktop#901]
As a user, when I purchase something, I want an easy way to immediately send a message to social media about my purchase.

It should explain that I just made a purchase on OpenBazaar and let me select between 2 types of messages, a "general" message, such as "I just made a purchase on OpenBazaar!" with a link to download OpenBazaar OR a "specifc" message that shares the item I bought, that I bought it on OpenBazaar, and have a link to the item.

**Comment by morebrownies** [comment]
I created a design for this a few months back. The design doesn't account for toggling between messages, but could be a good step 1 to get this in place.

If someone wants to take a stab at this, great! 

![screenshot 2017-09-20 15 37 35](https://user-images.githubusercontent.com/13066886/30671003-a92fb558-9e19-11e7-9a76-940d2dec8350.png)

**Comment by bglassy** [comment]
Going to look into this tomorrow.

**Comment by jjeffryes** [comment]
There's working code for something similar in v1 if you want an example to work from.
