### ISSUE TITLE
Increase clickable area for selecting a mod

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-desktop#909]
![image](https://user-images.githubusercontent.com/794517/30659454-b63ecaa8-9df2-11e7-8049-9cc68d065cb4.png)

Currently, if you click on the circular radio portion of a mod view, it will select the mod (circle gets filled in). Otherwise, any other click in the view results in the Moderator Details modal opening up.

It would be nice if the clickable area to select a mod were increased. Currently, you need to click *exactly* within the small circle. It would be nice if there was some padding around the circle which would give you a little leeway, so it doesn't feel like a game of operation:

![image](https://user-images.githubusercontent.com/794517/30659605-241f5592-9df3-11e7-8040-5181e40ea02b.png)

**Comment by rhcastilhos** [comment]
+1. I also find it difficult to click exactly on the radio button.
