### ISSUE TITLE
Store card cover image should link to store page

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#913]
![store card](https://user-images.githubusercontent.com/10789865/30674736-8a1acc00-9e52-11e7-999c-b023c7c74f74.png)
It should behave the same way as listings do (have a link on image).
Now it opens only if user clicks on avatar or page title.

**Comment by jjeffryes** [comment]
@morebrownies I do think we should make more of the user card clickable to go to that user. What do you think?

**Comment by morebrownies** [comment]
Yes, been meaning to ask for this as well.

Thank you for the suggestion @rhcastilhos

**Comment by rmisio** [comment]
What exactly is the ask here then... we just need to make the store image link to the user page?
