### ISSUE TITLE
Bad vertical alignment of categories with long names

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#926]
v.2.0.11 win7

seen on ob://QmdhCMFKrMXYbe65wLPAAeb9xx9BbyuuPsUPiG8GgHG3fn/store
![category alignment](https://user-images.githubusercontent.com/10789865/30769385-871b6392-9fed-11e7-9f7c-cd088e922f25.png)

**Comment by hoffmabc** [comment]
I think I have a duplicate on this one.

**Comment by rhcastilhos** [comment]
It's not duplicated (your issue: #434)

**Comment by morebrownies** [comment]
Here's a design of how the list would ideally display:

**Current**
![](https://user-images.githubusercontent.com/10789865/30769385-871b6392-9fed-11e7-9f7c-cd088e922f25.png)

**Ideal**
![screenshot 2017-09-25 13 28 04](https://user-images.githubusercontent.com/13066886/30829343-6229c98e-a1f5-11e7-8e27-62dac9180fef.png)
