### ISSUE TITLE
Listing title should span two rows

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#927]
Now there is too little space for the title. Amazon and ebay uses more than 1 line for title. Only etsy uses 1 line.

![listingstworows](https://user-images.githubusercontent.com/10789865/30769472-6b76a1d6-9fef-11e7-96cc-88b9c90a7339.png)

**Comment by morebrownies** [comment]
I would suggest prioritizing #928 first over this issue, and seeing how it feels with tooltips. If it still feels like we need multiple rows for the title, we can circle back and add them in.

**Comment by rmisio** [comment]
I'm going to close this for now. We got the tooltips in and it seems ok to me. If we find that even with the tooltip, the second line is important, we could always re-open.
