### ISSUE TITLE
Payment address is not copied to clipboard when clicked

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#929]
v2.0.11 win7 64 bits

Unlike the payment amount, you can't select the address text with mouse cursor (the complete address displays in a tooltip). 

Clicking on the bitcoin address should do the same thing as clicking on the "Copy" link (copy the address to the clipboard).

This behavior is already seen on addresses of Donation (About OpenBazaar modal) and of wallet's Receive Money function.

![nocopyaddress](https://user-images.githubusercontent.com/10789865/30769738-c6e718ba-9ff5-11e7-9309-1d93bd4257e0.png)

**Comment by rmisio** [comment]
Since this functionality is already available via the `Copy` button, I'm going to close this. The inconsistency between the Donations page seems like an extremely low priority issue to me.

@morebrownies If you feel differently, feel free to re-open.
