### ISSUE TITLE
No plural in search results by Tag 

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#932]
This should be "listings":

![listingplural](https://user-images.githubusercontent.com/10789865/30776028-46cec7d8-a075-11e7-8a92-f9f0f500ee34.png)

**Comment by jjeffryes** [comment]
I can't replicate this issue. 

![image](https://user-images.githubusercontent.com/1584275/30822825-206a2bda-a1f8-11e7-92c4-772f5a3e931d.png)

![image](https://user-images.githubusercontent.com/1584275/30822862-3e188384-a1f8-11e7-80d9-36b5331abd2a.png)

**Comment by jjeffryes** [comment]
@rhcastilhos can you give more details on what you're doing to trigger this?

Are you on the current release, or the latest master?

**Comment by rhcastilhos** [comment]
I closing this since it was seen on v.2.0.11 and I can't replicate on v.2.0.12.
