### ISSUE TITLE
"Sort by" filter works only when search term/tag is entered

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#933]
When you don't enter any search term or tag, it has no effect:
![sortby](https://user-images.githubusercontent.com/10789865/30776059-ca418542-a075-11e7-9a59-3c83b16e1731.png)

**Comment by rmisio** [comment]
@jjeffryes Do you want to validate this one?

**Comment by jjeffryes** [comment]
Confirmed. It looks like a search server issue, the parameter is being sent from the client correctly.

**Comment by jjeffryes** [comment]
I've opened an issue in the search repo for this.

**Comment by tyler-smith** [comment]
@rhcastilhos Thanks for this report. This is fixed in production.
