### ISSUE TITLE
Sales page search field has wrong prefilled text

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#937]
On Sales page, user searches for "Buyer".
On Purchases page, user searches for "Vendor".
On Cases page, user searches for "Vendor/Buyer"? (I have no case, need to check this).

![salesvendor](https://user-images.githubusercontent.com/10789865/30776819-0ba407fe-a084-11e7-814d-3b323d956cbf.png)

**Comment by morebrownies** [comment]
The placeholder is correct when you're on the `Purchases` tab, but incorrect when on the `Sales` tab.

We'll probably want to change the placeholder text to `Search by Order #, Title or Buyer` when on the Sales tab.
