### ISSUE TITLE
Items showing ratings when they don't have any reviews

### ISSUE THREAD

**Issue by ekerstein** [OpenBazaar/openbazaar-desktop#939]
I frequently click "Discover" and then search for 5-star ratings. I have seen several items that show 5-star when I search this way, but after I click the items they have no reviews. For example:

![screen shot 2017-09-24 at 4 06 54 pm](https://user-images.githubusercontent.com/6055508/30786337-6f50eb14-a142-11e7-9b1b-4e07fcad83cc.png)

This item shows a 5-star rating on the Discover page. However when I click the item it has no reviews.

![screen shot 2017-09-24 at 4 03 01 pm](https://user-images.githubusercontent.com/6055508/30786340-835306ba-a142-11e7-8abc-4ca27cd13be2.png)

And then when I click to the store for this item, it shows no ratings!

![screen shot 2017-09-24 at 4 04 07 pm](https://user-images.githubusercontent.com/6055508/30786341-8faece62-a142-11e7-839d-53b1527e2a4c.png)

**Comment by rhcastilhos** [comment]
Yes, there seems to be a bug there. Both these stores have just one sold item (and one review), but all their listings display 5.0 rating on OB1 search:
ob://QmVfsHYJwV7LMj7bnwfBBuTkFbHfWrPfBCjiqWqdthJYD7/store/
ob://QmfGL6dWz8NHwcD9aedL4Y73veqrBQ5Qw7EpQHa3EZ3t4c/store

![books rating](https://user-images.githubusercontent.com/10789865/30786499-3325be0c-a14d-11e7-83eb-f9d7aafc5689.png)

**Comment by jjeffryes** [comment]
Attn: @tyler-smith

**Comment by jjeffryes** [comment]
I've confirmed this issue is happening with the search service, and have opened an issue there.
