### ISSUE TITLE
Advanced Settings

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#94]
The existing settings modal should have an advanced tab with settings that are technical and/or less frequently used.

## Functional Requirements
The following settings should be available for the user:
**Appearance**
- [ ] Radio-style buttons to select the window controls style (Mac/Windows).*
- [ ] Radio-style buttons to turn advanced visual effects on or off.*
- [ ] **Transactions**
- [ ] Radio-style buttons to select whether additional data is saved to the wallet for each purchase.*
- [ ] Radio-style buttons to select a low, medium, or high default fee.*

**Server**
- [ ] Text displaying the current firewall type. 
- [ ] A button to open the connection management modal.
- [ ] A button to show a list of the connected peers. The list should show each GUID, clicking on one should navigate to that user's user page.
- [ ] A button to turn off the server.
- [ ] If the server is the local default server installed with the bundled app, a button to turn on the server.

**SMTP Integration**
- [ ] Radio-style button to turn SMTP notifications on or off.
- [ ] Text input for SMTP server address.**
- [ ] Text input for SMTP user name.
- [ ] Text input for SMTP password.
- [ ] Text input for SMTP email address. **
- [ ] Text input for SMTP recipient email address.**
- [ ] If the SMTP notifications are turned on, all the other SMTP fields must be filled out or an error should be thrown when the settings are saved.
- [ ] A button to test the SMTP settings. It will open a connection to the SMTP server using the user name and password in the inputs, and show a success/fail message.

* these settings are saved in local storage.
** these settings should be validated to make sure they have the right format.

## Data
- the current firewall type and SMTP settings should be retrieved from the settings API.
- the SMTP settings should be saved to the settings API.

**Comment by rmisio** [comment]
> the current firewall type and SMTP settings should be retrieved from the settings API.

The settings API is fetched on app startup and need not be fetched again. The data can be retrieved from the model available via `app.settings`.

> these settings are saved in local storage.

Please do so using the localSettings model which is available via `app.localSettings` and, like the Settings model, it is fetched at startup, so you do not need to fetch it.

> these settings should be validated to make sure they have the right format.

Validations should be integrated into their respective models (app.settings or app.localSettings)

>  Radio-style buttons to select the window controls style (Mac/Windows).

This is a matter of wiring in the radio button to the app.localSettings.macStyleWinControls field.

**Comment by jjeffryes** [comment]
> The settings API is fetched on app startup and need not be fetched again. The data can be retrieved from the model available via app.settings.

I should have been more explicit about the data already having been fetched, thanks.

**Comment by jjeffryes** [comment]
Closed by #111
