### ISSUE TITLE
Rating filter should display "All ratings" first

### ISSUE THREAD

**Issue by rhcastilhos** [OpenBazaar/openbazaar-desktop#940]
This way users  just have to select the first radio button of each filter to see all listings with no filters applied.

![allratings](https://user-images.githubusercontent.com/10789865/30786875-513800fc-a153-11e7-9f9d-dd91ade90937.png)

**Comment by morebrownies** [comment]
+1 I tend to prefer `All ratings` at the top too.

**Comment by morebrownies** [comment]
@tyler-smith FYI

**Comment by jjeffryes** [comment]
An issue has been opened on the search repo for this.
