### ISSUE TITLE
Show the languages the moderator understands

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#959]
We have the data for the languages a moderator understands, but it is not displayed in the Moderator Card or the Moderator Details modal. 

That information should be displayed.

**Comment by morebrownies** [comment]
Good catch. Will take a look when I can. Thanks

**Comment by rhcastilhos** [comment]
I think the spoken languages should be a setting of all users (buyers and vendors) and not only of moderators.

**Comment by morebrownies** [comment]
![screenshot 2017-10-05 11 03 16](https://user-images.githubusercontent.com/13066886/31242736-d086a23e-a9bc-11e7-83a7-6f0853ba677d.png)

**Comment by jjeffryes** [comment]
This was completed.
