### ISSUE TITLE
Add Bitcoin Units to the Settings/General Tab

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#96]
A radio-style control to select a bitcoin display unit should be added to the Settings/General tab.

## Functional Requirements
- [ ] the options are BTC, mBTC, μBTC and satoshi.
- [ ] the default is BTC.
- [ ] when the option is changed, any price data should be refreshed to be shown in that format (make sure cached renders, if any, don't show the old format).
- [ ] the option chosen should be shown in the format appropriate to the current language.

 ## Data
- [ ] the option chosen should be saved in local storage.

See https://github.com/OpenBazaar/OpenBazaar-Client/pull/1823 for an example of this functionality.

**Comment by rmisio** [comment]
I'll happily take this one. Looks like it's another wrinkle to the currency module, which I've worked heavily on.

I'll hold off until I get the go-ahead since I'm not sure priority-wise when I should work on this vs. something else.

**Comment by jjeffryes** [comment]
Go ahead.
