### ISSUE TITLE
Make http/https ursl in chat into links

### ISSUE THREAD

**Issue by rmisio** [OpenBazaar/openbazaar-desktop#965]
For example `https://bitcoinshirt.co/` should be a link there:

![image](https://user-images.githubusercontent.com/794517/31030045-c27462c0-a508-11e7-8ff9-c0f7fb1976ba.png)

**Comment by sahilsharma011** [comment]
This stackoverflow answer https://stackoverflow.com/a/21925491/4535741 can be referred for discussing which library should be used for this issue.
