### ISSUE TITLE
Add Clone Button to Listing Screen

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#966]
Add a clone button next to edit in the listing screen. 

The three buttons can be "Edit," "Clone," and "Delete."

**Comment by jjeffryes** [comment]
I've only had one report of a user not noticing the existing clone button right now, it makes sense to me to have it both in the store view and on the individual listing.

**Comment by rmisio** [comment]
@morebrownies If you're fine with this, this wouldn't be too hard to do. It's actually easier than at the store level, because at this point you already have the full listing data.

**Comment by morebrownies** [comment]
Yeah totally agree. Would be nice to have it in both spots.
