### ISSUE TITLE
Lot of unused space with HDPi screen

### ISSUE THREAD

**Issue by Kirvx** [OpenBazaar/openbazaar-desktop#967]
![sans titre](https://user-images.githubusercontent.com/6627786/31035991-8d38b78e-a56a-11e7-8476-a44443b9212a.jpg)

**Comment by rmisio** [comment]
@Kirvx Thanks for submitting this. We actually already have designs for a full screen layout, but due to some scope-cutting they did not make it in. It is on our radar, but there's a lot on that radar, so I'm not sure exactly when this will be addressed.

Closing this as a known issue.
