### ISSUE TITLE
Uncaught Exception: RangeError: Invalid string length

### ISSUE THREAD

**Issue by luemob** [OpenBazaar/openbazaar-desktop#971]
Brief Description: 
A JavaScript error occurred in the main process Uncaught Exception: RangeError: Invalid string length.

Operating System (OS and version): 
Windows 7 64bit 
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
OpenBazaar2 ver. 2.0.11.0 9/19/2017 
Hardware: 
toshiba satellite P755 i3-233 6 GB ram

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. launch openbazaar2
2. entered shop item 1 towards saving 1st entry the error would appear and I had to end it in task manager and relaunch program
3. update java to 8 update 144 and proceeded to log back into openbazaar2
4. entered second item to the end 
5. minutes later after entering and completing item the error appeared again. information of error taken from windows event viewer.

Observed Behavior:
The program OpenBazaar2.exe version 2.0.11.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Action Center control panel.
 Process ID: 1cf4
 Start Time: 01d33afe5113419a
 Termination Time: 37
 Application Path: C:\Users\User\AppData\Local\OpenBazaar2\app-2.0.11\OpenBazaar2.exe
 Report Id: 

xml version:
Log Name:      Application
Source:        Application Hang
Date:          10/1/2017 6:26:38 PM
Event ID:      1002
Task Category: (101)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      luemob
Description:
The program OpenBazaar2.exe version 2.0.11.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Action Center control panel.
 Process ID: 1cf4
 Start Time: 01d33afe5113419a
 Termination Time: 37
 Application Path: C:\Users\User\AppData\Local\OpenBazaar2\app-2.0.11\OpenBazaar2.exe
 Report Id: 

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Hang" />
    <EventID Qualifiers="0">1002</EventID>
    <Level>2</Level>
    <Task>101</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-10-01T23:26:38.000000000Z" />
    <EventRecordID>999564</EventRecordID>
    <Channel>Application</Channel>
    <Computer>xxxxx</Computer>
    <Security />
  </System>
  <EventData>
    <Data>OpenBazaar2.exe</Data>
    <Data>2.0.11.0</Data>
    <Data>1cf4</Data>
    <Data>01d33afe5113419a</Data>
    <Data>37</Data>
    <Data>C:\Users\User\AppData\Local\OpenBazaar2\app-2.0.11\OpenBazaar2.exe</Data>
    <Data>
    </Data>
    <Binary>54006F00700020006C006500760065006C002000770069006E0064006F0077002000690073002000690064006C00650000000000</Binary>
  </EventData>
</Event>

Expected Behavior:

Additional info (links, images, etc go here):

**Comment by jjeffryes** [comment]
@luemob I believe this is an issue we fixed in our latest release, it was caused by a log file becoming extremely large. 

Can you upgrade to 2.0.13 and let us know if that fixes it for you?

**Comment by luemob** [comment]
Thx for confirming and will do. Keep you posted.
