### ISSUE TITLE
Show SKU of Order in Order Details

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#972]
The order details screen does not show the SKU of the item ordered. This is important data for sellers tracking their inventory.

If there are no variants, the SKU is found in contract.vendor-listings[0].item.skus[0].productID.

If there are variants, the SKU is not directly available. The options chosen, and a list of the skus are available,. The options chosen by the buyer would need to be matched to the options available, and that information used to determine which SKU is associated with that combination.

**Comment by rmisio** [comment]
@morebrownies when you have some time (no rush at all) would you mind giving some direction as to where we should display the SKU?

**Comment by morebrownies** [comment]
I would suggest outputting it below the listing title / above the variants (as pictured below).

Something to keep in mind is we'll need to output the SKU of the variant (if a variant exists and if the variant has a SKU)

![screenshot 2017-10-02 10 46 51](https://user-images.githubusercontent.com/13066886/31091194-061407b2-a75f-11e7-9b0a-a4fbf25c64db.png)
