### ISSUE TITLE
Expired listings in the OB1 search results

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#973]
The OB1 search results return expired listings. Right now the listings from the following peer ids have expired but are shown in the search results:

QmNWizZaxVf9Ctm1XoxaXUa5Cw9VKWoAhoU5oP3RrBYefy
QmZPt7ky2AohS72yeypM31t1pv1H9XsL7SioFYUmGZMPkt
QmThx6pHSKQKsUAJKF4SdYQQqgrAUSK3cCsiWHC8AcmgtN
QmZNo84zmz6b5Ec2jH3Ats9mdZBnn1jeoK4PavizknkY3j
Qmd7neyqDRXmn326nVxMiueu3ZwnAGSRz118TNgrRHCLHW
QmRujYcMrQYhzokvVGzyD6j4y1zADb9qhYcGu6Xq5gpewT
QmX6yerpMDAuifZo2vs7pXiKJt4bBbcHG5TFd5m3T1nc5F
QmbnoUqBXUwYJTcoC1gvMjrsVRFdMbRqkxLtU5xsHKQPX3
QmSSpW62JM4t99dquEZW2x5hY994xsYnXVmaTMW1mHqpX4
QmYLPvxdpsrHBVCrj1wkxUAqqp775LyTzmyzV9c3HuAbmA
QmRHvF61Yk8vPYTAT54ZtnF9kAYLj5gnwibAXJV58vhbED
QmfUXGNm28UJa4kTjargNxa9HCKTBFBnLAF8ZPEcvNaKAU
QmZhoLxQQqqfXDHwUtknHkRQAWrERuzcWZaU19WejScD3D
QmbEQdkczwVEZLCEtTLKbasXnmZuHgAjsYNosFSt6SFYYV
QmbtxW8FtVmgTcWdTEmAMfVBVSeZecgRmN2AMmTGWkZFAG
QmZwi3yks6Xt4V3KP2GzrjraKzBeLttVC8Af2agyUmQM5n
QmUcqWLHFQanY1f2pjfPeEMiuE4AreFtjK4nJX6LyoJkUv

**Comment by rmisio** [comment]
attn: @tyler-smith
