### ISSUE TITLE
Replacing tags for a listing

### ISSUE THREAD

**Issue by anyone-ob** [OpenBazaar/openbazaar-desktop#978]
Brief Description: 
Replacing tags for listings does not work as expected. The replaced tag reappears.

Operating System (OS and version):  Mint 18
OpenBazaar version (shown on `About OpenBazaar` page in menu):  client 2.0.13, server 0.9.2

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. add a tag
2. remove the tag
3. add another tag
(check the video below)

Observed Behavior:
the removed tag reappears

Expected Behavior:
the removed tag does not reappear

Additional info (links, images, etc go here):
**Demo video: https://streamable.com/f58sb**

**Comment by rmisio** [comment]
This is another known quirk of the drop down library we are using. The workaround is to manually remove (click on the X) of the ones that reappear. We understand that's annoying.
