### ISSUE TITLE
[idea] Price negotiable

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-desktop#98]
What about having a boolean flag (similar to NSFW) that indicates whether or not the price for the listing is negotiable? I've personally lived in Shanghai, China for 4 years and back then buying stuff from the local markets without negotiating would have been weird/rude.

**Comment by anyone-ob** [comment]
I missed this too. It makes sense in some cases.

**Comment by jjeffryes** [comment]
We're not planning to implement this, we did discuss it at one point and it would add a lot of complexity.

Users are free, of course, to message a seller and negotiate a sale for whatever price they want, and send a payment directly through the wallet.
