### ISSUE TITLE
Verify tor connection

### ISSUE THREAD

**Issue by BuckminsterEmptier** [OpenBazaar/openbazaar-desktop#988]
Brief Description: 

Operating System (OS and version): Whonix
OpenBazaar version 2.2.0.13
Hardware: x64

Question:

Is it currently possible to verify I'm working on the TOR network?  With a browser I go to check.torproject.org.  

Feature Request: ability to use check.torproject.org or other way of verifying that OB is routing through TOR.

**Comment by cpacia** [comment]
The way we tested the client is to put images in the profile that load from a server and check the IP that was logged on the server when the image was loaded.

That's just the client though. The server also uses Tor.
