### ISSUE TITLE
OpenBSD 6.1 amd64 not supported

### ISSUE THREAD

**Issue by plavcik** [OpenBazaar/openbazaar-desktop#989]
on master

npm install
npm ERR! OpenBSD 6.1
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for electron-installer-debian@0.5.2: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"openbsd","arch":"x64"})
npm ERR! notsup Valid OS:    darwin,linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   openbsd
npm ERR! notsup Actual Arch: x64

**Comment by hoffmabc** [comment]
Ok I’ll take a look for OpenBSD

**Comment by hoffmabc** [comment]
I think Electron is not supported yet ok FreeBSD or OpenBSD.

**Comment by plavcik** [comment]
I have these files on my OpenBSD

$ cd .npm/electron
$ ls
1.7.6/ 1.7.8/ 1.7.9/
$ find .
.
./1.7.6
./1.7.6/package
./1.7.6/package/package.json
./1.7.6/package.tgz
./1.7.8
./1.7.8/package
./1.7.8/package/package.json
./1.7.8/package.tgz
./1.7.9
./1.7.9/package
./1.7.9/package/package.json
./1.7.9/package.tgz

is that helpfull or may I test something?

**Comment by jjeffryes** [comment]
@hoffmabc is there a way to support FreeBSD or OpenBSD, or should I close this?

**Comment by hoffmabc** [comment]
Electron uses libcc but it does not support FreeBSD/OpenBSD without hacks. For the time being we probably will not pursue supporting it. It is possible to hack electron support in as a quote from a GitHub project attempting that, but it seems like more work than we can take on at this time.

https://github.com/yzgyyang/freebsd-ports-electron

> Since FreeBSD is currently not officially supported by libcc, we manually build libcc as a prerequisite for the Electron port.
