### ISSUE TITLE
UX: Show 'Free' instead of '$0.00' under Shipping

### ISSUE THREAD

**Issue by anoadragon453** [OpenBazaar/openbazaar-desktop#994]
If an item does not charge for shipping, they have to input $0.00 as the price. This price is also shown to the user, as is a bit awkward to look at.

![2017-10-10-004319](https://user-images.githubusercontent.com/1342360/31374918-b5122366-ad54-11e7-87a2-9fc604fc3207.png)

Instead, it may be nicer if it said 'Free', rather than a price of zero dollars and zero cents.

**Comment by rhcastilhos** [comment]
I prefer displaying the green "free shipping" tag where "$0.00" is now. It would end redundancy.

**Comment by morebrownies** [comment]
Yeah good call. +1

**Comment by rmisio** [comment]
> Yeah good call. +1

By that, you mean moving the Free Shipping banner over to the far right column?

**Comment by morebrownies** [comment]
Sorry, yeah that's right @rmisio 

Replace $0.00 with the green `free shipping` banner
